### ISSUE TITLE
md-autocomplete: focus() and submit form with enter key does not work

### ISSUE THREAD

**Issue by evilru** [vuematerial/vue-material#1003]
you do awesome work here!
it is a pleasure to work with vue-material - also the documentation feels complete and is easy to understand!

i just found the following minor issues regarding md-autocomplete:

---

i am on 9182c2f5ec04b1b981ec041961fe93d7b35b4b3d (HEAD of develop branch)

while it is possible to set focus() on md-input elements and submit a form by hitting enter, this does not work for md-autocomplete.

```html
<form @submit.stop.prevent="submit">
  <md-autocomplete ref="autocomplete"></md-autocomplete>
  <md-input ref="input"></md-input>
</form>
```
```js
mounted () {
  this.$refs.autocomplete.$el.focus()
  this.$refs.input.$el.focus()
}
```
as the autocomplete input is wrapped with two divs, there might no way around doing something like:
```js
this.$refs.autocomplete.$el.querySelector('input').focus()
```
while taking a look at the event tab (vue dev tools) i just saw that the enter key event is being consumed by `<MdMenu>` to emit the close event

**Comment by waratah** [comment]
This is the same problem as above.  I have an autocomplete on a list item and I want to focus the title input.  I would be nice if there was a way to ref the input, even if it was a second autognerated ref like 'autocomplete-input'

    <div class="md-menu md-autocomplete-menu">
        <input type="text" md-menu-trigger="" class="md-input">
     </div>

**Comment by waratah** [comment]
I ended up doing focus by this:  (this.$refs.title as Vue).$el.querySelector('input').focus();

look at $refs for my name (title) and then find input and focus on it.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by KarineLiuti** [comment]
> I ended up doing focus by this: (this.$refs.title as Vue).$el.querySelector('input').focus();
> 
> look at $refs for my name (title) and then find input and focus on it.

This worked for me. Thank you!
