### ISSUE TITLE
[md-autocomplete] Avoid using non-primitive value as key, use string/number value instead.

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#1005]
Hello, 

i have an error when i use md-autocomplete and passing an array of object to the filter-list property of md-autocomplete 

`<md-autocomplete :min-chars="3" v-model="searchAgenciesQuery" :list="agencies" :filter-list="filteredAgencies"></md-autocomplete>`

> Avoid using non-primitive value as key, use string/number value instead.

It will be fixed to be less restrictive ? Or we have to be pass string key of our object we use ? 

Thank you

**Comment by alexMugen** [comment]
oups , similar to #930

**Comment by VdustR** [comment]
I found that it has been fixed in [1ab255dc1fbc037502d2191b592861248b7c045e](https://github.com/vuematerial/vue-material/commit/1ab255dc1fbc037502d2191b592861248b7c045e#diff-ce6ce6895a7f7bde55d0476c7ad2bbadR26)

**Comment by zapping** [comment]
It seems a strange issue. This pen, https://codepen.io/zapping/pen/GmVapv , has a working component of autocomplete. In the settings if you replace the vuejs file with https://unpkg.com/vue/dist/vue.js you get the error mentioned above. But if you use https://cdnjs.cloudflare.com/ajax/libs/vue/2.4.2/vue.min.js it works. 

But both the js file has the same version. But one is minified and the other is not.

**Comment by VdustR** [comment]
@zapping Warn messages only show in development mode. The minified one is production mode.
