### ISSUE TITLE
[md-select] opened and closed event never fired

### ISSUE THREAD

**Issue by Franzyval** [vuematerial/vue-material#1007]
Hello and first, thanks for the library :),

I either discovered a bug or misunderstood something, but events stated in doc are not emitted

### Steps to reproduce
https://jsfiddle.net/y7owLuz1/8/

Annotate any md-select with a `v-on:opened` or `@opened`

### Which browser?
latests firefox, chrome, edge and IE

### What is expected?
the event should be fired as indicated in documentation

### What is actually happening?
no event emitted

### Reproduction Link
https://jsfiddle.net/y7owLuz1/8/

in the code, i can see the event is supposed to be emited by this function : 
      `
onOpen() {
        if (this.lastSelected) {
          this.lastSelected.scrollIntoViewIfNeeded(true);
        }
        this.$emit('opened');
      },
`

which is never called. At least, i did not find any call to this function.

**Comment by robgev** [comment]
+1 here
