### ISSUE TITLE
md-hide-small-and-up triggers on 660px

### ISSUE THREAD

**Issue by mlg-ipleic** [vuematerial/vue-material#1010]
when I put my element 

`<div class="md-hide-small-and-up">`

to show only on xsmall, it triggers on 660px to show, not on 600px as it is documented by lib that it is its default breakpoint

and that leaves mine other elements for example

`<div class="md-button md-hide-xsmall">Shows</div>`

To exist in the same time like that first div, between 660px and 600px they both exist :S

**Comment by zapping** [comment]
Seems similar to #728

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
