### ISSUE TITLE
[mdProgress] error by binding progress

### ISSUE THREAD

**Issue by rafaelleru** [vuematerial/vue-material#1013]
I'm binding the progress to a mdProgress using vuex by v-bind:progress but I get the following error:
`webpack-internal:///1:480 [Vue warn]: Invalid prop: type check failed for prop "mdProgress". Expected Number, got String.`

how I can solve this?

**Comment by pablohpsilva** [comment]
Hello @rafaelleru :)
Use a String instead of a Number, just like the error said.
