### ISSUE TITLE
md-stepper issue with tabbing over input fields

### ISSUE THREAD

**Issue by cjpit** [vuematerial/vue-material#1017]
### Steps to reproduce
Use a standard md-stepper with input fields.  Press tab a few times

### Which browser?
All, latest vue, vue material

### What is expected?
Should stay on the current step, and circle over the fields there.
### What is actually happening?
...stepper gets all confused, goes and focuses something out there in another stepper
### Reproduction Link
https://codepen.io/anon/pen/wqZgQz

**Comment by cjpit** [comment]
yikes https://github.com/vuematerial/vue-material/issues/980 has already been filed, although hasn't been marked as a bug yet.  Feel free to delete if needed.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
