### ISSUE TITLE
Expose 'opened' property on md-dialog

### ISSUE THREAD

**Issue by nikkwong** [vuematerial/vue-material#1020]
Hi,

Right now if you want to keep md-dialog's open state in a store, you have to use `watch` somewhere in a component to trigger the method `this.$refs.dialog.open`, which is clunky. It would be nice if there was a public property `open` on the dialog so it would could watch a value in the store and open and close itself based on that.

This, for one, seems enormously clunky...

```
mounted() {

    this.$store.watch((state) => state.system.modalShouldOpen, (shouldOpen) => {

        if (!this.$refs.intro_modal) return

        this.$nextTick(() => {

            this.$refs.intro_modal[shouldOpen ? 'open' : 'close']()

        })

    }, { immediate: true })

}
```

Thanks.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
