### ISSUE TITLE
Any example how to use vue-material for a mobile app?

### ISSUE THREAD

**Issue by 5an1ty** [vuematerial/vue-material#1027]
This doesn't look very well when you set your browser to simulate an iphone or android device:

https://codepen.io/vue-material/pen/VmMrYW

**Comment by zapping** [comment]
I am not very sure when you say 'doesn't look very well'. I guess you must be referring to the font or text that is not scaling properly on the device screens. For that try adding the following to the head tag
`<meta name="viewport" content="width=device-width, initial-scale=1.0" />` . 

On a Codepen I guess you can only just resize the view area. To check try copy-paste the following to a html file and try the simulation options in your browser.

```
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link href="https://unpkg.com/vue-material@latest/dist/vue-material.css">
  <style>
    .main-content{padding: 16px;} 
  </style>
</head>
<body>
  <div id="app">
  <md-toolbar>
    <h1 class="md-title">My Title</h1>
  </md-toolbar>
  
  <div class="main-content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, rerum? Error sunt, aperiam dolores, atque expedita molestiae tenetur. Quis eveniet accusamus velit explicabo adipisci reiciendis modi eaque quas, officia excepturi.</p>
  </div>
</div>
</body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.1.6/vue.min.js"></script>
  <script src="https://unpkg.com/vue-material@latest"></script>
  <script>
    Vue.use(VueMaterial)

    var App = new Vue({
      el: '#app'
    })
  </script>
</html>
```
Vue-material is a UI Component framework based on [Material design](https://material.io/guidelines) standards for Vuejs from which you can pick and add UI components to your page/forms. It does provide you with components that are responsive but for your website to be responsive you will have to build up on your own with CSS or media queries etc etc that you usually do.

**Comment by 5an1ty** [comment]
That is exactly what I mean, thanks for the clarification and reading into my obscure question 😄!
Amazing library, thanks for the continued development!
