### ISSUE TITLE
[mdSelect]Is there a way input from keyboard?

### ISSUE THREAD

**Issue by phongle318** [vuematerial/vue-material#1035]
I had tried autoComplete input, but I'd like to see what in the list before I enter some words.

**Comment by VdustR** [comment]
> # min-chars
> Set the minimum number of characters before making opening the autocomplete options or making a request. 
> Default: `3`

Assign it `0`:

```html
<md-autocomplete :min-chars="0"></md-autocomplete>
```

**Comment by VdustR** [comment]
> ## min-chars
> `Number`
> Set the minimum number of characters before making opening the autocomplete options or making a request. 
> Default: `3`

Assign it `0`:
```html
<md-autocomplete :min-chars="0"></md-autocomplete>
```

**Comment by phongle318** [comment]
Thanks @VdustR
