### ISSUE TITLE
[mdSelect] Allow clear

### ISSUE THREAD

**Issue by SergioReis97** [vuematerial/vue-material#1036]
Add possibility to clear select with an easy prop

Q- What will it allow you to do that you can't do today?
A- Save about 1 minute per select
Q- How will it make current work-arounds straightforward?
A- Instead of having to put an icon button in the container and manually clear the select through an @click just pass it at prop
Q- What potential bugs and edge cases does it help to avoid?
A- Can't see any obvious bugs and alot of selects are going to need to be empty after set

Right now we do something like this

```
<md-input-container>
   <label>Frequência de sincronização</label>
   <md-select name="select" id="select" v-model="someModel">
   ....
   </md-select>
   <md-button @click="someModel = '' " class="md-icon-button">
      <md-icon>clear</md-icon>
    </md-button>
</md-input-container>
```

This just seems much more elequent

```
<md-input-container>
   <label>Frequência de sincronização</label>
   <md-select name="select" id="select" v-model="someModel" md-clearable>
   ....
   </md-select>
</md-input-container>
```

**Comment by waratah** [comment]
Why would you not use type ahead for this sort of thing?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
