### ISSUE TITLE
No date picker component?

### ISSUE THREAD

**Issue by KellerLong** [vuematerial/vue-material#1040]
I wish there were some other components. such as Date Picker component or  Page Index.

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/4

**Comment by redimongo** [comment]
Yeah this would be a good one to have, as I need an easy to use date picker for users to select their birthday and other important dates like travel dates.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/components/datepicker
