### ISSUE TITLE
Ok! I found some new problems again!

### ISSUE THREAD

**Issue by KellerLong** [vuematerial/vue-material#1041]
md-input-container:
When the cursor is in the middle of the text and constantly input, It doesn't automatically get bigger and text have overlap.
tabs:
 It's indicator, Once the rendering is done, it will be rendered again, and When use inspect of chrome, It becomes two.

**Comment by Samuell1** [comment]
Better will be include jsfiddle/codepen example or screenshot, gif.

**Comment by waratah** [comment]
@KellerLong   Please give this bug a valid heading that describes the problem.  and flag it with a component name.

I also cannot figure out if you have two issues in which case there should be two bugs or just one.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
