### ISSUE TITLE
mdSelect bare <select> element is sometimes visible

### ISSUE THREAD

**Issue by jeffbaumes** [vuematerial/vue-material#1045]
### Steps to reproduce
* Make a md-select in the last of a set of wide md-tab elements.
* Make a wide browser window and click on the tabs - it shows up on one of them.

### Which browser?
At least Chrome. Shows up on https://unpkg.com/vue-material@latest

### What is expected?
The select should not be visible, but it seems to arbitrarily choose `left: -999em` to attempt to hide itself.

### What is actually happening?
Shows up.

### Reproduction Link
https://codepen.io/anon/pen/eGzpvB

### Possible fix
Include `display: none` in the `.md-select select` css.

**Comment by VdustR** [comment]
Another solution:
```
.md-select {
  overflow: hidden
}
```

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
