### ISSUE TITLE
[MdChips] There is no props for `md-editable`

### ISSUE THREAD

**Issue by KevinNTH** [vuematerial/vue-material#1048]
Using this following example:
```javascript
<md-chips v-model="contacts" md-input-placeholder="Add a contact"></md-chips>
```

There is no props `md-editable` to be set to `true` or `false`, and then `MdChips` component always set `MdChip` with props `md-editable` to `true`.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
