### ISSUE TITLE
SpeedDial does not expand second time on hover after clicking on expanded item

### ISSUE THREAD

**Issue by giko45** [vuematerial/vue-material#1049]
### Steps to reproduce

1. goto: http://vuematerial.io/#/components/speed-dial
2. hover over the light blue speeddail in the first demo -> speeddail expands upward (OK)
3. click on the mail icon (first expanded item)-> speeddail closes (OK)
4. after click move mouse pointer in a strait line down to the speed dail -> speeddail does NOT expand upward (Error)
moving away from the speeddial and the placeholder for the expanded items or clicking somewhere else restores the toggle functionality on hover

### Which browser?
latest chrome

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
