### ISSUE TITLE
`<md-switch>` within a `<md-list-item>` with `@click` handler?

### ISSUE THREAD

**Issue by mismith** [vuematerial/vue-material#1051]
Is it not possible to have a switch within a list item button?

``` html
  <md-list>
    <md-list-item @click="doSomething()">
      <span>md-list-item with @click handler</span>
      <md-switch @change="notTriggered()" />
    </md-list-item>
  </md-list>
```

### Steps to reproduce
1. Visit: https://codepen.io/mismith/pen/qPagoE?editors=1011#
2. Click/touch a switch

### Which browser?
All, AFAIK.

### What is expected?
- Switches should flip
- Parent list item's click should *not* fire, nor should the ink ripple expand

### What is actually happening?
- Switches are ignored entirely

I would assume that adding the `md-list-action` class to the switch would work, but it doesn't. Is there some limitation or spec preventing this from happening, or has it just not just been implemented?

**Comment by mismith** [comment]
Anyone home?

**Comment by mismith** [comment]
While that will work, technically, I _need_ the click handler, so it doesn't solve the problem, overall.

I dug into it a little more, and the issue seems to be that an `.md-ghost-button` is overlaid on top of the list item button contents, meaning the switch never receives a click. A quick (hacky?) workaround is to make the `z-index` of the `<md-switch>` to something higher than the `.md-ghost-button`, e.g.:

``` scss
.md-list-item {
  .md-button {
    .md-list-action {
      &.md-switch {
        z-index: 2;
        margin-right: 0; // cancel out some margin offsets intended for icon buttons, I think
        margin-left: 8px; // ib id
      }
    }
  }
}```

Would this make for a PR-able solution?

**Comment by zapping** [comment]
Maybe you can also try and include them in separate `div`, something like this

```
  <md-list>
    <div style="display:flex; justify-content:space-between">
      <div style="flex:1">
        <md-list-item @click="doSomething()">
          md-list-item with @click handler
        </md-list-item>
      </div>
      <div>
          <md-switch @change="notTriggered()" />
      </div>
    </div>
  </md-list>
```

**Comment by mismith** [comment]
Haven't tried it, but I would assume that would break the underlying ink ripple, not to mention make styling things even more finicky given margins/padding etc.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
