### ISSUE TITLE
text alignment is not working for numeric table cells

### ISSUE THREAD

**Issue by janory** [vuematerial/vue-material#1052]
### Steps to reproduce
Just use the `md-numeric` attribute in the `md-table-cell` tag as it's suggested in the http://vuematerial.io/#/components/table example.

### System info
OS: macOS Sierra, Version 10.12.6
Browser: Google Chrome, Version 60.0.3112.113
Vue Version: 2.4.2
Vue Material Version: 0.7.5

### What is expected?
The numeric values are aligned to the right.

### What is actually happening?
The numeric values are centred.

### Reproduction Link
https://codepen.io/anon/pen/eGdqJv

### Possible solution
It is probably happening because of the `display: flex` CSS styling [here](https://github.com/vuematerial/vue-material/blob/b992c27a3b6407ae2fc836345dc91bcd32c1f379/src/components/mdTable/mdTable.scss#L159).

If you want to use flex layout for the numeric table-cell-containers, a possible solution would be to set the `justify-content` to `flex-end`.

Like this: https://codepen.io/anon/pen/pWEMeN

**Comment by janory** [comment]
I've just added a PR to fix this.
By the way is was correct in the [mdTable.old](https://github.com/vuematerial/vue-material/blob/b992c27a3b6407ae2fc836345dc91bcd32c1f379/src/components/mdTable/mdTable.old.scss#L155), so somebody probably just oversight this.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
