### ISSUE TITLE
[mdCheckbox]   change called before value set.

### ISSUE THREAD

**Issue by waratah** [vuematerial/vue-material#1057]
### Steps to reproduce

       <md-layout md-flex='50'>
            <md-checkbox class="md-primary" v-model='reports.traveller' @change='ReportChange'>Traveller Analysis Report</md-checkbox>
        </md-layout>
        <md-layout md-flex='50'>
            <md-checkbox class="md-primary" v-model='reports.spend' @change='ReportChange'>Spend Comparison Report</md-checkbox>
        </md-layout>

     ReportChange() {
        let result = [];
        console.log( this.reports);
        if (this.reports.isSelected) {
            result.push(0);
        }
        if (this.reports.traveller) {
            result.push(1);
        }
        if (this.reports.spend) {
            result.push(2);
        }

The above logic fails because when I check the values they are the previous values not the ones shown on screen.  This means my logic to push into an array is always wrong. 

Will look at Array logic to see if it works.

### Which browser?

all - chrome Mac tested

### What is expected?

value is set then the change function called so logic such as the above works correctly.

### What is actually happening?

When I check reports.traveller checkbox, screen shows selected but in ReportChange function Reports.traveller is false.  I am missing my value for the one that changed every time.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by mrts** [comment]
Try with `@click.native` and see if this fixes the issue for you.
