### ISSUE TITLE
Request: Multi line tooltip

### ISSUE THREAD

**Issue by MaximVanhove** [vuematerial/vue-material#1058]
Is it possible to add multi line tooltips?

```
<md-tooltip md-direction="bottom">
    <span>First line</span>
    <span>Second line</span>
</md-tooltip>
```

And maybe a new property `md-text-direction="center"`

**Comment by zapping** [comment]
Try setting the tooltip with a `div` tag instead of `span` like this
```
<md-tooltip md-direction="bottom">
    <div>First line</div>
    <div>Second line</div>
    <div>Third line</div>
</md-tooltip>
```
Then add this to your css and override the height attribute of tooltip
`.md-tooltip{height:auto}`

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
