### ISSUE TITLE
[mdCheckbox] documentation showing incorrect version

### ISSUE THREAD

**Issue by S9uare** [vuematerial/vue-material#1060]
Hi,
I noticed that the feature requested here https://github.com/vuematerial/vue-material/issues/414 seems to be added recently.

And according to the docs here, it's working fine and nicely.
http://vuematerial.io/#/components/checkbox

However it doesn't seem to be available in 0.7.5 distribution, despite that in the right top corner of the documentation shows `0.7.5`.

* I confirmed the source code that it is not implemented in v0.7.5
https://github.com/vuematerial/vue-material/blob/v0.7.5/src/components/mdCheckbox/mdCheckbox.vue

Edit:
My workaround for this issue.
https://codepen.io/s9uare/pen/MEQpVo

**Comment by SergioReis97** [comment]
Having same problem, can't use array of checkboxes, 
trying to bind the checkboxes to a model returns the following error

> Invalid prop: type check failed for prop "value". Expected String, Boolean, got Array.
> found in
> ---> <MdCheckbox>

And the value of the variable is then returned as true or false.

Maybe some PR overwrote this one? https://github.com/vuematerial/vue-material/pull/1029/

**Comment by happyleavesaoc** [comment]
Same problem on `0.7.5`. The documentation says it's possible, but it isn't!

**Comment by SergioReis97** [comment]
@happyleavesaoc Not really recomended but you can pull the project, make this changes https://github.com/vuematerial/vue-material/pull/1029 , build it and replace the dist folder with the one you build and it will work as said in the documentation. I'm not doing a P.R. for this because i'm not sure if the maintainers purposely removed this feature or if there is some other reason for it not to be there...

**Comment by vjoao** [comment]
@SergioReis97 but this feature is awesome! Especially with the new Firebase Firestore (to save an array of selected items).

**Comment by SergioReis97** [comment]
These changes were not dont by me btw. I just saw them in the PR. Since a road map is already planned ( https://github.com/vuematerial/vue-material/issues/1081 ) maybe this feature will be available on next release. @pablohpsilva Could you please clarify us?

**Comment by rayfoss** [comment]
works on the stable 0.8.1, however the model needs to be pre initialized to an array. Initializing to null or undefined won't work
