### ISSUE TITLE
Reduce size of dependency when installed using npm

### ISSUE THREAD

**Issue by hanxue** [vuematerial/vue-material#1061]
I am using vue-material 0.7.4, and the total size of `node_modules/vue-material` comes in at a hefty 111.3 MB

Specifically there seems to be older versions under `dist/docs/releases`

```
--- ..node_modules/vue-material/dist/docs/releases ---
   55.5 MiB [##########] /v0.7.2                                                
   36.0 MiB [######    ] /v0.7.1
    2.2 MiB [          ] /v0.7.3
    2.0 MiB [          ] /v0.7.0
    1.9 MiB [          ] /v0.6.3
    1.9 MiB [          ] /v0.6.2
```

Is there any way to remove those older versions?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
