### ISSUE TITLE
Enchantments to md-chips

### ISSUE THREAD

**Issue by stgunholy** [vuematerial/vue-material#1063]
Hi.
I am really enjoying using your library, but I have couple of suggestions that can improve usability of md-chips for example. 
1) I think it can be great, if the keys that add the chip to array can be configurable... something like
md-add-keys="[',', ';']" - so when user presses , or ; the chip is created and added to array
2) Also I think that allowing to use md-chips inside md-input-container can be a good idea (now the label does not "float" when chip is added)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
