### ISSUE TITLE
[Snackbar] Does'nt work anymore after switching routes

### ISSUE THREAD

**Issue by KevinNTH** [vuematerial/vue-material#1064]
I have this issue since upgrading vue-material from 0.7.2 to 0.7.5

Anyway, this lib seems to not be maintained anymore. I have encountered so many bugs and regressions from the lib.

**Comment by zapping** [comment]
https://github.com/vuematerial/vue-material/issues/921

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by adamsaeid** [comment]
I believe I was experiencing the same issue.

It seemed to work again after closing the snackbar in the mounted lifecycle hook

E.g

```
mounted: function () {
  this.$refs.mysnackbar.close()
}
```
