### ISSUE TITLE
ref attribute not working with md-button component

### ISSUE THREAD

**Issue by ezyyinc** [vuematerial/vue-material#1065]
### Reproduction Link

Ref attribute works  as expected  using button tag but md-button   seems to    remove the tag. Any idea why?  Refs called in method returns undefined  when using md-button button works though

**Comment by zapping** [comment]
Please check this pen https://codepen.io/zapping/pen/xLOjBp?editors=1011 . A ref attribute has been added to the previous and next buttons. The status of the buttons are accessed in the previous and next step functions.

**Comment by ezyyinc** [comment]
Thank you! Must be a bug in my code. Im a new vue
