### ISSUE TITLE
Tooltip in a stepper throwing error

### ISSUE THREAD

**Issue by S9uare** [vuematerial/vue-material#1066]
### Steps to reproduce
Create a stepper and place a tooltip into any step other than first step.

### Which browser?
Latest vue, vuematerial
IE, FF latest, Chrome latest

### What is expected?
No error.

### What is actually happening?
An error `"[Vue warn]: Error in beforeDestroy hook: 'TypeError: Cannot read property 'parentNode' of undefined'` appears when placing tooltip into a stepper.

The problem only appears when the tooltip is not in the first step, and the tooltip itself still works.

### Reproduction Link
https://codepen.io/s9uare/pen/boorwq?editors=1111

**Comment by Doodlepants** [comment]
This may help pinpoint, the issue, the error doesn't appear when removing **md-vertica**l from :
**`<md-stepper md-vertical>`**

**Comment by S9uare** [comment]
This problem is not happening in 0.8.1.
Closing the ticket, thanks everyone's support
