### ISSUE TITLE
[mdInputContainer] use custom element has mdInput

### ISSUE THREAD

**Issue by gquintana** [vuematerial/vue-material#1069]
In order to use same syntax for editable fields and non editable fields, I'd like to write something like:
```
      <md-input-container class="md-has-value">
        <label>Message</label>
        <div class="md-input">{{ msg }}</div>
      </md-input-container>
```
It nearly renders as a MdInputContainer containing a MdInput, so I am not far from my goal.
However:
* I have to handle the md-has-value by myself
* The  `{{ msg }}` in the above example is not updated in the example below:

```
<template>
  <div class="hello">
    <h1>{{ msg }}</h1>
    <div>
      <md-input-container>
        <label>Message</label>
        <md-input v-model="msg"/>
      </md-input-container>
      <md-input-container class="md-has-value">
        <label>Message</label>
        <div class="md-input">{{ msg }}</div>
      </md-input-container>
    </div>
  </div>
</template>

<script>
export default {
  name: 'hello',
  data: function () {
    return {
      msg: 'Hello world'
    }
  }
}
</script>
```
When I change the value of the md-input, the <h1> is updated but not the <div class="md-input"> content

**Comment by zapping** [comment]
You can use the disabled or readonly property of the `<md-input>` to show the non-editable fields like this

```
<md-input-container>
        <label>Message</label>
        <md-input v-model="msg" disabled=true/>
</md-input-container>
```

**Comment by gquintana** [comment]
I know I can do that. But an input field still is an input field even when readonly/disabled, it looks and behaves as such (focus), and it can still be enabled in the browser.

I also would like to us checkboxes and custom components.

**Comment by zapping** [comment]
Try this for the non-editable fields
```
      <div class="md-input-container" :class="msg?'md-has-value':''">
        <label>Message</label>
        <div class="md-input">{{ msg }}</div> 
      </div>
```

**Comment by waratah** [comment]
does https://github.com/vuematerial/vue-material/issues/1075 help you?  Seems to be a similar question.

**Comment by gquintana** [comment]
Yes this is what I am doing, look at my code sample: but it's not documented, and value is not updated.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
