### ISSUE TITLE
flatpickr date picker broken due to md-input-container font size

### ISSUE THREAD

**Issue by hanxue** [vuematerial/vue-material#1075]
The following code is broken, and the selected date is not displayed:

```html
<main id="app">
  <h1>
   Vue flatpickr in vueMaterial
  </h1>
  <md-input-container>
  <flat-pickr v-model="projectDeadline" input-class="md-input" style="font-size:16px!important">
    </flat-pickr>
  </md-input-container>

  <hr> v-model: {{projectDeadline}}
</main>
```

[jsfiddle link](https://jsfiddle.net/hanxue/ccpownfq/1/)

The date will only be displayed in `<md-input>` if `<md-input-container>` is replaced with a `<div>`

```html
<div class="md-input-container md-theme-default md-has-value">
    <md-icon>schedule</md-icon>
    <label>Project Deadline</label>
    <flat-pickr v-model="projectDeadline" input-class="md-input" placeholder="Select a date">
    </flat-pickr>
  </div>
```

[jsfiddle link](https://jsfiddle.net/ankurk91/r1en6te0/)

An alternative is to set the font size:

```html
<flat-pickr v-model="projectDeadline" input-class="md-input" style="font-size:16px!important">
```

[jsfiddle link](https://jsfiddle.net/ankurk91/r1en6te0/3/)

There seems to be CSS issue with the font-size

Reference: https://github.com/ankurk91/vue-flatpickr-component/issues/28#issuecomment-335015538

**Comment by EricTran5791** [comment]
Looks like md-input-container is applying a font-size of 1px, which seems unnecessary. Testing a fix right now.

**Comment by EricTran5791** [comment]
I don't think you need to use md-input-container because you're not using md-input, md-autocomplete, or md-textarea.

**Comment by hanxue** [comment]
@EricTran5791 thanks for looking at this issue. Although `<flat-pickr>` is a custom component, it is a type of `<input>`. If I don't nest it in `<md-input-container>`, this is how it will look like

![image](https://user-images.githubusercontent.com/760008/31367917-fb8cafc0-adac-11e7-9b06-28e2112bb2fc.png)

This is the rendered HTML output:

```html
<input class="md-input flatpickr-input form-control input active" placeholder="" type="text" readonly="readonly">
```

**Comment by zapping** [comment]
Since you are not using `<md-input>` of vue-material the `<md-input-container>` cannot process or check the value inside its child. As a work around try setting the container with the class statically like this

```
  <md-input-container  class="md-has-value">
  <flat-pickr v-model="projectDeadline" input-class="md-input">
    </flat-pickr>
  </md-input-container>

```

**Comment by hanxue** [comment]
@zapping Adding `class="md-has-value"` works! Thank you for your explanation

**Comment by SergioReis97** [comment]
For others that might land here.

```
<md-input-container :class="myDate ? 'md-has-value' : ''">
   <label>Date</label>
   <flat-pickr :inputClass="'md-input'" v-model="myDate" ></flat-pickr>
</md-input-container>
```
Adding the ternary expression to class makes so that the pretty effect of the label going up happens with the change of the date

**Comment by waratah** [comment]
Although not entirely relevant, just referencing implement data picker task for other searchers through issues:

https://github.com/vuematerial/vue-material/issues/4 . - implement date picker

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/components/datepicker/
