### ISSUE TITLE
supports requirejs-vuejs.

### ISSUE THREAD

**Issue by daewooLeeNy** [vuematerial/vue-material#1080]
Hi.

I using vuejs, vue-material in my simple standalong(browser) project.
When i include require-vuejs(https://github.com/edgardleal/require-vuejs) in my project, did not work caused by conflict by vue-material and require-vuejs.

The following error occurred. 
> Uncaught TypeError: r.default is not a constructor
>     at Object.defineProperty.value (VM2216 vue-material.js:9)
>     at e (VM2216 vue-material.js:8)
>     at Object.defineProperty.value (VM2216 vue-material.js:11)
>     at e (VM2216 vue-material.js:8)
>     at Object.<anonymous> (VM2216 vue-material.js:13)
>     at e (VM2216 vue-material.js:8)
>     at Object.defineProperty.value (VM2216 vue-material.js:8)
>     at e (VM2216 vue-material.js:8)
>     at Object.<anonymous> (VM2216 vue-material.js:15)
>     at e (VM2216 vue-material.js:8)
> Object.defineProperty.value @ VM2216 vue-material.js:9
> e @ VM2216 vue-material.js:8
> Object.defineProperty.value @ VM2216 vue-material.js:11
> e @ VM2216 vue-material.js:8
> (anonymous) @ VM2216 vue-material.js:13
> e @ VM2216 vue-material.js:8
> Object.defineProperty.value @ VM2216 vue-material.js:8
> e @ VM2216 vue-material.js:8
> (anonymous) @ VM2216 vue-material.js:15
> e @ VM2216 vue-material.js:8
> (anonymous) @ VM2216 vue-material.js:15
> e @ VM2216 vue-material.js:8
> t.exports.t @ VM2216 vue-material.js:8
> (anonymous) @ VM2216 vue-material.js:8
> execCb @ VM2174 require.min.js:1
> check @ VM2174 require.min.js:1
> (anonymous) @ VM2174 require.min.js:1
> (anonymous) @ VM2174 require.min.js:1
> (anonymous) @ VM2174 require.min.js:1
> each @ VM2174 require.min.js:1
> emit @ VM2174 require.min.js:1
> check @ VM2174 require.min.js:1
> enable @ VM2174 require.min.js:1
> init @ VM2174 require.min.js:1
> h @ VM2174 require.min.js:1
> completeLoad @ VM2174 require.min.js:1
> onScriptLoad @ VM2174 require.min.js:1
> 

(I guess vue-material refer to 'vue' using define())

Is require-vuejs possible support in VueMaterial?

`
!(function(t, e) { "object" == typeof exports && "object" == typeof module ? module.exports = e(require("vue")) : "function" == typeof define && define.amd ? define(["vue"], e) : "object" == typeof exports ? exports.VueMaterial = e(require("vue")) : t.VueMaterial = e(t.Vue) })(this, (function(t) {
`

VueMaterial add in require-vuejs simple example below.
(base on https://github.com/edgardleal/require-vuejs#source-code-example)
```
    requirejs.config({
        paths: {
            "Vue": "https://cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.min",
            "vue-material": "https://unpkg.com/vue-material@0.7.5/dist/vue-material.js"
            "vue": "https://rawgit.com/edgardleal/require-vue/master/dist/require-vuejs"
        },
        shim: {
            "Vue": {"exports": "Vue"},
            "vue-material": {"deps":["Vue"]}
        }
    });
    require(["Vue", "vue-material",  "vue!component"], function(Vue, VueMaterial){
        Vue.use(VueMaterial);
        var app = new Vue({
            el: "#app"
        });
    });
```

Thanks.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
