### ISSUE TITLE
[md-select] - Console error

### ISSUE THREAD

**Issue by waratah** [vuematerial/vue-material#1083]
### Steps to reproduce

Create an md select inside a td with no class variables.

main.236a1a6d88ded0bb675c.js:1207 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'contains' of undefined"

### Which browser?
Chrome

### What is expected?

no errors

### What is actually happening?

main.236a1a6d88ded0bb675c.js:1207 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'contains' of undefined"

**Comment by waratah** [comment]
This is in getClosestVueParent when the class list is not defined.

if ($parent.$el.classList.contains(cssClass)) {
    return $parent;
 }

I have replaced this with:

if ($parent.$el.classList && $parent.$el.classList.contains(cssClass)) {
    return $parent;
  }

**Comment by waratah** [comment]
I have also found this to be caused by not containing md-list-item inside md-list.  This cause parent to be just false which is in turn not handled by mdlistitemexpand.

Short term I have injected these lines into resetSiblings to handle this issue.

 resetSiblings() {
        if( this.parentList === false ) {
          throw "resetSiblings called without parent list being constructed, md-list-item not contained in md-list?"; 
        }

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
