### ISSUE TITLE
[Request + Temporary Solution] Autocomplete [{ text: '', value: ''}] as options.

### ISSUE THREAD

**Issue by xxRockOnxx** [vuematerial/vue-material#1086]
- What will it allow you to do that you can't do today?
    - have v-model return the value specified.
  - How will it make current work-arounds straightforward?
    - Have the value inside v-model automatically instead of manually setting in a callback for `@selected`
  - What potential bugs and edge cases does it help to avoid?
    - None.

I can make a PR when I got the time.

# Temporary Workaround
```
<md-autocomplete v-model="selected" @selected="onSelect" />

onSelect(option) {
  this.realSelected = option.value
}
```

**Comment by zapping** [comment]
It does already set the v-model automatically. Do check this pen https://codepen.io/zapping/pen/GmVapv and try selecting a state.

**Comment by xxRockOnxx** [comment]
the value passed to `v-model` is just the text identified by `print-attribute`

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
