### ISSUE TITLE
[md-select] - how to bind object to value?

### ISSUE THREAD

**Issue by monochromatique** [vuematerial/vue-material#1088]
I did not find anything in the documentation about this.

Actually - I can bind the object to a value - I can not get it selected when updating the component.

In AJS there was such a feature - "track by"

In :key attribute I can not set NOT plain object. I tried to set it to `:key={key:role.key}`

Is there a way?

```
<md-input-container>
            <label for="roles">roles</label>
            <md-select name="roles" id="roles" multiple v-model="item.roles">
                <md-option v-for="role in roles" v-bind:key="role.key" v-bind:value="role">
                    {{role.name}}
                </md-option>
            </md-select>
        </md-input-container>
```

**Comment by monochromatique** [comment]
```            
<select name="roles" id="roles" multiple v-model="item.roles">
     <option v-for="role in roles" v-bind:key="role.key" v-bind:value="role">
          {{role.name}}
     </option>   
</select> 
```

This code work as expect. I can't get it work with md-select

**Comment by xxRockOnxx** [comment]
What is `item.roles`? and `roles` also Can you provide more details?

**Comment by monochromatique** [comment]
Thanks for replay. Nevermind anyway. Switch to vuetify solved many problems.

**Comment by waratah** [comment]
This is a Vue question not a md-select one.  Just checked and I have never mixed v-for with md-option.  Probably will one day.

Key here refers to v-for not md-option at all.   The key would not normally be a composite key like that, something like an id for the roles themselves so that if a role is dropped or added in the middle Vue can quickly just remove that particular option.

**Comment by monochromatique** [comment]
it's ok, but how achieve my goal?

Can do it with pure HTML,
can do it with vuetify,
but can't do it with VUE Material

**Comment by Samuell1** [comment]
This should work:
```
<md-input-container>
  <label for="items">Label</label>
  <md-select name="items" id="items" multiple v-model="selectedItems">
      <md-option v-for="item in items" :key="item.id" :value="item">
        {{ item.name }}
      </md-option>
  </md-select>
</md-input-container>
```

**Comment by monochromatique** [comment]
2 Samuell1

You are really think, I did not do that?

It works for "filling form" time, but when you will try to open draw existing data - it fails

**Comment by zapping** [comment]
I tried to add this to a pen, https://codepen.io/zapping/pen/vZyrJm . Can you check if this is what you were trying to get to.
