### ISSUE TITLE
[mdAutocomplete] Using md-autocomplete with Axios

### ISSUE THREAD

**Issue by Linzdigr** [vuematerial/vue-material#1090]
In spite of the doc, I haven't find out yet how to get md-autocomplete work with a fetch function returning a promise (Axios).

Here is the code:

**Template:**
```vue
                <md-input-container md-clearable>
                    <label for="titre">Titre</label>
                    <md-autocomplete
                        id="titre"
                        name="titre"
                        v-model="titre"
                        print-attribute="name"
                        :minChars="3"
                        :debounce="1000"
                        :fetch="fetchSuggestion">
                     </md-autocomplete>
                </md-input-container>
```

**The method:**

```js
            fetchSuggestion(param) {
                var t = encodeURIComponent(param.q)
                return Axios.post(`api/suggestion/${t}`, {
                    app_uuid: APP_KEY
                }, {
                    _progress: {
                        context: this
                    }
                })
            },
```

**Remote response format:**

```json
[{"name":"bar","similarity":75},{"name":"foo","similarity":90}]
```

What am I missing?

**Comment by zapping** [comment]
Can you please mention what you get now too? Like any errors, warnings or unexpected results.

**Comment by Linzdigr** [comment]
Sure! When I input something into the field, no error nor warning, the fetchSuggestion is correctly fired and results occured in the network stack as expected but nothing happen next. Is returning simply the promise to fetch props is enough?

**Comment by Linzdigr** [comment]
Finally get it working passing prepareResponseData function props to format data. The first try with was unsuccessful because I was using a then() on the promise before returning it to fetchSuggestion (resulting in undefined value).
Thanks anyway!

**Comment by tsega** [comment]
It would be so great if you could share your entire solution here. I couldn't figure out how the autocomplete works just by reading the docs.

**Comment by Linzdigr** [comment]
Unfortunately, I haven't any example on hand where I am but passing a prop `:prepare-response-data` with your custom formater function which returuns an array of objects formated like so `[{text:'Displayed text', value: 'myVal'}]` worked for me.

**Comment by zapping** [comment]
@tsega I don't have one with Axios but here is a pen with lists if that will help
https://codepen.io/zapping/pen/GmVapv

**Comment by tsega** [comment]
@zapping Your example worked just fine but I couldn't really get it to work for my case.  I am using Meteor as my back end. I eventually settled for the Multi-Select component, it seems to do the job with minimum fuss. 
Thanks again for the help!
