### ISSUE TITLE
[mdAutocomplete] Clearable container generates error

### ISSUE THREAD

**Issue by Linzdigr** [vuematerial/vue-material#1091]
### Steps to reproduce
Use a md-autocomplete component inside a `md-input-container` with `md-clearable` prop set:

```vue
<md-input-container md-clearable>
    <label for="titre">Titre</label>
    <md-autocomplete
        id="titre"
        name="titre"
        v-model="titre"
        print-attribute="name"
        :min-chars="3"
        :debounce="1000"
        :prepare-response-data="formatSuggResponse"
        :fetch="fetchSuggestion">
    </md-autocomplete>
</md-input-container>
```

Click on the empty button

### Which browser?
Chrome latest

### What is expected?
Input to be cleared

### What is actually happening?
Got errors:

```
[Vue warn]: Error in event handler for "click": "TypeError: Cannot read property '$el' of null"

found in

---> <MdButton>
       <MdInputContainer>
         <MdLayout>... (2 recursive calls)
           <Anonymous>
             <MdLayout>
               <VTouch>
                 <Root>
```

> foo.js:2284 TypeError: Cannot read property '$el' of null
>     at VueComponent.clearInput (foo.js:15015)
>     at boundFn (foo.js:783)
>     at Proxy.invoker (foo.js:2534)
>     at Proxy.Vue.$emit (foo.js:3040)
>     at click (foo.js:15019)
>     at invoker (foo.js:2534)
>     at HTMLButtonElement.fn._withTask.fn._withTask (foo.js:2369)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
