### ISSUE TITLE
NPM VueMaterial Missing Code

### ISSUE THREAD

**Issue by djayd** [vuematerial/vue-material#1092]
It appears that code is missing from the VueMaterial v0.7.5 NPM package. We referenced the Md-Checkbox component, but it's missing the array functionality. When you view the NPM source code you can see that the "Array" type is missing, but whenever you download the 0.7.5 source code from the site directly, it is there.

I've also tried to use the newer layout attributes and they appear to be missing as well. (not looked at the code to verify 100%)

Is the NPM code being published from the same code base as the site?

**Comment by VdustR** [comment]
I checked the network graph and found that it's added after `0.7.5` released in the master branch.

I think the official documentation should stay in tag `0.7.5` instead of `master` branch.

I mentioned about this in slack channel `#random`.

**Comment by marcosmoura** [comment]
I released a new version today. It was mistakenly upload from master. Should be stable now!
Shame on me!
