### ISSUE TITLE
When scroll the page, elements "re-rendered"

### ISSUE THREAD

**Issue by ansonhorse** [vuematerial/vue-material#1093]
First of all, thanks for the great contributions!

The following description has been bothering me for some time.
Please see the gif: a table with about 200 items, and when scroll the page, the elements are re-rendered.

![vuematerial-issue](https://user-images.githubusercontent.com/7548142/31780800-5bc2e5b6-b529-11e7-91cf-3a57d10d1dd4.gif)

### Steps to reproduce
Please see the codepen below
### Which browser?

Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

### Reproduction Link
[https://codepen.io/ansonhorse/pen/XeOyVm](https://codepen.io/ansonhorse/pen/XeOyVm)

**Comment by ansonhorse** [comment]
Anybody else meet this problem?

**Comment by Samuell1** [comment]
Looks like issue with chrome, this is gif from firefox nightly
![2017-10-23_08-47-31](https://user-images.githubusercontent.com/3110002/31875530-e13e58a4-b7ce-11e7-9f93-0eca020e6287.gif)

**Comment by ansonhorse** [comment]
@Samuell1 Thanks for the reply.
Actually this's an page on a chrome extension I wrote, so I've never tested it on other browsers before.

**Comment by xxRockOnxx** [comment]
Tried pen on chrome. Looks good to me.

**Comment by Samuell1** [comment]
It can be missing GPU drivers
