### ISSUE TITLE
[md-select] in md-dialog stays open

### ISSUE THREAD

**Issue by Linzdigr** [vuematerial/vue-material#1097]
### Steps to reproduce
Implement an md-select into a md-dialog, then open the select and close the dialog by clicking outside of it.

### Which browser?
Chrome latest

### What is expected?
The whole to be closed and disappear.

### What is actually happening?
The modal is closed but the select menu stays open until you click one of its items.

Is there a way to provide a close event on the md-select component?

**Comment by VdustR** [comment]
Could you reproduce it in [codepen](https://codepen.io)?

The select menu would be closed at the first click before closing the dialog.

Here is my [code](https://codepen.io/VdustR/pen/BweOXb).

**Comment by Linzdigr** [comment]
Thanks for your time it helps me to understand, actually the backdrop was not filling all the display because of a `height: 100%` set to `body` .. 
Deleting this solved this issue.

Thanks again ;)
