### ISSUE TITLE
[snackbar] "TypeError: Object doesn't support this action" in IE11

### ISSUE THREAD

**Issue by Aymkdn** [vuematerial/vue-material#1099]
### Steps to reproduce
Go to the documentation website [http://vuematerial.io/#/components/snackbar](http://vuematerial.io/#/components/snackbar) into IE11.
Open the web console (F12).
The console says:
```
Error in mounted hook: "TypeError: Object doesn't support this action"  
Found in   
---> <MdSnackbar>
```

### Which browser?

VueMaterial 0.7.5
Internet Explorer 11

### What is expected?

No warning message.

**Comment by Aymkdn** [comment]
This is due to [`this.removedSnackBarElementEvent = new Event(this.removedSnackBarElementEventName);`](https://github.com/vuematerial/vue-material/blob/master/src/components/mdSnackbar/mdSnackbar.vue#L164) 

`new Event` for custom events is not valid in IE. You should apply a ([short polyfill](https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work))

Thanks

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
