### ISSUE TITLE
0.8.0 MdIconButton color defaulting to black instead of white

### ISSUE THREAD

**Issue by RedTn** [vuematerial/vue-material#1102]
### Steps to reproduce
From 0.7.5 -> 0.8.0, it seems all the icon buttons are being rendered in black instead of white on a default toolbar theme.
>         
      <md-toolbar>
      <md-button class="md-icon-button" @click="toggleLeftSidenav">
        <md-icon>menu</md-icon>
      </md-button>
      .....
      <md-button class="md-icon-button" @click="transition('users')">
        <md-icon>account_circle</md-icon>
      </md-button>
    </md-toolbar>

### Which browser?
Chrome Version 61.0.3163.100
### What is expected?
![image](https://user-images.githubusercontent.com/3923164/31981436-23985d14-b908-11e7-9b8d-0125a75cfddf.png)
![image](https://user-images.githubusercontent.com/3923164/31981446-2eb765dc-b908-11e7-8651-099e0488d496.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/3923164/31981459-45f9fd36-b908-11e7-9e5d-cd877ac39314.png)
![image](https://user-images.githubusercontent.com/3923164/31981464-4e4e63b4-b908-11e7-97ab-202b72132187.png)

**Comment by marcosmoura** [comment]
#1101
