### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by cars10** [vuematerial/vue-material#1103]
Hi, could you provide a changelog please? It's annoying to find out by trial & error what changed between the versions.

**Comment by alxpez** [comment]
It seems like the [changelog](http://vuematerial.io/#/changelog) got stuck on version 0.7.1

**Comment by marcosmoura** [comment]
I agree with you. I will provide the changelog for the new versions, with a automatic changelog.

**Comment by alxpez** [comment]
Nonetheless, great job @marcosmoura, really looking forward to see the 1.0.0 version!

**Comment by marcosmoura** [comment]
Two weeks!

**Comment by cars10** [comment]
So what is the changelog?
