### ISSUE TITLE
 Ink Ripple doesn't work

### ISSUE THREAD

**Issue by rony13** [vuematerial/vue-material#1110]
hi, my tools are:

- vue-material 0.8.1
- vue 2.4.2
- chrome, the latest version

i just follow the demo：
```
<div class="has-ripple">
  <md-ink-ripple />
  This div has ripple effect
 </div>
```
 but the ink ripple component doesn't work. BTW card-ripple works well
i have no idea of handling it, please give me a hand

**Comment by waratah** [comment]
ripple effects are mode for input's that are selected or menus that are clicked and highlighted.   You change the class and then the transition comes into effect.

**Comment by zapping** [comment]
Try this one
```
<div class="has-ripple">
  <md-ink-ripple></md-ink-ripple>
  This div has ripple effect
 </div>
```

Try clicking on the text 'This div has ripple effect' on this pen https://codepen.io/zapping/pen/bBPyOz

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
