### ISSUE TITLE
table row height

### ISSUE THREAD

**Issue by mhsystem** [vuematerial/vue-material#1112]
I'm sorry for my question, but how can I change row height of table to minimum?

Thanks

**Comment by zapping** [comment]
Sorry didn't get you on the 'minimum' one. Like you want to set a min-height or you want the table to auto adjust height?

**Comment by mhsystem** [comment]
It is easy, I don't know how can I change height of table row. When I use style=height:15px, it looks that nothing changed

**Comment by zapping** [comment]
Try changing this class in your css and set it to your required height.
```
.md-table {
    height:400px;
}
```

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
