### ISSUE TITLE
Enter button listener to <md-input>

### ISSUE THREAD

**Issue by VladPavliuk** [vuematerial/vue-material#1115]
Hello, I found you lib very useful, but I encountered with one problem, How could I registered enter pressing on <md-input> field? I found only @keydown.up, @keydown.down and they trigger onInput() method. Could you add @keydown.enter to <md-input> witch will trigger onEnter event, or some thing like this?

**Comment by Samuell1** [comment]
Use `@keydown.up.native`, `@keydown.down.native`

**Comment by VladPavliuk** [comment]
@Samuell1 Dude, thanks, it works =)
