### ISSUE TITLE
md-select in md-step throwing errors

### ISSUE THREAD

**Issue by ashmorr** [vuematerial/vue-material#1116]
### Steps to reproduce

When using a vertical stepper where each step contains a md-select several vue-warn's are outputted to the console on render complaining about 'TypeError: t.$refs.backdrop is undefined'  and 'TypeError: this.menuTrigger is undefined'. 

Things I've found whilst trying to find a solution:
- If I remove the selects from all but the first step, the errors do not occur.
- If I remove md-vertical from the stepper the error does not occur even with the selects in each step.

Example code:
` <md-stepper md-vertical>
      <md-step>
        <md-input-container>
            <label>Label</label>
            <md-select>
                <md-option>Option</md-option>
            </md-select>
        </md-input-container>
      </md-step>
    <md-step>
        <md-input-container>
            <label>Label</label>
            <md-select>
                <md-option>Option</md-option>
            </md-select>
        </md-input-container>
      </md-step>
     <md-step>
        <md-input-container>
            <label>Label</label>
            <md-select>
                <md-option>Option</md-option>
            </md-select>
        </md-input-container>
      </md-step>
</md-stepper>` 

### Which browser?
Vue & Vue Material: Latest versions
All latest browsers (Firefox 56) 

### What is expected?
Clean console output

### What is actually happening?
Console errors are being raised complaining about 
Error in nextTick: 'TypeError: t.$refs.backdrop is undefined'
Error in beforeDestroy hook: 'TypeError: this.menuTrigger is undefined'

### Reproduction Link
https://codepen.io/ashmorr/pen/RjGJpM?editors=1111

**Comment by zapping** [comment]
This seems strange. The error shows up only if you have a md-select but you don't get errors if you have any other component, in a step other than the first one.

Try removing the md-select from the 2nd and 3rd steps you don't get the error. But try keeping a md-step in either the 2nd or 3rd step you get the error.

**Comment by ashmorr** [comment]
@zapping and, if you remove the md-vertical from the stepper you don't get any errors either, even with the selects in step 1-3!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
