### ISSUE TITLE
md-list-expand inside md-sidenav don't work

### ISSUE THREAD

**Issue by Isaiasdd** [vuematerial/vue-material#1124]
### Steps to reproduce

-- create a md-toolbar
-- create a md-sidenav
-- create a md-list and md-list-expand

### Which browser?
vue js 2.1.6
chrome 61

### Reproduction Link

https://codepen.io/isaiasdd/pen/QOvMmK

**Comment by VdustR** [comment]
Position class is required by [`md-sidenav`](http://vuematerial.io/#/components/sidenav):

Name | Description
-- | --
`md-left` | Display the sidenav on the left of parent
`md-right` | Display the sidenav on the right of parent
`md-fixed` | Apply position fixed

Add the class and it would work:
```html
<md-sidenav class="md-left" ref="sidenav">
```

then open the `sidenav` via `this.$refs.sidenav.open()`.
