### ISSUE TITLE
md-radio not showing right

### ISSUE THREAD

**Issue by awoyele** [vuematerial/vue-material#1125]
Md-input is skewed in smaller screens e.g phones when the label has a long value
![screen shot 2017-11-12 at 4 42 00 pm](https://user-images.githubusercontent.com/16243076/32704487-99583db8-c7cb-11e7-84b9-5af5a3b3a77a.png)

**Comment by waratah** [comment]
This issue caused me to abandon radio buttons.   Definitely a problem.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
