### ISSUE TITLE
make header optional

### ISSUE THREAD

**Issue by cotterjd** [vuematerial/vue-material#1131]
this should be as simple as adding a boolean prop

**Comment by marcosmoura** [comment]
Can you provide more description of the issue?

**Comment by cotterjd** [comment]
![screen shot 2017-11-16 at 3 49 41 pm](https://user-images.githubusercontent.com/2576700/32917794-e5c668ec-cae5-11e7-97a5-a341aa4a4f46.png)
This is a feature request. I already have it implemented locally. But I'd like to see it in the main repo, so I don't have to maintain my own. 

My specific issue is that I wanted the stepper, but I had so many steps that the numbers in the header ran off the page. So I just wanted to disable the header and not have the numbers on top. 
![screen shot 2017-11-16 at 3 50 09 pm](https://user-images.githubusercontent.com/2576700/32917809-f406cff0-cae5-11e7-9c6d-5c2fd08a3de4.png)

**Comment by VdustR** [comment]
You could hide them via css.

## v1.0.0

```html
<template>
  <md-steppers class="hidden-head">
    <!-- your md-steps -->
  </md-steppers>
</template>

<style lang="scss" scoped>
.hidden-head /deep/ .md-steppers-navigation {
  display: none
}
</style>
```

## v0.8.1

```html
<template>
  <md-steppers class="hidden-head">
    <!-- your md-steps -->
  </md-steppers>
</template>

<style lang="scss" scoped>
.hidden-head /deep/ .md-steps-navigation {
  display: none
}
</style>
```

**Comment by cotterjd** [comment]
that could work. You got any tricks for attaching a function onto the continue button?
