### ISSUE TITLE
md-datepicker not working on firefox

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#1135]
On Chromium it works as expected.

### Steps to reproduce

Accessing https://vuematerial.io/components/datepicker and clicking on the input/icon.

### Which browser?

Firefox 56.0
Ubuntu 17.04

### What is expected?

The datepicker dialog be visible when accessing the input.

### What is actually happening?

Nothing.

### Reproduction Link

https://vuematerial.io/components/datepicker

**Comment by marcosmoura** [comment]
It's on the documentation website:
`The datepicker dialog is disabled in Firefox, because it have a built-in Datepicker on desktop.`
:)

**Comment by lucasfernog** [comment]
But shouldn't the built-in datepicker be visible when trying to use the input? Also, the framework's datepicker can't work on Firefox? It would be nice to allow that.

**Comment by abhay7030** [comment]
Can you please allow Firefox to use framework datepicker? The website will feel same for great user experience.
