### ISSUE TITLE
md-overlay above md-dialog

### ISSUE THREAD

**Issue by ivomarsan** [vuematerial/vue-material#1138]
### Steps to reproduce

I just installed the new version of vue-material with
```
$ npm install vue-material@beta --save
```
And I try to use Custom Dialog Markup Example from https://vuematerial.io/components/dialog

### Which browser?

`"vue": "^2.4.4",`
`"vue-material": "^1.0.0-beta-4",`
__Others details:__
_Browser_: Firefox Developer Edition 58.0b1 (64-bit)
_OS_: Windows 10

### What is expected?

Its expected 
https://screenshots.firefox.com/dJWuflaFYrogbOss/vuematerial.io
![IMG](https://screenshots.firefoxusercontent.com/images/37cece06-282e-4cb8-b3e2-4fc68b2cab8c.png)

### What is actually happening?

Its happening
https://screenshots.firefox.com/engQkOJC4Vc8S5jk/localhost
![IMG](https://screenshots.firefoxusercontent.com/images/9d0a38b0-4d9e-4447-9a60-f7865d60ec3e.png)

### Reproduction Link

https://jsfiddle.net/p2msah66/

But I fixed with
```
<md-dialog :md-active.sync="showDialog" style="background-color: #fff; background-color: var(--md-theme-demo-light-background,#fff); color: rgba(0,0,0,.87); color: var(--md-theme-demo-light-text-primary-on-background,rgba(0,0,0,.87)); }">
```
Waiting for new version

**Comment by Samuell1** [comment]
Can you please make codepen?

**Comment by ivomarsan** [comment]
``` json
"vue": "^2.5.8"
```
But, how can I do
``` js
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'
```
in JSFiddle / codepen ?

**Comment by ivomarsan** [comment]
Has been fixed

**Comment by NobelLiu** [comment]
@ivomarsan Hi there,
I have the same issue today, how you fix this?

**Comment by schmurfy** [comment]
I got the same issue so I checked the doc and when generating a codepen from the doc I also have the issue: https://codepen.io/anon/pen/dJOVBB?&editors=111

when you open the dialog the overlay is above the dialog...
As a workaround I tried to `md-backdrop` to false but it did not appear to do much :(

I tested this with the latest firefox & Chrome on OS X and win8, same result.

**Comment by VdustR** [comment]
@schmurfy hi, I checked your codepen and I found that might be another issue. The `MdDialog` do not have background therefore it's looks under the overlay. If you set a white background to it, it would looks fine. I'll open an issue for it.

**Comment by VdustR** [comment]
@schmurfy Would you check #1335 and replace the theme `.css` with [`https://unpkg.com/vue-material@beta/dist/theme/default.css`]()? That link [`https://cdn.rawgit.com/vuematerial/vue-material/master/dist/default-theme.css`]() in your reproduction is `404: Not Found`.

**Comment by schmurfy** [comment]
Thanks, I was missing the theme it works fine with it but the documentation should be fixed since the codepen I linked above was created directly by it.
