### ISSUE TITLE
theme-color html tag overridden by 'undefined'

### ISSUE THREAD

**Issue by jflaflamme** [vuematerial/vue-material#1139]
### Steps to reproduce

<meta name="theme-color" content="undefined">

Vue 0.8.1

### What is expected?
Having my primary color instead of undefined
`<meta name="theme-color" content="primary color">
`
### What is actually happening?

`<meta name="theme-color" content="undefined">
`
### Reproduction Link

the template is having the same problem

http://codepen.io/vue-material/pen/WGavBE

![image](https://user-images.githubusercontent.com/712558/32815479-dfdffd12-c9e6-11e7-9c11-1da2ef885388.png)

A nice fallback will be not to override the meta tag when the value is undefined. However, I still don't understand why it is undefined.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
