### ISSUE TITLE
Creating themes display error.

### ISSUE THREAD

**Issue by parasaro92** [vuematerial/vue-material#1140]
I am not able to create a theme in project.
Webpack is showing error related to 
@import "vue-material/dist/theme/engine.scss"
@include md-register-theme("default", (
  primary: #3fffbe, // The primary color of your brand
  accent: #1a11e8 // The secondary color of your brand
));

@import "~vue-material/dist/theme/all"
![screenshot from 2017-11-15 11-54-56](https://user-images.githubusercontent.com/13597713/32821891-da2df256-c9fb-11e7-9b2a-3c6bb9771b06.png)

**Comment by Samuell1** [comment]
Hey, you cant put SCSS inside JS file. Make new `*.scss` file and import it

**Comment by parasaro92** [comment]
Thanks
