### ISSUE TITLE
Documentation Page of V0.8.1

### ISSUE THREAD

**Issue by phil1996s** [vuematerial/vue-material#1143]
Hey there, 

very nice beta but I use the version 0.8.1 for a stable project and therefor the beta is in some animations very laggy and not so stable like the 0.8.1. Where can I access the old documentation site?

**Comment by Samuell1** [comment]
https://vue-material-old.netlify.com

**Comment by VdustR** [comment]
Duplicated #1133.

**Comment by Dafrok** [comment]
I suppose it's nessesary to have an entry of old version in current documentation.

**Comment by marcosmoura** [comment]
I'm working at this right now!

**Comment by Samuell1** [comment]
Link to old docs is now at snackbar on bottom of window.
