### ISSUE TITLE
Table selection doesn't work if the table model is empty initially

### ISSUE THREAD

**Issue by azzzy** [vuematerial/vue-material#1146]
### Steps to reproduce

Try to select a row in the provided codepen. The data is loaded asynchronously after a 200ms delay to simulate an AJAX call.

### Which browser?

All

### What is expected?

Table rows should be selectable

### What is actually happening?

Table rows can't be selected, the "default" cursor is shown instead of "pointer"

As a workaround you can add v-if to the table, so the initialization will be done after the data is retrieved, which isn't ideal, because the table header isn't visible also (see https://codepen.io/danyalex/pen/qVPrEN)

### Reproduction Link
https://codepen.io/danyalex/pen/WXZRZd

**Comment by zapping** [comment]
You can try adding an empty state tag, `md-table-empty-state`, to the table between the `md-table-toolbar` and the `md-table-row` tags , something like this

`<md-table-empty-state md-label="Loading..."></md-table-empty-state>`

https://vuematerial.io/components/table Search and empty table has this example

**Comment by marcosmoura** [comment]
This is definitely an issue. I will take a deep look. Shouldn't be tricky.
