### ISSUE TITLE
Official website router issue

### ISSUE THREAD

**Issue by VdustR** [vuematerial/vue-material#1148]
After click links in the documentation, the URL will changed, but that URL direct to a wrong path actually.

### Steps to reproduce

Click any link and request the URL via address bar.

### What is expected?

Direct to the right page.

### What is actually happening?

That URL direct to `404 Not Found`.

### Reproduction Link

For example: https://vuematerial.io/components/app

![peek 2017-11-16 11-50](https://user-images.githubusercontent.com/29639463/32873162-90ed7a60-cac5-11e7-9749-f49240840174.gif)

**Comment by zapping** [comment]
The github link on the top right of the pages too leads to Page Not Found

**Comment by VdustR** [comment]
@zapping #1142

**Comment by Samuell1** [comment]
There is bug with router and prerendering, we need to wait for fix.

**Comment by marcosmoura** [comment]
I'm aware of this behaviour. I will fix it today. Sorry for that!
This is due to an implementation on Netlify server.

**Comment by VdustR** [comment]
Fixed.
