### ISSUE TITLE
z-index of FAB in 1.0.0 too low

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1157]
### Steps to reproduce

Write a regular page, have some elements in a corner and add a Floating Action Button

### Which browser?

All browsers, Vue Material 1.0.0@beta4

### What is expected?

Floating Action Button should display over lower elements

### What is actually happening?
![screenshot from 2017-11-17 11-44-56](https://user-images.githubusercontent.com/6295583/32928519-3b8eee32-cb8d-11e7-8d0c-d97d3d7ca856.png)
(This is a card element overlapping)

**Comment by Samuell1** [comment]
Use css to position it how you like it? `:style:"{ zIndex: '9999' }"`

**Comment by emman27** [comment]
Where that's completely possible and a natural fix I do believe this warrants an actual fix in the source rather than leaving it for each user to implement

**Comment by marcosmoura** [comment]
This will be fixed ASAP!

**Comment by Samuell1** [comment]
@emman27 do you used classes `md-fixed md-fab-bottom-right` ?

**Comment by emman27** [comment]
Wasn't using md-fixed, though adding it doesn't solve the problem.

Read through your PR as well. Not sure about changing md-menu and the nav - kinda worries me about regressions. Is there a convention to z-indexes somewhere?

**Comment by Samuell1** [comment]
@emman27 can you provide your code?

**Comment by emman27** [comment]
Simplest example below. In particular, it's hidden by a card - which makes your PR perfect for my usage - then again it's not about my usage but more about working well for everyone.

Shouldn't the solution be to change the z-index of the md-fab classes instead of moving menu and card around?

```
  <md-button class="md-fab md-fab-bottom-right md-mini">
    <md-icon>help</md-icon>
    <md-tooltip md-direction="top">Need help?</md-tooltip>
  </md-button>
```

**Comment by Samuell1** [comment]
I changed it and now its working :)

![obrazok](https://user-images.githubusercontent.com/3110002/33664288-571df12e-da93-11e7-84b3-73579fe47660.png)
