### ISSUE TITLE
[mdField] keydown.enter sometimes got InputEvent object as it's v-model value

### ISSUE THREAD

**Issue by VdustR** [vuematerial/vue-material#1160]
### Steps to reproduce

In the official website, go to [Vue Material - Chips](https://vuematerial.io/components/chips) page.

Check **Editable model** example and insert chips quickly.

Got result like:
![selection_001](https://user-images.githubusercontent.com/29639463/32936251-72ae8230-cbae-11e7-8865-d2e7d54baf44.png)

I `console.log` that value in `insertChip()` method got this:
* Chrome: ![image](https://user-images.githubusercontent.com/29639463/32936332-d5e6a21a-cbae-11e7-9753-4d85bb79bb02.png)
* Firefox: ![image](https://user-images.githubusercontent.com/29639463/32936358-e915b4c0-cbae-11e7-8d8b-e98d752c1629.png)

### Which browser?

Google Chrome 62.0.3202.94 (64bit) and Firefox 56.0 (64bit) tested.

### What is expected?

`v-model` value should always be `String`.

### What is actually happening?

Sometimes got `InputEvent` object.

### Reproduction Link

https://vuematerial.io/components/chips

**Comment by marcosmoura** [comment]
This is due a change in Vue 2.5.3. I will change my implementation here to match with those changes.

**Comment by VdustR** [comment]
Related to Vue[#6846](https://github.com/vuejs/vue/issues/6846), [#7042](https://github.com/vuejs/vue/issues/7042).

According [#7042#issuecomment-344948474](https://github.com/vuejs/vue/issues/7042#issuecomment-344948474):

I tried:
```html
<input type='text' v-model='model' v-bind='$attrs' 
  v-on="{
    ...$listeners,
    input: event => $emit('input', event.target.value)
  }">
```
and it works.

Demo: [Codepen](https://codepen.io/VdustR/pen/gXeBmG)

**Comment by korylprince** [comment]
FYI, this happens even on `md-input`.

**Comment by marcosmoura** [comment]
Already fixed. Will release this soon!
