### ISSUE TITLE
[md-datepicker] shows day before the date given when initialized with a date

### ISSUE THREAD

**Issue by heymrcarter** [vuematerial/vue-material#1162]
### Steps to reproduce

install vue-material beta
add a md-datepicker to component and v-model bind it to a date property with a Date
the date displayed in the UI is the previous day

### Which browser?

vue: 2.5.2
vue-material: 1.0.0-beta-4
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### What is expected?

It should display the correct date

### What is actually happening?

Is displaying the date before the date given

### Reproduction Link

The bug is actually visible on the [md-datepicker documentation](https://vuematerial.io/components/datepicker); the date given is

    new Date('2018-03-26')

but the date rendered in the example is 03/25/2018

**Comment by VdustR** [comment]
It's not a bug.

`new Date('2018-03-26')` means 2018/03/26 00:00:00 UTC

`new Date('2018/03/26')` means  2018/03/26 00:00:00 in your timezone area.

**Comment by marcosmoura** [comment]
I will change Datepicker to work based on user Locale.
