### ISSUE TITLE
[md-file] Uncaught TypeError: this.onInput is not a function

### ISSUE THREAD

**Issue by CaiJimmy** [vuematerial/vue-material#1163]
### Steps to reproduce
1. Create a `<md-file>`
2. Select a file
3. Check console error
### Which browser?

* Browser: Chrome Version 62.0.3202.94 (Official Build) (32-bit)
* OS: Windows 10

### Reproduction Link

![image](https://user-images.githubusercontent.com/5889006/32960764-7318ac7e-cbc6-11e7-8521-091294f60ab7.png)

https://vuematerial.io/components/file

**Comment by marcosmoura** [comment]
Have you found this issue on documentation site?

**Comment by CaiJimmy** [comment]
@marcosmoura 

Yes:

![image](https://user-images.githubusercontent.com/5889006/32989609-f878c882-cd19-11e7-9eae-ac0e3d7f6efa.png)
