### ISSUE TITLE
[md-tabs] [help-wanted] Tabs content does not display on RTL directions

### ISSUE THREAD

**Issue by eyalcohen4** [vuematerial/vue-material#1165]
I don't know if this is actually a bug, but I'll be really happy if someone can provide any kind of help or workaround to solve this.
The triage for this problem can be found [here](https://github.com/vuematerial/vue-material/blob/7fdd318d9ebcf13e6c7d9a2e6a7de205f6918d53/src/components/MdTabs/MdTabs.vue#L208), And with some guidance about the RTL philosophy of the project, I'll be happy to make a PR.
cc @marcosmoura 

### Steps to reproduce
1. Display MD-tabs on RTL direction and RTL languages
2. Change tab.

### Which browser?
Chrome 
Vue: 2.5.2
Vue Material: beta
OS: Mac
Browser: Checked on chrome only 

### What is expected?
The tabs were expected to change their content and display them.

### What is actually happening?
The tabs are changing but the content is transformed and translated3D to the left instead of the right  

### Reproduction Link
https://codepen.io/eyalcohen4/pen/qVpWbj

**Comment by marcosmoura** [comment]
I'm aware of this bug. CSS transforms do not work with RTL out of the box and I will need to change that manually. The CSS transitions should be also RTL. I will improve this support really soon.

**Comment by eyalcohen4** [comment]
Cool, Thanks for taking the time to answer. 
I made a fork and add a prop named `mdRTL` for the md-tab component,  to make the transform plus/minus.
I'm sure this isn't the best way to deal with RTL support, 
So if you have a way you think we can apply here I'll be happy to implement it.\

**Comment by marcosmoura** [comment]
The CSS part is kind of easy. What we need to do is to add css rules for `[dir="rtl"] .md-something`.
But this is not enough. The best way is to also have a wide detection for [dir="rtl"] in the HTML script. 
This can be done using MutationObserver and to set a data variable on each Vue Material component.

**Comment by Samuell1** [comment]
Closing this issue because we have now issue #80 about RTL support.

**Comment by jonybar9** [comment]
Is this solved? Is there support for RTL?
Tabs component specifically? 
thanks
