### ISSUE TITLE
import md plugins as components

### ISSUE THREAD

**Issue by waozixyz** [vuematerial/vue-material#1166]
I think it would be great if it were possible to add the plugins as components

So instead of having a centralized file with all md plugins

```js
import { MdButton, MdContent, MdTabs } from 'vue-material/dist/components'

Vue.use(MdButton)
Vue.use(MdContent)
Vue.use(MdTabs)
```

you could just add what one needs for each component

```js
import { MdButton, MdContent, MdTabs } from 'vue-material/dist/components'
export default {
  components: {
    MdButton,
    MdContent,
    MdTabs 
  }
}
```
its the same way the quasar framework manages components and i think it is a nice approach since you have more control what plugins to use for each component instead of adding them globally

**Comment by Samuell1** [comment]
I think this is possible in new version no?

**Comment by spaceywolfi** [comment]
@Samuell1 when i try to do it i get this error:
```
[Vue warn]: Error in render: "TypeError: e.component is not a function"
```

**Comment by marcosmoura** [comment]
You can do this right now importing the component from the source, but you will have to import the dependencies manually. I will change that soon.

**Comment by jkosonen** [comment]
Any news on this? @marcosmoura

**Comment by Giorat** [comment]
import md as components should decrease the bundle size of the app am I right @marcosmoura ?
Can you help us or the rest of the team support this? 

How can we help?

**Comment by Samuell1** [comment]
@Giorat this will be supported in next release

**Comment by naimlatifi5** [comment]
Is this fixed yet ? :)

**Comment by JamesCoyle** [comment]
Any update on this? I thought this was how it worked until I searched for this issue as thats how Vue components are supposed to be implemented.

**Comment by ortonomy** [comment]
Same as above, I'm trying to do this and getting

```
[Vue warn]: Error in render: "TypeError: e.component is not a function"
```

Vue version: ``2.5.17``

**Comment by Epistol** [comment]
A year later, nothing ?

**Comment by margi212** [comment]
Any update?

**Comment by tekook** [comment]
Why is this so difficult? This should be standard to import the components via imports in vue-components.

**Comment by nathanael540** [comment]
Error in render: "TypeError: e.use is not a function"

Is Related?

**Comment by mora200217** [comment]
Same problem. Trying to import component with "vue-class-component" 

``` js
import Component from "vue-class-component";
import { MdIcon, MdButton } from 'vue-material/dist/components'; 

@Component({
  components: {
    MdIcon, 
   MdButton
}
})
```
Console throwing: 

``` bash
[Vue warn]: Error in render: "TypeError: e.component is not a function. (In 'e.component(s.default.name,s.default)', 'e.component' is undefined)"
```

### Environment / Setup 
* **vue**: 2.6.11
* **typescript**: 3.9.7
* **vue-class-component**. 7.2.3
* **vue-material**: 1.0.0-beta-15

Any new updates?

**Comment by goddas** [comment]
Any updates on this?

**Comment by MuhaddiMu** [comment]
It's been three years and there's no update on this issue. It's time to move on to Vuetify :(

**Comment by ortonomy** [comment]
Or just don't use Material design. It's only a few later and I already can't stand most interfaces that use it.

**Comment by tekook** [comment]
> It's been three years and there's no update on this issue. It's time to move on to Vuetify :( 

Moved on to vuetify long ago. The library is much easier to use and they listen to requests 👍

> Or just don't use Material design. It's only a few later and I already can't stand most interfaces that use it.

Do you have some alternatives which offer the same amount of features?

**Comment by ortonomy** [comment]
@tekook 

> Do you have some alternatives which offer the same amount of features?

https://athemes.com/collections/vue-ui-component-libraries/

Element, Ant, Bulma, Chakra, Semantic if you must use a pre-built..

it's still just as easy to build your own... Tailwind CSS, etc.. other opinions are available of course
