### ISSUE TITLE
[MdTooltip] do not work for buttons on firefox

### ISSUE THREAD

**Issue by waozixyz** [vuematerial/vue-material#1171]
When I try to add md-tooltip inside a md-button nothing shows up

**Comment by marcosmoura** [comment]
Can you provide an example?

**Comment by spaceywolfi** [comment]
@marcos-hotmart 

i am not really sure what changed, but it works now, sorry for the unnecessary issue!

**Comment by spaceywolfi** [comment]
turns out that it works on chrome, but it doesnt work on firefox (i'm using version 57.0 64bit)

```html
  <md-button>
    <md-tooltip>Tooltip Text</md-tooltip>
    <md-icon md-src="'src/assets/logo.svg'" />
  </md-button>
```

**Comment by marcosmoura** [comment]
Gotcha! I will fix it ASAP

**Comment by VdustR** [comment]
The [`targetEl`](https://github.com/vuematerial/vue-material/blob/ff24b8f359afcf0bb0f82f632e90e7c4fcaba5af/src/components/MdTooltip/MdTooltip.vue#L73) got this:
```html
<button type="button" class="md-button">
  <div class="md-ripple">
    <span class="md-button-content"> <--
```

I think we except this:
```html
<button type="button" class="md-button"> <--
  <div class="md-ripple">
    <span class="md-button-content">
```

Is it possible to get that via vnode?

**Comment by marcosmoura** [comment]
No. Because the `md-portal` element do not store to old vnode. But I will change that so this will become accesible by any children of a portal el

**Comment by VdustR** [comment]
@marcosmoura how do you think about changing the usage of `md-tooltip` to:

```vue
<md-tooltip>
  <md-button>
    <md-icon md-src="src/assets/logo.svg" />
  </md-button>
</md-tooltip>
```

**Comment by Pwntus** [comment]
Seems to be a bug in Firefox where the `mouseenter` event doesn't fire on children of a button:
https://bugzilla.mozilla.org/show_bug.cgi?id=1084196
https://bugzilla.mozilla.org/show_bug.cgi?id=843003

[targetEl](https://github.com/vuematerial/vue-material/blob/dev/src/components/MdTooltip/MdTooltip.vue#L74) whould have to point to the first parent-button element.

I'm not too familiar with the codebase but this will probably have side-effects where a `md-tooltip` is used elsewhere. Other frameworks (Material UI) structure tooltips like @VdustR says. Then it becomes trivial to listen for `mouseenter` events regardless of the content.

**Comment by Soletiq** [comment]
Having same issue.
