### ISSUE TITLE
[theme-engine] add support for stylus

### ISSUE THREAD

**Issue by waozixyz** [vuematerial/vue-material#1173]
I would like to use the theme engine, however currently the theme engine is made using scss,
i would prefer if i didn't have to add the sass-loader and node-sass to be able to use the theme engine

**Comment by leozdim** [comment]
@spaceywolfi I'm new with all this. How can you set up the theme?

**Comment by spaceywolfi** [comment]
@leozdim 
i'm just using the vue-material documentation:
https://vuematerial.io/themes/configuration

**Comment by marcosmoura** [comment]
I will add CSS Support really soon. It's already done but I need to write down the documentation.
Stylus support can be done using pure css.

**Comment by evaneus** [comment]
Any word on stylus ? thanks!
