### ISSUE TITLE
How to get value from v-model in autocomplete 

### ISSUE THREAD

**Issue by trucb1203981** [vuematerial/vue-material#1174]
I want to get value from v-model when not found options in vue-material v1 but I can't. Please can somebody help me? !!! . And when I set props md-open-on-focus="false", then sometimes I can't choose options. And How to @keyup.enter="function" get value when  options not found

**Comment by marcosmoura** [comment]
Sorry, but I didn't understand what you want. Can you provide an elaborated issue? Can you provide a Codepen example?

**Comment by trucb1203981** [comment]
Oh!! thank you. I resolved problem. I used refs to get value of searchTerm. One more thing, I detected bug on password toggle. I can't toggle

**Comment by marcosmoura** [comment]
The password thing is already fixed. I will release one version soon!

**Comment by alexwohlbruck** [comment]
I'm also having trouble using `v-model` on the `md-autocomplete` component. The value isn't being linked with the component data??
