### ISSUE TITLE
[md-button] Add consistent spacing between md-icon and md-tooltip

### ISSUE THREAD

**Issue by spaceywolfi** [vuematerial/vue-material#1175]
### Steps to reproduce

have 2 buttons with md-icons 
a) with a md-size-1x
b) with a md-size-2x

add a tooltip to each button

### Which browser?
vue-material: vue-material@beta
browser: chrome && friefox
os: manjaro

### What is expected?

To have a consistent spacing between the tooltip and the button

### What is actually happening?

When md-size is greater than 1 the difference in the space between the tooltip and the button increases

### Reproduction Link
https://codepen.io/anon/pen/zPpLMJ?&editors=111

**Comment by marcosmoura** [comment]
The spaces are consistent enough. They have the same % amount from the icon. Buttons shouldn't have a large icon inside of it. If you really want it, you can increase the button height, so you'll see the consistency. :)
