### ISSUE TITLE
[md-table] dont load rows by v-model

### ISSUE THREAD

**Issue by jessicamrbr** [vuematerial/vue-material#1184]
I try:

`
...<md-table-row slot="md-table-row" slot-scope="{ item }">
                <md-table-cell md-label="Código" md-sort-by="id">{{ item.id }}</md-table-cell>...
`

Vue 2.5.7
Vue material 1.0.0-beta-4
Linux Chrome 62

Expected the table, but blank div

Console:

- Duplicate presence of slot "default" found in the same render tree
- Property or method "item" is not defined on the instance but referenced during render

**Comment by marcosmoura** [comment]
Have you set up a v-model on the <md-table>?

**Comment by jessicamrbr** [comment]
Yes,
`
<md-table md-card v-model="dataTable.data">
`

**Comment by marcosmoura** [comment]
Can you provide an example on Codepen?

**Comment by jessicamrbr** [comment]
Very grateful for the attention, I think I discovered the problem.
I needed to install the "vue-template-compiler": "^ 2.5.8"

**Comment by Samuell1** [comment]
Dont forget updating all vue dev dependencies `vue-loader, vue-style-loader, vue-template-compiler` to latest version. 

Closing for now. If you get issue again, please reopen this isse.
