### ISSUE TITLE
How to achieve a tree multiple choice component 

### ISSUE THREAD

**Issue by Klay-Clam** [vuematerial/vue-material#1185]
As the title , I'm using this in my project,and i want a component which could multiple choice and like a tree.
By read the guide, i can not find how to do that.
of course, i have done some test.

**Comment by VdustR** [comment]
Like this?

[vue2-tree](https://halower.github.io/vue2-tree/)

**Comment by Klay-Clam** [comment]
That's right,Thanks you so much
