### ISSUE TITLE
Styles is not loaded for version 1.0.0-beta-4

### ISSUE THREAD

**Issue by vovkats** [vuematerial/vue-material#1188]
`import Vue from 'vue'`
`import VueMaterial from 'vue-material'`
`import 'vue-material/dist/vue-material.min.css'`

`Vue.use(VueMaterial) `

CSS is not applied for components(such as Input, Button and etc.)

**Comment by Samuell1** [comment]
Do you have any errors in console?

**Comment by vovkats** [comment]
@Samuell1 No I don't

**Comment by emman27** [comment]
When you refer to CSS not applying, do you just mean the coloring of items? If so you'll probably need to add a .scss file specifying the default theme. Here's a quick example.

```
// @/main.scss
@import "~vue-material/dist/theme/engine";

@include md-register-theme("default", (
  primary: md-get-palette-color(blue, A200),
  accent: #3fffbe,
  warn: #f0ad4e,
));

@import "~vue-material/dist/theme/all";
```

```
// main.js

import Vue from 'vue';
import VueMaterial from 'vue-material';
import 'vue-material/dist/vue-material.min.css';
import '@/main.scss';
```

**Comment by Samuell1** [comment]
For more informations about pre-preprocessors you can find here https://vue-loader.vuejs.org/en/configurations/pre-processors.html
