### ISSUE TITLE
Autocomplete menu hidden by dialog

### ISSUE THREAD

**Issue by woodcoder** [vuematerial/vue-material#1190]
In 1.0.0-beta-4 the `md-autocomplete` menu appears behind the `md-dialog`.

Workaround is to style the dialog with `z-index: 50`.

**Comment by Samuell1** [comment]
Duplicated https://github.com/vuematerial/vue-material/issues/1149

**Comment by Maseline** [comment]
Hey, still facing this issue, using 1.0.0-beta-10.2, z-index fix not working for me, md-autocomplete options not displayed in dialog, any solutions?

**Comment by Mashiane** [comment]
Thanks Rapol, just picked this issue up also just now, your advise helped.
