### ISSUE TITLE
[Doc] Add the @beta requirement for md-app

### ISSUE THREAD

**Issue by pierre-aurele-martin** [vuematerial/vue-material#1195]
Hello,

I've just struggle a bit as when I first intall vue-material, I didn't specify the @beta tag.

Then all md-app-* components were not working because not including in the regular version. It might be worth to add in the [doc on App](https://vuematerial.io/components/app) that latest version is required.

As I'm not 100% confident on VueJs yet, checking in node_modules was not my first guess.

Any links on how to submit a PR for the doc and I'll (try) to do it myself.

thanks a lot !

**Comment by Samuell1** [comment]
![obrazok](https://user-images.githubusercontent.com/3110002/33190156-f368ec44-d0a9-11e7-9815-6cbfd9a8ae8f.png)
