### ISSUE TITLE
How to call a custom component by calling a custom directive

### ISSUE THREAD

**Issue by MaximeAubry** [vuematerial/vue-material#1199]
Hello.

Today, i try to add a "copy" (in clipboard) button on an input using by a directive, which one calls a component i made.
I don't if it's a good way to customize a vue-material component. Maybe do you have a better idea ?

[Here](https://github.com/MaximeAubry/CallComponentWithDirective) is my code

Thanks a lot :)

**Comment by Samuell1** [comment]
Hey, i think this is now best way to create custom components. We have some plants in Roadmap to make some docs how to extend, add third Party Components.
