### ISSUE TITLE
Persistent app drawer does not work when combined with md-right

### ISSUE THREAD

**Issue by alexwohlbruck** [vuematerial/vue-material#1204]
The `md-app-drawer` component does not push content over in persistent mode when it is set to the right side. Instead, it just opens atop of the content, partially covering it. There should also be a small border on the left edge like its left-drawer counterpart.

![Example](https://i.imgur.com/MKnJ9r4.png)

**Comment by Samuell1** [comment]
Hey, can you please provide your code?

**Comment by alexwohlbruck** [comment]
@Samuell1 I tried to get a codepen demo but I can't get the scss theme import to work, do you have a working skeleton app I can fork on codepen?

**Comment by marcosmoura** [comment]
I forgot to think about persistent right drawers. I will improve this ASAP!

**Comment by deniszavadskiy** [comment]
@marcosmoura  So what? Does this feature implemented?

**Comment by deniszavadskiy** [comment]
@marcosmoura Bro, tell something

**Comment by ptrckdev** [comment]
So this comment in the docs for the "App"-component is now wrong I assume? Bummer :(

"md-app-drawer: Places the drawer panel, that also accepts any options from the md-drawer. You can have a left or right placed drawers. **Or both**."
