### ISSUE TITLE
Old documentation not accessible in IE11

### ISSUE THREAD

**Issue by Nirazul** [vuematerial/vue-material#1205]
I've wanted to check if the `md-tabs` and `md-tab` components generally work in IE11, as I'm having issues with them in `0.7.x`.

When I navigate to https://vue-material-old.netlify.com/ I'm always getting redirected to https://vue-material-old.netlify.com/undefined/#/ ...which does not exist.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by Nirazul** [comment]
So your old documentation is completely inaccessible for a browser you aim to support with version 1.0.0, which is not even out yet, and you're ok with that?

**Comment by Samuell1** [comment]
@Nirazul there was some changed for old versions do you tried 0.8.x version with IE11?
