### ISSUE TITLE
MdChips (1.0.0-beta-5) cannot create new chips with spaces

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1207]
### Steps to reproduce
```
<md-chips class="md-flex md-flex-small-100" v-model="someArray">
   <label>Some List</label>
</md-chips>
```
Also can be reproduced on docs site.

### Which browser?
Chrome 62

**Comment by VdustR** [comment]
Yes. The input value would be [trimmed](https://github.com/vuematerial/vue-material/blob/e9086778b965606153000453f022e7f0c43d8d43/src/components/MdChips/MdChips.vue#L19).

**Comment by emman27** [comment]
Sorry I think I wasn't clear. Was trying to insert the value "Hello world". The trimming is happening prematurely so I can't type the space after Hello

**Comment by VdustR** [comment]
@marcosmoura I saw this fix has been reverted 987600c097f5a3d57f0855828f299c246ec76e74.

Should we reopen this issue?

**Comment by emman27** [comment]
I'm currently running beta-7. This issue seems to be resolved?

**Comment by VdustR** [comment]
Yes, it seems work pretty well.

... but, why?!
