### ISSUE TITLE
IE11 crashes when md-tabs is a child of a flex container

### ISSUE THREAD

**Issue by Nirazul** [vuematerial/vue-material#1210]
### Steps to reproduce
Nothing, just load the example

### Which browser?
- Internet Explorer 11
- latest <1 version of vue-material
- vue version doesn't matter

### What is expected?
That the browser doesn't crash.

### What is actually happening?
The browser crashes violently.

### Reproduction Link
https://codepen.io/Nirazul/pen/MOGNzr

**Comment by Samuell1** [comment]
this is v0.8. version of Vue Material, but i think for IE you need install polyfills

**Comment by Samuell1** [comment]
Can you try new version of md-tabs?

https://vuematerial.io/components/tabs/

**Comment by Nirazul** [comment]
What polyfills? Where is it documented?

As for the new version, I've tried to update my codepen, but I can't seem to install it from the window object. No idea what's going on...
https://codepen.io/Nirazul/pen/MOGNzr

**Comment by Samuell1** [comment]
You doesnt need to install it to window object at codepen, you can use examples from there https://vuematerial.io/components/tabs to generate for you codepen example with md-tabs

**Comment by Nirazul** [comment]
- The new vuematerial page is broken in IE11
- Also the codepen examples are broken in IE11

**Comment by Samuell1** [comment]
Where you debuging IE11? I can debug only Edge at Windows 10

**Comment by Nirazul** [comment]
In a virtual machine, but https://www.browserstack.com/ is the same
