### ISSUE TITLE
Set a focus to  an element without setTimeout function

### ISSUE THREAD

**Issue by Accontech-Tigran** [vuematerial/vue-material#1213]
Tested with "vue": "2.4.4" and 2.5.8. and "vue-material": "0.8.1". 

Component code:
 mounted() {
     setTimeout(() => {this.$refs.zipCode.$el.focus();}, 0); 
} 
template:
 <md-input-container>
      <label for="phone">Zip Code</label>
      <md-input v-model="formData.zipCode.value" type="text" ref="zipCode">
      </md-input>
 </md-input-container> 

### What is expected? 
Expected to set a focus to an input field "WITHOUT" using setTimeout. 

### What is actually happening? 
setTimeout(() => {this.$refs.zipCode.$el.focus();}, 0) actually does what is supposed to do.
 It sets the focus and inside setTimeout function I can access $.refs which contains zipCode element. $refs is empty when used without setTimeout and inside <md-input-container>. 

I don`t know if it is  a component or Vue issue.  
What`s a proper way  of setting focus to a material input field?

**Comment by VdustR** [comment]
Check [Vue custom directives](https://vuejs.org/v2/guide/custom-directive.html).

**Comment by Accontech-Tigran** [comment]
Thanks for your reply, but I`m still confused why that $el or ref is not accessable in mounted() hook.

**Comment by Samuell1** [comment]
Try only `this.$refs.zipCode.focus();`

**Comment by Accontech-Tigran** [comment]
the problem is that there are not any $refs at that phase . Only through the use of timeout it gets available.

**Comment by Samuell1** [comment]
That is weird because $refs shoud be available it mounted hook

**Comment by Accontech-Tigran** [comment]
The reproduction of the problem. (see console)
http://jsfiddle.net/Megashark/apcz6pkw/3/

**Comment by Samuell1** [comment]
I think without setTimeout its not possible to do it in old version of Vue Material.
