### ISSUE TITLE
Add Promise polyfill on the demo website for IE11 support

### ISSUE THREAD

**Issue by Aymkdn** [vuematerial/vue-material#1220]
### Steps to reproduce

Go to https://vuematerial.io/ with IE11 and click on "Components"

### Which browser?

IE11

### What is expected?

To go to the Components.

### What is actually happening?

Error message in the console, and we don't move to Components.
The error message says : "Promise is undefined"

### Solution

Add the [Promise polyfill](https://github.com/taylorhakes/promise-polyfill/blob/master/dist/promise.min.js).

**Comment by Samuell1** [comment]
Better will be using https://babeljs.io/docs/usage/polyfill/#installation ?

**Comment by Aymkdn** [comment]
Yes @Samuell1 it would make more sense I guess :-) Whatever that will make the website working with IE11 !

**Comment by Aymkdn** [comment]
Is the website updated in live? If yes, then it doesn't work :) If not, then I'll check again later...

Thanks for the fix!

**Comment by Samuell1** [comment]
@Aymkdn its not yet live, but IE support for some components is not good because we using new features that IE doesnt not support.

**Comment by Aymkdn** [comment]
Thanks @Samuell1 for the clarification... Then I guess I won't use the new version of VueMaterial as IE11 is still the default browser in my company.

Thanks for the great work :-)
