### ISSUE TITLE
How to set full height in md-app

### ISSUE THREAD

**Issue by Isaiasdd** [vuematerial/vue-material#1222]
How to set a full height in md-app?

![full_height](https://user-images.githubusercontent.com/5838676/33283174-2de23e62-d392-11e7-852c-113520867295.PNG)

**Comment by emman27** [comment]
You could try
```
<md-app style="min-height: 100vh;">
  <whatever-you-need />
</md-app>
```
(or use a CSS class)

**Comment by Isaiasdd** [comment]
@emman27 Thank you, it's working!

**Comment by czy1996** [comment]
I tried adding class or style as such,
```
<md-app :class="appWrapper" class="app-wrapper">
```
```
.app-wrapper {
    min-height: 100vh;
  }
```
it didnt help, and html rendered didnt have the class added
but if i add `app-wrapper` in the chrome dev tool, the height changed
adding inline css didnt help too
my vue version is 2.5.2 and vue material is 1.0.0-beta-7

**Comment by Samuell1** [comment]
@czy1996 for beta-7 you need to add, in next version is allowed to add classes on **md-app** component

```
.md-app {
   height: 100vh;
}
```

**Comment by HappyBird233** [comment]
@Samuell1  
it complete slove my problem.  but i don't konw how come that the fixed class on md-app didn't work when i used  .md-app{ min-height: 100vh; }
sorry my english is poor

**Comment by jsantoru** [comment]
@marcosmoura @Samuell1 @HappyBird233 i might be missing something... is there a sandbox example of this working? when i try to set the full height it doesn't seem to work: https://codesandbox.io/s/6yv4myjynr

i am just getting the outer browser scroll bar and losing the content only scrolling. any help is appreciated. thanks!

**Comment by Samuell1** [comment]
@CreatixEA https://github.com/vuematerial/vue-material/issues/1222#issuecomment-361159516
