### ISSUE TITLE
The component md-chips‘s props md-limit is not work

### ISSUE THREAD

**Issue by Klay-Clam** [vuematerial/vue-material#1223]
Greetings

```
// my code here
<md-chips style="float:left" v-model="tags_contacts"  :md-limit="5"  md-input-placeholder="请添加标签，回车确认" @change="tagsChange">
          <div class="md-helper-text">至多可添加5个标签</div>
        </md-chips>
```
but the limit does not work.

Maybe it's not a bug,but could you help me solve the problem？

**Comment by Samuell1** [comment]
Its working https://codepen.io/anon/pen/aVaQPO?&editors=111

Can you please provide Vue and VueMaterial version?

**Comment by Klay-Clam** [comment]
Thanks for your replying.
My Vue version and  VueMaterial version here: 
```
"vue": "^2.4.2",
"vue-material": "^0.7.5",
```

**Comment by VdustR** [comment]
Please check the [old documentation](https://vue-material-old.netlify.com/#/components/chips) for versions <= 0.8.1.

**Comment by Klay-Clam** [comment]
Thanks so much
