### ISSUE TITLE
browser support 

### ISSUE THREAD

**Issue by a251115100** [vuematerial/vue-material#1224]
i want use this pretty UI framework,but i open website in  Edge,it not support friendly

**Comment by Samuell1** [comment]
I tested it in Edge and its fine.
![obrazok](https://user-images.githubusercontent.com/3110002/33306753-13577c42-d414-11e7-9ab3-3c7b72b0f5d1.png)

**Comment by marcosmoura** [comment]
Which version of edge? We only support the latest version.

**Comment by a251115100** [comment]
![tim 20171129103954](https://user-images.githubusercontent.com/3240441/33355286-d525d926-d4f1-11e7-8bdb-57207d1f4734.png)

**Comment by a251115100** [comment]
it show red

**Comment by Samuell1** [comment]
You using some older version of edge my edge is 41. And this can be issue with that older version of edge because that red color is selection color.

![obrazok](https://user-images.githubusercontent.com/3110002/33554460-1c05719e-d8fd-11e7-930e-4afdab78a6f7.png)

**Comment by SirCodewright** [comment]
I have the same problem ( using ms edge 40 ). Unfortunately, The Unfathomable Windows Update Spirit has chosen not to upgrade Edge on my system, thus I am stuck with a pretty much useless rendering - has anyone found a workaround ?

**Comment by Samuell1** [comment]
It looks like issue with variables in edge https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12132854/

**Comment by SirCodewright** [comment]
I have found a workaround in adding

    .md-theme-default :not(input):not(textarea)::selection { background-color: transparent; color: black; }

to my application css. I am not sure about crosstalk effects however.
