### ISSUE TITLE
MdBottomBarItem does not compile

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1230]
### Steps to reproduce
While using custom template BottomBar component like in the docs.

### Which browser?
Does not compile

### What is expected?
Compiling the Templates

### What is actually happening?
Dependencies are missing
These dependencies were not found:

* core/mixins/MdAssetIcon/MdAssetIcon in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-material/src/components/MdBottomBar/MdBottomBarItem.vue
* core/utils/MdRouterLinkProps in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-material/src/components/MdBottomBar/MdBottomBarItem.vue
* core/utils/MdUuid in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-material/src/components/MdBottomBar/MdBottomBarItem.vue

**Comment by Samuell1** [comment]
Can you please provide Vue, VueMaterial version?

**Comment by mrwhy-orig** [comment]
VueMaterial Versions beta-5 & beta-6
Vue 2.5.2

**Comment by Samuell1** [comment]
Do you using webpack template?

**Comment by mrwhy-orig** [comment]
Yes I do.

**Comment by Samuell1** [comment]
Can you provide your code? or make repo for it?

**Comment by mrwhy-orig** [comment]
sure do you need more then this part? I just tried to get the example running. If I use the whole VueMaterial import, it is compiling.
If I use  `import MdBottomBarItem from "vue-material/dist/components";` instead, it is compiling but i get an 

> regeneratorRuntime is not defined

error.

 
`
<template>
  <md-bottom-bar class="md-accent" md-type="shift" >
    <md-bottom-bar-item id="item-posts">
      <md-icon class="md-bottom-bar-icon" md-src="/assets/icon-whatshot.svg"></md-icon>
      <span class="md-bottom-bar-label">Posts</span>
    </md-bottom-bar-item>
  </md-bottom-bar>
</template>

<script>
  import MdBottomBarItem from "../../node_modules/vue-material/src/components/MdBottomBar/MdBottomBarItem";
  export default {
    components: {MdBottomBarItem},
    name: 'BottomNav'
  }
</script>

<style>

</style>`

**Comment by Samuell1** [comment]
with regeneratorRuntime is issue here: https://github.com/vuematerial/vue-material/issues/1182

Why you importing components from `src` ?

**Comment by mrwhy-orig** [comment]
Oh.. Webstorm integrated the imports by its own.. haven't had a look at these... regarding #1182 -> i will have a look.

**Comment by Samuell1** [comment]
You can find here how to import components: https://vuematerial.io/getting-started
