### ISSUE TITLE
Updating to latest Version via npm fails

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1231]
### Steps to reproduce
I tried to update to the latest version with "npm update"

### What is expected?
Updating to the latest version

### What is actually happening?
sh build/git-hooks/install.sh fails on Ubuntu 16.04 64bit, npm 4.9.0 - 5.5.1, node 7.9.0 - 9.2.0

**Comment by Samuell1** [comment]
I think you cant update it with `npm update` because in package.json is defined vue-material version 1.0.0-beta5 and npm doesnt know that version. Try removing node_modules and installing again.

**Comment by mrwhy-orig** [comment]
Removing the old version from package.json and reinstalling with "npm install vue-material@beta --save" install the actual beta version.

**Comment by Samuell1** [comment]
Duplicated: https://github.com/vuematerial/vue-material/issues/1155
