### ISSUE TITLE
Could't select item of list in md-select by enter key.

### ISSUE THREAD

**Issue by VladPavliuk** [vuematerial/vue-material#1232]
Hello, When using md-select I found that I have ability to use arrow key (up, down), to move across the list, but 'enter' pressing, does't do any action (selected element does't select). Is it a bug? Or there are some events of md-select to handle this?

**Comment by Samuell1** [comment]
Version of VueMaterial?

**Comment by VladPavliuk** [comment]
@Samuell1 - v. 0.7.4

**Comment by Samuell1** [comment]
Sorry but our focus is on the new 1.0.0 version.

In version 1.0.0 we want add better keyboard support for select. https://github.com/vuematerial/vue-material/issues/31 https://github.com/vuematerial/vue-material/issues/260

**Comment by VladPavliuk** [comment]
@Samuell1 Thanks of info) Could you also say, roughly, when 1.0.0 release would occur?

**Comment by Samuell1** [comment]
@VladPavliuk now you can try beta version of it
