### ISSUE TITLE
intended behavior of md-app and md-app-drawer

### ISSUE THREAD

**Issue by CharlesKumar** [vuematerial/vue-material#1236]
This is not an issue just to notify/clarify

I'm using vue-material@1.0.0-beta-6

[current behavior](https://codepen.io/pen) is breaking the navigation and layout 

This is because it adds .md-layout-row, .md-layout-column classes that are not used in beta-6

Layout section in the docs were updated...

**Comment by marcosmoura** [comment]
Already fixed! Will be available soon!

**Comment by CharlesKumar** [comment]
This is fixed in version 1.0.0-beta-7
