### ISSUE TITLE
md-layout

### ISSUE THREAD

**Issue by jackovsky888** [vuematerial/vue-material#1242]
I try to make some responsive page:
Depending on size either Column 1 or 2 should be shown, column 3 contains should be shown always.
### Steps to reproduce

        <div class="md-layout">
            <div class="md-layout-item md-xlarge-size-30 md-large-size-30 md-medium-size-33 md-small-size-40 md-xsmall-hide">
                Column 1 
            </div>
            <div class="md-layout-item md-xlarge-hide md-large-hide md-medium-hide md-small-hide">
                Column 2
            </div>
            <div class="md-layout-item">
                Column 3
            </div>
        </div>
### Which browser?
Tried it with the newest chrome and firefox.

### What is expected?

First column width depending on the size,
second column hiding except on xsmall.

### What is actually happening?
The second column is not hiding on xlarge and large,
and is not shown on xsmall.

Also md-large-size and md-xlarge-size are not working, the columns are then equal sized.

### Reproduction Link
https://codepen.io/jackovsky888/pen/MOZZxd?editors=1111

**Comment by marcosmoura** [comment]
I will take a look on this ASAP.
