### ISSUE TITLE
v-model on md-textarea sets the modeled variable to InputEvents

### ISSUE THREAD

**Issue by zevdg** [vuematerial/vue-material#1247]
To  reporduce, use v-model in an md-textarea and watch the value of the model

### Which browser? 

at least chome and firefox  
vue-material@1.0.0-beta-6
### What is expected?

the string attached to v-model should always remain a string and map to the contents  of the textarea (just like md-input)

### What is actually happening?
every time the md-textarea is updated, the model is first set to the value of the input event that updated the md-textarea.  it is then immediately updated to the correct value, but this momentary alternate type would break any code that assumes that the variable will always be a string and causes unnecessary computation 

### Reproduction Link

https://codepen.io/zevdg/pen/XzOWma

P.S. you should update [your codepen template](https://codepen.io/vue-material/pen/WGavBE) to use v1.0  It took me way longer to get codepen to load vue-material correctly than any other part of this bug report.

**Comment by VdustR** [comment]
Similar to #1160
