### ISSUE TITLE
Vue should probably be a peerDependency, rather than a dependency

### ISSUE THREAD

**Issue by chrisvfritz** [vuematerial/vue-material#1248]
By listing Vue as a dependency, users of this library will actually be including Vue _twice_ in their bundle, as [demonstrated here](https://github.com/vuejs-templates/webpack/pull/1126). 😅  This is probably unintended, so instead, I recommend listing Vue as a [peer dependency](https://github.com/vuejs-templates/webpack/pull/1126#issuecomment-348665961). You can see [an example in Vuetify](https://github.com/vuetifyjs/vuetify/blob/master/package.json#L104).

**Comment by VdustR** [comment]
Related to #1144.

**Comment by marcosmoura** [comment]
Done!
