### ISSUE TITLE
App Layout height - beta 1.0.6

### ISSUE THREAD

**Issue by C0d1ngJammer** [vuematerial/vue-material#1250]
### Steps to reproduce

In my Layout I added the default App Layout "Reveal" [https://vuematerial.io/components/app](https://vuematerial.io/components/app)

This is what my layout looks like:

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Material+Icons">

    <link rel="stylesheet" href="https://unpkg.com/vue-material@beta/dist/theme/default.css">

`<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width,initial-scale=1,minimal-ui" name="viewport">

    <style lang="scss" scoped>
        /*.md-app {
            /*max-height: 400px;
            height: 100%;
        }*/
    </style>
</head>
<body>

    <div  id="app">
        <div class="page-container">
            <md-app md-mode="reveal">
                <md-app-toolbar class="md-primary">
                    <md-button class="md-icon-button" v-on:click="menuVisible = !menuVisible">
                        <md-icon>menu</md-icon>
                    </md-button>
                    <span class="md-title">My Title</span>
                </md-app-toolbar>

                <md-app-drawer :md-active.sync="menuVisible">
                    <md-toolbar class="md-transparent" md-elevation="0">Navigation</md-toolbar>

                    <md-list>
                        <md-list-item>
                            <md-icon>move_to_inbox</md-icon>
                            <span class="md-list-item-text">Inbox</span>
                        </md-list-item>

                        <md-list-item>
                            <md-icon>send</md-icon>
                            <span class="md-list-item-text">Sent Mail</span>
                        </md-list-item>

                        <md-list-item>
                            <md-icon>delete</md-icon>
                            <span class="md-list-item-text">Trash</span>
                        </md-list-item>

                        <md-list-item>
                            <md-icon>error</md-icon>
                            <span class="md-list-item-text">Spam</span>
                        </md-list-item>
                    </md-list>
                </md-app-drawer>

                <md-app-content>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error quibusdam, non molestias et! Earum magnam, similique, quo recusandae placeat dicta asperiores modi sint ea repudiandae maxime? Quae non explicabo, neque.</p>
                </md-app-content>
            </md-app>
        </div>
    </div>
</body>
</html>

@{ IgnoreBody(); }
<script type="text/javascript" src="~/scripts/dist/main.build.min.js"></script>

And my Typescript:

`// main.ts
import Vue from 'vue';
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'

Vue.use(VueMaterial);

var app = new Vue({
    el: '#app',
    name: 'Reveal',
    data: {
        message: 'Hello Vue!',
        menuVisible: false
    }
});`

Following happens in Chrome:

And this happens in Microsoft Edge when opening the side navigation:
![image](https://user-images.githubusercontent.com/10685463/33514022-b7d49332-d74c-11e7-853b-932571e64b15.png)

Also Edge
![image](https://user-images.githubusercontent.com/10685463/33514029-d7ec43cc-d74c-11e7-87d1-f342a5b79494.png)

`
### Which browser?

Google Chrome
Google Chrome ist auf dem neuesten Stand.
Version 62.0.3202.94 (Offizieller Build) (64-Bit)

Edge
Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

Chrome has problems with the height of the toolbar navigation. 
Edge has a issue with the select color (in this case red....).

Both having issues with the height of the "App" ('#App') itself.

### What is actually happening?

I know you having troubles with the flexbox, not shure if this is the cause of one of these problems.
To fix the height of the App itself I added following to my scss:

`        .md-app {
            height: 100%;
        }`

Fixing the navigation items in the toolbar in chrome:
Added `height: 50px` to `.md-list-item-content` 

For the edge problem also see #1151 

Using Visual Studio 2017 Community
Asp.Net Core 2.0 with webpack and babel support

**Comment by Samuell1** [comment]
Hey, can you explain what you mean app layout height?

**Comment by C0d1ngJammer** [comment]
Oh no. It didnt save my edit....Sorry

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/1222

**Comment by Samuell1** [comment]
Red background is because you using some old version of edge. https://github.com/vuematerial/vue-material/issues/1224#issuecomment-348958526
