### ISSUE TITLE
Fixed + Waterfall display issues

### ISSUE THREAD

**Issue by akomarovsky** [vuematerial/vue-material#1253]
Seems like app with Fixed + Waterfall layout causing display issues. You can see it in the official codepen
https://codepen.io/anon/pen/dZajgr

**Comment by akomarovsky** [comment]
and also scroll bar disappeared

**Comment by Samuell1** [comment]
Quote from @marcosmoura :
> The MdApp have a small problem related to flexbox. This is already fixed and will be release along with other fixed.
