### ISSUE TITLE
Adding layout predictions to md-x-size-y

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1257]
### Steps to reproduce
[https://gist.github.com/mrwhy-orig/5e233ade79a17f5b0b55637dfc928c6c]()

I would expect, that the large size would be used for x-large desktops as well. This could save some time. I guess it would be an improvement.

### Which browser?
Chrome latest, Firefox latest, VueMaterial 1.0.0beta 7

### What is expected?
Using the large settings for the x-large desktops.

### What is actually happening?
No use of any configured sizes.

**Comment by Samuell1** [comment]
Same issue is here: https://github.com/vuematerial/vue-material/issues/1242
