### ISSUE TITLE
md-layout md-gutter with md-card

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1258]
### Steps to reproduce

Using md-layout md-gutter in combination with md-card. No visiual gutter is applied between both cards. 

### Which browser?
Tested with
Firefox, Chrome
on Ubuntu 16.04

VueMaterial 1.0.0-Beta7

### What is expected?

A gutter between both cards should be visible.

### What is actually happening?

![nogutter](https://user-images.githubusercontent.com/5978271/33549047-9143d612-d8e9-11e7-9216-7baf756b1ca0.png)

**Comment by Samuell1** [comment]
Can you post your code?

**Comment by mrwhy-orig** [comment]
https://gist.github.com/mrwhy-orig/17eb3f54b7f174195231c888ebff794a

**Comment by Samuell1** [comment]
You cant use layout classes on `md-card` because `md-gutter` is adding padding and it can be overwrited by md-card. Best way is to create new div with all layout classes and inside will be md-card.
