### ISSUE TITLE
[md-menu] missing events in beta release.

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1259]
The pre-beta version had events and methods for both `md-menu` and `md-menu-item` https://vue-material-old.netlify.com/#/components/menu. But these are missing in the beta releases. 

The hover highlight on the md-menu-item is also missing in the beta release.

Can these be added back please.

**Comment by Samuell1** [comment]
Events can be added but for `open, close` methods use `md-active`

**Comment by Samuell1** [comment]
I found you can use for detecting opened, closed menu `md-active` prop on md-menu. @zapping

**Comment by zapping** [comment]
Rather than the opened and closed events I was looking for the click event of md-menu and the selected event of the md-menu-item. 

Also the hover highlight on the md-menu-item.

**Comment by Samuell1** [comment]
`@click` exists because its native. and selected is same as `@click`

**Comment by zapping** [comment]
Oh ok, thank you. 

Can you let me know on the other 2 options too please.
-- The selected event of the md-menu-item.
-- The hover highlight on the md-menu-item.

**Comment by Samuell1** [comment]
@zapping selected is same as @click and hover is there but in docs doesnt work because there is not defined any action for items
