### ISSUE TITLE
Datepicker not working on Firefox 57.0.1 

### ISSUE THREAD

**Issue by abusalameh** [vuematerial/vue-material#1260]
Datepicker is showing the browser's default datepicker on Firefox 57.0.1

![image](https://user-images.githubusercontent.com/9642482/33553496-ad3a671a-d901-11e7-9689-8dba8074749f.png)

**Comment by Samuell1** [comment]
Quote from docs:
> The datepicker dialog is disabled in Firefox, because it have a built-in Datepicker on desktop.
