### ISSUE TITLE
[MdSelect] not rendering correctly with backend service

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1262]
### Steps to reproduce
Have an md-select with options coming from an endpoint. Options load correctly, values load correctly but doesn't display in the select box.

### Which browser?
Chrome 62, Ubuntu 16.04

VueMaterial 1.0.0-beta-7
### What is actually happening?
![screenshot from 2017-12-05 15-55-18](https://user-images.githubusercontent.com/6295583/33595903-c951a606-d9d4-11e7-8628-086a2f7b7b33.png)
![screenshot from 2017-12-05 15-54-39](https://user-images.githubusercontent.com/6295583/33595907-cb8565e8-d9d4-11e7-90d6-6fff7146d52d.png)

As can be seen, the v-model is correctly loading but the field remains empty (here this select in particular is a multiple, but it's also broken for the single selects)

### Reproduction Link
Simplest repro:

```
<template>
  <md-field>
    <label>Payment Modes <span class="red">*</span></label>
    <md-select required v-model="paymentModes" multiple>
      <md-option v-for="option in options" :key="option" :value="option">{{option}}</md-option>
    </md-select>
  </md-field>
</template>

<script>
export default {
  data() {
    return { options: [] }
  },
  async mounted() {
    this.options = await someApiCall();
    this.selected = await anotherApiCall();
  }
}
</script>
```

**Comment by Samuell1** [comment]
Hey, can you try calling api before rendering? in `created` hook?

**Comment by emman27** [comment]
@Samuell1 Thanks for the suggestion. Didn't work though.

**Comment by Samuell1** [comment]
@emman27 do you get any errors in console?

**Comment by Samuell1** [comment]
Tested it in created hook with fake api call and works https://codepen.io/anon/pen/eeoYpJ?editors=1010

Can you try removing async ?

**Comment by emman27** [comment]
The only thing in console is

```[Violation] Forced reflow while executing JavaScript took 40ms```

Which I believe means nothing.

Seems like it might potentially be a browser issue. Check this out!

![ouch](https://user-images.githubusercontent.com/6295583/33599162-3d9f1682-d9e0-11e7-8492-b98be45fb467.gif)

I swapped the async statement out for a Promise (then...catch) implementation and it didn't work either.

**Comment by Samuell1** [comment]
yeah i had that infinite reloading few days ago too, try restarting browser @emman27

**Comment by emman27** [comment]
Ah I see. I think we have a bit of miscommunication. Here's the updated pen
https://codepen.io/anon/pen/jaREaL?editors=1010#anon-login

**Comment by Samuell1** [comment]
You cant set v-model for that value that is not in array.

**Comment by emman27** [comment]
Whoops silly me. Doesn't change the outcome though. Same result even if it's in the array

**Comment by Samuell1** [comment]
I tested it without timeout nad works fine. https://codepen.io/anon/pen/QOPeyN?editors=1010

**Comment by emman27** [comment]
@Samuell1 Hey great idea it works!

Proposing to keep this issue open until a permanent fix?

**Comment by Samuell1** [comment]
Yes i leave it open. I now updating project to new vue-material and selects works fine with loading, thats why i ask if you have loading there to prevent rendering before its api loaded.

**Comment by Samuell1** [comment]
Tested it with `v-if` and it works: https://codepen.io/anon/pen/qVGvYm?editors=1011

**Comment by emman27** [comment]
Proposing to leave issue open as low priority since it has to do with reactivity of the VueMaterial components.

**Comment by Samuell1** [comment]
I found out it can be because `stringValue` is generated from select items if there is nothing selected value is set to empty. Best to fix this is to add loading like i said some messages on top.

Without loading:
![2017-12-11_10-42-27](https://user-images.githubusercontent.com/3110002/33824859-030f4fe4-de60-11e7-8b3f-2d06f516ac80.gif)

With loading:
![2017-12-11_10-43-39](https://user-images.githubusercontent.com/3110002/33824918-30400e54-de60-11e7-8ff7-37c02ece95a2.gif)

Source: https://github.com/vuematerial/vue-material/blob/dev/src/components/MdField/MdSelect/MdSelect.vue#L227

**Comment by andershjort** [comment]
I have an issue that I think is the same as this, but mine is with regards to "multiple" MdSelect.

CodePen: https://codepen.io/andershjort/pen/qpoeyq

I am not showing the select until after the data is loaded, but it still does not render correctly. The checkboxes in the dropdown are not checked
