### ISSUE TITLE
Feature request - option to override Firefox default datepicker

### ISSUE THREAD

**Issue by dakdad** [vuematerial/vue-material#1267]
First of all, thanks for the great work. The datepicker is something we waited for :)

With the latest release, it is there, but disabled on Firefox to enable the browser default. Nothing wrong with that, however, it would be nice to be able to override it when initiating the component.

`<md-datepicker v-model="selectedDate" :md-override-firefox="true" />`

Which makes it possible to have all the same controls and unified user experience across browsers.

**Comment by Samuell1** [comment]
Hey. you cant override native things thats why needs to be disabled for firefox

**Comment by dakdad** [comment]
😭
Respectfully disagree!

Implementing these custom styles (such as material design) is all about overriding the native look and provide a modern interface to the end user.

But hey, that's fine and it's just my opinion. Thanks for the quick response.

**Comment by Samuell1** [comment]
@dakdad yes, i know but native datepicker from firefox we cant affect :( One thing that we can do is change type of input to text but that is not good.

**Comment by abhay7030** [comment]
![upload](https://user-images.githubusercontent.com/19907218/33667461-ebadcd08-dac2-11e7-9f11-cf9ba5b85b6b.JPG)

**Comment by Samuell1** [comment]
@abhay7030 what you mean with that screenshot?

**Comment by dakdad** [comment]
@Samuell1 I believe he's referring to [another framework](https://vuetifyjs.com/components/pickers) where they use text input type for the date pickers.

**Comment by Samuell1** [comment]
@dakdad i can try to make some prop to make type as text and that can override firefox native datepicker
