### ISSUE TITLE
How to compile from SCSS?

### ISSUE THREAD

**Issue by ArnyS** [vuematerial/vue-material#1269]
Guys, great job with framework, but it's the same bullshit from release to release with SCSS workflow...

How can we import SCSS sources to edit or fix some bugs in?
Please show clean proper way with vue webpack! What files to import?
Trying different ways but got errors like
```
Module build failed: 
@import "~components/MdAnimation/variables";
^
      File to import not found or unreadable: ~components/MdAnimation/variables.
Parent style sheet: stdin
```
Also it'll be very usefull to know the same thing with Gulp

**Comment by Samuell1** [comment]
You can import scss like `@import '~vue-material/dist/path/to/scss/file'`

**Comment by marcosmoura** [comment]
You can't import sources to edit or fix some bugs in your codebase.
If you want to fix things and edit Vue Material source files, please create a fork and run it locally by yourself.

<sub><sup>P.S. Be kind with your words. Nothing here is a bullshit. This is a OOS library.</sup></sub>

**Comment by ArnyS** [comment]
@Samuell1 It's clear.. but what files should I import to compile lib properly without errors?
@marcosmoura ;) I'm not interested in editing other users repositories on github... of course locally

**Comment by Samuell1** [comment]
If you want use themes you can use prebuilded themes (https://vuematerial.io/themes/prebuilt) or you can define themes by yourself with SCSS https://vuematerial.io/themes/configuration

**Comment by ArnyS** [comment]
@Samuell1 I want to compile from sources directly, instead of import compiled vue-material.min.css

**Comment by marcosmoura** [comment]
@ArnyS Why you need to "compile" sources? The build version is the way to use.

**Comment by ArnyS** [comment]
@marcosmoura There are many ways to go, I think... but the question wasn't about WHY, but HOW

**Comment by marcosmoura** [comment]
The question about why is for me to understand what you want to do, for help purposes!
There is no way to import the source files. Vue Material sources relies on Webpack's aliases. This is because the sources are only for development. That's why you couldn't import the src file. I don't plan to add support for it anytime soon, because this will change the entire architecture of Vue Material source code, and honestly, I don't want to do that.
Please follow the documentation closely and notice that Vue Material is a **beta** version that is walking towards to be 'stable' soon.

**Comment by ArnyS** [comment]
@marcosmoura ok. thanx for your answer.
I guess, there is no any way to extract components css to single file? It's very bad practice for my project to inline tonns of css.
Another question - component internal scss editing if I need.. where and how?

**Comment by marcosmoura** [comment]
No. There is: https://github.com/vuejs/vue-loader/blob/master/docs/en/configurations/extract-css.md
About editing internal SCSS. You can't right now. Just override the css on your own codebase.

**Comment by ArnyS** [comment]
@marcosmoura 
1. Vue-loader with axtract, actually resolve nothing while I can't compile from source...
2. Inline styles <style>..</style> appears always after any imported css files in HEAD in html, so I can't override..

**Comment by Samuell1** [comment]
@ArnyS in vue-cli templates its possible to overwrite, i think you using some weird boilerplate

**Comment by akaSybe** [comment]
I agree with @ArnyS. It will be great to have ability to override SASS variables.

**Comment by zevdg** [comment]
Another good reason to compile SCSS from source would be to reduce bundle size as described in https://github.com/vuematerial/vue-material/issues/1413#issuecomment-358842505.  For people trying to [keep their bundle sizes small](https://youtu.be/0A-2BhEZiM4?t=650), having a well documented, officially supported, advanced "compile SCSS from source" option would be immensely helpful.
