### ISSUE TITLE
reduce npm engine requirement to 6

### ISSUE THREAD

**Issue by phlogisticfugu** [vuematerial/vue-material#1271]
Currently the package.json requires node 7 or higher to be installed
```
"node": ">= 7.0"
```

But this seems to be stricter than necessary, as vue-material doesn't actually use some of the new features in node 7.  Note also that node 7 is not a long term support version for node.js:
https://github.com/nodejs/Release

This is, however, causing problems in our own code as I am deploying to AWS Lambda which supports node version 6.x (LTS) and thus am running that locally to ensure compatibility.
https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

Could the package.json requirement be reduced to:
```
"node": ">= 6.0"
```
?

**Comment by Samuell1** [comment]
When i was testing on node 6, i get error with SSR because node 6 doesnt support `Object.values`.  https://stackoverflow.com/questions/40421825/how-to-use-object-values-on-server-side-in-node-js

**Comment by phlogisticfugu** [comment]
oh, would there be any possibilty for using a shim?
https://www.npmjs.com/package/object.values

using that would help with expanding the platforms that one is able to deploy to.

**Comment by Samuell1** [comment]
Can you try if your project is running on node 6.10.x? like they using on aws

**Comment by phlogisticfugu** [comment]
actually it did not run on node 6.10 (MacOSX) due to missing ES6 features in node.

It may help to use this babel plugin when compiling the code: https://www.npmjs.com/package/babel-preset-vue-app
