### ISSUE TITLE
[md-select] v-model in @md-selected returns previous value

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1275]
If you try to get the value of v-model in the @md-selected event of md-select then it always shows the previous value and not the current selected one. 

Is it possible to get the current value of v-model like in the @change event of select in vuejs?

**Comment by Samuell1** [comment]
Do you using 1.0.0-beta7 version? I tested it and its working normally.

**Comment by zapping** [comment]
Its 1.0.0-beta7

**Comment by Samuell1** [comment]
Can you please provide example at codepen or your code?

There is gif i tested it with multiple select
![2017-12-07_09-17-23](https://user-images.githubusercontent.com/3110002/33726574-b0ff5b78-db75-11e7-8afa-077263881a73.gif)

**Comment by VdustR** [comment]
In your case,

```javascript
mdSelected () {
  this.paymentMode = this.paymentModes;
  console.log(this.paymentModes);
}
```

`this.paymentModes` would be changed on the next tick (it's next **x2** actually), you should change it to:

```javascript
mdSelected (val) {
  this.paymentMode = val;
  console.log(val);
}
```

and your would get the right value.

**Comment by zapping** [comment]
What would go into the parameter `val`? I tried changing the event to  `@md-selected="mdSelected(paymentModes)"` but still the same result. The pen mentioned above has been modified.

**Comment by zapping** [comment]
Thank you. Figured it. Its working now.

**Comment by VdustR** [comment]
No problem.

I already sent a PR for fixing the event emit time.

Your original code will work after it merged.
