### ISSUE TITLE
How to use primary / accent for text colour?

### ISSUE THREAD

**Issue by philBrown** [vuematerial/vue-material#1276]
Hi

I'm probably missing something very obvious here but I'd like to use the primary or accent colours in title elements. For example

```html
<h1 class="md-display-2 md-primary">Welcome</h1>
```

This does not currently do anything and I can't seem to find anything that works.

**Comment by Samuell1** [comment]
Material Design doesnt allow you to use primary or accent colors on titles. 

But if you want it you can define it by yourself on your custom scss.
