### ISSUE TITLE
Checkbox does not allow dynamic values

### ISSUE THREAD

**Issue by philBrown** [vuematerial/vue-material#1277]
Say I have an array of objects and want to use checkboxes to create a filtered set of attributes, for example

 ```javascript
{
things: [{id: 1, name: 'One'}, {id: 2, name: 'Two'}, {id: 3, name: 'Three'} ... ],
selectedThings: []
}
```
Because you've used `v-model` in the checkbox component, we cannot bind the `value` attribute like this.

```html
<div v-for="thing in things" :key="thing.id">
  <md-checkbox v-model="selectedThings" :value="thing.id"/>
  <span>{{thing.name}}</span>
</div>
```

Vue triggers the error...

> - :value conflicts with v-model on the same element because the latter already expands to a value binding internally

All you would have to do is use a different prop name than `value`.

**Comment by philBrown** [comment]
Ah, after looking through the source code, I see I can use `:model` instead of `v-model` to get around this limitation.

Might be good to add that to the documentation :)

**Comment by Samuell1** [comment]
This is weird because i tested it and i doesnt get any error.

**Comment by philBrown** [comment]
I'm using Vue 2.5.5 if that helps. The error was reported by vue-template-compiler

**Comment by Samuell1** [comment]
@philBrown update vue and vue-template-compile to 2.5.9 and should work

**Comment by philBrown** [comment]
Yep, that sorted it :)

**Comment by philBrown** [comment]
For reference ~ https://github.com/vuejs/vue/issues/7084

**Comment by Samuell1** [comment]
Yeah we had this issue few weeks ago https://github.com/vuematerial/vue-material/issues/1167
