### ISSUE TITLE
[md-input] is not recognized in form-serialize

### ISSUE THREAD

**Issue by CharlesKumar** [vuematerial/vue-material#1278]
vue.js latest stable (^2.5.8)
vue-material@beta latest (^1.0.0-beta-7)

[form-serialize](https://github.com/defunctzombie/form-serialize) is popular for serializing form inputs 

It process the input element correctly but returns nothing with md-input

> // node names which could be successful controls
var k_r_success_contrls = /^(?:input|select|textarea|keygen)/i;

Upon rendering md-input becomes input (inspected and copied from browser console)

`<div class="md-field md-layout-item md-size-48 m-1p md-small-size-100 md-theme-default md-has-value">
<label for="username">Your Name</label>
 <input id="username" class="md-input" type="text">   </div>`

How to approach this 

1. whether modify serialize function to see for md-input 

2. use vuejs hooks to determine post DOM render and call serialize

Expected behavior:

serialize the form data to use in ajax request (XMLHttp)

**Comment by Samuell1** [comment]
I recommend using vuelidate to validate forms. You can see example here: https://vuematerial.io/components/form

**Comment by CharlesKumar** [comment]
Thanks for quick reply 

The above examples doesn't contain information on how to serialize form data 

I am looking for serialize the form in client side and send them through ajax request to the server.

Based on response display success or failure message.

**Comment by zapping** [comment]
Can you try by including the `name` attribute as well along with the `md-input` component? Like this:

```
<md-field>
    <label for="username">Your Name</label>
    <md-input id="username" name="username" v-model="initial"></md-input>
</md-field>
```

**Comment by Samuell1** [comment]
@CharlesKumar vuelidate is cool package to validate or serialize you can see info about it here: https://monterail.github.io/vuelidate/

**Comment by korylprince** [comment]
@CharlesKumar I've created an example of how you could use this library: https://codepen.io/korylprince/pen/LOwNro

However, you really shouldn't. You're much better off constructing the data object you want to send your self and using something like axios to serialize and do your XMLHttpRequest.

Using serialize makes you interact directly with the DOM which isn't really the Vue way, especially if there's a lot better alternatives.

**Comment by CharlesKumar** [comment]
Thanks for the quick response and especially for an example in codepen 

your [example](https://codepen.io/korylprince/pen/LOwNro) has error both in firefox and chrome

> Uncaught ReferenceError: module is not defined

why Vue.use(VueMaterial.default) works well but Vue.use(VueMaterial) breaks in the [pen](https://codepen.io/korylprince/pen/LOwNro)

The click me button shows the correct value (desired serialized object) for default/initial values (John Smith) but breaks if i change value and hit click me

Actually setting `empty: true` in [options](https://github.com/defunctzombie/form-serialize#api) works well

**Comment by CharlesKumar** [comment]
@zapping Yeah I created like the same way you shown -- no problem with that

[1](https://www.w3.org/WAI/tutorials/forms/labels/)

**Comment by korylprince** [comment]
@CharlesKumar the reason for the VueMaterial.default and the console error is because I'm just importing from a CDN instead of using Webpack to build.

If you were to use webpack, you wouldn't see either of those issues.

As far as it only working once, I'm really not sure why.

**Comment by CharlesKumar** [comment]
The problem is still worse...

```
<form @submit.prevent="saveProduct" action="/fileupload.php" id="pform" name="pform" method="POST" enctype="multipart/form-data" class="md-layout md-gutter jcc">
      <md-field class="md-layout-item md-size-80">
        <label for="name">Product Name</label>
        <md-input name="name" id="name" type="text" value="model name" v-model.lazy="form.name" />
      </md-field>
      <md-field class="md-layout-item md-size-80">
        <label for="brand">Brand</label>
        <md-input name="brand" id="brand" type="text" value="brand name" v-model.lazy="form.brand" />
      </md-field>
      <md-field class="md-layout-item md-size-30">
        <label for="price">Price</label>
        <md-input name="price" id="price" type="number" value="price" v-model.lazy="form.price" />
      </md-field>
      <md-field class="md-layout-item md-size-30">
        <label for="imgsrc">Upload Image</label>
        <!-- <input type="hidden" name="MAX_FILE_SIZE" value="30000" /> -->
        <md-file name="imgsrc" id="imgsrc" v-model="form.imgsrc" accept="image/*"></md-file>
      </md-field>
      <img class="thumb" src="" alt=""/>
      <md-field class="md-layout-item md-size-80">
        <label for="description">Description</label>
        <md-textarea id="description" name="description" value="desc" v-model="form.description"></textarea>
      </md-field>
      <md-field class="md-layout-item md-size-60">
        <md-button type="submit" name="submit" class="theme-teal" value="Add Product">Add Product</md-button>
      </md-field>
    </form>
```

```
js

serializedData = new FormData(form);
```

In the request payload all the values for md-input are not showing up...

simply md-input not working as expected. I am reading [this article](https://www.smashingmagazine.com/2017/08/creating-custom-inputs-vue-js/) but couldn't get a viable solution
