### ISSUE TITLE
[MdDialog] title not support direction: RTL

### ISSUE THREAD

**Issue by omriLugasi** [vuematerial/vue-material#1284]
md-dialog component not support `RTL` direction

### Which browser?
Chrome, Explorer, FF

### What is expected?

md-dialog should support rtl option with directive of `rtl-dialog`.

Should I create a pull request?

**Comment by omriLugasi** [comment]
@Samuell1  Should i help you with `RTL ` issues through pull request?

**Comment by Samuell1** [comment]
@omriLugasi there will be good to have global RTL support for all components (https://github.com/vuematerial/vue-material/issues/80)

**Comment by Samuell1** [comment]
Closing this issue, please point any questions about RTL in issue #80
