### ISSUE TITLE
[MdChips] custom duplicated checking method

### ISSUE THREAD

**Issue by VdustR** [vuematerial/vue-material#1288]
As we have rejecting duplicated chip by comparing strings whether they are equal, I think we could add an optional `props` for the comparing method for cases like regarding `apple` and `Apple`  as the same chip or regarding accent characters like `e`, `è`(`String.fromCharCode(0x65, 0x300)`), `è`(`String.fromCharCode(0xe8)`) as the same character.

**Comment by Samuell1** [comment]
Maybe we can use fuzzy search like table is using?
