### ISSUE TITLE
[1.0.0-beta-7, Bug] App doesn't working in miui browser

### ISSUE THREAD

**Issue by Gagydzer** [vuematerial/vue-material#1289]
Hello, i've got the bug in the xiaomi browser, my clear app just doesn't working with a version 1.0.0-beta-7.  If i use 0.8.1 it's ok.

**Comment by VdustR** [comment]
Any error message or screenshot?

**Comment by Gagydzer** [comment]
just whitescreen

**Comment by Samuell1** [comment]
Can be same issue as this? https://github.com/vuematerial/vue-material/issues/1137

**Comment by Gagydzer** [comment]
yeah, i see same whitescreen :smile_cat:
