### ISSUE TITLE
[Bug - MdAutocomplete] Error when selecting an option from Object array

### ISSUE THREAD

**Issue by sim-jo** [vuematerial/vue-material#1290]
### Steps to reproduce
Reproducible on the demo site (https://vuematerial.io/components/autocomplete)
demo site -> autocomplete -> custom template -> select any option

### Which browser?
Vue 2.5, Material1 beta7

### What is expected?
The selected option is supposed to be selected

### What is actually happening?
Selected option does not get selected!

The searchTerm parameter expects a string as opposed to an object -> matchText method calls string.toLowerCase which doesnt exist on object.

Error: this.searchTerm.toLowerCase is not a function

### Reproduction Link
https://vuematerial.io/components/autocomplete

**Comment by Samuell1** [comment]
Duplicated: https://github.com/vuematerial/vue-material/issues/1243
