### ISSUE TITLE
[MdTable] pre select items with selection

### ISSUE THREAD

**Issue by samuelazran** [vuematerial/vue-material#1292]
Is it possible to programmatically select items in the table?
I can't find the option in the api as well as when looking at the code of the table component.
Would be handy to have property for it for example:
``
<md-table>
            <md-table-row slot="md-table-row" slot-scope="{ item }" md-selectable="multiple" md-auto-select :md-is-selected="true">
``
If it's not possible currently, is my only option is to fork and add the option?

Thanks

**Comment by Samuell1** [comment]
Hey, yes now its not possible. If you can add it it will be cool!
