### ISSUE TITLE
md-datepicker events

### ISSUE THREAD

**Issue by mhsystem** [vuematerial/vue-material#1296]
Hello, how can I take date change event on:click or on:selected not work ...

**Comment by Samuell1** [comment]
Use `v-model`

**Comment by mhsystem** [comment]
OK, but there is still some mistakes, when I type into date field manually, it randomly change date, not possible to type it directly

**Comment by VdustR** [comment]
which browser?

**Comment by mhsystem** [comment]
Safari, macOS

**Comment by Samuell1** [comment]
Can you make gif? @mhsystem

**Comment by mhsystem** [comment]
it looks like some problem with national date format, because unde MAC I have YYYY/MM/DD and in Windows I have dd.mm.yyyy. For our country is typically dd..mm.yyyy }and in windows I see .rrrr instead of .yyyy, it is also correct)

**Comment by Samuell1** [comment]
@mhsystem its because datepicker now using local date format
