### ISSUE TITLE
md-select with md-dialogs

### ISSUE THREAD

**Issue by leozdim** [vuematerial/vue-material#1298]
When you have a md-select inside a md-dialog, the select options aren't displayed because z-index
### Steps to reproduce
`
<md-dialog>
	<md-dialog-title>Lorem</md-dialog-title>
	<md-dialog-content>
		<md-field :class="v.lorem">
			<label for="lorem">Tipo</label>
			<md-select v-model="d.lorem" name="lorem" id="lorem">
				<md-option value="a">A</md-option>
				<md-option value="b">B</md-option>
				<md-option value="c">C</md-option>
				<md-option value="d">D</md-option>
			</md-select>
		</md-field>
	</md-dialog-content>
</md-dialog>
`

### Which browser?
Safari, Chrome, Chromium, Firefox

### What is expected?
The md-option muy be at front, not in the back from the md-dialog

### What is actually happening?
md-option is imposible to be selected because it appears in the back of the md-dialog

### Temporal solution
.md-dialog {
  z-index: 60 !important;
}

**Comment by Samuell1** [comment]
This is fixed in PR after new update you can remove your temp solution: https://github.com/vuematerial/vue-material/pull/1264
