### ISSUE TITLE
IE11 Bug - Object doesn't support property or method 'values'

### ISSUE THREAD

**Issue by tarvold** [vuematerial/vue-material#1299]
var MdComponents = _interopRequireWildcard(_components);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var VueMaterial = function VueMaterial(Vue) {
  (0, _material2.default)(Vue);

  Object.values(MdComponents).forEach(function (MdComponent) {
    Vue.use(MdComponent);
  });
};

**Comment by Samuell1** [comment]
Duplicated: https://github.com/vuematerial/vue-material/issues/1182
