### ISSUE TITLE
How to use `Form Validate` for detail?

### ISSUE THREAD

**Issue by thearabbit** [vuematerial/vue-material#1300]
How to use `Form Validate` for detail?

**Comment by VdustR** [comment]
I wrote an example on [Codepen](https://codepen.io/VdustR/pen/goOOQW)

Add class `md-invalid` to `<md-field>` while the field is invalid, then it will show `<span class="md-error"></span>`.

**Comment by thearabbit** [comment]
`Rules` detail?

**Comment by VdustR** [comment]
The rules do not defined in vue material. You need to customize methods to decide when class `md-invalid` add and what is the error message or use it along with other Vue 3rd party validation libraries, like [Vuelidate](https://monterail.github.io/vuelidate/) or [Vee-Validate](http://vee-validate.logaretm.com/) as the [documentation](https://vuematerial.io/components/input) said.

**Comment by thearabbit** [comment]
Thanks again, i will try 👍
