### ISSUE TITLE
md-large-size-70

### ISSUE THREAD

**Issue by larrymacbarry** [vuematerial/vue-material#1302]

**Comment by larrymacbarry** [comment]
md-[breakpoint]-size-[amount] layout system not working for "large" and "xlarge" breakpoints, looks like it absent in vue-material.css. Also I like ur framework but could u make something like ".container" class as in bootstrap or materialize?

**Comment by Samuell1** [comment]
Duplicated: https://github.com/vuematerial/vue-material/issues/1242
