### ISSUE TITLE
[md-input] min-length property

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1303]
Similar to max-length property can a min-length property be included to the input component. 

Also an option to hide the counter. This is useful in case of password component so that somebody else does not see how many characters are being entered or have been entered by the profile owner.

**Comment by zapping** [comment]
Please ignore the request for hiding the counter. Just noticed that `md-counter` property is already available. Sorry for the confusion.

**Comment by VdustR** [comment]
You could pass attributes to `md-input` if you need:

```vue
<md-field>
  <label>Initial Value</label>
  <md-input v-model="initial" minlength="3"></md-input>
</md-field>
```
