### ISSUE TITLE
[MdTabs] indicator has wrong behaviour in Safari

### ISSUE THREAD

**Issue by andershjort** [vuematerial/vue-material#1304]
### Steps to reproduce

Go here: https://vuematerial.io/components/tabs/home with Safari on OSX and click the tabs

### Which browser?

Safari 11.0.2 (12604.4.7.1.4) OSX Sierra 10.12.6 (16G1036)

### What is expected?

The tab indicator should slide gracefully back and forth when I click the tabs.

### What is actually happening?

The indicator slides back and forth, but the width varies from 0 to much-too-wide

This seems to be an issue with transitioning the value for "right" on the tab indicator. The issue is not appearing in Chrome or Firefox, just Safari.

**Comment by VdustR** [comment]
![dec-16-2017 00-51-38](https://user-images.githubusercontent.com/29639463/34051986-79053512-e1fb-11e7-83f4-de5161183a15.gif)
