### ISSUE TITLE
md-toolbar changes size at incorrect widths

### ISSUE THREAD

**Issue by zevdg** [vuematerial/vue-material#1307]
### Steps to reproduce

open https://vuematerial.io/components/app  
Resize the screen and note exactly where the toolbar changes height.

### Which browser?

At least chrome

### What is expected?

The toolbar should changes size at 600 and 960 (as per https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints )

### What is actually happening?

the toolbar is resizing at 600 and 944 due to https://github.com/vuematerial/vue-material/blob/652a0c684d336227cb55a8f5f159bdb6161d214c/src/components/MdLayout/mixins.scss#L15

This line of code appears to be compensating for margins or something, but it doesn't seem to be necessary in this case.

### Reproduction Link

https://vuematerial.io/components/app

**Comment by Ten-Taken** [comment]
Can confirm this affects more than the toolbar, it's the breakpoints in general. Have tested with.

`md-small-size-[amount]`

and the `md-hide` classes.

Media query is triggered at 944px, while the closest breakpoint in documentation is 960px.  

It would also be nice to know if the responsive classes work on a range (and in which direction) similar to bootstrap, or if there needs to be an explicit class for each breakpoint.  It seems like it is triggered from high --> low, but not sure.

Thanks for the work, the library is pretty nice.

**Comment by Samuell1** [comment]
@marcosmoura this can be fixed by removing that `- 16px` ?

**Comment by marcosmoura** [comment]
Yes. :D
