### ISSUE TITLE
Vue Material beta-7 not working in IE11

### ISSUE THREAD

**Issue by andtii** [vuematerial/vue-material#1308]
The latest version of "vue-material": "1.0.0-beta-7" dosent work in IE11

### Steps to reproduce
Run VueMaterial in IE11

### Which browser?
IE11

### What is expected?
VueMaterial working in IE11

### What is actually happening?
IE Throws exception that Object.values is undefined

![image](https://user-images.githubusercontent.com/1434571/33990751-46375d3e-e0cc-11e7-846d-dafdcc62ba3a.png)

**Comment by VdustR** [comment]
Duplicated: #1182
