### ISSUE TITLE
DatePicker locale

### ISSUE THREAD

**Issue by frankpaul142** [vuematerial/vue-material#1310]
DatePicker can't set locale language.

**Comment by Samuell1** [comment]
You can access locales with `this.$material.locale`

Here is object what you need to pass there: https://github.com/vuematerial/vue-material/blob/dev/src/material.js#L9

**Comment by frankpaul142** [comment]
thanks so much !

**Comment by epileftro85** [comment]
Great!, but what about the cancel and ok buttons?

**Comment by Samurai016** [comment]
> You can access locales with `this.$material.locale`
> 
> Here is object what you need to pass there: https://github.com/vuematerial/vue-material/blob/dev/src/material.js#L9

And so I need to edit `material.js` in my node_modules and then I need to run `npm install` command to rebuild the vue-material node?

**Comment by Samuell1** [comment]
@epileftro85 https://github.com/vuematerial/vue-material/issues/1970

**Comment by BorisBrogle** [comment]
I am trying to add localisation support to my project but I cannot find any way to override/hack the default Cancel button. 
I prefer to avoid switching to another datepicker (as the rest of my project uses vue-material) so if someone has a solution I would be very thankful..

**Comment by ianacid** [comment]
@BorisBrogle Hi,
I found a small solution for that, I think that it could be more clean, but for now it do the job:

so, in my javascript file, I wrote that:
`Vue.material.locale.cancelButton = "Annuler";`  (for a french translation for example)

the second step is to search/replace in the **vue-material.min.js** file the following content 
search `e._v("Cancel")`  and replace by `e._v(e.locale.cancelButton)`

for me now I can change the label easily

**Comment by BorisBrogle** [comment]
Hi @ianacid, thanks for your answer.

Yeah I guess the only solution at the moment is to change directly in the package files like you did. I will do it that way then. 

Hopefully it will change pretty soon as I saw there are new maintainers on the project!
