### ISSUE TITLE
Uncaught TypeError: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by iamaaron** [vuematerial/vue-material#1313]
Including the beta version (7) of VueMaterial breaks my application.

**Below is the error I receive in the browser.**

> vue.esm.js?65d7:4669 Uncaught TypeError: Cannot read property 'install' of undefined
    at Function.Vue.use (vue.esm.js?65d7:4669)
    at eval (main.js?1c90:15)
    at Object.<anonymous> (app.js:1227)
    at __webpack_require__ (app.js:660)
    at fn (app.js:86)
    at Object.<anonymous> (app.js:1925)
    at __webpack_require__ (app.js:660)
    at app.js:709
    at app.js:712
Vue.use @ vue.esm.js?65d7:4669
(anonymous) @ main.js?1c90:15
(anonymous) @ app.js:1227
__webpack_require__ @ app.js:660
fn @ app.js:86
(anonymous) @ app.js:1925
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712
vue.esm.js?b306:8427 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Below is what my implementation looks like.**

```
import Vue from 'vue';
import * as VueMaterial from 'vue-material';

Vue.use(VueMaterial);
Vue.use(VueMaterial.MdCore);
```

I've seen others with the same issue denoting that change mdCore to capitalized MdCore fixes the issue, but it does not for me.

### Steps to reproduce

1. Use Vue CLI or any other means of installation.
2. Import VueMaterial in the main.js file, per the getting started docs.
3. Run the application.

### Which browser?

Vue: 2.5.4
Vue-Material: 1.0.0-beta-7
Browser: Chrome

### What is expected?

The application to work properly.

### What is actually happening?

It looks like VueMaterial isn't being installed correctly.

**Comment by Samuell1** [comment]
Try without `Vue.use(VueMaterial);`

**Comment by qodehub-nanadjei** [comment]
I am having the same issue.
