### ISSUE TITLE
<md-select multiple> Clicking on tick does not toggle the corresponding option in v-model

### ISSUE THREAD

**Issue by ValentineStone** [vuematerial/vue-material#1314]
### Steps to reproduce
1. Open https://vuematerial.io/components/select
2. Go to **Multiple selection** section
3. Clicking on items in selection list works great, but clicking on the tick is ignored. The selection animation still happens, but the model is not modified creating a ghost-selected item. Clicking somewhere else and then back on `md-select` removes all ghosts.

NOTE: Clicking not on the tick of an already ghost-selected item preforms the deselect animation, but actually selects the item and adds it to the model.
This leads me to believe that there is something up with event bindings, maybe a `.self` modifier creeping into `@click` of `<md-option>` or something.

### Which browser?

Google Chrome
Version 63.0.3239.84 (Official Build) (64-bit) [Windows 10]

### What is expected?

Clicking on the tick in an `<md-select multiple>` option should toggle the item's presence in  `v-model` array

### What is actually happening?

Clicking on the tick in an `<md-select multiple>` option is ignored by model, yet selection animation still happens

### Reproduction Link

https://vuematerial.io/components/select

**Comment by VdustR** [comment]
#1293
