### ISSUE TITLE
Font-size is rendered to 1 px and not visible in textarea in Mac

### ISSUE THREAD

**Issue by s4jj4n** [vuematerial/vue-material#1315]
### Steps to reproduce
Visit https://vuematerial.io/components/input using Mac 
and type anything in the textarea, font-size is rendered to 1 px and not visible. 

### Which browser?

Chrome

### What is expected?

When you type in textarea, it should be visible.

### What is actually happening?

Font size is too small to see anything.

### Reproduction Link

https://vuematerial.io/components/input

**Comment by Samuell1** [comment]
Related to? https://github.com/vuematerial/vue-material/pull/1156
