### ISSUE TITLE
bug(MdAutocomplete) (1.0.0-beta) Disabled autocompletes shouldn't be clearable

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1321]
### Steps to reproduce
```
<md-autocomplete :md-options="choices" v-model="text" disabled>
  <label>Text</label>
</md-autocomplete>
```

### Which browser?

1.0.0-beta-7

**Comment by praveenpuglia** [comment]
Can you please explain what you mean by clearable? I am setting disabled attribute to autocomplete and i don't see an enabled input. 

Would be great if you could make a CodePen or similar example.

**Comment by emman27** [comment]
@praveenpuglia The cross still shows up and you can click it to clear the field, the example given above is actually sufficient to showcase this. Sorry I can't seem to get a working pen using the beta versions of VueMaterial.
