### ISSUE TITLE
Autocomplete with template + object array this.searchTerm.toLowerCase is not a function

### ISSUE THREAD

**Issue by Abenezer** [vuematerial/vue-material#1322]
when autocomplete with object array options is used the searchTerm  is bounded to the whole object (value), then  it tries to to execute toLowerCase assuming it is a string (but it is an object ) 

`<md-autocomplete v-model="value" :md-options="colors">
      <label>Color</label>
   <template slot="md-autocomplete-item" slot-scope="{ item, term }">
                 {{item.name}}
      </template>
</md-autocomplete >`
....
`      colors: [
        { name: 'Aqua', color: '#00ffff' },
        { name: 'Aquamarine', color: '#7fffd4' },
`

Steps to reproduce 

1 the bug is  is even on the [documentation ](https://vuematerial.io/components/autocomplete) custom template section 
open-up debugger (dev-tools) and see the bug after selecting a 'color' (usually after the second selection) 

2 if i searched '#ff' (in the documentation ) it shows results (colors with 'ff') but this should not be the accepted behavior (only the specific field should be searched (the name attribute in this case) not the whose stringfied object

the workaround is to use v:bind, v:on instead of v-model 
`<md-autocomplete  :value="color.name"  v-on:md-selected="val=>color=val"  :md-options="colors">`

but like other frameworks you should have a 'label' property to indicate witch attribute out of the selected object acts like a search term

**Comment by VdustR** [comment]
duplicated: #1243
