### ISSUE TITLE
Low framerate coming from getParentSize in md-ink-ripple effect - when rendering lots of checkboxes

### ISSUE THREAD

**Issue by VisualBean** [vuematerial/vue-material#1324]
I am getting terrible framerates when loading an array as checkboxes apparently it forces a complete reflow in chrome due to GetParentSize in md-ink-ripple

**Comment by VisualBean** [comment]
using 
```
var App = new Vue({
  el: '#app',
  mounted() {
    this.$material.inkRipple = false;
  }
})
```

Fixes the issue.

I believe it is due to checkboxes doing a collaborative wave when they are rendered?

**Comment by Samuell1** [comment]
Version of VueMaterial?

**Comment by VisualBean** [comment]
0.7.5 it would seem

**Comment by Samuell1** [comment]
Yes, older version has problems with framerate thats why there is new version. 

Sorry but now we are focused on new version. Can you try it?
