### ISSUE TITLE
File to import not found or unreadable: ~vue-material/theme/engine

### ISSUE THREAD

**Issue by leereichardt** [vuematerial/vue-material#1325]
### Steps to reproduce

1. Ran `vue init vuematerial/webpack .` to install the boilerplate template
2. Copy the columns example from (https://vuematerial.io/ui-elements/layout) and paste in to the default .vue file

### What is expected?

File should properly compile

### What is actually happening?

Module build failed: 
  @import "~vue-material/theme/engine";
^
      File to import not found or unreadable: ~vue-material/theme/engine.
Parent style sheet: stdin
      in /XXX/YYY/ZZZ/src/components/Index.vue (line 16, column 1)

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":false}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-82b7485c","scoped":true,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0&bustCache!./src/components/Index.vue 4:14-384 13:3-17:5 14:22-392
 @ ./src/components/Index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

I'm relatively new to webpack and I can't figure out why I can't compile the example using the boilerplate.

Hopefully, you can help?

**Comment by emman27** [comment]
I think you're looking for `~vue-material/dist/theme/engine` instead?

**Comment by Samuell1** [comment]
Like @emman27 said, you need to put `dist` in import.
