### ISSUE TITLE
md-app, md-app-toolbar, and  md-elevation

### ISSUE THREAD

**Issue by saknarak** [vuematerial/vue-material#1333]
### Steps to reproduce
```
<md-app md-waterfall md-mode="fixed">
  <md-app-toolbar md-elevatioin="4">
    <span class="md-title">My Title</span>
  </md-app-toolbar>
</md-app>
```

When its scroll top, elevation was gone (`md-no-elevation` was inserted)
I want to keep elevation, how can I do this?
Currently, I overwrite in css !important flag
But it would be nice if I can control via property.

**Comment by VdustR** [comment]
remove `md-waterfall`
