### ISSUE TITLE
[MdDialog] background color missing

### ISSUE THREAD

**Issue by VdustR** [vuematerial/vue-material#1335]
### Steps to reproduce

as @schmurfy mention in #1138.

Click the button to open the dialog.

https://codepen.io/anon/pen/dJOVBB

### Which browser?

`vue-material@1.0.0-beta-7`

Chrome 63.0.3239.84 (64bit) on Mac tested.

### What is expected?

Dialog should have a background color style from theme.

### What is actually happening?

It's transparent.

### Reproduction Link

https://codepen.io/anon/pen/dJOVBB

**Comment by Samuell1** [comment]
Looks like issue with theme, if you change CSS links to theme from `https://cdn.rawgit.com/vuematerial/vue-material/master/dist/default-theme.css` to `https://unpkg.com/vue-material@beta/dist/theme/default.css`

**Comment by VdustR** [comment]
Thanks, that works. I'll close this issue and reply in original post.
