### ISSUE TITLE
Cannot load only component in v.1.0.0 beta 7

### ISSUE THREAD

**Issue by Branksy** [vuematerial/vue-material#1336]
Trying the following:
import { MdDatepicker } from 'vue-material/dist/components'
Vue.use(MdDatepicker)

But Getting: 
Uncaught ReferenceError: regeneratorRuntime is not defined
    at eval (webpack-internal:///649:1)
    at Object.defineProperty.value (webpack-internal:///649:1)

However loading up all of VueMaterial works fine.

**Comment by korylprince** [comment]
I think this is a duplicate of issue #1182.

**Comment by Samuell1** [comment]
Duplicate of #1182
