### ISSUE TITLE
[MdTable] Table Select-All Issue

### ISSUE THREAD

**Issue by SirNeural** [vuematerial/vue-material#1348]
### Steps to reproduce

Create table with elements that can be sorted by id and other types, and sort them in a way that breaks the linearity of the id numbers. Once the select all checkbox is clicked, only some are selected.
Edit - There seems to be a litany of issues with select all, the same issue also appears and is reproducable in the codepen below with many other cases,
- By searching for specific elements and selecting all, not all are selected (e.g. search for 't' and try to select all elements https://i.imgur.com/YHyIUlS.png
- Exit out of that search and again try to select all on all elements, all of a sudden a few elements are not selected when clicking the select all. https://i.imgur.com/3ELZgb2.png

### Which browser?

Vue-Material@^1.0.0-beta-7
Vue@^2.5.0
Electron@1.7.10

### What is expected?

It should select all elements regardless of id order

### What is actually happening?

I believe it is using the id's to decide which elements to select, and when it encounters out of order id's it goes off.

### Reproduction Link

https://codepen.io/anon/pen/RxKMxW
Selecting all when sorted by id works fine, but when sorting by name or anything else that breaks the order of the ID column, not all elements are selected, only around half. https://i.imgur.com/pSTfj6N.png

**Comment by SirNeural** [comment]
Hi,
I see that the bug fix that fixed this issue was merged into beta-8, and I checked to see if my problem was fixed; Using the sort to sort ids out of order and then selecting works now, but while searching and then selecting elements, either not all, or more elements than were shown in the search results are selected.

This is a screenshot I got from the codepen posted above, updated to use the new beta-8
https://i.imgur.com/R609U8z.png
https://codepen.io/anon/pen/RxKMxW

Could you guys look into this?

Thanks a lot!

**Comment by VdustR** [comment]
@SirNeural :

Would you fix your production for missing method `getAlternateLabel`?


@marcosmoura:

I tried to remove this `abstract` to make it work

https://github.com/vuematerial/vue-material/blob/612a63d4f7e9908e2ed0a4a2986bd7a542357ce9/src/components/MdTable/MdTableRowGhost.vue#L4

It's seems that `abstract` is not documented. Is it a vue.js bug or should it be removed?

https://github.com/vuejs/vue/issues/7571

**Comment by SirNeural** [comment]
@VdustR heres the updated codepen
https://codepen.io/anon/pen/zRGema
