### ISSUE TITLE
Wrong backdrop when showing two dialogs on top of each other

### ISSUE THREAD

**Issue by timoschwarzer** [vuematerial/vue-material#1361]
### Steps to reproduce
Open a dialog with a button that opens a second dialog so we have two opened dialogs.
Make sure you leave the backdrop enabled for both dialogs.

### Which browser?
Vue 2.5.13
Vue Material 1.0-beta7
Chrome 63

**Note:** The dialog implementation in Vue Material 0.8 didn't have that problem.

### What is expected?
The backdrop of the second dialog should be shown in front of the first dialog.
The correct order should be (front to back): Dialog 2, Backdrop 2, Dialog 1, Backdrop 1

### What is actually happening?
The backdrop of the topmost dialog is shown behind the first dialog.
So the real order is (front to back): Dialog 2, Dialog 1, Backdrop 2, Backdrop 1

**Comment by Samuell1** [comment]
I think using 2 modals on top of each other is not a good from UX. Best way to make it looking good is to hide first and show second.

**Comment by marcosmoura** [comment]
I can see only one fix for this. As its not a good recommendation to have 2 opened dialogs, we will create a mechanism for close the last dialog before open another.
