### ISSUE TITLE
Responsive toolbar menu for 1.0

### ISSUE THREAD

**Issue by linde12** [vuematerial/vue-material#1364]
I have a question regarding making the drawer and toolbar behave responsively.

When running on a desktop i have a permanent drawer and a logo in the toolbar (just like the docs app https://vuematerial.io/getting-started) but when switching to a phone i want the menu icon to appear and the logo to disappear.

The way the docs app solves it is by importing some sass mixins and adding this sass snippet:

```
  .menu {
    display: none;
    @include md-layout-xsmall {
      display: inline-block;
    }
  }
```

Is there no way to solve this without using sass? I would like to avoid using sass at all (or any kind of styling if possible) and simply use something like md-xsmall-hide but reversed. md-hide is basically "show this for screens larger than X" but i want to do "show this for screens smaller than X" with a class.

If nothing like this exists, wouldn't it be a good feature? To me it seems like a pretty common thing that you might use in many places.

**Comment by Samuell1** [comment]
You can use media queries from CSS if you doesnt want to use SCSS mixins.

**Comment by linde12** [comment]
Yes but then i'd have to know the actual breakpoint sizes. That would result in duplication of the width value media query. If classes were exposed that used the same breakpoint variables it would be super simple and no custom css needed.
