### ISSUE TITLE
is safe to use beta version in production?

### ISSUE THREAD

**Issue by epileftro85** [vuematerial/vue-material#1366]
it is safe to use your beta version, should i wait or i have to use old version?

**Comment by tachiaus** [comment]
The new version appears to be much faster, and has a nicer look and feel to it.

I have been building a site to be used in production with it, the present beta 7 has a few issues with IE.

I think the issues will be ironed out by reading the threads here though.

**Comment by fimdomeio** [comment]
From my experience using it for a little bit while developing an app it seems pretty stable... there are some bugs that are a little annoying but nothing too serious.

**Comment by epileftro85** [comment]
I am planning using it in two proyects and I like the first version, well I will give it a try, than you

**Comment by Gagydzer** [comment]
new version still doesn't working in Xiaomi browser, at all.

**Comment by Samuell1** [comment]
@Gagydzer default browser for Xiaomi is IE?

**Comment by Gagydzer** [comment]
@Samuell1 
https://github.com/vuematerial/vue-material/issues/1289

**Comment by Samuell1** [comment]
@Gagydzer you can add https://babeljs.io/docs/usage/polyfill#installation polyfills and it should work in IE and other mobile browsers that doesnt support few things

**Comment by romuloalves** [comment]
I've developed a PWA with `vue-material@beta` and in a list of 20 items the scroll was pretty slow, so I re-wrote with `vuetify` and now it's smooth.

It seems to be not ready for production yet.

**Comment by felipekm** [comment]
@romuloalves I've experienced the same issue in one of my side projects.

**Comment by marcosmoura** [comment]
Vue Material *IS NOT* production ready yet, for big projects with lots of pages and lots of resources, like any other alpha/beta framework. This includes Vue Material, Vuetify, iView, Buefy and many others. In fact the 0.8.1 version of Vue Material have less bugs than beta version, which doesn't mean that it's better. 

We are still working on bugs and performance improvements to fine tune it to be stable enough for those scenarios.

We have plans to release a new version (beta 8) this month, with several bug fixes and documentation improvements.

Stay tuned! :)

**Comment by marcosmoura** [comment]
@romuloalves Can you detail better the issue? I've tested the md-list component with more than 100 items, in an 2011 mac mini, and everything went well. Maybe you created a scenario that I didn't covered.

**Comment by romuloalves** [comment]
@marcosmoura It was in Android 7.1.1 (Moto X4 - Google Chrome).
Every list item has its own input field.

I'm going to re-test in the next pre-release.

**Comment by marcosmoura** [comment]
Cool! Thanks!
I will try to address this fix to next version. I think ripple component on list item may create a performance glitchy. I will take a look asap

**Comment by Samuell1** [comment]
@romuloalves can you try turning off ripple with `this.$material.ripple = false` ?
