### ISSUE TITLE
MdSelect @change

### ISSUE THREAD

**Issue by brunosc** [vuematerial/vue-material#1374]
Hi,

Event change from MdSelect dont fire.

```
<md-field>
      <md-select name="deck" id="deck" @change="greet">                    
          <md-option value="1">1</md-option>
          <md-option value="2">2</md-option>
          <md-option value="3">3</md-option>
      </md-select>
  </md-field>

methods: {
    greet: function(event) {
      console.log('teste');
    }
  }
```

What I missing?

**Comment by tachiaus** [comment]
You could have a v-model on the select, you will need to specify greet as a variable in data.

Then watch for changes to the variable, changing the option will update set the option value to the greet variable.

eg
```
<md-field>
      <md-select name="deck" id="deck" v-model="greet">                    
          <md-option value="1">1</md-option>
          <md-option value="2">2</md-option>
          <md-option value="3">3</md-option>
      </md-select>
  </md-field>

watch: {
    greet: function(event) {
      console.log('teste');
    }
  }
```

**Comment by VdustR** [comment]
There is an event `md-selected` triggered when model changes.

https://vuematerial.io/components/select

**Comment by aleks-b** [comment]
how to use `md-selected`? can you proved some samples please

**Comment by piyushdolar** [comment]
<md-select
                      name="locationProvince"
                      id="locationProvince"
                      v-model="form.location.provinceId"
                      md-dense
                      :disabled="sending"
                      @md-selected="onProvinceSelect"
                    >

... // your option here
                    </md-select>


Just use @md-selected="functionName"



methods:{
functionName(v){
console.log(v);
}
}

**Comment by manojrai9889** [comment]
> <md-select
> name="locationProvince"
> id="locationProvince"
> v-model="form.location.provinceId"
> md-dense
> :disabled="sending"
> @md-selected="onProvinceSelect"
> >
> 
> ... // your option here
> Just use @md-selected="functionName"
> 
> methods:{
> functionName(v){
> console.log(v);
> }
> }

Thanks
