### ISSUE TITLE
How to disable md-table-row on hover styling?

### ISSUE THREAD

**Issue by fizxmike** [vuematerial/vue-material#1375]
- What will it allow you to do that you can't do today?
  - Disable the "active" highlighting of rows on hover for md-table
 - How will it make current work-arounds straightforward?
   - I haven't been able to disable this using css (but maybe I just suck)
 - What potential bugs and edge cases does it help to avoid?
   - Basically, I have a requirement where the background of a row should be slightly colored based on the contents... but the built in md-table-row hover styling interferes with that.

**Comment by Samuell1** [comment]
You can change color of row by adding class to it with background or with inline styles

**Comment by fizxmike** [comment]
Background styling works, But I can't figure out how to **disable the "active on hover highlighting" of the row**.

**Comment by Samuell1** [comment]
You can try

```
:hover {
 background: inherit;
}
```

**Comment by fizxmike** [comment]
didn't work: https://codepen.io/anon/pen/BJmaxG?&editors=111

Is the highlighting done with JS inside the component? I do not see any :hover definitions in the entire table when inspecting the CSS with Chrome developer tools:
![image](https://user-images.githubusercontent.com/4626398/34624656-af2cc440-f21b-11e7-94eb-0698f2ae03ff.png)

**Comment by Samuell1** [comment]
hover is on `tr`

**Comment by fizxmike** [comment]
Thanks, posting your solution here, Thanks!
```
.md-table-row:hover:not(.md-header-row) .md-table-cell{
  background: unset!important;
}
```
