### ISSUE TITLE
[MdDialog] can't scroll down in content

### ISSUE THREAD

**Issue by epileftro85** [vuematerial/vue-material#1381]
Reporting a bug?
================
YES

Have a feature request?
=======================
NO

### Steps to reproduce

Open a dialog with a table with several data, or just bunch of text, it doesn't scroll to view the bottom of the data, even in a table with fixed header or wrapping the content inside an scroll.

### Which browser?

tested in Chrome

### What is expected?

Can be able to scroll down to the bottom content.

### Reproduction Link
it is happening in your documentation too

https://vuematerial.io/components/dialog

**Comment by Samuell1** [comment]
If you wrap your content with `md-dialog-content` element, then it should allow scrolling in dialog
