### ISSUE TITLE
Can't install 1.0.0 on Windows

### ISSUE THREAD

**Issue by rcurrier666** [vuematerial/vue-material#1386]
The 1.0.0 version (the latest) can't be installed via `npm i --save` on WIndows in a cmd shell (aka a DOS prompt) because the postinstall process is attempting to execute a shell script (build/git-hooks/install.sh. Windows (obviously) doesn't support shell scripts.

I'm using Meteor+Vue so the NPM must be installed into my projects local node_modules folder. Output from the command:
```
C:\Users\Ron\vueStuff\penproject4>meteor npm i --save vue-material

> vue-material@1.0.0 postinstall C:\Users\Ron\vueStuff\penproject4\node_modules\vue-material
> sh build/git-hooks/install.sh

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-material@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ron\AppData\Roaming\npm-cache\_logs\2018-01-10T06_28_54_671Z-debug.log
```
The log file is attached.
[2018-01-10T06_23_47_514Z-debug.log](https://github.com/vuematerial/vue-material/files/1617742/2018-01-10T06_23_47_514Z-debug.log)

**Comment by Samuell1** [comment]
Can you try this? `npm i --save vue-material@beta`

**Comment by rcurrier666** [comment]
Works like a charm. Thanks for the quick fix.
