### ISSUE TITLE
[md-select] Only one populates value

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1389]
Can you please check this pen https://codepen.io/zapping/pen/RxMGZj ? If you click on the edit icon the corresponding md-select is supposed to show-up for edit. 

For some reason the md-select shows value for only one component and the rest does not populate. I tried adding normal select also along and that seems to populate without issues.

**Comment by Samuell1** [comment]
This is maybe same issue as this https://github.com/vuematerial/vue-material/issues/1262

**Comment by VdustR** [comment]
```
<md-option v-for="option in options[key]">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
```

Works fine with keys.
https://codepen.io/VdustR/pen/QaVvVz

Check [Vue.js guide](https://vuejs.org/guide/list.html#key)

**Comment by zapping** [comment]
Thank you for looking into it. It does work with the keys set.

 But actually what I have are different sets of select components in the form. As a short-cut to typing up different set of select components I had put them in a loop to generate a series of select components. In the same pen https://codepen.io/zapping/pen/RxMGZj the select components have been typed or entered separately. Unfortunately only one select component populates.

Sorry for the confusion.

**Comment by VdustR** [comment]
As @Samuell1 said, the options of `MdSelect` is not reactive yet. We will look into it. Thanks for reporting.

**Comment by zapping** [comment]
Can you please check this again? The vue-material .js and .css have been set to version beta-8 but the issue still exists.

**Comment by Samuell1** [comment]
@zapping can you please make reproduction in repository?

**Comment by zapping** [comment]
Sorry I didn't get you. The codepen for the issue was included before. 

If it will help I have removed all the additional code and included just the necessary code in this pen https://codepen.io/zapping/pen/BYzMKY

**Comment by Samuell1** [comment]
@zapping yeah i mean codepen sorry

**Comment by VdustR** [comment]
`v-model` must be updated on the next tick after `MdOptions` updated to make `MdSelect.items` be updated, or `MdSelect` could not get the value / text pair for the new options.

https://codepen.io/VdustR/pen/jZrJzq
