### ISSUE TITLE
[MdDialog] Prompt dialog – Cursor goes out of input in iOS

### ISSUE THREAD

**Issue by romuloalves** [vuematerial/vue-material#1391]
### Steps to reproduce

Open a prompt dialog, set the focus in the input and start typing.

### Which browser?

Browsers in iOS

### What is expected?

The cursor inside the input.

### Reproduction Link

[https://vuematerial.io/components/dialog](https://vuematerial.io/components/dialog)

**Comment by Samuell1** [comment]
Its same issue like this? If yes its bug in iOS. https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8

**Comment by romuloalves** [comment]
Ahhhh, OK!
Thank you @Samuell1 !
