### ISSUE TITLE
[MdTableRow] Allow custom click events

### ISSUE THREAD

**Issue by dreyn74** [vuematerial/vue-material#1392]
Is it possible to have custom click events(right-click[context]) on md-table-rows or md-table-cells?
Here is an example of the custom context menu, but if you remove the `@contextmenu="openMenu"` from 
`<div id="app" @contextmenu="openMenu">` the event's will not fire when clicking on the table rows,
even though there is also an `@contextmenu="openMenu` prop in the md-table-row tag.

https://codepen.io/dreyn74/pen/xppzjm?editors=1010

**Comment by Samuell1** [comment]
You need to use native events for components `@contextmenu.native`

**Comment by dreyn74** [comment]
Thanks for the quick reply!
Closed!

**Comment by marcosmoura** [comment]
@Samuell1 We can pass the events down using `$listeners` object. What do you think?

**Comment by Samuell1** [comment]
@dreyn74 after will be PR merged you can use simply `@contentmenu` without `native`
