### ISSUE TITLE
[MdSpinner] cannot be displayed in Microsoft Edge

### ISSUE THREAD

**Issue by tomzheng77** [vuematerial/vue-material#1398]
### Steps to reproduce

1. Create a new HTML file
2. Paste the code below
3. Save it and open it in Microsoft Edge

```<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width,initial-scale=1,minimal-ui" name="viewport">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Material+Icons">
    <link rel="stylesheet" href="https://unpkg.com/vue-material@beta/dist/vue-material.min.css">
    <link rel="stylesheet" href="https://unpkg.com/vue-material@beta/dist/theme/default.css">
  </head>

  <body>
    <div id="app">
      <md-progress-spinner md-mode="indeterminate"></md-progress-spinner>
    </div>

    <script src="https://unpkg.com/vue@2.5.13/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-material@1.0.0-beta-7/dist/vue-material.min.js"></script>
    <script>
      Vue.use(VueMaterial.default)
      new Vue({
        el: '#app'
      })
    </script>
  </body>
</html>
```

### Which browser?

I'm using Vue 2.5.13 and Vue Material 1.0.0-beta-7.
My browser is Microsoft Edge 17 running on Windows 10.

### What is expected?

An indeterminate spinner should be shown, similar to https://vuematerial.io/components/progress-spinner. The spinner on that page is displayed correctly in Edge.

### What is actually happening?

A circle is displayed, but it is not animated.

### Reproduction Link

https://jsfiddle.net/or5jhoyz/3/

**Comment by Samuell1** [comment]
For now EDGE doesnt not support CSS transform animations
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/supportcsstransformsonsvg/
