### ISSUE TITLE
[MdSelect] multiple value not populated when checkbox clicked.

### ISSUE THREAD

**Issue by Mac21** [vuematerial/vue-material#1405]
### Steps to reproduce
Click select to trigger open event, then click check box next to option and see that paymentModes doesn't update with new selected value.

### Which browser?
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

### What is expected?
paymentModes has value of checked item.

### What is actually happening?
paymentModes doesn't have value inserted/appended when checkbox is checked.

### Reproduction Link
https://codepen.io/anon/pen/aEabpw?editors=1011

**Comment by VdustR** [comment]
fixed in #1293.

It would work with next release.
