### ISSUE TITLE
Value not updated before blur

### ISSUE THREAD

**Issue by dtruel** [vuematerial/vue-material#1411]
Thanks for the hard work on this! It is a great library.

I have an input on my page that has a listener for the blur.native event. If the input is empty, it deletes it.  (these inputs are generated from a v-for. So if the last item is empty, it just cuts it out of the list).  The problem is that due to debouncing, If I type really quickly then push tab, it just deletes the input because when the blur event runs, the model value hasn't been updated yet.  I think to fix this, the component would need to listen for the blur event, update the model value, and then pass it on.  If you know of any fixes in the mean time, I would appreciate the help.  I am on the 0.7 branch.

**Comment by Samuell1** [comment]
You can disable debouncing by settings `:debounce="0"` on `md-input`

**Comment by dtruel** [comment]
Thank you @Samuell1
