### ISSUE TITLE
[MdBottomBarItem] Conditional Rendering of MdBottomBarItem

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1412]
Use v-if with computed property on MdBottomBarItem

Recent Chrome/Firefox

### What is expected?
The item shoukd be displayed or not and the correct route should be applied.

### What is actually happening?
The item is displayed on the actual condition but, there is thrown an error as well and the routing isn't applied.
The error message tells that the "to" property has to be passed. The property is passed as simple String,

**Comment by Samuell1** [comment]
Version of Vue Material?

**Comment by mrwhy-orig** [comment]
Sorry, i forgot to provide the requested infos:

VueMaterial Beta 7

```
<md-bottom-bar md-type="shift" class="md-layout md-alignment-center-center md-primary" md-sync-route>
<md-bottom-bar-item to="/" md-icon="home" md-label="Home" class="md-layout-item">
      </md-bottom-bar-item>
<md-bottom-bar-item v-if="funcPresent" to="/func" md-icon="lightbulb_outline" md-label="Func" class="md-layout-item"> </md-bottom-bar-item>
</md-bottom-bar>
```

```
export default {
    name: 'BottomNav',
    computed: {
        funcPresent(){
            return this.$store.getters.isFuncPresent;
        }
    }
}
```
