### ISSUE TITLE
Vue Material Imported Size

### ISSUE THREAD

**Issue by arranf** [vuematerial/vue-material#1413]
I've been doing some profiling on the size of my app bundles and it seems like the biggest contributor to my bundle (by a large margin) is Vue Material.

Additionally, this is complicated by the fact there doesn't seem to be a way to import individual components into a single file component so the code isn't split into a bundle per route. This means all of Vue Material is put into `main.js`. 

Are there any plans to make importing a components into components or plans to reduce the size of Vue Material?

**Comment by marcos-hotmart** [comment]
In fact there is a way to import individual components:
``` js
import Vue from 'vue'
import { MdButton, MdContent, MdTabs } from 'vue-material/dist/components'

Vue.use(MdButton)
Vue.use(MdContent)
Vue.use(MdTabs)
```

This can be done anywhere, even inside a SFC.

**Comment by Grawl** [comment]
You can import components individually. Built components have not styles because they are extracted to one large stylesheet with styles from all components, **but if you can build from sources you have individual components styles**.

Here's how I import components from sources.

`poi.config.js`

```js
module.exports = {
	webpack(config) {
		const VueMaterialJavaScriptLoader = {
			test: /vue-material.src.*?js$/,
			use: 'babel-loader'
		}
		config.module.rules.push(VueMaterialJavaScriptLoader)
		// there is some aliases Vue Material uses to build own sources, so we have to add them too
		config.resolve.alias['vue-material'] = 'vue-material/src'
		config.resolve.alias['components'] = 'vue-material/src/components'
		config.resolve.alias['core'] = 'vue-material/src/core'
		config.resolve.alias['theme'] = 'vue-material/src/theme'
		return config
	},
}
```

I build using [`poi`](https://poi.js.org), but it's a webpack config part so you can use it in webpack directly

`.babelrc`

```json
{
	"presets": [
		"env"
	],
	"plugins": [
		"transform-object-rest-spread"
	]
}
```

```sh
# install babel parts
yarn add -D babel-loader babel-plugin-transform-object-rest-spread babel-preset-env
# install Vue Material missing parts
yarn add is-firefox
```

I use yarn but you can use npm of course

`index.js`

```js
import Vue from 'vue'
import {
	MdApp,
	MdToolbar,
	MdDrawer,
	// …
} from 'vue-material/src/components'
Vue.use(MdApp)
Vue.use(MdToolbar)
Vue.use(MdDrawer)
// …
```

`vendor-vue-material.scss`

```scss
@import '~vue-material/theme/engine';
@include md-register-theme('default', (
  primary: skyblue,
));
@import "~components/MdApp/theme";
@import "~components/MdToolbar/theme";
@import "~components/MdDrawer/theme";
@import "~components/MdButton/theme";
@import "~components/MdIcon/theme";
@import "~components/MdList/theme";
@import "~components/MdContent/theme";
@import "~components/MdField/theme";
@import "~components/MdTable/theme";
```

Vue is about writing styles and templates with logic part inside one file, so importing Vue Material components from sources will get you what you want.

**Comment by qgustavor** [comment]
I tried importing like shown in the documentation and above - `import { MdButton, ... } from 'vue-material/dist/components'` - and the bundle size kept the same no matter how many components I select. Then I checked [the imported file](https://unpkg.com/vue-material/dist/components/index.js) and I found the problem: as it's a UMD module it's not possible to do tree shaking on it.

I tried importing components individually like `import MdButton from 'vue-material/dist/components/MdButton'`. Doing that reduced the bundle size, but it's still not optimal as those components are also UMD modules which can lead to code duplication (in case two or more imported modules depend on the same thing it will be duplicated).

What's the recommended workflow? Bundling from the source code like suggested on #1269?

**Comment by Huupke** [comment]
Now #1182 is solved in beta-10 I also started importing individual components but it only shaved of 6kb (from 645kb to 639kb). When I import components very specific like @qgustavor mentioned I shave of an additional 222kb (from 639kb to 417kb) which proves tree shaking needs these specific imports which makes importing a bit more verbose, especially when you import multiple components in one file.

I'm using the following:

```
"dependencies": {
...
    "typescript": "^2.9.2",
    "vue": "^2.5.17",
    "vue-material": "^1.0.0-beta-10.2"
  }
```

and  

```
"devDependencies": {
...
    "vue-class-component": "^6.3.2",
    "vue-loader": "^13.7.3",
    "vue-property-decorator": "^6.1.0",
    "vue-template-compiler": "^2.5.17",
    "webpack": "^3.12.0",
    "webpack-dev-server": "^2.11.3"
  }
```

**Comment by amucunguzi** [comment]
@Grawl how would you import a component like MdDialogAlert that does not seem to be in `dist/components`? @marcos-hotmart
