### ISSUE TITLE
Can´t register themes in the new beta version

### ISSUE THREAD

**Issue by cotufaloschiflones** [vuematerial/vue-material#1428]
Hello, I'm not be able to registering themes with the new beta version, this feature is not already available, right?

Awesome library btw 👍 ❤️

**Comment by Samuell1** [comment]
Can you please provide your code?

**Comment by Samuell1** [comment]
For registering theme you can use [Prebuild themes](https://vuematerial.io/themes/prebuil) or [configuration with SCSS](https://vuematerial.io/themes/configuration)

**Comment by bretonio** [comment]
In which file does one place the `@import` statements? I have a [simple PWA](https://github.com/groman00/vue-pwa-starter) starter project.with `main.js`.  Forgive my nubilism.

**Comment by Samuell1** [comment]
@bretonio `*.SCSS` files

**Comment by gaby64** [comment]
and then? one imports the scss in main.js?
