### ISSUE TITLE
Registering custom palette in beta

### ISSUE THREAD

**Issue by Ten-Taken** [vuematerial/vue-material#1429]
Hello, this can be marked as a question.

*Has a custom palette definition method been implemented in beta yet?* 
 
Along the lines of:  

`@include md-register-palette('color', {
50: '#hex',
100: '#hex' ...
})` 

 The [documentation](https://vuematerial.io/themes/configuration) provides for registering a theme via scss, but I do not see info on the palette.

In the theme engine source I see some functions to extend the palette, but I am new to scss, so I'm not sure what I need. Thanks.

**Comment by Samuell1** [comment]
You can register custom theme like this if you want custom HEX colors

```
@import "~vue-material/dist/theme/engine"; // Import the theme engine

@include md-register-theme("default", (
  primary: #3fffbe, // The primary color of your brand
  accent: #1a11e8 // The secondary color of your brand
));

@import "~vue-material/dist/theme/all"; // Apply the theme
```

**Comment by Ten-Taken** [comment]
Alright, thanks. Yeah I saw adding the custom colors and I can use that.  Was mostly curious if I could generate a palette map using the theme engine.  Appreciated.

**Comment by Samuell1** [comment]
You doesnt need to do that, you need to only define primary and accent colors.
