### ISSUE TITLE
[MdFile] - Doesn't return a FileList 

### ISSUE THREAD

**Issue by MickCoelho** [vuematerial/vue-material#1433]
The md-change event doesn't return a FileList, but an Event instead. 
Maybe I missed something, but AFAIK, the only way (as of now, using 1.0.0-beta-7) to get the FileList from it, is to do `event.target.files`.

**Comment by Samuell1** [comment]
Browser?

**Comment by Samuell1** [comment]
When you check in devtools what you see? Do you see this payload?
![obrazok](https://user-images.githubusercontent.com/3110002/35324431-fecb9b14-00f0-11e8-9f2a-cd86a4bf7a90.png)

**Comment by MickCoelho** [comment]
My bad, I was using `@change` instead of `@md-change`
