### ISSUE TITLE
MdSelect - Multiple selection - click on checkbox not working + preselection not working correctly

### ISSUE THREAD

**Issue by koslo** [vuematerial/vue-material#1443]
Hi,
it is not possible to select an item by clicking on the checkbox.
Providing an filled selectedValue array will mark the items but they are not shown in the text/input of the select.

**Comment by VdustR** [comment]
duplicated #1314 

fixed #1293

**Comment by koslo** [comment]
ok. thx.
when will the newest beta version be published on npm?

**Comment by nodetech-architecture** [comment]
This is happening to me too

**Comment by lightwaver** [comment]
yes when will this fix be available ?
