### ISSUE TITLE
TypeError: _vue2.default is not a constructor

### ISSUE THREAD

**Issue by newprogrammeram** [vuematerial/vue-material#1449]
i did'nt use of npm and 
it got show this error TypeError: _vue2.default is not a constructor 
in this line :_vue2.default
i use of  v1.0.0-beta-7
i work with  chrome 56 #error

**Comment by Samuell1** [comment]
Looks like you missing Vue in your project

**Comment by newprogrammeram** [comment]
<?php
$uvpath="vue-material/dist";

?>
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">

<link rel="stylesheet" href="<?=$uvpath?>/vue-material.css">
<script src="<?=$uvpath?>/vue-material.js"></script>
<template>
  <div class="example">
    <md-speed-dial :class="topPosition" md-direction="bottom">
      <md-speed-dial-target class="md-primary">
        <md-icon>my_location</md-icon>
      </md-speed-dial-target>

      <md-speed-dial-content>
        <md-button class="md-icon-button">
          <md-icon>directions</md-icon>
        </md-button>

        <md-button class="md-icon-button">
          <md-icon>streetview</md-icon>
        </md-button>
      </md-speed-dial-content>
    </md-speed-dial>

    <md-speed-dial :class="bottomPosition">
      <md-speed-dial-target>
        <md-icon>add</md-icon>
      </md-speed-dial-target>

      <md-speed-dial-content>
        <md-button class="md-icon-button">
          <md-icon>note</md-icon>
        </md-button>

        <md-button class="md-icon-button">
          <md-icon>event</md-icon>
        </md-button>
      </md-speed-dial-content>
    </md-speed-dial>

    <div class="demo-option">
      <div>
        <label for="top">Top</label>
        <select id="top" v-model="topPosition">
          <option value="md-top-left">Left</option>
          <option value="md-top-center">Center</option>
          <option value="md-top-right">Right</option>
        </select>
      </div>

      <div>
        <label for="bottom">Bottom</label>
        <select id="bottom" v-model="bottomPosition">
          <option value="md-bottom-left">Left</option>
          <option value="md-bottom-center">Center</option>
          <option value="md-bottom-right">Right</option>
        </select>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PositionDirection',
  data: () => ({
    topPosition: 'md-top-left',
    bottomPosition: 'md-bottom-left'
  })
}
</script>

<style lang="scss" scoped>
  .example {
    min-height: 300px;
  }

  .demo-option {
    display: flex;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);

    div {
      margin: 0 6px;
      display: flex;
      flex-direction: column;
    }
  }
</style>

**Comment by Samuell1** [comment]
And vue version?

**Comment by newprogrammeram** [comment]
it s  v1.0.0-beta-7

**Comment by Samuell1** [comment]
i mean vuejs version

**Comment by Samuell1** [comment]
You can read how to use vue-material here: https://vuematerial.io/getting-started/

**Comment by newprogrammeram** [comment]
thank i knew problem :)
i add vue js and solved problem
script src="https://unpkg.com/vue"></script
script src="https://cdn.jsdelivr.net/npm/vue-resource@1.3.4"></script

**Comment by newprogrammeram** [comment]
that give error of this line
export default {
and did'nt show anything!
