### ISSUE TITLE
is poosible angular material js without nodejas and npm?

### ISSUE THREAD

**Issue by newprogrammeram** [vuematerial/vue-material#1452]
i used, but that show this error
that give error of this line
export default {
and did'nt show anything!

**Comment by Morgul** [comment]
From the [docs](https://vuematerial.io/getting-started):

> Although is not the recommended approach, you can always use CDNs for fast prototyping:
> 
> ```html
> <!doctype html>
> <html>
>   <head>
>     <meta charset="utf-8">
>     <meta content="width=device-width,initial-scale=1,minimal-ui" name="viewport">
>     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic|Material+Icons">
>     <link rel="stylesheet" href="https://unpkg.com/vue-material@beta/dist/vue-material.min.css">
>     <link rel="stylesheet" href="https://unpkg.com/vue-material@beta/dist/theme/default.css">
>   </head>
> 
>   <body>
>     <div id="app">
>       
>     </div>
> 
>     <script src="https://unpkg.com/vue"></script>
>     <script src="https://unpkg.com/vue-material@beta"></script>
>     <script>
>       Vue.use(VueMaterial.default)
> 
>       new Vue({
>         el: '#app'
>       })
>     </script>
>   </body>
> </html>
> ```
>

The reason it gave you an `export default` error is because the code is build using `es modules`, which will not work in normal script tags. Using the packaged bundle will do what you want without requiring a build step.

**Comment by VdustR** [comment]
#1450
