### ISSUE TITLE
npm install error on 1.0.0 and beta

### ISSUE THREAD

**Issue by adrianjost** [vuematerial/vue-material#1453]
### Steps to reproduce

If I install vue-material with the command
`npm install vue-material@beta`
everything works fine. But when any of my co-workers than runs `npm install` to install all dependencies of the project on his device the following error occurs:

`sh: build/git-hooks/install.sh: No such file or directory`

Here is a [travis test](https://travis-ci.org/schul-cloud/schulcloud-content-editor/builds/333366780?utm_source=github_status&utm_medium=notification) where you can check out the complete log: [link](https://travis-ci.org/schul-cloud/schulcloud-content-editor/builds/333366780?utm_source=github_status&utm_medium=notification)

The same error occurs when using `npm install vue-material`

### solve temporarily
I can fix this issue by manually downloading vue-material from github and copy the files from `build` to my `node_modules` folder inside my project. Especially the `build/git-hooks` folder solves the problem. But I can't apply these tests on travis and the error shoudn't ever happen. Hope you can solve the  issue. Feel free to ask me if anything is unclear. 
Thanks

**Comment by VdustR** [comment]
duplicated #1155
