### ISSUE TITLE
Vue.material.registerTheme causes an error

### ISSUE THREAD

**Issue by larrymacbarry** [vuematerial/vue-material#1454]
Trying to register my theme:

Vue.use(VueMaterial);

Vue.material.registerTheme( 'default', { primary: 'red' } );

And it causes a next error:

**Uncaught TypeError: _vue2.default.material.registerTheme is not a function**

**Comment by Samuell1** [comment]
Do you have Vue in your project?

**Comment by czy1996** [comment]
i have the same issue, my vue version is 2.5.2 and vue material version is 1.0.0-beta-7

**Comment by VdustR** [comment]
`Vue.material.registerTheme` is for [old version](https://vue-material-old.netlify.com/#/themes/configuration).

You have to use [new API](https://vuematerial.io/themes/configuration) for `1.0.0-beta-7`.

**Comment by czy1996** [comment]
Thanks a lot!

**Comment by larrymacbarry** [comment]
If I want use several themes in my app:

@include md-register-theme("yellow", (
        primary: md-get-palette-color(yellow, A400), // The primary color of your application
        accent: md-get-palette-color(yellow, A200) // The accent or secondary color
))

@include md-register-theme("indigo", (
        primary: md-get-palette-color(indigo, A400), // The primary color of your application
        accent: md-get-palette-color(indigo, A200) // The accent or secondary color
))

How could I force change theme on my app?
There is no compilied styles for "indigo" and "yellow", only for "default"

**Comment by Samuell1** [comment]
Do you using SCSS? @larrymacbarry

**Comment by larrymacbarry** [comment]
Yes. I wanna change color themes in app using js methods in a components

**Comment by Samuell1** [comment]
@larrymacbarry do you have included theme engine? like is in docs?

**Comment by larrymacbarry** [comment]
yes:

@import "~vue-material/dist/theme/engine";

@include md-register-theme("default", (
        primary: md-get-palette-color(red, A400), // The primary color of your application
        accent: md-get-palette-color(red, A200) // The accent or secondary color
))

@include md-register-theme("yellow", (
        primary: md-get-palette-color(yellow, A400), // The primary color of your application
        accent: md-get-palette-color(yellow, A200) // The accent or secondary color
))

@include md-register-theme("indigo", (
        primary: md-get-palette-color(indigo, A400), // The primary color of your application
        accent: md-get-palette-color(indigo, A200) // The accent or secondary color
))

@import "~vue-material/dist/theme/all"; // Apply the theme

It's working as I change colors for "default"

How to apply my 'indigo' theme dynamically in component on emit event callback?

**Comment by Samuell1** [comment]
@larrymacbarry you can apply theme to components with `md-theme` prop

**Comment by larrymacbarry** [comment]
I get it. Thx, It will be fine to include that string to [](https://vuematerial.io/themes/configuration/)
with example.

**Comment by paraself** [comment]
@Samuell1 
Like this?
```
<md-app md-theme="default">
</md-app>
```
Tried, but did not work.
Could demonstrate how to change theme dynamically ? Many thanks!

**Comment by Samuell1** [comment]
@paraself yes like that but on md-app doesnt have that, only other components or you can change theme globally with
`this.$material.theming.theme = 'myTheme'`

**Comment by paraself** [comment]
```
this.$material.theming.theme = 'myTheme'
```
Thanks, this is exactly that I am looking for!

**Comment by adityatandon007** [comment]
@samuel1 I am looking to switch between default theme and dark theme for my entire app and I couldn't figure out how to do this. Here is my `App.vue`:
`<template>
  <div id="app">
    <md-app>
      <md-tabs md-alignment="fixed">
      <md-tab id="tab-home" md-icon="home" md-label="Pokemons"><PokeArc/></md-tab>
      <md-tab id="tab-search" md-icon="search" md-label="Find Pokemon"><FindPoke/></md-tab>
      <md-tab id="tab-fav" md-icon="favorite" md-label="Favorites"><Favorite/></md-tab>
      <md-tab id="tab-about" md-icon="pages" md-label="About"><About/></md-tab>
      </md-tabs>
      <div>
        <md-switch v-model="isDark">Toggle dark theme</md-switch>
      </div>
    </md-app>
  </div>
</template>`

and here is the `script` 
`<script>
export default {
  name: 'app',
  data () {
    return {
      isDark: false
    }
  }
}
</script>`

I want to use that switch to toggle the theme of `<md-app>` . How to do this. Any help would be great because I couldn't find in the docs how to do this.
