### ISSUE TITLE
[MdDatepicker] Needs to be timezone aware

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1459]
### Steps to reproduce
VueMaterial@1.0.0-beta-8

### Which browser?
Chrome 62

### What is expected?
Datepickers should be timezone aware. That is, if I select 1st Jan 2018 and my browser is in a +8GMT timezone, when cast to JSON the value I should get is `2018-01-01T00:00:00.000Z` and not `2017-12-31T16:00:00.000Z`

**Comment by emman27** [comment]
On second thoughts this doesn't really make sense. Shall close this.

**Comment by Samuell1** [comment]
Yes, value returned from datepicker is ISO. But i think we need to to change returned value from datepicker should be only date without time.
