### ISSUE TITLE
[MdRipple] does not work on buttons in Firefox

### ISSUE THREAD

**Issue by anckaertr** [vuematerial/vue-material#1461]
### Steps to reproduce

simply add a button on a page.

### Which browser?

Firefox 57.x, Firefox 58.x

### What is expected?

the ripple effect

### What is actually happening?
Nothing

**Comment by Samuell1** [comment]
Doesnt work only if **md-button** element is `button` because elements inside button doesnt have events.

**Comment by Soletiq** [comment]
+1 please fix
