### ISSUE TITLE
[md-expand] :md-expanded.sync not working

### ISSUE THREAD

**Issue by damaragung** [vuematerial/vue-material#1463]
Hi,, :md-expanded.sync is not working on codepen but working on doc site.  how can i make it work? 

https://codepen.io/anon/pen/JpYRbK

thank you very much for you help

**Comment by Samuell1** [comment]
Hey, its because unpkg is targeting beta-7, you can change manually in codepen external Scripts to `https://unpkg.com/vue-material@1.0.0-beta-8/dist/vue-material.min.js`

**Comment by damaragung** [comment]
its work,, thank you! then next question is how to update it via npm ?

**Comment by VdustR** [comment]
```text
// package.json
{
  "dependencies": {
    "vue-material": "1.0.0-beta-8"
  }
}

**Comment by damaragung** [comment]
thank you very much you help
