### ISSUE TITLE
How to make md-input and md-button display inline?

### ISSUE THREAD

**Issue by arkceajin** [vuematerial/vue-material#1469]
Browser: Chrome
`Vue 2`  with `vue-material-beta`

For example:
```
  <md-content>
    <md-field class="md-alignment-top-left">
     <md-input></md-input>
    </md-field>
    <md-button class="md-alignment-top-right">test</md-button>
  </md-content>
```

**Comment by Samuell1** [comment]
Hey, can you please explain what you mean inline? or create some example?

**Comment by arkceajin** [comment]
@Samuell1 I wish the components display in the same row.
 like `<span></span> <span></span>`  not `<div></div> <div></div> `

**Comment by Samuell1** [comment]
You can use **Layout** (https://vuematerial.io/ui-elements/layout)

```
<div class="md-layout">
   <div class="md-layout-item">
      input here
   </div>
   <div class="md-layout-item">
      button here
   </div>
</div>
```

**Comment by VdustR** [comment]
https://codepen.io/VdustR/pen/mXVyjp

**Comment by arkceajin** [comment]
@Samuell1  I tried that but the width of `md-layout-item` are equal, looks really weird. it better displays `flex`. I wonder why the `md-alignment-top-right` doesn't work.

**Comment by arkceajin** [comment]
@VdustR  Thanks!

**Comment by Samuell1** [comment]
@arkceajin `md-alignment-top-righ` works only if`display: flex` is on element

**Comment by arkceajin** [comment]
@Samuell1 
https://codepen.io/arkceajin/pen/ZrQGVy
Could please help check this code, still not work.

**Comment by Samuell1** [comment]
it needs to be on same element @arkceajin

**Comment by VdustR** [comment]
That is for parent

```vue
  <div class="md-layout box md-alignment-top-right">
    <md-button>TOP RIGHT</md-button>
    <span>SPAN TOP RIGHT</span>
  </div>
```
