### ISSUE TITLE
[MdEmptyState] on IE 11 - description overflows and does not respect width of parent md-state div

### ISSUE THREAD

**Issue by JJButler** [vuematerial/vue-material#1470]
### Steps to reproduce

```
<template>
  <md-content>
        <md-empty-state
            md-icon="do_not_disturb"
            md-label="Unsupported Browser!"
            md-description="Our website will not work with the web browser you are using. 
            Either use a different up-to-date browser or upgrade your browser to the latest version.">
        </md-empty-state>
![screenshot_ie_11](https://user-images.githubusercontent.com/1808201/35731590-1450eab0-080e-11e8-99ae-be7366bb54e1.png)
          <md-button
              class="md-primary md-raised"
              :to="{name: 'Home', params: {userId: $route.params.userId}}"
          >I understand, proceed anyway</md-button>
        </md-empty-state>
  </md-content>
</template>
```

### Which browser?

IE11 but I believe older IE browsers effected too

### What is expected?

The md-empty-state-description should not be able to expand past the max with set on the parent md-empty-state which has max-width: 420px;

### What is actually happening?

md-empty-state-description expands to the width of the description attribute when displayed on a single line 

![screenshot_ie_11](https://user-images.githubusercontent.com/1808201/35731667-78f1d83a-080e-11e8-9d14-b39a11285842.png)

**Comment by Samuell1** [comment]
I was trying to fix it but i found out its bug with IE and flexbox. If flexbox have children flexbox `max-width` doesnt work.
