### ISSUE TITLE
no view right inner stepper when i use 2 stepper 

### ISSUE THREAD

**Issue by newprogrammeram** [vuematerial/vue-material#1472]
i used 2 stepper but no view inner steper right  
no view item contents in inner except first stepper
when inner isnt md-vertical
you can view that here http://mehdibashirinejad.ir/index.php?lang=en
detail : it had problem in 6 step ,with label status
![stepper](https://user-images.githubusercontent.com/22255338/35766579-55f20a52-08f0-11e8-96c0-33fc4ca1011a.png)

**Comment by Samuell1** [comment]
I think stepper should not be used inside other stepper, like you see it can break code and it can be bad for UX.
