### ISSUE TITLE
How to add a 'totals' row to mdTable which sums columns, using v-model

### ISSUE THREAD

**Issue by travisstaloch** [vuematerial/vue-material#1479]
Is there any way to add a totals row to the bottom of an md-table where I can sum the values from certain columns?  I guess this question is twofold. 
  1. How to sum the data.  Is there a callback, something like @rowDataBind which I could use that has access to the row data and overall data structure?
  2. How to display this row?  Because I'm using v-model, is there a special component like md-table-row which can be used for this purpose?  

Or should I just use a v-for and build a custom table?  Below is a simplified version of my md-table component.  

Thank you for any advice.  

```html
        <md-table v-model="apiData[id].result" md-card md-gutter>
            <md-table-toolbar class="md-caption">
              <div class="md-subheading">Heading</div>
            </md-table-toolbar>
            <md-table-row slot="md-table-row" slot-scope="{ item }">
              <md-table-cell md-label="Name">{{ item.data_col }}</md-table-cell>
              <md-table-cell md-label="Name2">{{ item.data_col2 }}</md-table-cell>
            </md-table-row>
          </md-table>
```

**Comment by arkceajin** [comment]
Hi @travisstaloch  check [this](https://codepen.io/arkceajin/pen/XZjBOa)

**Comment by travisstaloch** [comment]
Thank you for creating that pen.  I was hoping to create a row at the bottom of the table with totals for some columns that line up with those columns.

**Comment by arkceajin** [comment]
Sorry misunderstand your question, I think you need to calculate the sum when `v-model` data created, prepare it at first. Then add a row to the table bottom.

**Comment by travisstaloch** [comment]
Ok thanks you.  I think I can do that.  

Any idea how I can make that row stand out?  I was thinking I could put an indicator in the data, something like `totalRow = true`.  But then how can I display it?  I tried adding to the pen, changing the data and adding v-if/v-else but the final row isn't being displayed.  I guess now I'm not sure how to do this with slots.  

[Altered Pen](https://codepen.io/anon/pen/rJMqyg)

**Comment by travisstaloch** [comment]
Figured it out.  I saved the working pen.  Thanks again for your help.

**Comment by zapping** [comment]
Maybe you could consider adding `md-table-row` after the md-table-row slot. Something like a sort of table footer. Like this:

```
    <md-table v-model="users" md-card>
      <md-table-toolbar> .... </md-table-toolbar>

      <md-table-row slot="md-table-row" slot-scope="{ item }">  ....  </md-table-row>
      
      <md-table-row class="TotalsFooter">
        <md-table-cell>Totals</md-table-cell>
        <md-table-cell>40</md-table-cell>
        <md-table-cell>50</md-table-cell>
        <md-table-cell>60</md-table-cell>
        <md-table-cell>70</md-table-cell>
      </md-table-row> 
    </md-table>

```

**Comment by travisstaloch** [comment]
That is interesting.  But how would you access the data?  

I adding the totals row as a md-table-pagination slot, but that didn't seem to allow access to any of the data.  Updated the pen with this attempt.

**Comment by arkceajin** [comment]
I update the [demo ](https://codepen.io/arkceajin/pen/XZjBOa), the last row `totals` calculate and display each `sum` if the value is number, otherwise display the empty string.

**Comment by zapping** [comment]
The data can be access like this if you have the totals in the array itself
```
    <md-table v-model="users" md-card>
      <md-table-toolbar> .... </md-table-toolbar>

      <md-table-row slot="md-table-row" slot-scope="{ item }">  ....  </md-table-row>
      
      <md-table-row class="TotalsFooter">
        <md-table-cell>Totals</md-table-cell>
        <md-table-cell>{{users[users.length-1].id}}</md-table-cell>
        <md-table-cell>{{users[users.length-1].name}}</md-table-cell>
        <md-table-cell>60</md-table-cell>
        <md-table-cell>70</md-table-cell>
      </md-table-row> 
    </md-table>
```
Or instead of appending it to the array if it can be set in a different object then it can be done like this too

```
    <md-table v-model="users" md-card>
      <md-table-toolbar> .... </md-table-toolbar>

      <md-table-row slot="md-table-row" slot-scope="{ item }">  ....  </md-table-row>
      
      <md-table-row class="TotalsFooter">
        <md-table-cell>Totals</md-table-cell>
        <md-table-cell>{{total.col1}}</md-table-cell>
        <md-table-cell>{{total.col2}}</md-table-cell>
        <md-table-cell>{{total.col3}}</md-table-cell>
        <md-table-cell>{{total.col4}}</md-table-cell>
      </md-table-row> 
    </md-table>
```
