### ISSUE TITLE
vertical layout in vue-material-beta

### ISSUE THREAD

**Issue by arkceajin** [vuematerial/vue-material#1480]
If I need the vertical layout like [this ](https://codepen.io/arkceajin/pen/ZrQGVy), the bottom part has a fixed size and the top part will fill the remaining.
mix `flex CSS` with `md-xxx`, makes code look not so good.

**Comment by Samuell1** [comment]
Layout is created for basic usage, if you want some advanced layouts you need to create/add your custom SCSS/CSS to it.
