### ISSUE TITLE
Auto md-layout-item height for masonry style layout 

### ISSUE THREAD

**Issue by ashleywm** [vuematerial/vue-material#1482]
I'm unable to find a way to create a masonry style layout for my nuxt.js app, I'm looking for something like this with md-cards where the height of the cards is dynamic based on their content:

http://jsfiddle.net/tQANc/

However when using md-layout & md-layout-item the next row of the cards will sit under the 'tallest' card within the row, rather than keeping the same gutter under each card. Is this right?  

As i'm using nuxt.js I'm not able to use plugins like vue-masonry as they require SSR to be turned off.

Any recommendations or advice?

**Comment by Samuell1** [comment]
I think best is to make 3 columns and filling them with cards separately.
