### ISSUE TITLE
[Md-AutoComplete] Icon with box layout

### ISSUE THREAD

**Issue by SirNeural** [vuematerial/vue-material#1483]
### Steps to reproduce
Create an autocomplete form with a label inside, and put an icon with it

### Which browser?
Vue-Material@1.0.0-beta-8
Chrome 63

### What is expected?
Icon should be on the left side of label, and look somewhat like this
https://i.imgur.com/cQvfDqI.png

### What is actually happening?
Icon is way off to the right, and disappears on focus, looks like this
https://i.imgur.com/KNvg4Ze.png

### Reproduction Link
https://codepen.io/anon/pen/VQKBYr
Also happening but I can't reproduce it in the codepen, when text is typed, the x icon is just blank,
https://i.imgur.com/OZVZesx.png

**Comment by arkceajin** [comment]
Hi @SirNeural  check [this](https://codepen.io/arkceajin/pen/PQGdpq)
