### ISSUE TITLE
[MdSnackbar] - The position of md-snackbar changes if its inside md-drawer

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1485]
### Steps to reproduce
1. Click on the edit icon to pop out the `md-drawer`.
2. Click on the Save button to show the snackbar.
3. Once the snackbar disappears. Click on the save button again to show the snackbar

### Which browser?
Chrome and Firefox. Vue-material beta-8

### What is expected?
The position of the snackbar be consistent

### What is actually happening?
The `md-snackbar` initially displays centered to the page. Then for all subsequent displays it is centered to the `md-drawer`.

### Reproduction Link
https://codepen.io/zapping/pen/BYzMKY

**Comment by VdustR** [comment]
Seems `<md-snackbar :md-persistent="true">` works.

**Comment by zapping** [comment]
The codepen has been updated with your tip but unfortunately it didn't help.
