### ISSUE TITLE
[md-chips] trigger all events 

### ISSUE THREAD

**Issue by newprogrammeram** [vuematerial/vue-material#1488]
[md-chips] trigger all events (both md-delete and md-insert) 
on remove or add event
![host](https://user-images.githubusercontent.com/22255338/35945684-471f2094-0c76-11e8-84c4-61acb0d59b7d.png)
i search but i dont found any thing about that
can u show me an example about it?

**Comment by VdustR** [comment]
https://codepen.io/VdustR/pen/eVBPdP

`md-delete` would emitted with the deleted string and its index.

`md-insert` would emitted with the inserted string.

**Comment by newprogrammeram** [comment]
thanks but i need to index in insert action to earn element

**Comment by VdustR** [comment]
If you are looking for API to modify the chips, you could insert / delete strings from your `v-model` directly.

**Comment by newprogrammeram** [comment]
thanks but i need to pass index to select chips element and get other info and need to pass how maybe?

**Comment by VdustR** [comment]
Sorry, I don't understand.

What do you mean 'current element'?

I think it's better to let us know what you want to do.

**Comment by newprogrammeram** [comment]
i need to pass index of chips to earn which email ,in here, and or pass email manually
please see this 
![structurehostemail](https://user-images.githubusercontent.com/22255338/36016655-51c1ba3e-0d89-11e8-9f61-ab5bdc3c1c30.png)


![](https://user-images.githubusercontent.com/22255338/35996766-9ea412be-0d2c-11e8-8be0-d9db9080f093.png)

**Comment by VdustR** [comment]
As I said, you could interactive with `MdChips` via `v-model`.

How about provide your 'chip and no chips element' version in [Codepen](https://codepen.io/) and I'll try to make a `MdChips` one?
