### ISSUE TITLE
[md-radio] Radio buttons display opposite of their value 

### ISSUE THREAD

**Issue by brianboyko** [vuematerial/vue-material#1489]
### Steps to reproduce
`I used <md-radio>`

### Which browser?

Chrome running 1.0@b

### What is expected?
`
When <md-radio :value="true"> the radio button should light up. `

### What is actually happening?

The radio button lights up with false values, and is dark on true values; 

### Reproduction Link

https://codepen.io/anon/pen/vdyjoE

**Comment by brianboyko** [comment]
Done a little bit more digging into this and I think I know what the problem is. 

What it's actually doing, is comparing the value it has to the v-model that it is assigned. Which is great, if you're using v-model, because then "v-model === value" is a good test.  But if you're not using v-model (like, for example, you want to bind the value to a computed property or getter) then your v-model is undefined, so it compares (undefined == true) as false, and undefined == false as true.

**Comment by VdustR** [comment]
Yes, that's aim to works similar to native radio.

In this case, you could write like:

```vue
<md-content>
  <md-radio :model="true" :value="true">Value is True</md-radio>
  <md-radio :model="false" :value="true">Value is False</md-radio>
</md-content>
```

**Comment by brianboyko** [comment]
That's what I ended up doing.  The confusion here stems partially from the documentation and partially from the keyword uses.  Usually when I see a :value in a component that reacts to changes in state, that the :value is the item that changes.  

I'm not a fan of two-way binding, so I rarely if ever use v-model, I had to go into the source code to figure out that you could use :model because it just passes down model as a prop to the md-radio component. 

May I suggest renaming the :value= binding to be :option=?

**Comment by VdustR** [comment]
The value for `radio` is like the value for `<option>` in `<select>`. They are options to let user choose, not the value which is selected by user.

You could check how native radio work and how vue works with radio.

https://vuejs.org/v2/guide/forms.html#Radio

If you really want to use `v-model` with it's status, you should use `MdCheckbox` or `MdSwitch` instead of `MdRadio`.
