### ISSUE TITLE
:md-expanded.sync toggle not working in chrome but working in firefox

### ISSUE THREAD

**Issue by damaragung** [vuematerial/vue-material#1490]
### What is expected?

just one click to show list child, and close other expaded list. working perfectly in firefox. 
in chrome need to click 3 times (expand, close, then expand) to show the child.
### Reproduction Link

https://codepen.io/damaragung/pen/JpYRbK

is there another way to create toggling function md-expand list .
thank you

**Comment by VdustR** [comment]
Click event is not good for this case.

I'll sent a PR to add `@md-expanded` event for this.

**Comment by damaragung** [comment]
just need to remove this line "this.expand[val] = true" and it works  ;p  . md-expanded event will be great . thanks a lot
