### ISSUE TITLE
[md-datepicker] Evaluate current implementation of Datepicker for Microsoft Edge compatibility

### ISSUE THREAD

**Issue by iamaaron** [vuematerial/vue-material#1491]
Currently, Microsoft Edge does not allow you to disable a native datepicker, eg `input type="date"`. Chrome does through a few CSS capabilities, but Microsoft Edge does not.

https://stackoverflow.com/questions/32910586/how-do-you-disable-the-datepicker-in-microsoft-edge

Statistically, very few use Microsoft Edge, but if that is going to be a considered supported browser, a strategy to be able to handle Edge may be on the table.

Worst case scenario, we could always add a `v-if` to key off of the user agent string and turn the input field into the type of text, but this is just a thought. I am open for ideas or thoughts.

Thanks,
Aaron

**Comment by VdustR** [comment]
I think developers could handle that via `md-override-native`.

**Comment by Samuell1** [comment]
Datepicker should be on all browsers same because we using `type="text"` as default

**Comment by iamaaron** [comment]
Yeah, I have tested this. It actually does not work `:md-override-native="true"` does not work.

**Comment by Samuell1** [comment]
@iamaaron because default is true
