### ISSUE TITLE
md-table's data doesn't get updated properly

### ISSUE THREAD

**Issue by ueharajohji** [vuematerial/vue-material#1492]
### What is actually happening?

I'm trying to implement a pagination function with vue 2.5.3 / vue-material1.0.0 and the problem is whenever I update the
model , the table gets updated with the newly fetched model but the md-table component still has the previous data so when I check the "select all" box it gets the previous data only which makes the selected variable contain only the page 1 data when in fact I am in page 2. anyone have any suggestions on how to deal with this?

**Comment by VdustR** [comment]
You need to clear that by yourself.

Clear the value you bind with `:md-selected-value.sync`.

We don't clear it because of considering some cases that developers want to keep the values the end users selected from previous page.

**Comment by VdustR** [comment]
Would you provide a reproduction for this?

**Comment by ueharajohji** [comment]
Sorry for the late reply ,

here is the reproduction , I forked your codepen a while ago and then tweaked it to
reproduce the problem I am experiencing right now.

https://codepen.io/ueharajohji/pen/NybVMy

to reproduce the bug

Just simply click the next page button and check the select all box, and you will see 
even though I already replaced the people array with just 1 data ( dummy ) it still gets
the previous data.

**Comment by ueharajohji** [comment]
Thank you @VdustR  ! I will inform you about my progress on the pagination once I applied your patch.
