### ISSUE TITLE
[MdTable] customizable height for table content

### ISSUE THREAD

**Issue by kiwokiwotiwo** [vuematerial/vue-material#1497]
I am adding a tableview like this:
```

<template>
  <div>
    <md-table v-model="searched" md-sort="name" md-sort-order="asc" md-card md-fixed-header>
      <md-table-toolbar>
        <div class="md-toolbar-section-start">
          <h1 class="md-title">Users</h1>
        </div>

        <md-field md-clearable class="md-toolbar-section-end">
          <md-input placeholder="Search by name..." v-model="search" @input="searchOnTable" />
        </md-field>
      </md-table-toolbar>

      <md-table-empty-state
        md-label="No users found"
        :md-description="`No user found for this '${search}' query. Try a different search term or create a new user.`">
        <md-button class="md-primary md-raised" @click="newUser">Create New User</md-button>
      </md-table-empty-state>

      <md-table-row slot="md-table-row" slot-scope="{ item }">
        <md-table-cell md-label="ID" md-sort-by="id" md-numeric>{{ item.id }}</md-table-cell>
        <md-table-cell md-label="Name" md-sort-by="name">{{ item.name }}</md-table-cell>
        <md-table-cell md-label="Email" md-sort-by="email">{{ item.email }}</md-table-cell>
        <md-table-cell md-label="Gender" md-sort-by="gender">{{ item.gender }}</md-table-cell>
        <md-table-cell md-label="Job Title" md-sort-by="title">{{ item.title }}</md-table-cell>
      </md-table-row>
    </md-table>
  </div>
</template>
```

The annying thing is that vuematerial gives me a 400px fixed height:

`<div class="md-content md-table-content md-scrollbar md-theme-default" style="height: 400px; max-height: 400px;">`

How can I prevent it form generatig this: **style="height: 400px; max-height: 400px;"** ?????

even the examples as https://vuematerial.io/components/table has a 400px heigght......

**Comment by Samuell1** [comment]
Do you tried overwriting it?

**Comment by christoph-bessei** [comment]
Overwriting works (with ```!important```, since the height is set as inline style), but IMHO the question is still valid:
Why is ```height: 400px``` and ```max-height: 400px``` there in the first place and can a user prevent it?

**Comment by christoph-bessei** [comment]
I understand that, but isn't there a better solution, than overwriting with ```!important```?
E.g. add an option to ```md-table``` (disable-default-height?) ?

I'm using flexbox so the table fills the viewport (or parent element) and than starts scrolling.
This works pretty nice and I would like to disable the hardcoded 400px height.

**Comment by Samuell1** [comment]
@christoph-bessei @kiwokiwotiwo @SirNeural I looked into it and there is already prop for table `md-height` but can only accept number value.

I changing it a bit to allow pass custom value like `100%` or `400px`

**Comment by christoph-bessei** [comment]
May I suggest a special value like "none" which disables the height?
This would allow us to use css, without !important.

**Comment by Samuell1** [comment]
Yes,  you can use all values for CSS like: `none`, `auto`, `100%`, `100vh` or `Xpx`, after is PR merged and released.

**Comment by github-gabo** [comment]
> I am adding a tableview like this:
> 
> ```
> 
> <template>
>   <div>
>     <md-table v-model="searched" md-sort="name" md-sort-order="asc" md-card md-fixed-header>
>       <md-table-toolbar>
>         <div class="md-toolbar-section-start">
>           <h1 class="md-title">Users</h1>
>         </div>
> 
>         <md-field md-clearable class="md-toolbar-section-end">
>           <md-input placeholder="Search by name..." v-model="search" @input="searchOnTable" />
>         </md-field>
>       </md-table-toolbar>
> 
>       <md-table-empty-state
>         md-label="No users found"
>         :md-description="`No user found for this '${search}' query. Try a different search term or create a new user.`">
>         <md-button class="md-primary md-raised" @click="newUser">Create New User</md-button>
>       </md-table-empty-state>
> 
>       <md-table-row slot="md-table-row" slot-scope="{ item }">
>         <md-table-cell md-label="ID" md-sort-by="id" md-numeric>{{ item.id }}</md-table-cell>
>         <md-table-cell md-label="Name" md-sort-by="name">{{ item.name }}</md-table-cell>
>         <md-table-cell md-label="Email" md-sort-by="email">{{ item.email }}</md-table-cell>
>         <md-table-cell md-label="Gender" md-sort-by="gender">{{ item.gender }}</md-table-cell>
>         <md-table-cell md-label="Job Title" md-sort-by="title">{{ item.title }}</md-table-cell>
>       </md-table-row>
>     </md-table>
>   </div>
> </template>
> ```
> The annying thing is that vuematerial gives me a 400px fixed height:
> 
> `<div class="md-content md-table-content md-scrollbar md-theme-default" style="height: 400px; max-height: 400px;">`
> 
> How can I prevent it form generatig this: **style="height: 400px; max-height: 400px;"** ?????
> 
> even the examples as https://vuematerial.io/components/table has a 400px heigght......

I fixed this problem by
```
<script>
...
mounted(){
    this.$el.childNodes[0].childNodes[6].attributes[1].value = "";
  }
...
</script>
```
Where childNodes are my components in this instance.

**Comment by aburai** [comment]
this works for me
`<md-table md-height="100%"`

**Comment by olvisdevalencia** [comment]
This work for me too.
<md-table v-model="searched" md-sort="name" md-sort-order="asc" md-fixed-header :md-height="tableSize(60)">

and then create a method to handle the %

      tableSize(val) {
          let fullSizeScreen = window.screen.height
          let finalSizeScreen = (fullSizeScreen * val) / 100
          return finalSizeScreen +'px'
      }
