### ISSUE TITLE
[MdTabs] content length calculations

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1500]
### Steps to reproduce
Use md-tabs with long content, in my case several md-cards in a tab within a sub tab.
I'm using vue-material beta 7 (edit) and 8

### Which browser?

FF (v. 58) and Chrome (v. 64)

### What is expected?
Displaying the whole content. Scrollable in the full height.

### What is actually happening?
The outer tab height is not equal to the inner tab height. Actually in my setup it is much smaller (inner tab height = 2489px, outer = 1748px)

**Comment by VdustR** [comment]
Would you provide your code in [Codepen](https://codepen.io/)?

**Comment by mrwhy-orig** [comment]
https://codepen.io/MrWhy/pen/YeVRZw

**Comment by emman27** [comment]
Hey! I'm facing similar issues.

**Comment by VdustR** [comment]
This reproduction act differently between `1.0.0-beta-7` and `1.0.0-beta-8`. I got CPU leakage with your code in `1.0.0-beta-8` and I fixed that with #1506. Would you kindly to check whether if this is fixed with #1056?

**Comment by mrwhy-orig** [comment]
I tried your fix without any luck. With your code, there is another issue. If i use the route url directly the sub tabs are not getting rendered anymore. If I use the index url and navigate to the page the sub tabs are getting rendered.
