### ISSUE TITLE
"Select all" md-table checkbox with wrong state when number of rows = 1

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#1502]
### Steps to reproduce

Create a table with one row, selectable.
Click on "select all".
Unselect the item.

### Which browser?

Chromium 64

### What is expected?

The "select all" checkbox is unchecked

### What is actually happening?

The "select all" checkbox remains checked

### Reproduction Link

https://codepen.io/lucasfernog/pen/vdxRGX

**Comment by VdustR** [comment]
Seems fixed in `1.0.0-beta-8`
