### ISSUE TITLE
[Feature-Request: MD-Drawer] Is there any way to disable slide-out on touch-swipe?

### ISSUE THREAD

**Issue by brianboyko** [vuematerial/vue-material#1505]
I'm using Vue-Material to develop (primarily) a desktop app.  It's working well except that on multitouch devices, swiping with two fingers opens the drawer.  I want to disable this behavior so that it can only be opened via button, and closed via clicking on the "x" or the overlay.  

The main problem is this.  I'm opening the drawer by passing in a prop. 

```
// parent Template
    <app-assign-researcher :assignResearcherTabIsOpen.sync="assignResearcherTabIsOpen"></app-assign-researcher>

// parent Script
  data () {
     assignResearcherTabIsOpen: (boolean)
  }

// child Script
  methods(){
    closeTab() {
      this.$emit("update:assignResearcherTabIsOpen", false);
    },
  }
```

Because swiping does not change the value of data.assignResearcherTabIsOpen, it cannot be closed with an X. 

If there's a value that we can tap into that determines if the drawer is swiped on screen or not, we can tie that programatically into the app, but for now, the problem is that the swipe behavior is not documented or expected.

**Comment by Samuell1** [comment]
Can you please provide a version of vue-material?
