### ISSUE TITLE
[MdCheckbox] inside MdField not working

### ISSUE THREAD

**Issue by andershjort** [vuematerial/vue-material#1507]
Not totally sure if this is a bug or expected behaviour. But the thing is, it prevents me from using Vuelidate on the checkbox out-of-the-box, which is the validation library that you use yourself on the form demo page here: https://vuematerial.io/components/form

### Steps to reproduce

Place an md-checkbox inside an md-field.

### Which browser?

Tried in Chrome, Firefox and Safari on OSX

### What is expected?

When I click the text label for the checkbox, the checkbox should switch state

### What is actually happening?

The checkbox only switches state if I click the checkbox itself

### Reproduction Link

https://codepen.io/andershjort/pen/EQvOXp

**Comment by Samuell1** [comment]
Its not a bug because MdField is wrapper for input, textarea and select.

**Comment by andershjort** [comment]
Ok, thanks
