### ISSUE TITLE
MdOverlay allowing page scrolls

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#1508]
### Steps to reproduce

Open dialog/drawer and try to scroll the page (via mouse or touch)

### Which browser?

Latest Vue, Vue Material 1.0 beta 8, Chrome 64/Android N Chrome

### What is expected?

The overlay prevents page scroll (only the dialog should be scrollable)

### What is actually happening?

The page scrolls as if there is no overlay present.

https://vuematerial.io/components/dialog

**Comment by Samuell1** [comment]
Native `dialog` [specs](http://w3c.github.io/html/interactive-elements.html#dom-htmldialogelement-showmodal) doesnt say scrolling should be disabled when a modal is open. (https://demo.agektmr.com/dialog/)

Content of dialog should be scrollable. As is said in Material Designs Guidelines.

**Comment by lucasfernog** [comment]
I never saw this behavior, but ok

**Comment by Samuell1** [comment]
@lucasfernog we prevent it by adding class to body that hide scrollbar but can have weird effect as scrolling you to top etc, moving content etc
