### ISSUE TITLE
[MdField] text field prefixes and suffixes

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#1509]
"Prefixes and suffixes can be used to clarify units or to add input in advance. Prefixes are left justified in the text field; suffixes are right justified. Text fields can have both prefixes and suffixes."

![image](https://user-images.githubusercontent.com/20051258/36218928-07b5591a-119d-11e8-9bee-597ac9159931.png)

![image](https://user-images.githubusercontent.com/20051258/36218936-108623f8-119d-11e8-954c-5a7662dbfdcb.png)

https://material.io/guidelines/components/text-fields.html#text-fields-input-types

**Comment by arkceajin** [comment]
Hi, I made a temporary solution [this](https://codepen.io/arkceajin/pen/aqLYdq).
