### ISSUE TITLE
[md-expand] .sync and .once are deprecated in vue 2+

### ISSUE THREAD

**Issue by icosamuel** [vuematerial/vue-material#1514]
Since [vue 2.0](https://vuejs.org/v2/guide/migration.html#once-and-sync-Modifiers-on-v-bind-removed), the `.sync`and `.once` were removed. 
>Props are now always one-way down. To produce side effects in the parent scope, a component needs to explicitly emit an event instead of relying on implicit binding.

### What is expected?

The features using `.sync` like `md-expended` should be controllable pragmatically

### What is actually happening?

Changing the synced value pragmatically does not trigger `md-expanded`

### Reproduction Link

https://codepen.io/anon/pen/QQOyqQ which is also accessible from the documentation

**Comment by marcosmoura** [comment]
Since Vue.js 2.3, we do have a '.sync' modifier:

> In some cases we may need “two-way binding” for a prop - in fact, in Vue 1.x this is exactly what the .sync modifier provided. When a child component mutates a prop that has .sync, the value change will be reflected in the parent. This is convenient, however it leads to maintenance issues in the long run because it breaks the one-way data flow assumption: the code that mutates child props are implicitly affecting parent state. 

> This is why we removed the .sync modifier when 2.0 was released. However, we’ve found that there are indeed cases where it could be useful, especially when shipping reusable components. What we need to change is making the code in the child that affects parent state more consistent and explicit. 

> In 2.3.0+ we re-introduced the .sync modifier for props.

https://vuejs.org/v2/guide/components.html#sync-Modifier

**Comment by icosamuel** [comment]
hey @marcosmoura! thanks for the fast response.

I've tested within codepen, which uses vue 2.5.3 and the 2way binding does not work. Maybe something is wrong with my environment?

**Comment by Nepoxx** [comment]
https://vuematerial.io/components/list/

The codepen link next to "Lists can have expansion panels to reveal more options:" also leads to a broken codepen example.

**Comment by VdustR** [comment]
@Nepoxx That's because the current unpkg link is redirect to `1.0.0-beta-7`

You could replace it with `https://unpkg.com/vue-material@1.0.0-beta-8/dist/vue-material.min.js` manually to make it work for now.
