### ISSUE TITLE
md-app add prop to support other components, not only     'md-app-toolbar',     'md-app-drawer',     'md-app-content'

### ISSUE THREAD

**Issue by mikkiek** [vuematerial/vue-material#1515]
Hello,

At the moment if use "md-app" then inside allowed "md-app-content" and inside "md-bottom-bar" then you can't stick it to the bottom, coz' of issues for case
overflow: auto (for parent "md-app-content")
and position:fixed (for child "md-bottom-bar") then can happen following thing
http://prntscr.com/ifcqus

I've found a work around: is to move "md-bottom-bar' on one level up (to be a child of 'md-app") and manually specify the attribute "slot": http://prntscr.com/ifcrf6

But i think it's really bad practice.

**Comment by Samuell1** [comment]
Your workaround is not a bad practice, you should use slots to inject other components.

**Comment by mikkiek** [comment]
@Samuell1 
I don't think that for <md-bottom-bar> pretend to be <md-app-drawer> is a good idea

**Comment by Samuell1** [comment]
You can inject any component or your custom components.

**Comment by mikkiek** [comment]
@Samuell1 

Without hack i've mention above you can't use any component except:
md-app-content
md-app-drawer
md-app-toolbar
http://prntscr.com/iflf2d

It happends coz' of validation in md-app
http://prntscr.com/iflgcn

**Comment by Samuell1** [comment]
Its not a hack, its a normal solution with that you can inject your custom component.
