### ISSUE TITLE
version info in min.js file

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1516]
Can the info of the current version be included in the min.js file like as shown below
![versioninfo](https://user-images.githubusercontent.com/4123026/36292242-13ef12d0-12c8-11e8-837d-fb4cf5b4d54e.PNG)
Its a bit tough to know the current version if the min.js file is downloaded and used. I think it existed in files prior to the beta release.

**Comment by Samuell1** [comment]
Looks like in build config is there but compressing is removing all comments including version info too

**Comment by zapping** [comment]
Thank you for this fix. Since the default.css theme file also needs to be used, can this info section be included along with the theme/default.css file too?
