### ISSUE TITLE
Misleading instruction in readme

### ISSUE THREAD

**Issue by icosamuel** [vuematerial/vue-material#1520]
The instruction `npm install vue-material@beta --save` installs v1.0.0-beta-7
If you want all the latest juicy features and bugfixes, you must simply run `npm install vue-material --save`, which contains the [v1.0.0-beta-8](https://github.com/vuematerial/vue-material/releases/tag/v1.0.0-beta-8)

**Comment by Samuell1** [comment]
Looks like something is wrong :( @marcosmoura
