### ISSUE TITLE
Not working in vue application while adding vue-material

### ISSUE THREAD

**Issue by nkarthikeyan90** [vuematerial/vue-material#1527]
Hi,
I have used vue material using this npm command "npm install vue-material@beta --save"
but import the vue-material page load empty what am i missing seeting.
i have an atached the screen short for your ref

this is my main.js file please help us to resolve this

Import Vue from 'vue’
import App from './App’
import router from './router’
import VueMaterial from 'vue-material’
import ‘…/node_modules/vue-material/dist/vue-material.css’

Vue.use(VueMaterial)
Vue.config.productionTip= false

/* eslint-disable
no-new */
new Vue({
el: ‘#app’,
router,
components: { App },
template: ‘’
})

**Comment by Samuell1** [comment]
Do you get any console errors?

**Comment by marcosmoura** [comment]
@nkarthikeyan90 Remove that `../node_modules`
It should be `vue-material/dist/vue-material.css`

**Comment by nkarthikeyan90** [comment]
it is working on google chrome browser but not showing in firefox browser.why is not working in firefox browser  in vue application.

**Comment by Samuell1** [comment]
Check console for errors.
