### ISSUE TITLE
[MdTooltip] causing infinite render loop

### ISSUE THREAD

**Issue by tobiaswuerth** [vuematerial/vue-material#1529]
I'm using the latest version (v1-beta8) in [my project](https://github.com/tobiaswuerth/mux-www) and came upon [this issue](https://stackoverflow.com/questions/48879686/vue-material-md-tooltip-causing-infinite-render-loop).  I posted it on Stackoverflow since I need a solution for this, you can find a code snipped there.

I didn't have any problem with `md-tooltip` until now which brings me to the conclusion that this must be caused by some special constellation of components or so.

I published a minimalistic project on [codesandbox](https://codesandbox.io/s/lr3q0qyyo7). **BEWARE**! This WILL exhaust your CPU and might leave your browser unresponsible. If you cannot close your browser tabs anymore, you can just kill the browser process which consumes the most CPU power and memory to end it.

### Which browser?

Chrome, latest

### What is expected?

I expect it to not get into this render loop and show the tooltip correctly if hovered over the icon

### What is actually happening?

Once I load the page my developer console gets filled with the same message over and over again.

> [Vue warn]: You may have an infinite update loop in a component render function. found in ..

Every second or so this message is printed, the page never finishes loading, my CPU burns until it runs into a out-of-memory exception and/or I kill the responsible javascript process of chrome.

**Comment by Samuell1** [comment]
Hey,
when you check events in vue-devtools  do you see any events from tooltip?

**Comment by tobiaswuerth** [comment]
@Samuell1 no I don't. only events from `md-initial-parent`

**Comment by VdustR** [comment]
It's better to reproduce it with simplest code in [Codepen](https://codepen.io/) to make helps more quickly and easier.

**Comment by Samuell1** [comment]
I tested it in **DEV** with this code and all things works. I think you have issue with *dataLoader**

```html
<template v-if="test">
    <template v-for="i in ['a', 'b']">
        <span :key="i">
            <span v-for="k in ['CH', 'US']" :key="k">
                {{k}}
                <md-tooltip>{{k}}</md-tooltip>
            </span>
        </span>
    </template>
</template>

<button @click="test = !test">swap</button>
```

**Comment by tobiaswuerth** [comment]
I see. As I said, I never had issues before using `md-tooltip`, so I guess you're right. I've done some modifications to the dataLoader, I should try if the issue die is resolved already, otherwiese I have to dig for the issue.. Thank you for your effort. I think we can close this issue.
