### ISSUE TITLE
Unable to add VueMaterial to Vue

### ISSUE THREAD

**Issue by jrods** [vuematerial/vue-material#1536]
### Steps to reproduce

I'm using a `@vue/cli` setup project (PWA preset). In my main.js file
```
import Vue from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import VueMaterial from 'vue-material'
//import { VueMaterial } from 'vue-material'

Vue.use(VueMaterial.default)
//Vue.use(VueMaterial)  same issue

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')

console.log(Vue)
console.log(VueMaterial)
console.log(VueMaterial.default)
```

### Which browser?

All (I test in firefox, but problem affects all other platforms)

package.json:
```
{
  "name": "hello-vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve --open",
    "build": "vue-cli-service build",
    "test": "vue-cli-service test",
    "e2e": "vue-cli-service e2e",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "register-service-worker": "^1.0.0",
    "vue": "^2.5.13",
    "vue-material": "^1.0.0-beta-8"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.1",
    "@vue/cli-plugin-e2e-nightwatch": "^3.0.0-beta.1",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.1",
    "@vue/cli-plugin-pwa": "^3.0.0-beta.1",
    "@vue/cli-plugin-unit-mocha": "^3.0.0-beta.1",
    "@vue/cli-service": "^3.0.0-beta.1",
    "@vue/test-utils": "^1.0.0-beta.10",
    "chai": "^4.1.2",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.6",
    "vue-template-compiler": "^2.5.13"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

### What is expected?
No console errors on initial page load

### What is actually happening?
There are no build errors, but browser errors on page load. States that plugin is undefined.
Are there undocumented settings I need to include with my project?
<img width="1437" alt="screen shot 2018-02-21 at 11 56 59 am" src="https://user-images.githubusercontent.com/5874122/36502327-6ea20626-16fe-11e8-8560-943d7fe3b91e.png">

### Reproduction Link
Sorry, local environment.

**Comment by Samuell1** [comment]
You using new vue-cli template ?

**Comment by jrods** [comment]
@Samuell1 yes, i went through the cli setup, with PWA, unit/e2e testing, lint, scss; All with dedicated configs (.babelrc, postcss, eslint, etc.)

**Comment by Samuell1** [comment]
@jrods new vue-cli template is not yet tested with vue-material, I look into it later.

**Comment by Samuell1** [comment]
For me works with vue-cli 3 template

**Comment by jrods** [comment]
@Samuell1 Do you mind sharing what you did? because using `Vue.use(VueMaterial)` still doesnt work for me.

**Comment by Samuell1** [comment]
Simply created new vue-cli template and installed `vue-material` and added in `main.js`

```
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'

Vue.use(VueMaterial)
```

**Comment by jrods** [comment]
@Samuell1 ahh ok, I un-commented my Vue import and it worked. Thank you for the help =)

however, I am working on a from scratch approach (no vue/cli setup) and running into the same kind of issue, would i have to do something specify in my webpack config?
