### ISSUE TITLE
Open side menu for large screens

### ISSUE THREAD

**Issue by abooysen** [vuematerial/vue-material#154]
Do you have any plans to implement something similar to the Navigation layouts used by Material Design Lite (getmdl.io > Layout). I’m looking for the functionality where the side menu is shown for large screens but hidden for small screens. I see that you use custom css media queries in your demo site to achieve this effect. In getmdl.io, “mdl-layout--fixed-drawer” is added to the parent layout container. It would be nice if this could be configured as a property on the SideNav and also on the Title bar where menu icon should go.

**Comment by marcosmoura** [comment]
Hi @abooysen 

I have plans to develop that. It's on my [backlog](https://github.com/marcosmoura/vue-material/projects/1) (Layout components). The idea is to create some components like the [App Layout](https://elements.polymer-project.org/elements/app-layout) from Polymer.

I will not schedule this for now, but I will update this issue soon.

Thanks.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/components/drawer
