### ISSUE TITLE
[MdTextarea] label is mixed with content when scrolling

### ISSUE THREAD

**Issue by jimmywarting** [vuematerial/vue-material#1541]
### Steps to reproduce

I wrote lots of content into a textarea and scrolled down

### Which browser?

Chrome, Mac OS

### What is expected?

too look good

### What is actually happening?

the label and content get mixed togheter

### Reproduction Link

You got same problem on your website:
https://vuematerial.io/components/input

![skarmavbild 2018-02-23 kl 13 39 25](https://user-images.githubusercontent.com/1148376/36594638-429b565c-189f-11e8-82e2-204b70824e7e.png)

**Comment by Samuell1** [comment]
Firefox is fine, looks like its only in chrome

**Comment by Samuell1** [comment]
Looks like its chrome bug/rendering: https://stackoverflow.com/questions/12709988/padding-bottom-for-textarea-isnt-considered
