### ISSUE TITLE
<md-sidenav> not working in latest version

### ISSUE THREAD

**Issue by larsmars** [vuematerial/vue-material#1542]
Using latest version on npmjs.com:

[https://www.npmjs.com/package/vue-material](https://www.npmjs.com/package/vue-material)

`vue.esm.js?efeb:578 [Vue warn]: Unknown custom element: <md-sidenav> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

in main.js

```
import VueMaterial from 'vue-material'
Vue.use(VueMaterial)
```

Use of sidenav in template:

```
    <md-sidenav class="md-left" ref="sidenav">
     <md-toolbar class="md-account-header">
      <md-list class="md-transparent">
        <md-list-item>
          <div class="md-list-text-container">
            <span>{{firstName}} {{lastName}}</span>
            <span>{{email}}</span>
          </div>
        </md-list-item>
      </md-list>
    </md-toolbar>
    <md-list>
      <md-list-item>
        <md-icon>home</md-icon> <span>Dashboard</span>
      </md-list-item>
      <md-list-item>
        <md-icon>account_circle</md-icon> <span>Profile</span>
      </md-list-item> 
    </md-list>
  </md-sidenav>

```

If I downgrade to version "vue-material": "0.7.5"
Everything works fine.

### Which browser?

Chrome

### What is expected?

left side menu

### What is actually happening?

Error thrown in console, side menu all over the place

**Comment by Samuell1** [comment]
Because it was removed and renamed to md-drawer
