### ISSUE TITLE
[MdTextarea] bug with autogrow 

### ISSUE THREAD

**Issue by Gagydzer** [vuematerial/vue-material#1543]
Hi. Looks like i've found a bug in textarea with an autogrow in Chome 63. An autogrow just didn't work, thx.
![image](https://user-images.githubusercontent.com/30010914/36612430-a81f3dde-18e7-11e8-80fb-c44c1ce21e56.png)

**Comment by Samuell1** [comment]
![2018-02-26_19-39-22](https://user-images.githubusercontent.com/3110002/36688431-c4c87d3c-1b2c-11e8-84eb-f072887d777b.gif)

Tested and it works

**Comment by Gagydzer** [comment]
@Samuell1 just look, i create a clear pen and still got this bug (in Ffox and Chrome)
https://codepen.io/Gagydzer/pen/vdwGeo?editors=1111
![autogrow-bag](https://user-images.githubusercontent.com/30010914/36949468-e6fb17da-1ff9-11e8-864b-5c5cc71b7a1e.gif)

**Comment by Samuell1** [comment]
@Gagydzer Because there is bug with unpkg and it uses beta-7 . Just change your link to vue-material without `@beta`

**Comment by Gagydzer** [comment]
thx
