### ISSUE TITLE
[MdDialog] wrapping the content in an element breaks UI

### ISSUE THREAD

**Issue by jimmywarting** [vuematerial/vue-material#1544]
Just wanted to wrap my `md-dialog-content` around a `<form>` element
so that the buttons in `md-dialog-actions` would trigger the submit event.
There are grate benefits with form element that gives constraint validation to the form.
I think they are useful and think promps should wrap it in a form element also

```html
<md-dialog :md-active.sync="show" @md-closed="closed">
  <form submit.prevent="updateSettings">
    <md-dialog-title>Settings</md-dialog-title>
    <md-dialog-content>
        ...
    </md-dialog-content>
    <md-dialog-actions>
      <md-button type="submit" class="md-primary">save</md-button>
    </md-dialog-actions>
  </form>
</md-dialog>
```

But this breaks the UI.
just having the form in dialog content won't help the buttons that are outside.

Are the any workarounds for this?
Will you fix this?

----

(wished md-dialog was built on native html [dialog](https://demo.agektmr.com/dialog/))

**Comment by lucasfernog** [comment]
One workaround is the form attribute: https://www.w3schools.com/tags/att_input_form.asp

**Comment by Samuell1** [comment]
You can maybe try something like this

```
<md-dialog :md-active.sync="show" @md-closed="closed">
    <md-dialog-title>Settings</md-dialog-title>
    <md-dialog-content>
        <form ref="myForm" @submit.prevent="updateSettings">
                ...
        </form>
    </md-dialog-content>
    <md-dialog-actions>
      <md-button class="md-primary" @click="$refs.myForm.submit()">save</md-button>
    </md-dialog-actions>
</md-dialog>
```

**Comment by jimmywarting** [comment]
Thanks @Samuell1, that workaround will work for now. 
Wished I didn't have to solve it that way

Found out about form attribute also but using $refs is a safer bet

**Comment by Samuell1** [comment]
@jimmywarting or you can use without form and simply add `@click="updateSettings"` on button

**Comment by jimmywarting** [comment]
No, constraint validation don't kick in if you use onclick. Only on submit

**Comment by jimmywarting** [comment]
How would you feel about re-building the dialog element in order to use native dialog?

```html
<dialog :open.sync="show" @close @cancel>
  <form method="dialog">
    <md-dialog-title>
    <md-dialog-content>
    <md-dialog-actions>
  </form>
</dialog>
```

**Comment by Samuell1** [comment]
@jimmywarting native dialog element needs polyfills - https://caniuse.com/#search=dialog

**Comment by jimmywarting** [comment]
I know, I'm almost thinking of building my own componenet. cuz i don't really like the way it `<md-dialog>` works right now.

**Comment by Samuell1** [comment]
@jimmywarting yes but that polyfill have one big limitation

> The major limitation of the polyfill is that dialogs should not have parents that create a stacking context. The easiest way to solve this is to move your `<dialog>` element to be a child of `<body>`.

**Comment by Samuell1** [comment]
@jimmywarting I tried to fix it with slots but i found better solution just simply put this CSS in your project

```css
.md-dialog-container form {
  display: flex;
  flex-flow: column;
  flex: 1;
}
```
