### ISSUE TITLE
[MdSelect] displays down arrow on top of the clear X

### ISSUE THREAD

**Issue by goatandsheep** [vuematerial/vue-material#1553]
### Steps to reproduce

1. Use md-select + md-clearable together
2. select a value

### Which browser?

- [x] Chrome

### What is expected?

Clear button appears to the right of down arrow. or down arrow disappears

### What is actually happening?

Both down arrow and clear button appear on top of each other

### Reproduction Link

[Codepen link](https://codepen.io/anon/pen/ZrqGde)

**Comment by Samuell1** [comment]
MdSelect cant be clearable because it have arrow on right.

**Comment by goatandsheep** [comment]
For anyone wondering how I worked around this, I made an additional option called None and set the value to empty string. This reset the form. See this codepen for details: https://codepen.io/anon/pen/xYQKRE
