### ISSUE TITLE
[MdAutocomplete] Get a property of the slot-item to v-model

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1557]
Hi,
 Is it possible to get a property of the slot-item to `v-model` of the `md-autocomplete`. There is a sample in this codepen https://codepen.io/zapping/pen/mXzqNV .

 The slot-item displays item.name in the dropdown and is it possible to get item.id of the selected item to the `v-model` of the `md-autocomplete`? Currently the entire item object gets assigned to the `v-model`.

Cheers!

**Comment by Samuell1** [comment]
This PR can solve this issue: #1338

**Comment by zapping** [comment]
On the documentation site too if you try changing the value of the autocomplete in the 'Spinner Loading' section of https://vuematerial.io/components/autocomplete/ the same issue can be seen.

**Comment by Samuell1** [comment]
@zapping yeah that PR should solve that problems and separate searched value and selected value
