### ISSUE TITLE
Checkboxes etc should accept object as a value/model

### ISSUE THREAD

**Issue by jkosonen** [vuematerial/vue-material#1562]
### Steps to reproduce

Add object as a value for checkbox/switch/select etc..
`Invalid prop: type check failed for prop "value". Expected String, Number, Boolean, got Object.`

### Which browser?

All

### What is expected?

You should be able to use objects as values too

### What is actually happening?

`Invalid prop: type check failed for prop "value". Expected String, Number, Boolean, got Object.`

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/pull/1556
