### ISSUE TITLE
Vue Material md-table-pagination

### ISSUE THREAD

**Issue by rodrigues86** [vuematerial/vue-material#1565]
I'm trying create a pagination on a md-table on the Vue Material, but without successful. the method "onPagination" not returned nothing if I to put a console.log(). Follow the code below:

```
<md-table v-model="infoPdv" 
    :md-sort.sync="currentSort" 
    :md-sort-order.sync="currentSortOrder" 
    :md-sort-fn="customSort" 
    :md-fixed-header.sync="ifFixedHeader">

        <md-table-row slot="md-table-row" 
            :key="item.pdv" 
            :md-item="item" 
            slot-scope="{ item }">

        ...

        </md-table-row>


    <md-table-pagination md-label="Páginas" 
        :md-size="limit" 
        :md-page="offset + 1" 
        :md-total="infoPdv.length" 
        md-separator="de" 
        :md-page-options="[5, 10, 25, 50]" 
        @pagination="onPagination">
    </md-table-pagination>

</md-table>


methods: {
    onPagination(pagination) {
      if (pagination) {
        this.limit = pagination.size;
        this.offset = (pagination.page - 1) * this.limit;
      }

      this.find()

    }
}
```

Can someone help me?

**Comment by Samuell1** [comment]
Pagination is not yet implemented in new version.

**Comment by monirul-islam777** [comment]
> I'm trying create a pagination on a md-table on the Vue Material, but without successful. the method "onPagination" not returned nothing if I to put a console.log(). Follow the code below:
> 
> ```
> <md-table v-model="infoPdv" 
>     :md-sort.sync="currentSort" 
>     :md-sort-order.sync="currentSortOrder" 
>     :md-sort-fn="customSort" 
>     :md-fixed-header.sync="ifFixedHeader">
> 
>         <md-table-row slot="md-table-row" 
>             :key="item.pdv" 
>             :md-item="item" 
>             slot-scope="{ item }">
> 
>         ...
> 
>         </md-table-row>
> 
> 
>     <md-table-pagination md-label="Páginas" 
>         :md-size="limit" 
>         :md-page="offset + 1" 
>         :md-total="infoPdv.length" 
>         md-separator="de" 
>         :md-page-options="[5, 10, 25, 50]" 
>         @pagination="onPagination">
>     </md-table-pagination>
> 
> </md-table>
> 
> 
> methods: {
>     onPagination(pagination) {
>       if (pagination) {
>         this.limit = pagination.size;
>         this.offset = (pagination.page - 1) * this.limit;
>       }
> 
>       this.find()
> 
>     }
> }
> ```
> Can someone help me?

I am also facing the same problem?? can anyone help me providing their pro tables from vue material pro
