### ISSUE TITLE
[MdDialog] Bug if use MdDialog in v-else-if

### ISSUE THREAD

**Issue by uginroot** [vuematerial/vue-material#1578]
### Steps to reproduce

Use MdDialog in v-else-if condition. The following condition will not occur.

### Which browser?

Firefox, Google Chrome, IE
vue: 2.5.13
vue-material: 1.0.0-beta-8

### What is expected?

Continuation of the following conditions.

### What is actually happening?

Conditions cease to be met

### Reproduction Link

https://codepen.io/anon/pen/MQdPKp?editors=1010

**Comment by Samuell1** [comment]
Because you cant show it like that, use other function that will open dialog if your step is selected.

**Comment by uginroot** [comment]
I did this, but I decided that this bug should be fixed

**Comment by uginroot** [comment]
My app works like this:
```html
<template>
  <div>
  
    <!-- Children MdProgressSpinner -->
    <my-loading v-if="showLoading"/>
	
    <!-- Children MdDialog -->
    <my-login v-else-if="showLoginForm"/>
	
    <!-- Application broken -->
    <slot v-else/>
	
  </div>
</template>
```

Whichever way I showed the modal window when the variable showLoginForm is set to false, the whole application breaks. Before that, with bootstrap-vue everything was fine. The behavior of the component breaks the logic of the operation of vue.

**Comment by Samuell1** [comment]
Do you get any errors?

**Comment by uginroot** [comment]
No...

**Comment by Samuell1** [comment]
I was trying to fix it but i cant find a solution that doesnt make other issues. This is because we moving dialog element as parent of body. 

But i found a other solution that you can use: https://codepen.io/Samuellsk/pen/yKQWoV?editors=1010
