### ISSUE TITLE
Md-select multiple md-option checkbox not preselecting.

### ISSUE THREAD

**Issue by d0190535** [vuematerial/vue-material#1579]
**Stesp to reproduce**
Use md-select with multiple option, and return data with an initial value in the v-model array.

**Which browser?**
Google chrome (did not test on other browsers)
vue: 2.3.3 (also exists in 2.5.13)
vue-material: 1.0.0-beta-7

**What is expected?**
The value from the array should be preselected on the md-option field when the dropdown is opened.

**What is actually happening?**
The md-option for that value corresponding to the v-model array is not getting checked.  However, the option text is getting highlighted so it is being recognized as selected.

Also, if I open the dropdown and select another item, close the dropdown and reopen it, the initial value (fight club in the sample code) will be selected with check.

**Reproduction Link**
https://codepen.io/anon/pen/bLPpBN?&editors=111

**Comment by Samuell1** [comment]
In beta-8 its fixed

**Comment by d0190535** [comment]
updated to beta-8 and it is working as expected thanks.
