### ISSUE TITLE
md-dialog-alert

### ISSUE THREAD

**Issue by zhuyinjing** [vuematerial/vue-material#1581]
hey
when i use it in my code
`<md-dialog-alert :md-content="alertcontent" md-ok-text="ok" ref="alertbox">
  </md-dialog-alert>`
chrome shows error:
`vue.esm.js?5425:578 [Vue warn]: Error in mounted hook: "Error: Missing md-content or md-content-html attributes"`
if i use `md-content `  not ` :md-content`
it doesn't show error.
what's wrong?
how should i do?
thanks so much!!

**Comment by Samuell1** [comment]
Then your `alertcontent` is empty.

**Comment by zhuyinjing** [comment]
no..
i set `alertcontent` with '1',
`export default {
  data () {
    return {
      alertcontent: '1',`
}}}
it shows this error too.
`vue.esm.js?5425:578 [Vue warn]: Error in mounted hook: "Error: Missing md-content or md-content-html attributes"`
what's wrong?

**Comment by VdustR** [comment]
Would you provide your code in Codepen?
