### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by Feduch** [vuematerial/vue-material#1582]
Hi! 

When I added 

import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'
import 'vue-material/dist/theme/default.css'
Vue.use(VueMaterial)

then build and run 
npm run build
cordova run android

in console

Object.values is not a function 
![2018-03-06 12 37 40](https://user-images.githubusercontent.com/5888590/37026567-dd224e94-213f-11e8-9463-145cf69065cc.png)

How repear it?

**Comment by Samuell1** [comment]
You need to include polyfills for that in your app.

**Comment by Feduch** [comment]
polyfills - It is this https://babeljs.io/docs/usage/polyfill/ ?

**Comment by Samuell1** [comment]
I think yes.
