### ISSUE TITLE
[MdCheckbox] meaningless behavior in checked for non-model bound checkboxes

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1586]
Using VueMaterial 1.0.0-beta8

`<md-checkbox :value="true" />` yields an unchecked checkbox, but `<md-checkbox :value="true" :model="true" />`will render a checked checkbox.

This behavior is due to the boolean check found here:
https://github.com/vuematerial/vue-material/blob/7e7249afef716898f69b838ecd3d1506810f35b9/src/components/MdCheckbox/MdCheckboxMixin.js#L25

Would suffice to do a value check if there's no model bound to the checkbox I believe.

**Comment by VdustR** [comment]
How to detect if there was no model bound?

**Comment by VdustR** [comment]
similar to #1489

**Comment by emman27** [comment]
Was going to go with `this.model === null` but it seems after examination of other parts of the code base this isn't going to work...
