### ISSUE TITLE
[MdMenu] does not close in safari/iOS

### ISSUE THREAD

**Issue by idlinnes** [vuematerial/vue-material#1588]
I used MdMenu in a website, it works with desktop safari, but when I open it in a ios version of safari(IPAD\IOS10-11), the menu does not close when I click outside or clicked one item. The same happened with IE11 but i fix it by adding polyfill to Node.contains.

I can reproduce it with https://www.browserstack.com
Link to video - https://drive.google.com/open?id=1Mye-13daptmoCcst1iizTIvwjvTGutSl

**Comment by Samuell1** [comment]
> this goo.gl shortlink has been disabled. It was found to be violating our Terms of Service. Click here and here for more information about our terms and policies respectively.

**Comment by Samuell1** [comment]
Do you get any errors in console ?

**Comment by idlinnes** [comment]
> Do you get any errors in console ?
no.

**Comment by andreofthecape** [comment]
Have something similar, viewing vuematerial website on osx chrome, safari and firefox the menu's only close when I click outside, but not by clicking on item. In codepen they close normally by clicking outside and by clicking on item. Also tried windows now and getting same behaviour.

**Comment by Samuell1** [comment]
@andreofthecape its because items in menu doesnt have defined any action thats why you cant click on them, if you add `@click` or prop `to` it should allow clicking.

**Comment by VdustR** [comment]
I can fix that if @marcosmoura agree it should be close when plain text item be clicked.

**Comment by VdustR** [comment]
https://material-components-web.appspot.com/menu.html

It's closed while click on the white padding space.
