### ISSUE TITLE
[Safari] Theming broken?

### ISSUE THREAD

**Issue by caseyprovost** [vuematerial/vue-material#1589]
### Which browser?

Safari OS X

### What is expected?

It should look the same as on chrome

### What is actually happening?

Theming appears broken

#### Chrome
![screen shot 2018-03-08 at 12 18 57 pm](https://user-images.githubusercontent.com/210048/37165549-ebdf2cb8-22ca-11e8-883c-e07f31dcf4ab.png)

#### Safari
![screen shot 2018-03-08 at 12 18 42 pm](https://user-images.githubusercontent.com/210048/37165563-f1d854e6-22ca-11e8-95e5-7e9447ae9814.png)

**Comment by Samuell1** [comment]
It can be because of this https://github.com/vuematerial/vue-material/issues/1305

**Comment by VdustR** [comment]
yes, it's not because of safari. It's rendered that way in all browsers when visit that page directly.
