### ISSUE TITLE
@md-selected not documented for md-select/md-field. Please add this to documentation

### ISSUE THREAD

**Issue by brianboyko** [vuematerial/vue-material#1590]
Running on ^1.0.0-beta-7, I'm using md-select inside of a v-for loop, and because I will not know what my data model will look like until runtime, I can't just assign a property in the this.data() of the Vue component to act as a model.  

The solution is to use the @md-selected event, which can pass in the value to a method (in this use case, along with the index of the array so it is know what property to modify.) 

Use case for @md-selected that CANNOT be solved using v-model only at this pen https://codepen.io/anon/pen/JLjJdM

**Comment by Samuell1** [comment]
![obrazok](https://user-images.githubusercontent.com/3110002/37176901-120de0ca-231e-11e8-9b43-c1edab634bc0.png)
