### ISSUE TITLE
RTL Components needed

### ISSUE THREAD

**Issue by Hkh12** [vuematerial/vue-material#1594]
Hi
I'm working on a big project and I want to build it with vuematerial, and I need __RTL__ components.
This solves some problems: 
```html
<body dir='rtl'>
```
But some components (like tabs and progress spinners) don't perform well.
So, Should I wait for v1.0.0?

Thanks ;) 
and sorry for my bad English

**Comment by Samuell1** [comment]
Yes, RTL is on roadmap https://github.com/vuematerial/vue-material/issues/1081

**Comment by Samuell1** [comment]
Duplicate of #80
