### ISSUE TITLE
[MdMenu] items are not well aligned vertically with IE11.

### ISSUE THREAD

**Issue by cbgrape** [vuematerial/vue-material#1596]
As stated in the title, the menu items are shown with too much space at the bottom of the pop menu. This problem occurs both at [the official Vue Material website](https://vuematerial.io/components/menu/) and my latest installation(1.0.0-beta-7). 

See [the screenshot of the problem](https://user-images.githubusercontent.com/16728636/37289064-b7362fbc-2643-11e8-977b-b5278542ff02.png).

**Comment by Samuell1** [comment]
Can you please try version beta-8?

**Comment by cbgrape** [comment]
After solving some compatibility problems, I finally got beta-8 run on IE11. The problem is still there.  Please see [the screenshot of the problem](https://user-images.githubusercontent.com/16728636/37319251-5147fee0-26a9-11e8-9fe7-9ac7f2341b96.png). 

In addition, you may notice that the position of the pop menu is not correct, but I think this additional problem (related to MdPopover) should have been solved in the latest version. 

.

**Comment by Samuell1** [comment]
This looks like flexbox bug in IE
