### ISSUE TITLE
[MdTablePagination] Unused method parameter "pageSize" in mdPageSize watch handler

### ISSUE THREAD

**Issue by hiddenwaffle** [vuematerial/vue-material#1599]
I was browsing the source when I noticed this:

https://github.com/vuematerial/vue-material/blob/bfc3e04caa9415b04d6f70f9548ce5bf32e1b6f3/src/components/MdTable/MdTablePagination.vue#L70

pageSize is an expected parameter, but the one line of code uses "this.pageSize", which I cannot find defined anywhere else in the project.

**Comment by Samuell1** [comment]
Pagination is not completed.
