### ISSUE TITLE
[MdDatepicker] typing broken as of 1.0.0-beta-8

### ISSUE THREAD

**Issue by emman27** [vuematerial/vue-material#1602]
### Reproduction Link

In 1.0.0-beta-7, you could use the keyboard to input a date in the format YYYY-MM-DD.
In 1.0.0-beta-8, this method of input has become extremely clunky with the datepicker aggressively filling up the date.

Random fact: The way the remaining numbers are filled up are different for Chrome and Firefox (the 2 browsers I have on my machine)

(Sorry for the random letters at the end, I just got really frustrated at the datepicker)

![datepicker](https://user-images.githubusercontent.com/6295583/37380614-69e0f2b0-2774-11e8-87e6-042348cd9bbe.gif)

**Comment by Samuell1** [comment]
Its because in beta-7 was enabled native "date" input you can enable it by prop `md-override-native` to false

**Comment by emman27** [comment]
Just another suggestion: I think plaintext is fine, with a debounce on input for the conversion to a Date object, and simply don't do the conversion if the string isn't a valid date.

**Comment by Samuell1** [comment]
@emman27 good idea! I loot at it later.

**Comment by qubitron** [comment]
Being able to type in dates is very important for data entry, so glad you are looking into this! When addressing this you may need to take into account the dateformat used in the current locale, similar to  #1422

**Comment by Samuell1** [comment]
@qubitron you can change format of date with `this.$material.locale.dateFormat = 'YYYY-MM-DD'`

**Comment by qubitron** [comment]
@Samuell1 I wasn't having trouble with setting the date format. I was just trying to be helpful and suggesting the date format should also be used when parsing date input as well, since the built-in JavaScript date type may not accept many date locales as valid.

**Comment by Samuell1** [comment]
@qubitron oh sorry i misunderstand it :D yeah thats true it should be both ways
