### ISSUE TITLE
Vue-Material css broke my design

### ISSUE THREAD

**Issue by MaximeScibetta** [vuematerial/vue-material#1605]
Before : https://puu.sh/zISro/858aa7e83a.png

after imported with this code 

```
// Import library
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.min.css'

// Use library
Vue.use(VueMaterial)
```

https://puu.sh/zISsw/5d29e7dc5c.png

**Comment by Samuell1** [comment]
Can you provide what classes you using?

**Comment by VdustR** [comment]
Would you provide more information like reproduce it in CodeSandbox or Codepen for help?
