### ISSUE TITLE
[MdTable] selectable count after removing item(s)

### ISSUE THREAD

**Issue by osamaz26** [vuematerial/vue-material#1610]
When i'm trying to remove one or more items from MdTable by changing source, i found that the removed items are still existed somewhere because SelectAll button is showing the count of removed items. 

I'm using 1.0.0-beta8 version and table has md-selectable="multiple" flag with SelectAll button.

if checked the code and found this line in MdTableRow is preventing removing item from selectable array. 
line number 125.
        if (!this.hasMultipleSelection) {
          return
        }
I'm not sure if there is another way to remove item(s) from table and fix selectable items when clicking on SelectAll button.

**Comment by VdustR** [comment]
I think this was fixed with https://github.com/vuematerial/vue-material/pull/1496. Would you check it with `dev` branch or give me your reproduction code to let me confirm this?

**Comment by osamaz26** [comment]
I created a small demo in codepen that using last release 1.0.0-beta8 
https://codepen.io/osamaz26/pen/XEpozo
The main issue is with SelectAll button that is always shown.

I will check dev branch.

**Comment by osamaz26** [comment]
I checked your last commit and everything works fine.
Thanks

**Comment by Amikre** [comment]
Hello @osamaz26 is there any way to contact you? 
i have something to talk to you about privately but i don't see any email to reach you
