### ISSUE TITLE
[MdTable] Re-selecting the same row fails

### ISSUE THREAD

**Issue by mfalthaw** [vuematerial/vue-material#1613]
Hi,

I'm not sure if this is actually a bug, but the behaviour certainly isn't right. It's possible this is due to my implementation, however, I wanted to bring it to your attention.

### Steps to reproduce
- Use this snippet: https://codepen.io/anon/pen/aYpqoz?editors=1011
- Open up browser console
- Select any row
- A dialog will show, click `Cancel`
- Select the same row again
- Console error `TypeError: Cannot read property 'name' of null`

### What is expected?
- Selecting the same row again should have the same behaviour (ie, open the dialog)

### Question
- If this is indeed due to bad implementation, how would toggle the row selection? The documentation didn't provide event description.

**Comment by Samuell1** [comment]
You should use `:md-selected-value.sync="selected"` on `md-table`

**Comment by rayfoss** [comment]
This should probably be in the docs... to clarify... `@md-select` is mostly useless on multiple select, it'll fire only when unselecting. Instead just use computed/watch to listen for changes. This should probably be filed as a bug as it violates one-way data flow
