### ISSUE TITLE
[MdAutoComplete] options are not visible when component is inside MdDialog

### ISSUE THREAD

**Issue by osamaz26** [vuematerial/vue-material#1617]
I'm trying to use MdAutoComplete inside MdDialog but options are not visible.
I have created a snippet https://codepen.io/osamaz26/pen/qorNeQ

I think changing the z-index of md-menu-content-bottom will fix the issue but I'm not sure what about other components.

**Comment by Samuell1** [comment]
Yes we know about it its issue with compiler.

https://github.com/vuematerial/vue-material/pull/1525#issuecomment-369331004

**Comment by osamaz26** [comment]
I'm sorry, It is my mistake that I did not search in the opened issues. 
Thanks
