### ISSUE TITLE
Suggestion: Add more specific classes to the buttons in MdDialogConfirm

### ISSUE THREAD

**Issue by mattgrande** [vuematerial/vue-material#1622]
I came across this while writing some E2E tests. It's difficult to target the buttons in the current implementation of MdDialogConfirm, as they are both rendered the same.

I think it would be nice to see some classes added to the buttons, eg, `md-dialog-confirm-button` and `md-dialog-cancel-button` to make CSS & testing targeting easier.

If others agree, I'm more than willing to make a PR.

**Comment by Samuell1** [comment]
I think in `MdDialogConfirm` component should not be close button with `md-primary` class, then it will be easy to target buttons.

**Comment by mattgrande** [comment]
Agreed; Should it be `md-accent`, or just nothing?

**Comment by Samuell1** [comment]
@mattgrande just nothing, accent means more like "danger" button :D
