### ISSUE TITLE
Md-primary or accent not working

### ISSUE THREAD

**Issue by maarteNNNN** [vuematerial/vue-material#1623]
### Steps to reproduce

I'm trying to get `md-primary` on `md-button` but I'm not getting the styles
I have seen the node-sass issue #1619 but I trying to install `"node-sass": "^4.5.3"` doesn't work.
Here you can see the class defined:
![2018-03-23_18-20-51_screenshot](https://user-images.githubusercontent.com/14275291/37853921-82adfebe-2ec7-11e8-910b-ceec8e4e32b1.png)
This is what I'm getting in the developer console:
![2018-03-23_18-21-26_screenshot](https://user-images.githubusercontent.com/14275291/37853925-844057d6-2ec7-11e8-8628-b5f5c56ba87f.png)
Here is how the button looks:
![2018-03-23_18-26-21_screenshot](https://user-images.githubusercontent.com/14275291/37853982-ba4b42e6-2ec7-11e8-9593-11bb86b5e359.png)

### Which browser?

```json
    "vue": "^2.5.2",
    "vue-material": "^1.0.0-beta-7",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.7",
```
I've only tested in Chromium Version 65.0.3325.181 (Developer Build) (64-bit)

### What is expected?

The button should color blue.

### What is actually happening?

The button stays the normal style

### Navigation drawer
The navigation drawer does indeed color to md-primary which is defined in `App.vue`:
```
md-app-toolbar.md-primary(md-elevation="0")
```
This works.

**Comment by maarteNNNN** [comment]
I'm terribly sorry, I my `App.vue` i put `scoped` now it is resolved. I overlooked the simplest solution.

**Comment by CristiAllan** [comment]
Hi, I'm with the same issue, I'm using Vue Cli 3 and I already have tried to put scoped at my App.vue and it not worked to me, my components are without any color

**Comment by salissadiq** [comment]
I'm with the-same issue too

**Comment by krysalead** [comment]
Hi, same issue here no color
