### ISSUE TITLE
TypeError in MdAutocomplete.vue

### ISSUE THREAD

**Issue by maarteNNNN** [vuematerial/vue-material#1625]
### Steps to reproduce
I open this issue to refer to my pull request.
`Md.Autocomplete.vue` has a bug which wants `toLowerCase` a string. But isn't always defined as a string. That's why there should be a `toString().toLowerCase()`. So there no nasty TypeError.

### Which browser?
Chromium Linux v65

### What is expected?
No TypeError

### What is actually happening?
Getting a TypeError `toLowerCase() is not a function` like this:
![2018-03-24_18-57-05_screenshot](https://user-images.githubusercontent.com/14275291/37869443-653a32ec-2f96-11e8-8222-399508a9fbc7.png)

**Comment by VdustR** [comment]
Related to https://github.com/vuematerial/vue-material/issues/1243

**Comment by Samuell1** [comment]
Duplicate of #1243
