### ISSUE TITLE
Menu :md-close-on-select="true" not working

### ISSUE THREAD

**Issue by dhalturin** [vuematerial/vue-material#1627]
Hello. 

Menu don't closing on click in vue-material@1.0.0-beta-8. Reproduction Link:
https://codepen.io/anon/pen/aYyMEO

In issue 1279 it's working (vue-material@1.0.0-beta-7):
https://github.com/vuematerial/vue-material/issues/1279

**Comment by VdustR** [comment]
There is no selectable item in your menu.

Click on plain item will not close the menu for now. 

https://github.com/vuematerial/vue-material/issues/1588#issuecomment-371737740

**Comment by dhalturin** [comment]
Okay. how to make a menu item for close menu on click item? Adding "v-on:click" or "to='url'" (with vue-router) for md-menu-item? 

https://codepen.io/anon/pen/GxMNBp?editors=1010
It's doesn't correct?

**Comment by VdustR** [comment]
duplicated #1471

**Comment by dhalturin** [comment]
Ok.. thnx )
