### ISSUE TITLE
[MdInput] v-model triggers second invalid input

### ISSUE THREAD

**Issue by hanxue** [vuematerial/vue-material#1628]
### Steps to reproduce

1. Create a form with `<md-input>`

```html
              <md-input 
                  v-model="growthRateFormatted"
                  :name="'growthRate' + props.rowIndex"
                  :id="'growthRate' + props.rowIndex">
                </md-input>
```

2. Have a computed property that accepts `%` input and convert to numerical value

```javascript
computed: {
    growthRateFormatted: {
      get: function () {
        return accounting.formatMoney((this.growthRate * 100), "%", 2, ",", ".", "%v %s")
      },
      set: _.debounce(function (newGrowthRate) {
        this.growthRate = newGrowthRate / 100
      }, 2000)
    }
  },
data: () => ({
    growthRate: 0.12,
})
```

3. Enter an input value, and it will be overwritten to `""`

### Environment

Browser: Chrome 67.0.3379.0 
Vue: 2.5.16
Vue-material: 1.0.0-beta-8

### What is expected?

The input value should not be overwritten

### What is actually happening?

See video capture

![md-input trigger input twice 2018-03-26 at 13 57 22](https://user-images.githubusercontent.com/760008/37889392-a3e9e546-30fe-11e8-8f9a-1002d4ac2696.gif)

**Comment by VdustR** [comment]
I think it's better to use `watch` instead of `computed` in this case.

**Comment by Samuell1** [comment]
Any updates? Do you found a solution?

**Comment by hanxue** [comment]
Thanks @VdustR , using `watch` works:

```javascript
watch: {
    growthRateFormatted: function (newRate, oldRate) {
      this.growthRate = (accounting.unformat(newRate) / 100)
    },
  },
```

At the vue-material level, is it possible to change the display of the value, so that it will always append ` %` after user has completed editing?

There should be 3 values of the same property:

- User input `12.55`
- md-input display as `12.55 %`
- watcher convert data variable as 0.1255

How can I automatically remove the `%` when user edits the value, and append `%` after edit is completed?

**Comment by VdustR** [comment]
I think using postfix is better in this case. This will be released with next version.

https://github.com/vuematerial/vue-material/pull/1592/files

**Comment by Y0hy0h** [comment]
@hanxue I had a similar issue to yours. I wanted to let the user input a currency which would be formatted while he types. But I don't know any elegant way that `MdInput` can support this.

In the end you want to intercept what the user inputs and treat it in a special way. I managed to do that by registering a `@keypress` on the `input` and manually processing the key that was pressed. Then I display the finished, formatted value in the `input` using the `:value` binding.  
This way I can separate what the user puts in from what the `input` displays. You can have a look at [my code](https://github.com/Y0hy0h/plusminus/blob/master/src/components/ExpenseInput/ExpenseInput.vue) to see exactly how I did it. (Note that I used [pug](https://pugjs.org/api/getting-started.html) for the `<template>`, alongside TypeScript in the `<script>`.)

Also note that I wanted to emulate the way you can input a timer value in the default Android timer app, which works similarly to a calculator. So in my case there is no way to select text with the mouse and no "text cursor", just as with a calculator input. I hope what I wrote is understandable. :D

Maybe this gives you a starting point.

**Comment by hanxue** [comment]
@VdustR the suffix will be useful, though it still does not solve the problem of changing the percentage value to decimal. 

Thanks for the example @Y0hy0h ! Yep, that is exactly what I need. I can figure out the pug syntax, but the Typescript section seems to be very different, using `vue-property-decorator` instead of `computed` or `watched` properties.

**Comment by Y0hy0h** [comment]
@hanxue, yes, that's exactly what I used. Nice isn't, it? 😁

In case you have trouble figuring out how to do it in plain Vue, it translates to roughly
```
...
model: {
  prop: 'expense',
  event: 'change',
},
methods: {
  updateAmount(event) {
    // implementation which emits 'change' events
    // ...
  }
}
...
```
No magic involved. ;)

**Comment by hanxue** [comment]
Thanks again @Y0hy0h ! I resorted to using child component for now. On the parent:

```html
              <md-field md-inline>
                <percentage-input v-model="growthRate"></percentage-input>
              </md-field>
<script>
export default {
  // ...
  data: () => ({
    growthRate: 0.12,
</script>
```

Then in the child component

```js
Vue.component('PercentageInput', {
  props: ['value'],
  template: `
    <div>
      <md-input
        v-model="formattedGrowthValue"
        @blur="focusOut"
        @focus="focusIn"></md-input>
    </div>`,
  data: function() {
    return {
      formattedGrowthValue: '12 %',
    }
  },
  methods: {
    focusOut: function() {
      let parsedValue = parseFloat(this.formattedGrowthValue.replace(/[^\.\d]/g, "")) / 100
      if (isNaN(parsedValue)) {
        this.$emit('input', 0.0)
        this.formattedGrowthValue = ' 0.0 %'
      } else {
        this.$emit('input', parsedValue)
        this.formattedGrowthValue = Math.floor(parsedValue * 100) + ' %'
      }
    },
    focusIn: function() {
      this.formattedGrowthValue = (this.value * 100).toString()
    }
  },
});
```
