### ISSUE TITLE
The sass style does't work.

### ISSUE THREAD

**Issue by Reprieving** [vuematerial/vue-material#1629]
### Steps to reproduce

I build a vue project by vue-cli, install vue-material, sass-loader, node-sass, and configure the webpack.base.conf.js. But the style have some problem.

### the webpack.base.conf.js
![qq 20180326160850](https://user-images.githubusercontent.com/26201038/37894216-1c7cf62c-3110-11e8-9dab-c098e69539f5.png)

### the vue component code
![qq 20180326161933](https://user-images.githubusercontent.com/26201038/37894662-7cfe047c-3111-11e8-93a0-8f1dcaca6027.png)

### the result
![qq 20180326161807](https://user-images.githubusercontent.com/26201038/37894597-4a43d2b4-3111-11e8-97e9-a429e7fe8c6c.png)

it is the sass'configure problem?

**Comment by Samuell1** [comment]
vue-cli should have predefined all things for SCSS/SASS you need to only install packages `sass-loader, node-sass`

**Comment by VdustR** [comment]
I think you miss material icon font.

**Comment by Reprieving** [comment]
@VdustR That is it. thanks. 
@Samuell1 and thanks for your apply.
