### ISSUE TITLE
[Feature request] shrinking toolbars

### ISSUE THREAD

**Issue by breadlesscode** [vuematerial/vue-material#164]
Hi,

first of all, **I LOVE YOUR WORK!** And a big thanks for your daily work! 

Would you implement shrinking toolbars? 

Examples: https://material.google.com/patterns/scrolling-techniques.html#scrolling-techniques-behavior

I love this material design feature =)

**Comment by sombriks** [comment]
indeed, this is a nice project and this is a marvelous feature.

hey maintainer, you should set up a [patreon](https://www.patreon.com/). So we could financiante a beer or two.

**Comment by marcosmoura** [comment]
Hi @breadlesscode @sombriks 
Thanks for the words! :D

About the feature: Yes. I will be implemented. Like I said ins #154 I have plans to implement some core components to deal with application shell. And a shrink and the Flexible space feature will also be developed. I will try to address this to 0.7.0.

About patreon: Not for now. I want to make it almost stable and then I will think about that. Fortunately I have a daily job so I still get paid. But who knows?

Thanks again!

**Comment by alexche77** [comment]
Hi! I was wondering, it says this feature is implemented, how do i use it in my project? :D

thanks! :+1:

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/components/app
