### ISSUE TITLE
[MdFile] style wrong

### ISSUE THREAD

**Issue by VdustR** [vuematerial/vue-material#1642]
### Which browser?

`dev`(ecf5cb7bcc80c1bac247a80d53e2ba6bf90421ee) branch(after f2347f18843686e2197d750fe1ec0776f0806109)

### What is expected?

<img width="344" alt="file_-_vue_material" src="https://user-images.githubusercontent.com/29639463/38076247-a58808c2-3367-11e8-9f1b-3ee2000e5e04.png">

### What is actually happening?

<img width="347" alt="file_-_vue_material" src="https://user-images.githubusercontent.com/29639463/38076306-ce36d258-3367-11e8-9b09-108099277152.png">

### Reproduction Link

Run `yarn dev` with branch `dev` (commit ecf5cb7bcc80c1bac247a80d53e2ba6bf90421ee)

Related to #1545

**Comment by Samuell1** [comment]
Its because this is not merged yet https://github.com/vuematerial/vue-material/pull/1549
