### ISSUE TITLE
CSS Performance

### ISSUE THREAD

**Issue by caseyprovost** [vuematerial/vue-material#1648]
### Steps to reproduce

All you need is a page with lots of dom elements. Say 1000, you can even cheat and make most of those options in a drop down. Introduce Vue Material and watch your performance drop.

### Which browser?

Chrome - Latest (Mac)

### What is expected?

Reasonable performance

### What is actually happening?

We have a legacy app that we are introducing this to and we are seeing about a 2x speed loss when rendering heavier pages. The culprit seems to be this guy:

```
html * { box-sizing: inherit }
```

If we remove the above all performance issues are rendered moot (mostly). How can we make this more performant?

-- EDIT --
It is worth noting that if you add more and more dom elements you can watch performance degrade. Our situation is a page with over 14,000 dom elements. I know that seems nuts, but it does render fast without this additional css.

**Comment by Samuell1** [comment]
If you remove `box-sizing: inherit` all elements will be not working like expected, because its uses `box-sizing: border-box`.

But you should use some optimalizations on your side, virtual scroll, lazyloading, pagination etc

**Comment by caseyprovost** [comment]
Would something like this get better performance?

```
html {
  box-sizing: border-box;
  overflow-y: scroll; /* All browsers without overlaying scrollbars */
  -webkit-text-size-adjust: 100%; /* iOS 8+ */
}

*,
::before,
::after {
  box-sizing: inherit;
}
```

**Comment by caseyprovost** [comment]
@Samuell1 and I hear ya about optimizations, but a new framework causing rendering slow-downs over 2x or more seems a bit non-standard too. Im not a CSS wizard, but I am curious what tweaks can be done in this framework to reduce the performance impact.

**Comment by caseyprovost** [comment]
@Samuell1 I think the key is `box-sizing: border-box;` vs inherit. Setting a value explicitly rather than dynamically inheriting from the dom tree is a performance cost for sure.

**Comment by Samuell1** [comment]
@caseyprovost can you test that?

**Comment by caseyprovost** [comment]
@Samuell1 I have locally in my environment and it does seem to improve page load times by 1-1.5seconds. Do we have tests in this repo for performance that would be a good place to add something like this?

**Comment by Samuell1** [comment]
@caseyprovost do you using only vue-material without any your code?
