### ISSUE TITLE
[MdListItem] Clickable MdListItem hides its action button's click

### ISSUE THREAD

**Issue by Y0hy0h** [vuematerial/vue-material#1653]
### Steps to reproduce

1. Create a list containing a `<md-list-item/>`.
2. Add a click handler to that list item: `<md-list-item @click="console.log('clicked')"/>`.
3. Add a button as an action to that item:
   ```js
   <md-list-item @click="console.log('clicked')">
     <md-button class="md-list-action" @click="console.log('action')"/>
   </md-list-item>
   ```
4. Try to click the list item's action button.

### Which browser?

Firefox 59.0.2
(it *works* in Chrome 65.0.3325.181)

### What is expected?

The button reacts to hover and triggers its click action.

### What is actually happening?

Only the list item's "selection" is triggered. The button displays neither a hover effect, nor is its click action called.

### Reproduction Link

https://codesandbox.io/s/p4y4ykxo7

**Comment by VdustR** [comment]
related to #1461

seems same reason with https://github.com/vuematerial/vue-material/issues/1461#issuecomment-361883201

**Comment by Y0hy0h** [comment]
Thanks for the reference! Indeed it looks like buttons inside buttons are illegal ([relevant StackOverflow](https://stackoverflow.com/a/39386695/3287963)). So this is undefined behaviour.

I now also more carefully read the documentation on the list component. It clearly states that passing a `@click` will make the list item a button. I thought that I could work around this by also passing an empty `href` to make it a link, but apparently it will still be rendered as a button ([relevant CodeSandbox](https://codesandbox.io/s/y0j2xp2k9z)).

I feel that a list item being selectable and having an action at the same time is a legitimate use case. However, I couldn't find anything on list item selection in the Material Design spec. And I admit that having the list item hover effect overlay the button is at least awkward.

If you decide that you do not want to support list item selection and actions simultaneously, could you update the documentation to warn against this or ideally throw an error when nested buttons are detected? (I don't know how difficult the error would be...)

**Comment by Samuell1** [comment]
`@click` on md-list-item will automatically create it as button if you remove it it should work.

**Comment by Y0hy0h** [comment]
@Samuell1, how do I know whether the list item was selected, then?

**Comment by Samuell1** [comment]
@Y0hy0h list should have action only if doesnt have action inside

**Comment by Y0hy0h** [comment]
@Samuell1 Ok, I understand! :)

Is it possible to reflect this in the documentation or even better throw an error if it is detected?

**Comment by Samuell1** [comment]
@Y0hy0h Maybe we can allow passing `tag` prop that can change md-button to any element you want?

**Comment by Y0hy0h** [comment]
No, I think that would make things too complicated. For the moment, I seem to be the only one that has thought of this combination, and I'm beginning to think that it's not good to mix item selection and actions.

So for me the easist thing right now would be to just state in the list documentation that these two options don't mix well. In the "List Action" segment I would add something like:
> Mixing a list action with actions on the list items hurts usability. When clicking on the list item action, will the list action be triggered as well? Therefore, when using a list action, do not use actions on the list items. Mixing them additionally has technical compatibility issues between browsers.

I will try to come up with a solution for my problem and share my suggestion of what to do exactly with the list item actions.
