### ISSUE TITLE
[MdDatePicker] does not update date when month or year is selected

### ISSUE THREAD

**Issue by Y0hy0h** [vuematerial/vue-material#1654]
### Steps to reproduce

1. Add a date picker: `<md-datepicker/>`
2. Set some (random) date. Either using `v-model` or just choosing one with the picker.
3. a. Change the month by clicking on the month's name and then choosing another month.
    b. Change the year by clicking on the month's name, then the year and choosing another year.
4. Click "OK".

### Which browser?

Firefox 59.0.2
Chrome 65.0.3325.181

### What is expected?

After choosing a different month (or year), the date should update both in the dialog and in the input field. At the very latest, the date should update when clicking "OK".

### What is actually happening?

The change to the date is lost. The actual date is the one selected before changing the month.

### Reproduction Link

https://codesandbox.io/s/81rj9wvlj0

### Suggestion for Fix

[`switchMonth()`](https://github.com/vuematerial/vue-material/blob/dev/src/components/MdDatepicker/MdDatepickerDialog.vue#L312) and [`switchYear()`](https://github.com/vuematerial/vue-material/blob/dev/src/components/MdDatepicker/MdDatepickerDialog.vue#L316) should update `selectedDate` just as [`selectDate()`](https://github.com/vuematerial/vue-material/blob/dev/src/components/MdDatepicker/MdDatepickerDialog.vue#L320) does.

**Comment by Y0hy0h** [comment]
I could submit a PR, if the suggested fix is ok.

**Comment by VdustR** [comment]
No, I think selected date only update when a date is clicked because there are different amount of days between months. I think the date string on the left should be the selected date, not the current page year and month with the selected date, or that will miss leading user that is the picked date.

@marcosmoura , @Samuell1

**Comment by Y0hy0h** [comment]
Yes, you're right in that the feedback is currently the correct one. If the date is not actually selected, the UI should not update.

My suggestion is that clicking a month or year actually selects a new date. Clamping the day to the month's range is totally fine.

The issue is about intention: If the user clicked the month, she told the system that she wanted a different one. Currently, the system does not immediately react to that, but waits until she chooses a day.

There are cases where chosing the day additionally is against the mental model of the user. Imagine you want to change the date to exactly one year ago. Instead of scrolling a lot, you go to the month and then the year selection. Then you select the new year and feel that you're done, so you click OK. But the date will not have changed, which is against what you wanted to do.

My main point is that by clicking a month or year, the datepicker should acknowledge the user's input and immediately select the most appropriate new date.

**Comment by Samuell1** [comment]
I agree with @VdustR and i looked in other material libraries and they have this selecting functionality same.

**Comment by Y0hy0h** [comment]
I would still argue that the current behaviour is confusing, since it doesn't acknowledge the user input until very late.

I'd like to figure out where exactly our views on this issue diverge. I hope you don't mind discussing it a little bit more. :)  
So, basically, my main question is: If you click on the month, what do you expect to happen?
