### ISSUE TITLE
MD-Table slot-scope loading fails with beta-8.

### ISSUE THREAD

**Issue by sfyrious** [vuematerial/vue-material#1659]
### Steps to reproduce

https://codepen.io/sfyrious/pen/zWarZa

### Which browser?

vue-material-1.0.0-beta8 (Firefox 59.0.2)

### What is expected?

The table should load with slot-scope.

### What is actually happening?

Table is not loading. 

### Reproduction Link

https://codepen.io/sfyrious/pen/zWarZa

**Comment by Samuell1** [comment]
Because **entries** must be _array_ not a object and _slot-scope_ must be **item** not a **entry**

https://codepen.io/Samuellsk/pen/bvKBaM?editors=1010

**Comment by sfyrious** [comment]
Thanks!

I missed that in documentation... :/

Best regards,
Markus

2018-04-02 18:58 GMT+03:00 Samuell <notifications@github.com>:
