### ISSUE TITLE
[MdInput] type="password"

### ISSUE THREAD

**Issue by zhuyinjing** [vuematerial/vue-material#1661]
hey,i use old version `vue-material v0.8.1`
i use it in my code
`<md-input-container>
        <label>密码</label>
        <md-input maxlength="20" type="password" v-model="password" @blur.native="passwordBlur" @focus.native="hideMessage"></md-input>
      </md-input-container>`
and when i set chrome remember username and password,
when i open the html the second time,
i saw it with my md-input : 
![2018-04-03 15-45-08](https://user-images.githubusercontent.com/25977997/38236313-5dfcb8ca-3756-11e8-91cc-53be4623a18a.png)
it has password,but i can't get password.
what's wrong with my code?
thanks so lot!

**Comment by VdustR** [comment]
We could check this improvement with new version.
The old v0.8.x is deprecated. It will not be maintained anymore.

**Comment by Samuell1** [comment]
![obrazok](https://user-images.githubusercontent.com/3110002/38238500-4e9d3598-372a-11e8-996f-8c6de6569ed9.png)

In new version its fine.
