### ISSUE TITLE
[MdMenu] broken on IE11

### ISSUE THREAD

**Issue by heymrcarter** [vuematerial/vue-material#1669]
### Steps to reproduce

Click on any md-menu, then click on one of the menu items
Click on another menu and its menu items

### Which browser?

Internet Explorer 11
Vue Material 1.0.0-beta-8

### What is expected?

The menus can open and close successfully

### What is actually happening?

The menus cannot dismiss, and in the console you see this error:

```
Object doesn't support property or method 'contains'
File: app.79bf427e.js, Line: 6, Column: 211676
```

### Reproduction Link

https://vuematerial.io/components/menu

**Comment by Samuell1** [comment]
For IE you should include polyfills.

More about IE polyfills here: https://github.com/vuematerial/vue-material/issues/1526
