### ISSUE TITLE
[MdTable] Unable to customize the header.

### ISSUE THREAD

**Issue by csjiabin** [vuematerial/vue-material#1675]
Unable to customize the header.I want to customize the watch head so troublesome that I give up.

**Comment by csjiabin** [comment]
>  <md-table-row>
        <md-table-head md-numeric>ID</md-table-head>
        <md-table-head>
          <md-menu md-direction="bottom-start">
            <md-button md-menu-trigger>Bottom Start</md-button>
            <md-menu-content>
              <md-menu-item>My Item 1</md-menu-item>
              <md-menu-item>My Item 2</md-menu-item>
              <md-menu-item>My Item 3</md-menu-item>
            </md-menu-content>
          </md-menu>
        </md-table-head>
        <md-table-head>Email</md-table-head>
        <md-table-head>Gender</md-table-head>
        <md-table-head>Job Title</md-table-head>
      </md-table-row>
      <md-table-row slot="md-table-row" v-dropdown="people" slot-scope="{ item }" :md-disabled="item.name.includes('Stave')" md-selectable="multiple" md-auto-select>
        <md-table-cell  @click="test" md-sort-by="name">{{ item.name }}</md-table-cell>
        <md-table-cell md-sort-by="email">{{ item.email }}</md-table-cell>
        <md-table-cell  md-sort-by="gender">{{ item.gender }}</md-table-cell>
        <md-table-cell md-sort-by="title">{{ item.title }}</md-table-cell>
      </md-table-row>
![_20180410160044](https://user-images.githubusercontent.com/20592953/38543866-60b44998-3cd8-11e8-9071-9321191f0894.png)

**Comment by Samuell1** [comment]
You cant use autogenerating rows with custom header.

**Comment by fcpauldiaz** [comment]
How autogeneration rows can be used? I tried using `<md-table-head>` but an empty header is rendered. @csjiabin did you fix this?
