### ISSUE TITLE
[MdButton] Stop using `<div>` within `<button>`

### ISSUE THREAD

**Issue by kdex** [vuematerial/vue-material#1680]
Version: `1.0.0-beta-8`

After rendering, an `md-button` will become an element of type `<button>`.

But if the `md-button` uses a ripple animation (which in turn uses `<div>` elements), the end result will be a `<button>` containing a `<div>`, which is invalid HTML markup.

Errors like these could easily be checked for pre-rendered sites by [validating](https://html5.validator.nu/) the HTML.

**Comment by VdustR** [comment]
related to #1461

**Comment by Samuell1** [comment]
@kdex from latest version beta-10 ripple now is using spans to generate ripple waves, but still ripple parent is still div

**Comment by marcosmoura** [comment]
The HTML5 validation is not a thing to consider these days. The div inside button is only because Firefox can't work with `display: flex` for buttons. So that's why we need that.

**Comment by kdex** [comment]
> The HTML5 validation is not a thing to consider these days.

@marcosmoura Please do correct me if I'm misinterpreting you, but did you mean to say that invalid markup is acceptable these days? If so, I couldn't disagree more. Markup bears implicit semantics that are important for screen readers, search engines and UX in general. Just because often times, "it renders just fine" doesn't mean it's justified to use it, as the visual rendering is just one aspect of what markup describes.

There's much more to it than what's visible on your screen.

Would you please re-open this issue until it's fixed?

**Comment by marcosmoura** [comment]
@kdex What I meant to say is that we shouldn't be that focused on the strict markup validation. Semantics and right markup is a must for several reasons, but I believe that there is more than just semantics to think here. 

Just because the button element doesn't "allow" divs inside does not mean that is not fine to use it. In fact we have to use not only for ripple effects but also to support other elements than just text inside buttons. If we think on Chrome it is OK to have only the button with a bunch of other inline children. But we also have to support IE, Safari, Firefox, UC Browser and many more. That's why we also have to use some other quirks to achieve what we want.

Regarding screen readers, in my personal tests, the buttons didn't have a problem with the text recognition and text to speech.

**Comment by kdex** [comment]
@marcosmoura If the problem is related to Firefox's `display: flex` behavior, is it out of the question to implement a solution using methods that predate flexboxes?

**Comment by marcosmoura** [comment]
Yep. It is.
For example the `md-tabs` and `md-list-item` components. They have a lot of flexibility that Flexbox solves for us.

But I'm trying to understand. Why are you complain about the Button markup? Is it just to make the final HTML code "valid"? Are you having additional issues apart for that?

**Comment by kdex** [comment]
@marcosmoura First of all, thanks for taking the time to discuss this. :) I appreciate it.

The website of one of my clients needs to be pre-rendered, which more or less requires me to use the very markup that `vue-material` puts into the DOM. Hence, I'm more concerned than usual with regards to what exactly I serve to clients, as the source that I serve is statically analyzable for search engines.

Search engines are generally free to define the set of metrics they respect when ranking websites. Bing, for instance, even went as far as integrating a markup validator into their webmaster console. It wouldn't be too far off for them to use the very same code as an input in their page rank as well; however minimal this factor may be, it would still be disadvantageous to us. The same principle basically applies to every other search engine.

Next, the Chromium team has recently begun integrating Lighthouse into DevTools. In addition to page speed and some SEO/PWA metrics, Lighthouse hints at problems with semantics/accessibility and computes a score based on the flaws it finds. Again, I don't think it would be too far off if Google were to spawn a puppeteer instance on their back-end and use Lighthouse scores as a metric for ranking pages; in fact, a subset of these scores are already used for this purpose.

Perhaps we have a different opinion here, but in all honesty I just doubt that it's particularly future-proof to rely on something that HTML doesn't even specify (or explicitly forbids); relying on non-standard hacks might be prone to undefined behavior, it might stop working at any time, and if we're particularly unlucky, the page rank might suffer as well. It would further not surprise me if major browser vendors didn't even care to regression-test non-standard behavior.
