### ISSUE TITLE
[MdSelect] menu width is hardwired to 280px

### ISSUE THREAD

**Issue by BigBadaboom** [vuematerial/vue-material#1681]
The `md-select` dropdown menu seems to be hardwired to a width of 280px (the default `md-menu` `max-width`).  It doesn't adjust to the size of the `md-option` content.

Test case: https://jsfiddle.net/td3cyjcr/2/

I was able to work around the problem by using the following CSS in my project. But it "fixes" all select menus, which may not be desirable in all cases..

```
.md-menu-content.md-select-menu {
  width: auto;
  max-width: none;
}

```

It would perhaps be nice if the `md-size` property was available on `md-select` also. Defaulting to `"auto"`.

**Comment by VdustR** [comment]
I think it's better to be auto as default, too.

**Comment by Samuell1** [comment]
Its because specs saying it should be max 280px 

https://material.io/design/components/menus.html?image=https%3A%2F%2Fmaterial.io%2Fdesign%2Fassets%2F1c6YlGcX30bO1M9SDmcIcnOYY6nQY6HdF%2Fspecs-menu-width-max.png#specs

**Comment by ErickPetru** [comment]
I believe you're misleading the interpretation of the **Dropdown Menu**: 

> Dropdown menus display a list of options, triggered by an icon, button, or action. Their placement varies based on the element that opens them.

Also, there are many images in the spec showing that the menu opened by a dropdown should follow the main element width. So that 280px `max-width` just doesn't makes sense in this context.

**Comment by Mashiane** [comment]
Thanks hey this helped!
