### ISSUE TITLE
[MdProgressBar] bug

### ISSUE THREAD

**Issue by UXMichael** [vuematerial/vue-material#1682]
### Steps to reproduce

Go to the demo Page. Open the "query" progress bar in code pen and remove the css part.

### Which browser?

Chrome

### What is expected?

progressbar works without additional css

### What is actually happening?

The progressbar isnt shown without the extra css

**Comment by VdustR** [comment]
![codepen_io_pen__editors_111](https://user-images.githubusercontent.com/29639463/38779808-25e36fe8-4100-11e8-861e-60572e9e06cd.png)

I got this from the demo without the css. Would you provide your exact in codepen and take a screenshot how it looks like?

**Comment by UXMichael** [comment]
I see in your html there are 2 md-progress-bar's . In your screenshot is only one. Remove one frome the html Code
