### ISSUE TITLE
[MdTabs] Height of the second tab not working

### ISSUE THREAD

**Issue by davidhoeck** [vuematerial/vue-material#1684]
Add `<md-tabs>` component to page and add two or more `<md-tab>` components. 

### What is expected?

the height should automatically adjust.

### What is actually happening?

The second tab always cuts the content at around 100-200px. 
If moving the tab to third or first position it is working.

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/pull/1552

**Comment by davidhoeck** [comment]
@Samuell1 will it be solved by the next beta release ?

**Comment by Samuell1** [comment]
@davidhoeck yes
