### ISSUE TITLE
Corrections to Breakpoints in online docs

### ISSUE THREAD

**Issue by thdoan** [vuematerial/vue-material#1685]
This is not a bug report for the framework, but for the online docs regarding the breakpoints table here:

https://vuematerial.io/ui-elements/layout

Assuming the breakpoints work similarly to Bootstrap, then the following corrections should be made:

- **xsmall**:  "maximum of 600px" -> "maximum of 599px"
- **small**:  "between of 600px and 960px" -> "from 600px to 959px"
- **medium**: "between of 960px and 1280px" -> "from 960px to 1279px"
- **large**: "between of 1280px and 1920px" -> "from 1280px to 1919px"
- **xlarge**: "bigger than 1920px" -> "1920px and larger"

This makes the breakpoint boundaries very clear (e.g., in its current form it isn't entirely clear whether 600px belongs to "xsmall" or "small" breakpoint).

**Comment by Samuell1** [comment]
Breakpoints for Material design are here, but iam not sure if its correct to make it 1px down. Because we support only breakpoints `up`, `only`
https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints

**Comment by thdoan** [comment]
> Breakpoints for Material design are here, but iam not sure if its correct to make it 1px down.

Usually when it states "600px breakpoint" it means that breakpoint begins at 600px and up to but NOT including the starting point for the next breakpoint. This makes sense since a breakpoint label like "small" cannot belong to more than one breakpoint range or else it would be confusing for the developer.

Note that I also recommend using "from/to" instead of "between" because "between" is [ambiguous](https://english.stackexchange.com/questions/7871/between-a-and-b-or-from-a-to-b): it could be interpreted as being inclusive ("between 600px and 960px" = 600-960) or exclusive ("between 600px and 960px" = 601-959).

**Comment by Samuell1** [comment]
@thdoan new breakpoints table they added :) 
https://material.io/design/layout/responsive-layout-grid.html#breakpoints

**Comment by thdoan** [comment]
Yeah, material.io has got it right -- it still needs to be revised on vuematerial.io for better clarity.
