### ISSUE TITLE
[MdSelect] not work

### ISSUE THREAD

**Issue by zhuyinjing** [vuematerial/vue-material#1687]
i use vue-material `^1.0.0-beta-7`
and i write my code : 
```
<md-field class="width-50">
                <label for="input_shape">input_shape</label>

                <md-select v-model="input_shape" name="input_shape" id="input_shape">
                  <md-option :value="item" v-for="(item, index) in inputshapeArgs" :key="index">{{item}}</md-option>
                </md-select>
              </md-field>
```
if i select `md-option `  the md-select doesn't work , it shows nothing ... actually  i already selected...
![2018-04-17 11-07-24](https://user-images.githubusercontent.com/25977997/38846555-92e20976-422f-11e8-9975-a62258a09d69.png)
what's wrong with my code??
thanks so much!!!

**Comment by zhuyinjing** [comment]
![2018-04-17 11-31-46](https://user-images.githubusercontent.com/25977997/38847201-02564df0-4233-11e8-8f84-e58a4b7dc0bb.png)
I want to select the first option by default, but there is no display of the value on select, but the first one is actually selected.

**Comment by VdustR** [comment]
Would you upgrade `vue-material` to latest beta and provide your code in Codepen or CodeSandbox?

**Comment by zhuyinjing** [comment]
ok...
[https://codesandbox.io/s/0ow377y17n](url)
i set a default value already,and it doesn't show on md-select

**Comment by VdustR** [comment]
Thanks.

I believe it has been fixed with commit https://github.com/vuematerial/vue-material/commit/01dfdfb2cf23adba1b48589ce61a164b601bd46c.

It's weird that this commit is before `1.0.0-beta-8` released.

I tested this case and it runs great with `dev` branch. It should be duplicated with #1262.

Before next release, you could fix it with followed codes temporary:

```vue
<template>
  <md-field v-if="show">
</template>

<script>
export default {
  data () {
    return {
      show: false
    },
  },
  mounted () {
    this.show = true
  }
}
</script>

**Comment by Samuell1** [comment]
Loading data for selects should be in `created` hook
