### ISSUE TITLE
`md-numeric` sorting doesn't work.

### ISSUE THREAD

**Issue by selway** [vuematerial/vue-material#1688]
## Browser
Chrome 65.0.3325.181

## Package
 - vue: https://unpkg.com/vue
 - vue-material: https://unpkg.com/vue-material@beta

## Source
https://vuematerial.io/components/table/
**Fixed headers** demo
`md-sort-by="id" md-numeric`

## What is actually happening?
 It works well in the guide page, but it doesn't work when I click  `Open on Codepen`  after. And it also doesn't work in my copy-code.

**Comment by VdustR** [comment]
Because that codepen use `beta` resolved as `1.0.0-beta-7` in that demo . Please use `1.0.0-beta-8` instead of it.

Related to #1353.

**Comment by selway** [comment]
Thanks! It's working, now.
