### ISSUE TITLE
[MdDatepicker] using format 'DD/MM/YYYY' exceeding stack size

### ISSUE THREAD

**Issue by Simillo** [vuematerial/vue-material#1689]
### Steps to reproduce
Setting `Vue.material.locale.dateFormat = 'DD/MM/YYYY'`.
Trying to select a date using `md-datepicker`.

### Which browser?
Chrome Canary.

### What is expected?
Be able to select a date.

### What is actually happening?
When selecting a date using the dateFormat is `DD/MM/YYYY` the watcher for `selecteDate` is again executed and then there is loop.

https://github.com/vuematerial/vue-material/blob/dev/src/components/MdDatepicker/MdDatepicker.vue#L88

### Reproduction Link
https://codesandbox.io/s/6398yyjqn

**Comment by terean-dspd** [comment]
the same with DD.MM.YYYY

**Comment by terean-dspd** [comment]
With  'DD.MM.YYYY' Chrome hangs after 3 or 4 selects in a row.
Firefox is not...

**Comment by DavidLambauer** [comment]
Yeah, same here. Firefox seems to work fine but after selecting a couple of dates in a row with format DD.MM.YYYY, it hangs up.

**Comment by DavidLambauer** [comment]
I just tried to use the master branch instead of the release. Does not work either.

**Comment by VdustR** [comment]
Try `dev` branch

**Comment by terean-dspd** [comment]
Bad lack...
Using dev branch, now I don't need to select dates 3-4 times. Chrome hangs up immediately...
Firefox is still ok...

**Comment by Samuell1** [comment]
Dont forget to rebuild dev branch, we dont provide rebuilded dist files with fixes.

**Comment by irineos1995** [comment]
**is this ever going to get fixed???**

**Comment by abhimanusharma** [comment]
@Samuell1 I have two date-picker in the same form, one of them is giving date value as object `Tue Jan 05 2021 00:00:00 GMT+0530 (India Standard Time)` and other is logging out `2021-01-05` The data from first datepicker is giving error while inserting in my db. I even added computed 
```
dateFormat: {
            get() {
                return this.$material.locale.dateFormat;
            },
            set() {
                this.$material.locale.dateFormat = 'yyyy-MM-dd';
            }
        }
```

but format is still giving format error.
