### ISSUE TITLE
[MdTable] single selection not working

### ISSUE THREAD

**Issue by safrashenkov** [vuematerial/vue-material#1691]
### Steps to reproduce

Clone single selection from example https://vuematerial.io/components/table

### Which browser?

Chrome 66.0.3359.117

### What is expected?

The `selected `object must contain the object of the selected user

### What is actually happening?

`selected `object is empty

### Reproduction Link

https://codepen.io/safrashenkov/pen/WJrjQK

**Comment by VdustR** [comment]
Because `@beta` is `1.0.0-beta-7` now.

Please use `1.0.0-beta-8` instead of it.

https://unpkg.com/vue-material@1.0.0-beta-8/dist/vue-material.min.js
