### ISSUE TITLE
[MdTextarea] Bug in documentation

### ISSUE THREAD

**Issue by vaishnavmhetre** [vuematerial/vue-material#1699]
Need to report a bug in the Vue material 1.0 beta documentation [doc link](https://vuematerial.io/components/input/). The text size and the look of the normal textarea input is buggy and need a look at it.

Be noted, the auto growing textarea works good. Hence shall work as a reference for comparison.

![input textarea - vue material - https___vuematerial io_components_input_](https://user-images.githubusercontent.com/14543290/39415089-c2e37f06-4c5c-11e8-8efa-27debd781329.png)

**Comment by VdustR** [comment]
#1156

**Comment by vaishnavmhetre** [comment]
The issue isn't solved. Yet both back-ref and this issues are closed.

**Comment by Samuell1** [comment]
@vaishnavmhetre its solved in dev branch.
