### ISSUE TITLE
[MdStepper] Bug in documentation

### ISSUE THREAD

**Issue by vaishnavmhetre** [vuematerial/vue-material#1700]
I would like to inform that the component md-stepper **cannot** be visited directly by entering [url -https://vuematerial.io/components/steppers](https://vuematerial.io/components/steppers) in the address bar. Shows blank window and the console is clear too.

![screenshot from 2018-04-30 10-29-45](https://user-images.githubusercontent.com/14543290/39415526-042b6dac-4c62-11e8-9cf1-925f6900ef13.png)

**Comment by Samuell1** [comment]
We know there was issue with infinite loop in latest release. In dev is fixed.

**Comment by vaishnavmhetre** [comment]
But I still can't visit directly.

**Comment by VdustR** [comment]
related to #1555
