### ISSUE TITLE
[MdTable] Add 3rd table sort state for reset?

### ISSUE THREAD

**Issue by jaminroe** [vuematerial/vue-material#1706]
Recently I was browsing the [Angular 2 Material framework's data table component](https://material.angular.io/components/sort/examples), and I noticed that they have a 3rd click state for their table's sort headers — A reset sort!

I thought this would be a very beneficial feature to have. I can imagine a user sorting a massive table of data, and then they want to get the table back to its original state. 

What do you all think?

![angular 2 sort header](https://user-images.githubusercontent.com/1559447/39602954-bb7f41d8-4ef4-11e8-929a-ed27121e4145.gif)

**Comment by Samuell1** [comment]
I think this will be impossible to implement because we have default as ASC and angular material is using default as empty string.
