### ISSUE TITLE
[MdTable] Prevent text selection on md-sortable

### ISSUE THREAD

**Issue by jaminroe** [vuematerial/vue-material#1707]
### Steps to reproduce

Click relatively quickly on a sortable table header

### Which browser?

System/browser info: https://whatsmybrowser.org/b/E6UHBGZ

### What is expected?

I wouldn't want the text to be selectable/highlighted if I'm sorting. 

### What is actually happening?

It's selecting the text when sorting. A bit annoying

### Reproduction Link

Happening on the demo pages: https://vuematerial.io/components/table/
![may-03-2018 17-27-15](https://user-images.githubusercontent.com/1559447/39603737-7f56bdc8-4ef7-11e8-91af-ebd3233b9641.gif)

### Suggestion
I recommend adding this SCSS

```
md-sortable {
    ...
   .md-table-head-label {
      user-select: none;
   }
}
```

**Comment by VdustR** [comment]
It should be able to be selected for copy & paste the table into Excel or other sheets softwares.

I think it's flexible enough to customize that you can add the style in your project.

**Comment by jaminroe** [comment]
@VdustR ah okay, agreed! 😊
