### ISSUE TITLE
[MdSteppers] Some clickable elements inside steps cause UI freeze on Chrome

### ISSUE THREAD

**Issue by kurbar** [vuematerial/vue-material#1708]
With version 1.0.0-beta-8 I've noticed that some clickable elements inside MdSteppers steps (e.g. MdCheckbox, MdButton) cause Chrome to freeze up the UI when clicking on them. The CPU usage jumps to ~60% and the only way to close the tab is to kill it in Chromes task manager.

This issue does not seem to exist in version 1.0.0-beta-7 nor on other browsers like Firefox.

### Steps to reproduce
- Include the whole VueMaterial library
- Add a MdSteppers component
- Add a MdCheckbox component
- Click on checkbox

### Which browser?
- VueJS 2.5.9
- Vue Material 1.0.0-beta-8
- MacOS Sierra 10.12.6
- Chrome 66.0.3359.139

### What is expected?
I am able to click the checkbox and the checkbox becomes active.

### What is actually happening?
Chrome freezes up the UI and CPU usage goes to ~60%.

### Reproduction Link
I was able to reproduce the issue on the VueMaterial docs page https://vuematerial.io/components/steppers > "Linear Steppers" > Click continue

**Comment by VdustR** [comment]
duplicated #1555
