### ISSUE TITLE
[MdInput] Outlined text field option

### ISSUE THREAD

**Issue by jaminroe** [vuematerial/vue-material#1709]
With Material 2 coming in the near future,[ Google has added the Outlined Text Field option to their components](https://material-components-web.appspot.com/text-field.html) (scroll down). I have been incorporating this into our Figma design components for "floating/persistent" input fields as well as for a general "search" field above elements. There are much more use cases for having an outlined text field as well.

With Google recently adding it to their components, would be awesome if you could add it as well. There are no other Material frameworks (that I know of) that have added this as an option. It's been a huge pain trying to override other frameworks as well.

Hopefully, others also see the added benefit of having this option, to also match the outlined textarea.

<img width="320" alt="material 2 outlined text field" src="https://user-images.githubusercontent.com/1559447/39643720-a5da10ce-4fa3-11e8-97af-9f22129761c7.png">

**Comment by Samuell1** [comment]
I closing this for now because of new material.io guidelines. This will be added in Vue Material 2.

**Comment by jaminroe** [comment]
Sounds good

**Comment by Samuell1** [comment]
@jaminroe you can see here they removed that one bottom line input and only filled and outlited exists :)

https://material.io/design/components/text-fields.html

**Comment by jaminroe** [comment]
Oh wow, you're right!! I didn't notice that! I love that, the older ones were difficult to see sometimes depending on the UI

**Comment by sbrin** [comment]
@Samuell1

how about to re-open this issue? 

can't live without outlined inputs

**Comment by megaroeny** [comment]
> @Samuell1
> 
> how about to re-open this issue?
> 
> can't live without outlined inputs

They already exist... What do you mean?
