### ISSUE TITLE
[MdFile] empty selection cause error

### ISSUE THREAD

**Issue by jan-johansson-mr** [vuematerial/vue-material#1711]
### Steps to reproduce
1. Choose a file from the file dialog (using md-file component)
2. Open file dialog again, but this time press "escape" or "abort" (not picking a new file)

### Which browser?
Using Chrome browser

Vue version 3.0 beta, Vue Material 1.0 Beta, Linux, Chrome

### What is expected?
The old file name that was picked should remain in field

### What is actually happening?
The old file name is replaced by [object Event] and an exception is thrown (Uncaught TypeError: Cannot read property 'constructor' of null)

### Reproduction Link
https://vuematerial.io/components/file (choose any of the file components - same behavior)

**Comment by Samuell1** [comment]
This is how file input works natively we cant detect if user clicked abort or clossed window.

**Comment by jan-johansson-mr** [comment]
Hi again,

The issue is not about detecting if the user clicked abort or closed the window. The issue is that there is an exception when the user chooses either action. The file picker on Mozilla doesn't throw exception if the user choose abort or closed, but MdFile does. So the report is more about how to strengthen the component, rather than introducing new features.

Thanks

**Comment by jan-johansson-mr** [comment]
Now for some reason I don't get the same behavior in Chrome. It's goofy. But thanks for responding!
