### ISSUE TITLE
[MdApp] with MdBottomBar and FAB

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1712]
Use a BottomBar with the App component and add a FAB to it.

Chrome Mobile 66.0.3359.126
Safari Mobile recent

Vue2
vue-material beta 8

The FAB should be placed above the BottomBar component with class md-fab-bottom-right or below the app header with class md-fab-top-right

### What is actually happening?
On mobiles the FAB gets overlayed by the BottomBar component. 
Or the FAB overlays the app header.
The height of the App component seems to be miscalculated.

**Comment by Samuell1** [comment]
Can you please provide reproductiong link?

**Comment by VdustR** [comment]
FAB position was not calculated, it's absolute. It's simply depended on it's parent.

I think it could be implemented like this:
https://codepen.io/VdustR/pen/xjpvLX
