### ISSUE TITLE
[MdTabs] md-active-tab style does not work

### ISSUE THREAD

**Issue by fengxuway** [vuematerial/vue-material#1715]
Md-tabs with attribute md-active-tab="tab-pages", tab content is right, but not found blue bottom border.
[code: md-active-tab example](https://codepen.io/fengxu/pen/wjpKmQ)

**Comment by Samuell1** [comment]
`md-active-tab` cant work when you using `md-sync-route` because active tab depends on your router, removing it it works normally.

**Comment by fengxuway** [comment]
Very thanks, worked for me.
