### ISSUE TITLE
[MdApp] rreturn is not defined

### ISSUE THREAD

**Issue by mgobishop** [vuematerial/vue-material#1727]
Following error with Beta 10:

[Vue warn]: Error in render: "ReferenceError: rreturn is not defined"

I look at my bundle and see 'rreturn' the following function:

function shouldRenderSlot(data, componentOptions) {
  rreturn(data && componentTypes.includes(data.slot)) || isValidChild(componentOptions);
}

**Comment by NightravenJames** [comment]
Thanks this will really help me alot
