### ISSUE TITLE
v1.0.0-beta-10.1 Release Doesn't Actually Contain rreturn Fix

### ISSUE THREAD

**Issue by aeolingamenfel** [vuematerial/vue-material#1735]
It seems as though the beta 10.1 (`v1.0.0-beta-10.1`) release does not actually contain the fix for the `rreturn` typo, despite citing it as the reason for the release (see the [release notes](https://github.com/vuematerial/vue-material/releases/tag/v1.0.0-beta-10.1)). You can see the `rreturn` is still present [here, in the file on that tag (line 30)](https://github.com/vuematerial/vue-material/blob/v1.0.0-beta-10.1/src/components/MdApp/MdApp.vue). 

I tried installing the release from NPM and had the same issue, and I confirmed in the repo that the typo still exists (see link above). 

I'm just trying to raise attention to that discrepancy, hopefully so it can get repaired!

**Comment by VdustR** [comment]
It's fixed in `dev`. I think it should be a publish accident. @marcosmoura would you publish again for this?

**Comment by danielwaltz** [comment]
Perhaps the unit test for this should be improved as well.

**Comment by marcosmoura** [comment]
I already published a new version. It was a problem on Travis CI configuration. My bad!
@danielwaltz Indeed!

**Comment by aeolingamenfel** [comment]
🙌🏻Thanks for the quick turnaround!
