### ISSUE TITLE
Last update to 1.0.0-beta-10.1 broke my solution: Reason is that package.json contains 'sh build/git-hooks/install.sh', a reference that's not recognized on my setup

### ISSUE THREAD

**Issue by jan-johansson-mr** [vuematerial/vue-material#1738]
### Steps to reproduce
1. npm update

### Which browser?
N/A

Vue material 1.0.0-beta-10.1

### What is expected?
Upgrade to 1.0.0-beta-10.1, not breaking my current project on earlier Vue material

### What is actually happening?
NPM outputs the following error:
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the vue-material@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Then when doing (Vue version 3.0.0-beta.10) **npm run serve**, I get:

These dependencies were not found:

* vue-material in ./src/main.ts
* vue-material/dist/vue-material.min.css in ./src/main.ts

To install them, you can run: npm install --save vue-material vue-material/dist/vue-material.min.css

That is, my project is broken.

### Reproduction Link
N/A

**Comment by VdustR** [comment]
did you try removing node_modules folder and lock file and reinstall again?

**Comment by marcosmoura** [comment]
I think you installed a wrong version. You are on vue-material@1.0.0.
Please update your version with npm i --save vue-material@1.0.0-beta-10.2

**Comment by jan-johansson-mr** [comment]
I've successfully updated to vue-material@1.0.0-beta-10.2, thanks!
As a side node, thanks four your excellent work!!
