### ISSUE TITLE
[MdAutocomplete] not selecting option

### ISSUE THREAD

**Issue by tudor33sud** [vuematerial/vue-material#1740]
### Steps to reproduce

I just tried to use autocomplete as specified in the docs. For me, it's unusable with both static options or promise based. Sometimes it works , sometimes it doesn't. 

1. Open autocomplete
2. Select one of the given option without typing anything

### Which browser?

Chrome Version 66.0.3359.139, Vue material  1.0.0-beta-10.1

### What is expected?

Option to be selected.

### What is actually happening?

Select menu dissapears, no option is selected.

### Notes
If I type a letter, and then I click the option, it correctly selects my option.
Also, when I add autocomplete in my page, I get a warning that required prop value is missing, although in the docs it's not mentioned anywhere.

### Reproduction Link
https://codesandbox.io/s/mjrq8o7zvy?module=App.vue   ( taken from your documentations )

**Comment by tudor33sud** [comment]
Yes, I went through the issues and saw that, but it was closed, so I thought reopen it might get attention again and fix it. One more thing, do you think it would work when bug will be fixed to use an autocomplete component in conjunction with md chips??

I have a usecase where I want to tag some event, and I'd like to select from list, search it, and also have multiple selection in forms of chips, so that the user will easily visualize and remove his selected tags. Do you think this would be appropriate? Or there is somethjing else that I didn't check.

Thank you

**Comment by tomasvanrijsse** [comment]
I'm also seeing this bug in my project.
And i did take a look at #1656 but [the codesandbox](https://codesandbox.io/s/l28mppv53z) posted by the OP still demonstrates this bug.
Even though the sandbox is using the latest version of vue-material.

**Comment by williamchong007** [comment]
@Samuell1 just tried this on https://codesandbox.io/s/mjrq8o7zvy?module=App.vue, still no luck
![qq20180516-173135-hd](https://user-images.githubusercontent.com/6198816/40109127-48d415b0-592f-11e8-8987-f490e5fd823c.gif)

**Comment by kfirufk** [comment]
Hi :) this bug still occurs even when I close the dev repository. any fix for that or  a workaround?

**Comment by VdustR** [comment]
@kfirufk it's not merged yet. You could try branch [fix/MdAutocomplete/option-selecting](https://github.com/vuematerial/vue-material/tree/fix/MdAutocomplete/option-selecting).

**Comment by pranayrauthu** [comment]
I am still seeing this issue with v1.0.0-beta-10.2.

**Comment by juakotorres** [comment]
vuetify >> vue material 

Take as example :D : https://vuetifyjs.com/en/components/autocompletes

**Comment by avdept** [comment]
Any update on this?

**Comment by atheodor** [comment]
poke^2

**Comment by Samuell1** [comment]
Its merged in dev branch you can use it guys.

**Comment by tomocrafter** [comment]
> vuetify >> vue material
> 
> Take as example :D : https://vuetifyjs.com/en/components/autocompletes

Really? I'm using the vue-material in my project now, but I'm gonna use the vuetify. Thanks for letting me know this library.

**Comment by fazega** [comment]
I still have the problem on the latest version of vue-material.

**Comment by frodonLD** [comment]
any update on this one plz? still having the same issue

**Comment by Darxeal** [comment]
poke
