### ISSUE TITLE
[MdAutocomplete] Cant select option when using highlighting

### ISSUE THREAD

**Issue by tomasvanrijsse** [vuematerial/vue-material#1748]
### Steps to reproduce

1. Click on an autocomplete field to open the options
2. Type in 'Aq' to filter down the results (and to be able to select an item, see #1740)
3. Then try to select on an option with the mouse or keyboard. The option won't be selected, instead this error is thrown `Error in render: "TypeError: this.searchTerm.toLowerCase is not a function"`

### Which browser?

Vue: v2.5.16 (latest)
Vue Material: 1.0.0-beta-10.2
OS: Windows 10
Browser: Chrome 66.0.3359.181

### Reproduction Link

https://codesandbox.io/s/y3w5v3w34x?module=App.vue

**Comment by VdustR** [comment]
Autocomplete is not support object yet, #1243

**Comment by tomasvanrijsse** [comment]
This code sample came right out of the docs. It is the example for "Custom Template". Perhaps it's better to remove it there if it isn't supported.

**Comment by VdustR** [comment]
I'm sorry about that. I'll send another PR for MdAutocomplete via another way without breaking changes asap. Thanks for your feedback.

**Comment by hakanozen** [comment]
Hey, any updates?

**Comment by phocea13** [comment]
Interested in updates too.

**Comment by timbmg** [comment]
+1
