### ISSUE TITLE
MdGutter layout with MdCard overflowing container width

### ISSUE THREAD

**Issue by tudor33sud** [vuematerial/vue-material#1752]
### Steps to reproduce

Add parent md layout div with md gutter and  2 md-layout-item divs using md-size-50.
If you put a card into each child div of size 50, horizontal scrollbar appears on the page. If I remove it, then I get no spacing between my cards. I think that according to docs md gutter shouldn't break width size of the layout.

Am I trying to use layout with cards the wrong way? 

### Which browser?

Chrome Windows Version 66.0.3359.170

### What is expected?

Have 2 cards spaced between themselves.

### What is actually happening?

I have 2 cards spaced between themselves overflowing the container div.

### Reproduction Link

https://codesandbox.io/embed/ljv5n3x09

**Comment by VdustR** [comment]
duplicated #1657
