### ISSUE TITLE
 [MdStepper] There should be a way to switch the order of the buttons

### ISSUE THREAD

**Issue by baristaGeek** [vuematerial/vue-material#1757]
Let's say I want to have `md-button-back` to the left of `md-button-continue`. I can change the styling, the label and lots of other things but not their order. It's way more intuitive to have the buttons ordered consistent with the direction they send you in the stepper.

**Comment by Samuell1** [comment]
Hey, can you please provide more info? What buttons you mean? Because steppers dont autogenerate buttons you can put them where you need.
