### ISSUE TITLE
Md-tabs-content height not updated on v-show

### ISSUE THREAD

**Issue by zevdg** [vuematerial/vue-material#1761]
### Steps to reproduce

put static content in a md-tab that is inside an element where v-show=false on page load
then set v-show to true

### Which browser?
at least chrome
vue-material-1.0.0-beta-10.2

### What is expected?
height of md-tabs-content should be large enough to show content

### What is actually happening?
height of md-tabs-content is 0 and therefore content isn't shown

### Reproduction Link
https://codesandbox.io/s/rl3j52n9pp (toggle switch to show content)

**Comment by Samuell1** [comment]
I recommded you to use `v-if` with that all works fine.

**Comment by zevdg** [comment]
yeah, I had already changed it to v-if in my own codebase.  :-)
