### ISSUE TITLE
[MdSpeedDial] Suggestion for improvement (md-speed-dial-content hide content and can block access to buttons or otherwise on screen)

### ISSUE THREAD

**Issue by jan-johansson-mr** [vuematerial/vue-material#1764]
### Steps to reproduce
1. Open documentation page at: https://vuematerial.io/components/speed-dial
2. At "Speed Dial positions", select either of the speed dial buttons to center
3. Hover and expand speed dial
4. The drop down buttons blocks access to one of the expanded speed dial buttons

### Which browser?
Using Chrome Version 66.0.3359.181

### What is expected?
The speed dial buttons to be accessible, regardless of content below

### What is actually happening?
The area (with class) 'md-speed-dial-content' is obscured by other controllers.

And in my case, it went the other away around, the 'md-speed-dial-content' obscures controllers on my page, even if the speed dial is not expanded. Suggestion is that the area (with class) 'md-speed-dial-content' is 'active' only when speed dial is active, and when active, the area overlaps anything on page so the speed dial expanded buttons are accessible.

### Reproduction Link
https://vuematerial.io/components/speed-dial

Thanks

**Comment by Pwntus** [comment]
Something like this seems to solve it:
```
diff --git a/src/components/MdSpeedDial/MdSpeedDial.vue b/src/components/MdSpeedDial/MdSpeedDial.vue
index 8570fec0..2bc4de0f 100644
--- a/src/components/MdSpeedDial/MdSpeedDial.vue
+++ b/src/components/MdSpeedDial/MdSpeedDial.vue
@@ -60,6 +60,7 @@
   .md-speed-dial {
     display: inline-flex;
     flex-direction: column;
+    z-index: 2;
 
     &.md-top-right,
     &.md-top-left {
diff --git a/src/components/MdSpeedDial/MdSpeedDialContent.vue b/src/components/MdSpeedDial/MdSpeedDialContent.vue
index 7ebf15ce..e2f07a32 100644
--- a/src/components/MdSpeedDial/MdSpeedDialContent.vue
+++ b/src/components/MdSpeedDial/MdSpeedDialContent.vue
@@ -49,7 +49,6 @@
     flex-direction: column;
     align-items: center;
     position: relative;
-    z-index: 2;
     transition: .3s $md-transition-default-timing;
   }
 </style>
```

As for obscuring underlying interactions I think it would be unwise to place those kinds of things under a speed-dial. It seems to be intended behavior to reveal the content by simply hovering the hidden content.

The specified documentation example should probably also be modified with a larger gap between drop-down selections and speed-dials to avoid this issue.

**Comment by VdustR** [comment]
@Samuell1 do you think this could be closed or not?
I don't think it's a bug.

**Comment by Samuell1** [comment]
@VdustR there is one more bug, if you hover under main button of speed dial it opens up other buttons but it should not because you dont hovered on toggle button

**Comment by jan-johansson-mr** [comment]
Thanks Samuell,

I think it is kind of serious if I have to move around my controls of the UI to make space for speed dial invisible area (e.g. to move other buttons away of the invisible area where the speed dial may expand [area (with class) 'md-speed-dial-content']).

The speed dial stuff should only take space when active (e.g. expanded), not when sitting and waiting to be used.
