### ISSUE TITLE
some components clones root in vue dev tools

### ISSUE THREAD

**Issue by Graziel** [vuematerial/vue-material#1777]
im using [vue dev tools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) and some of the vue-material components clones root

### Steps to reproduce
add component ie `<md-menu-content>`

### Which browser?
chrome

### What is expected?
single root

### What is actually happening?
root is cloned
![image](https://user-images.githubusercontent.com/5963584/40457717-3930227e-5ef8-11e8-92f8-5d7890b32261.png)

**Comment by VdustR** [comment]
https://github.com/vuejs/vue-devtools/issues/645

**Comment by Graziel** [comment]
yup that looks like its it
