### ISSUE TITLE
[MdTable] on md-selectable="multiple", @md-selected doesn't reliably fire

### ISSUE THREAD

**Issue by MystK** [vuematerial/vue-material#1786]
### Steps to reproduce
ISSUE 1
open https://codesandbox.io/s/lrz0np1m0q in a new tab(needs to be fresh)
select 1 row
notice the selected row isn't displayed below(incorrect behavior)
unselect 1 row
select 1 row
notice the selected row is displayed below(expected behavior)

ISSUE 2
open https://codesandbox.io/s/lrz0np1m0q in a new tab
open dev tools
select 1 row
notice that there is no console log(incorrect behavior)
unselect row
notice that there is a console log(expected behavior)

### Which browser?

Latest Chrome, Windows 10

**Comment by railken** [comment]
I still have the problem:

https://codesandbox.io/s/o7n643p6zq

![img](https://i.imgur.com/bH5PXbX.gif)

**Comment by aburai** [comment]
this is already fixed on dev branch

i think it is this change (this.$nextTick) in MdTable.vue

```javascript
      syncSelectedValue () {
        this.$nextTick().then(() => { // render the table first
          if (this.MdTable.selectingMode === 'single') {
            this.MdTable.singleSelection = this.mdSelectedValue
          } else if (this.MdTable.selectingMode === 'multiple') {
            this.MdTable.selectedItems = this.mdSelectedValue || []
          }
        })
      }
```

see also the change in watch

```javascript
      value () {
        this.syncSelectedValue()
        this.setWidth()
      }
```

hope that helps

**Comment by railken** [comment]
As you can see here: https://codesandbox.io/s/o7n643p6zq?module=package.json, the sample code has been configured to use the dev branch.

**Comment by aburai** [comment]
ok, i tested it with `yarn dev` in the table examples and it works, but in the sandbox it doesn't :(

**Comment by Samuell1** [comment]
@railken @aburai Because dist isnt recompiled in dev branch, then using github version will use same version old version.

**Comment by UnknownGuardian** [comment]
@Samuell1 This issue seems to be duplicated a lot, but this answer (which works!) took a bit of searching to get to. 

Could you build dev branch so we don't have to fork this just to build it?

**Comment by LeiwenL** [comment]
Hi, how about this issue ? 
VueMateriel is still in active development or is being deprecated? 
Thanks for your answer! 😄
