### ISSUE TITLE
[MdSnackbar] error upon closing when non-infinite, non-persistent

### ISSUE THREAD

**Issue by hiddenwaffle** [vuematerial/vue-material#1791]
### Steps to reproduce

I added a finite-duration snackbar without md-persistent=true and it prints an error to the console upon close: "Uncaught TypeError: Cannot read property '_vnode' of undefined
    at eval (MdSnackbarQueue.js?137b:17)"

You can see the behavior in my CodeSandbox link below and also by setting the docs App.vue snackbar duration to something other than Infinity. You can also see the behavior when removing md-persistent from the SnackbarExample.vue in the src.

I did not navigate away or remove elements or anything out of the ordinary other than kicking off the snackbar and waiting.
Perhaps I am misunderstanding the use of md-persistent, but I would still not expect an undefined error to be thrown the the console?

### Which browser?

This can be reproduced on the latest dev branch of the Vue Material examples when running in development mode, on Mac and in a CodeSandbox on Windows 7. Both using Chrome and Chrome Canary. Therefore the versions are Vue 2.5.13, Vue Material 1.0.0-beta-10.2.

### What is expected?

I think it should not error on close when md-persistent is not set.

### What is actually happening?

I believe that calls to createPromise() in createSnackbar() in MdSnackbarQueue.js should be updated to call with 3 arguments instead of 2. Please see PR #1792 

### Reproduction Link

https://codesandbox.io/s/6lk5p7w6n

**Comment by dakshshah96** [comment]
I'm still getting the same error:

```
Uncaught TypeError: Cannot read property '_vnode' of undefined
    at eval (vue-material.js?43f9:27001)
(anonymous) @ vue-material.js?43f9:27001
setTimeout (async)
(anonymous) @ vue-material.js?43f9:26998
createPromise @ vue-material.js?43f9:26989
createSnackbar @ vue-material.js?43f9:27027
mdActive @ vue-material.js?43f9:10507
run @ vue.runtime.esm.js?2b0e:3229
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:2977
(anonymous) @ vue.runtime.esm.js?2b0e:1833
flushCallbacks @ vue.runtime.esm.js?2b0e:1754
```

**Comment by Awais-cb** [comment]
getting this error too

**Comment by syonip** [comment]
For people getting this error, the fix exists in the dev branch.
To save you some time, this is what you need to run:

npm i "vue-material@vuematerial/vue-material#dev"

**Comment by FroeMic** [comment]
Same error

**Comment by szymsza** [comment]
getting this error right now
