### ISSUE TITLE
html and body styles conflicting with SharePoint Page Styles

### ISSUE THREAD

**Issue by joselarios** [vuematerial/vue-material#1797]
### Issue

We are finding that the html and body styles in the vue-material.css file are conflicting with default html and body styles in Microsoft SharePoint. From what we have been able to tell, the specific styles are:

html {
    box-sizing: border-box;
}

html * {
    box-sizing: 
}

body {
    font-weight: 400;
    line-height: 20px
}

body {
    font-size: 14px;
    letter-spacing: .01em
}

This list may not be exhaustive, though it is unlikely that other vue material styles are conflicting given that the rest are dependent on an "md-" selector. While these styles are conflicting with SharePoint styles, they are necessary for the look of various components. 

Unfortunately adding all these rules to the most parent element of a vue material component does not quite work. Would there be a way to apply these styles more individually, or at least not universally to the html and body elements?

### Which Versions?

Vue - Version: 2.5.16, Vue Material - Version: 1.0.0-beta-8

**Comment by Samuell1** [comment]
You can edit our scss files and apply styles to only element what you want, i think now its there not other way.
