### ISSUE TITLE
[MdDatepicker] the clear button on datepicker not work

### ISSUE THREAD

**Issue by hirohe** [vuematerial/vue-material#1803]
### Steps to reproduce

- set a datepicker with startDate as initial value.
```
<md-datepicker v-model="startDate" />
<span>{{startDate}}</span>
```

- click the clear button on datepicker
- and the `startDate` value is not cleared

### What is expected?

when i click the clear button, i think the `startDate` should be clear

### Reproduction Link

[codesanbox](https://codesandbox.io/s/l79jq8oqn9)

**Comment by VdustR** [comment]
This would be fixed with #1698

**Comment by sergeytkachenko** [comment]
Why you closed this issue? 
I have in my package.json :
 `"dependencies": {
		"vue-material": `"github:vuematerial/vue-material#dev"`
But after click to clear button -> v-model not changed

**Comment by Samuell1** [comment]
@sergeytkachenko because dev branch is not recompiled, dist is just same as latest release.

**Comment by Samuell1** [comment]
@brunogarcia dev branch, release depends on @marcosmoura

**Comment by Sotatek-HenryPham** [comment]
@Samuell1 

Currently, we don't have any way to handle the action clear, do we? If have please help me to handle this :( I need validate the required the input date.
