### ISSUE TITLE
Scrollbar on dialog content is not visible

### ISSUE THREAD

**Issue by PrismPrince** [vuematerial/vue-material#1804]
Scrollbar is not visible inside dialog content but it works. You can even click and drag it. Only the styling did not apply.

### Steps to reproduce

1. Make button to show dialog.
1. Add long content
1. Add `.md-scrollbar` class on content.

### Which browser?

Google Chrome

### What is expected?

- Scrollbar must be visible

### What is actually happening?

- Scrollbar is not visible on content

### Reproduction Link

Sample here:
https://codesandbox.io/s/z3nk3vvmlp

**Comment by Samuell1** [comment]
Its only chrome issue. Firefox doesnt have custom scrollbar

**Comment by PrismPrince** [comment]
Yes, the scrollbar is visible but not the styled one 😕
![image](https://user-images.githubusercontent.com/20511972/41070688-c06d1812-6a26-11e8-87f0-36f4396d58b9.png)

**Comment by Samuell1** [comment]
Yes because firefox doesnt support custom scrollbars. @PrismPrince

**Comment by PrismPrince** [comment]
I'm using Google Chrome

**Comment by Samuell1** [comment]
If you remove that custom class it works?

**Comment by PrismPrince** [comment]
If I remove the class `.md-scrollbar`, it appears the *unstyled/native* scrollbar.
If I add the class, it still works but *not visible*.

I'm using *Google Chrome Version 67.0.3396.79 (Official Build) (64-bit)*

**Comment by Samuell1** [comment]
Now iam not sure if this is bug with colors or something.

**Comment by PrismPrince** [comment]
I think .md-theme-default will fix it. 😸

**Comment by Samuell1** [comment]
Yes but we cant apply this class it needs to be with theme engine applied.
