### ISSUE TITLE
[MdTabs]how to remove tab from MdTabs?

### ISSUE THREAD

**Issue by zhangpy** [vuematerial/vue-material#1806]
I want to remove tab from MdTabs, is there any example to show how to do it?
I guess maybe md-active-tab.sync is an elegant way?

**Comment by Samuell1** [comment]
Please post your questions in our discord or slack channel. Issues are mostly for bug reports.
Follow this link: https://discord.gg/rgcmTtm

**Comment by zhangpy** [comment]
Thanks for your quick response!
