### ISSUE TITLE
[MdTable] Duplicate keys detected

### ISSUE THREAD

**Issue by Pit37** [vuematerial/vue-material#1807]
Create a table with the model, in the elements of which there is an "id" field. The md-table component uses the value of the id field from the record. In this model, we start two records with the same value in the "id" field, for example, 1. As a result, an error occurs:
[Vue warn]: Duplicate keys detected: '1'. This may cause an update error.

found in

---> <MdTable> at src / components / MdTable / MdTable.vue
         ...
          <MdTab> at src / components / MdTabs / MdTab.vue
            <MdContent> at src / components / MdContent / MdContent.vue
              <MdTabs> at src / components / MdTabs / MdTabs.vue
                ...
                  <MdContent> at src / components / MdContent / MdContent.vue
                    ...
                      <Root>

**Comment by Samuell1** [comment]
Can you please provide reproduction? If yes ping me i reopen it again.
