### ISSUE TITLE
[MdTable] select issue at first time to select

### ISSUE THREAD

**Issue by zhangpy** [vuematerial/vue-material#1814]
when I select any item instead of all at the first time, the select section under the table will not update. if I unselect any selected item. the select section will update
https://codesandbox.io/s/qx8kmwok76?module=App.vue

**Comment by VdustR** [comment]
duplicated #1786

**Comment by zhangpy** [comment]
I use dev branch and still can reproduce this issue. 
Maybe I will wait for new beta release to have another try. When will that happen?

**Comment by Samuell1** [comment]
@zhangpy you need to rebuild dev branch if you want to use it
