### ISSUE TITLE
[MdDialogAlert] Cannot use md-icon as part of content

### ISSUE THREAD

**Issue by echodrome** [vuematerial/vue-material#1815]
I have been trying to use Vue Material icons inside md-dialog-alerts but it does not seem to work even though it should accept HTML

### Steps to reproduce

Create a simple md-dialog-alert:

`<md-dialog-alert :md-active.sync="active" :md-content="message" md-confirm-text="Ok" />`

Pass the content through a method:

```
doWarning() {
  if (!this.test) {
    this.message = '<md-icon>warning</md-icon> This is a warning!'
    this.active = true
  }
}

```

### Which browser?

    "vue": "^2.5.2",
    "vue-material": "^1.0.0-beta-10.2",

### What is expected?

The warning icon should appear but instead only the warning text is showing up

**Comment by Samuell1** [comment]
Yes you cant use it in alert dialog, to use components, icons, images,... you need to use custom md-dialog.
