### ISSUE TITLE
[MdDrawer] options conflict: md-persistent / md-right / clipped

### ISSUE THREAD

**Issue by awc737** [vuematerial/vue-material#1817]
For example:
`<md-app-drawer md-permanent="clipped" md-right=true>`
the clipped drawer under the toolbar is still stuck left.

Also, md-persistent with md-right looks broken:
`<md-app-drawer md-persistent="full" md-right=true>`
It slides an empty drawer on the left, and the drawer on the right.

Also, it would be nice to reveal `"clipped"` with `:mt-active-sync`, instead of stuck with `md-permanent`.
I suppose using a layout column could achieve the same effect?

Thank you for this amazing framework!
If anyone has thoughts on the missing code, I would try to dig

**Comment by awc737** [comment]
Sorry for all the edits.. how do you clear that?

**Comment by Samuell1** [comment]
You cant clear that :D Can you make reproduction what you mean at codesandbox?

**Comment by flpgst** [comment]
There is some possibility of use `md-drawer md-permanent="clipped"` on the right of the screen?
Even is in the documentation that permant is pinned to the left edge. It would be great tp use it like a Right Side Panel.
