### ISSUE TITLE
[MdTable] Scroll to selected element

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1818]
It would be a nice feature, to be able to scroll to the selected element programatically.

**Comment by Samuell1** [comment]
You can make this with pure JS to scroll to element.

https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo

**Comment by mrwhy-orig** [comment]
I know, i just thought it would be a handy helper.
[](
https://codesandbox.io/s/r010prymo)
