### ISSUE TITLE
[Theme] --md-theme-default-primary and accent transparent on some components

### ISSUE THREAD

**Issue by nicolasreszka** [vuematerial/vue-material#1822]
### Steps to reproduce

I wanted to register a theme, so I did that (like in the example) : 

@import "~vue-material/dist/theme/engine";

@include md-register-theme("default", (
  primary: md-get-palette-color(green, 600), // The primary color of your application
  accent: md-get-palette-color(pink, 500) // The accent or secondary color
));

@import "~vue-material/dist/theme/all"; 

### Which browser?

Same thing happens on all browsers.

### What is expected?

The colors should be applied.

### What is actually happening?

Some components have a transparent color.

![screenshot_20180620_154517](https://user-images.githubusercontent.com/9148582/41662453-7f26f118-74a1-11e8-999c-298633dfe73a.png)

![screenshot_20180620_154631](https://user-images.githubusercontent.com/9148582/41662671-ea67f5bc-74a1-11e8-94ce-d60e840a2a78.png)

But when I deactivate the style in the inspector, the colors apply.

![screenshot_20180620_154813](https://user-images.githubusercontent.com/9148582/41662501-980554cc-74a1-11e8-92f1-b275f5a9281c.png)

![screenshot_20180620_154756](https://user-images.githubusercontent.com/9148582/41662518-a08342bc-74a1-11e8-956d-31436e9caa88.png)

Not all components have this problem, icons and text is fine, usually the problem is with background-color : 

![screenshot_20180620_155135](https://user-images.githubusercontent.com/9148582/41662656-dd8db8f4-74a1-11e8-9fb7-2f7fd9052a5b.png)

![screenshot_20180620_155456](https://user-images.githubusercontent.com/9148582/41662864-54dd5838-74a2-11e8-97ea-a991259f5afe.png)

### Reproduction Link
 https://codesandbox.io/s/vvv6p479x5
for some reason it works well on this editor, maybe because I use webpack ?

Thank you very much.

**Comment by Samuell1** [comment]
If you dont use webpack with .scss compiler then thats the issue.

**Comment by nicolasreszka** [comment]
Oh I see, I'm going to try that.
Thank you very much.

**Comment by theanhmx** [comment]
> If you dont use webpack with .scss compiler then thats the issue.

i used vue-cli to create the app, i guess webpack come with it by default but this issue still happen to me.
did i miss something else?
