### ISSUE TITLE
Disable global theme class on html tag

### ISSUE THREAD

**Issue by RichieMerchant** [vuematerial/vue-material#1824]
## Environment
vue: 2.5.16
vue-material: 1.0.0-beta-10.2
OS: MacOS 10.13.4
Browser: All latest

### Issue
I have VueJS running in a legacy codebase, hooking into id's. I trying to add material design forms to a page but the global theme class is being added to the `<html>` tag. This is causing the material design styles to bleed into the legacy code.

#### Question
Is there a way to turn of the global class style being added to the `<html>` tag?

**Comment by Samuell1** [comment]
Best is to fork vue-material and edit code that you dont need.
