### ISSUE TITLE
Updates broken on windows (git-hooks managed in NPM package at install time?)

### ISSUE THREAD

**Issue by fizxmike** [vuematerial/vue-material#1826]
### Steps to reproduce

Run: `npm update vue-material` on windows machine
I have 1.0.0-beta-7 currently installed

### Which browser?

N/A

### What is expected?

Package updates to latest release

### What is actually happening?
[This install.sh script](vue-material/build/git-hooks/install.sh) can't execute on windows. Why are developer hooks for git living in an NPM release? And why are sym links being added to .git directory locally, at install?
```
C:\Users\...\source\repos\...\Main\node_modules\vue-material>npm update vue-material

> vue-material@1.0.0 postinstall C:\Users\...\source\repos\...\Main\node_modules\vue-material
> sh build/git-hooks/install.sh

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-material@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Samuell1** [comment]
Do you tried to remove node_modules and install again?

**Comment by fizxmike** [comment]
Yes, removing node_modules and re-doing npm install "fixes" it... not sure why such a heavy handed move is needed for a simple upgrade. Is this just the nature of Node.js?

**Comment by Samuell1** [comment]
@fizxmike if you updated from beta there was bug with npm it was forcing to update it to 1.0.0 but that version doesnt exists
