### ISSUE TITLE
[MdSelect] remove transition

### ISSUE THREAD

**Issue by spaceywolfi** [vuematerial/vue-material#1829]
I personally dislike the md-select transition and would like it if there were an option to disable it.

personally i like this style of this md-select https://stasson.github.io/vue-mdc-adapter/#/component/select
(i don't use it, because its bloated ~ 32kb just for a select component)

**Comment by Samuell1** [comment]
That doesnt looks like Material Design select but native select and only input is restyled. Vue Material is built exactly according to the Google Material Design specs.

**Comment by spaceywolfi** [comment]
@Samuell1 my main request was to just add an option to be able to remove the transition, but if that is not in your interest than thats also fine for me
