### ISSUE TITLE
[MdTabs] router-link append prop doesn't work

### ISSUE THREAD

**Issue by dnewh** [vuematerial/vue-material#1830]
### Steps to reproduce

I created an md-tabs element with several md-tab elements inside of it and tried to add the "append" router-link prop but it doesn't seem to actually set the prop.

### Which browser?

Vue 3.0.0, Vue Material 1.0.0-beta-10.2

### What is expected?

Behave like router-link with the append prop set to true

### What is actually happening?

It behaves like a router-link without the append prop set

**Comment by Samuell1** [comment]
This will maybe fix tihis? #1651

**Comment by dnewh** [comment]
Which part exactly? It looks like there are issues with router link props but the suggested fix doesn't look like it's been implemented yet.

**Comment by dnewh** [comment]
I looked at that thread earlier and I don't see anything in there that
would help other than the part regarding changes to MdRouterLink props
which don't seem to have been implemented yet.

**Comment by dnewh** [comment]
![image](https://user-images.githubusercontent.com/10915817/42042992-f9181af0-7aba-11e8-9ead-bf87d3c1e1f1.png)

Here is an example of what gets rendered. The top, bracketed section is just a button wrapped in a router link, and the bottom section is the tabs. It looks like the append gets passed all the way down to the <a> tag in the md-tab.

**Comment by VdustR** [comment]
I think that props is not reactive yet.

**Comment by dnewh** [comment]
Is there a timeline on when that will get added in or any suggested
workarounds in the meantime?
