### ISSUE TITLE
[MdDaterpicker] There is no callback for clear date.

### ISSUE THREAD

**Issue by zeroarst** [vuematerial/vue-material#1831]
### Steps to reproduce

When manually clear the input value, or click the cross button, there is no callback event.
In my code I need to do something when there is no value in the datepicker field. ex. showing the error message immediately. 

I looked at the source code, only valid date will emit an event, means empty value does not emit.

### What is expected?

Have a callback event. maybe `onCleared`?

**Comment by VdustR** [comment]
duplicated #1803
