### ISSUE TITLE
[MdAutocomplete] Fire change event on clearing input field

### ISSUE THREAD

**Issue by mrwhy-orig** [vuematerial/vue-material#1837]
The change event should be emitted, when the user clears the input field with "x".

Emitting a change event

### What is actually happening?

Change event does not get emitted

**Comment by VdustR** [comment]
I tested and it works great with `1.0.0-beta-10.2`, `master` and `dev`.

Would you provide more information?

**Comment by VdustR** [comment]
Please fill the questions from the issue template.

Feel free to complete your question and reopen this if you still have problem.

Thanks.
