### ISSUE TITLE
[MdTheme] How to change the theme?

### ISSUE THREAD

**Issue by Shuo1030** [vuematerial/vue-material#1838]
Hello,
How can use the active theme in my project?
![image](https://user-images.githubusercontent.com/36422711/42083375-fde28cfc-7b8a-11e8-977b-8421d1c628de.png)
I'd like to change the color of the theme like what you have shown in the web page.If I click the different color,it will change.How can I do with that?

**Comment by Samuell1** [comment]
Hey, you can change theme with `this.$material.theming.theme = 'myTheme'`

**Comment by moshmage** [comment]
for anyone from the future and using vue typescript:

```ts
Vue.use(VueMaterial);
// ...
changeTheme(name: string) {
  (Vue as any).material.theming.theme = 'theme name';
}
```
