### ISSUE TITLE
Vue-material and exception at startup with Internet Explorer (Object.values causes the exception)

### ISSUE THREAD

**Issue by jan-johansson-mr** [vuematerial/vue-material#1842]
What to do:
Create a vue-material client, and execute on Internet Explorer...

Versions:
Vue: 2.5.16
Vue-material: 1.0.0-beta-10.2
OS: Windows
Browser: Internet Explorer (any)

I expect the Vue client to be the same as it is on Edge, Chrome, Safari, Firefox, etc.

But what is happening is that there is an exception with Internet Explorer at startup:

vue-material.js:

```
var VueMaterial = function VueMaterial(Vue) {
  (0, _material2.default)(Vue);

  Object.values(MdComponents).forEach(function (MdComponent) {   <--- Object doesn't support this property or method
    Vue.use(MdComponent);
  });
};

```

According to the link: [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values#Browser_compatibility), the `Object.value` is not supported on IE. It is however supported on all other browsers, including Edge.

I can add that I'm building the client with vue-cli (version 3.0.0-beta.10) and with Typescript profile, with tsconfig.json:

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    // "inlineSourceMap": true,
    // "inlineSources": true,
    "baseUrl": ".",
    "types": [
      "node"    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

Kind regards,
Jan

**Comment by VdustR** [comment]
duplicated #1582
