### ISSUE TITLE
[MdInput] Show maxlength counter only if required

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1847]
If the maxlength property of the input is set then a counter also appears below the input field. In majority of the use cases its desirable to have the maxlength field set but not always displayed. Can this counter display be made optional for maxlength property?

**Comment by nkoik** [comment]
`<md-field :md-counter="false">
<label>Maxlength with disabled counter</label>
<md-input v-model="disabled" maxlength="10"></md-input>
</md-field>`

At [Maxlength with disabled counter](https://vuematerial.io/components/input)

**Comment by zapping** [comment]
Thank you, that works fine!
