### ISSUE TITLE
[MdTabs] label is disappeared after switching tabs

### ISSUE THREAD

**Issue by pranayrauthu** [vuematerial/vue-material#1849]
### Steps to reproduce

- Setup a tabs component. 

- switch tabs by clicking on labels.

### Which browser?

Google Chrome Canary (v69.0.3484.0)

### What is expected?

tabs should be rendered properly.

### What is actually happening?

currently selected tab label is disappeared.

### Reproduction Link

[link](https://codesandbox.io/embed/0p6xz572rn)

**Comment by nkoik** [comment]
Canary is an unstable version of Google Chrome.

(Maybe it's not vue-material problem)
It seems that when md-ripple-wave transition goes off, the button content dissapears
