### ISSUE TITLE
How to use multiple themes ?

### ISSUE THREAD

**Issue by vivek1996** [vuematerial/vue-material#1858]
I want to  have dark and light themes for my site . May I know how to do this ?
The Answers for this question is available but It is for the older version . The method mentioned in those issues does not works . Please help me to solve this issue.

**Comment by dimasrismail** [comment]
Hi, you can check [this out](https://stackoverflow.com/questions/46730904/user-switchable-custom-themes-with-vue-js)

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/1838#issuecomment-401699165

Please next time use our discord, slack channel to ask this type of questions.
