### ISSUE TITLE
[MdTable] Change v-model when are rows selected, error on next dataset when select a row.

### ISSUE THREAD

**Issue by DouglasOGarrido** [vuematerial/vue-material#1864]
### Steps to reproduce

I copy the md-table example from the website. Follow this:
1. Click select all;
2. Click the button "Change dataset"
3. Click select all again.

And see the section below "What is actually happening?".

### Which browser?

Vue Material: last version (1.0.0-beta-10.2)
OS: Windows 10 64bit
Chrome: 67

### What is expected?

Clear the variable that contains selected items when dataset changed (v-model).

### What is actually happening?

The items returned on method "onSelect", are from dataset1 and dataset2. That is, is adding the items.

### Reproduction Link

https://codesandbox.io/s/p4kyk7zz7

**Comment by VdustR** [comment]
Use `:md-selected-value.sync=selected` instead of `@md-selected` and clear `selected` while `changePeople()`.
