### ISSUE TITLE
[MdTable] Reactive Selection requires next tick after data loaded

### ISSUE THREAD

**Issue by rayfoss** [vuematerial/vue-material#1866]
### Steps to reproduce

1. Load table data and selected at the same time asynchronously 

### Which browser?

Chrome Stable

### What is expected?

Selected options should be selected

### What is actually happening?

Selected options don't appear

### Reproduction Link
Case 1: Update at same time
https://codesandbox.io/s/lp7117wylq

Case 2: Give selection AOT
https://codesandbox.io/s/6j7n78mz6z

**Comment by Samuell1** [comment]
Can you test this with dev branch? There was some changes to this merged.

**Comment by VdustR** [comment]
I think I can't fix that because table get the value on the row created.
Do you have any idea?

**Comment by rayfoss** [comment]
@VdustR The codesandbox example works normally with the pull request

**Comment by VdustR** [comment]
@rayfoss great!

**Comment by rayfoss** [comment]
This bug also prevents onSelect from firing until something is unselected. I updated the Sandbox to show that. Even after the patch, the md-select event is extremely unreliable

https://codesandbox.io/s/6j7n78mz6z

-- We need more tests
