### ISSUE TITLE
[mdInput] <md-input v-model="number" type="number"> - turns type number to type string

### ISSUE THREAD

**Issue by MystK** [vuematerial/vue-material#1867]
The v-model type is a number, but when I modify the input, it changes the type to string.

https://codesandbox.io/s/w7vylk70l8

Is this intentional? It's an issue for me at the moment because I send this data to the backend, and it's expecting a number. If I don't edit the field, it sends it as a number. If I edit the field, it sends it as a string.

**Comment by Samuell1** [comment]
To convert v-model as a number you need to use: `v-model.number`
