### ISSUE TITLE
[MdAutocomplete] displayed behind the dialog

### ISSUE THREAD

**Issue by jiwan2004** [vuematerial/vue-material#1869]
![image](https://user-images.githubusercontent.com/3247990/43036046-4dc5402c-8d2c-11e8-928e-edb047f402d8.png)

I have checked previous bug. md-select has been fixed. if I use md- autocomplete I still get the same problem.
How to work it around? thanks

**Comment by Samuell1** [comment]
This should be fixed because code for autocomplete is same but you can use this workaround: https://github.com/vuematerial/vue-material/issues/1149

**Comment by Blquinn** [comment]
This still happens for me.

<img width="401" alt="Screen Shot 2019-06-11 at 4 45 19 PM" src="https://user-images.githubusercontent.com/6005812/59305571-7fcadf00-8c68-11e9-9248-59e1be7f3be5.png">

My markup:

```html
<template>
  <div>
    <md-dialog :md-active.sync="showAddMembersDialog">
      <md-dialog-title>Add members</md-dialog-title>

      <md-content class="dialog-contents">
        <md-autocomplete class="autocomplete" value="user" v-model="query" :md-options="searchUsers()"
                         @md-opened="addUser()">
          <label>Search</label>

          <template slot="md-autocomplete-item" slot-scope="{ item }">{{ item.username }}</template>
        </md-autocomplete>
      </md-content>

      <md-dialog-actions>
        <md-button class="md-primary" @click="setShowAddMembersDialog(false)">Close</md-button>
        <md-button class="md-primary" @click="setShowAddMembersDialog(false)">Save</md-button>
      </md-dialog-actions>
    </md-dialog>
  </div>
</template>
```
