### ISSUE TITLE
MD Backdrop Component

### ISSUE THREAD

**Issue by RoelZ** [vuematerial/vue-material#1873]
I understand this will be a groundbreaking feature, but I wonder if components like these are in scope of Vue Material since it aims to be lightweight.

https://material.io/design/components/backdrop.html

As it look from the MD documentation it simplifies user navigation and context related content.

**Comment by Samuell1** [comment]
Their new guides are for Material Design 2. When we make stable actual vue-material then we upgrade to new guidelines :)
