### ISSUE TITLE
More selective Theming

### ISSUE THREAD

**Issue by askdesigners** [vuematerial/vue-material#1879]
It would be nice to have an option to apply the theming to the whole app or not. Currently I'm wanting to use only a couple of components with the resting being custom elements. It seems like this is the goal of the library. However when I install it, it's overriding really basic things like link colors. Not great as I have button elements which are links that take the text color from the theme rather than the css I have written for it. 

As it stands now I will have to do some css jiggery to get it to work properly. 
For the rest it's super nice to work with.

**Comment by rbayley** [comment]
I am having the same issue.

I fail to understand why we have to :
import 'vue-material/dist/vue-material.min.css'

if we already do:

@import "~vue-material/dist/theme/engine"; // Import the theme engine
@include md-register-theme("default", (
  primary: $primary-color, // The primary color of your application
  accent: $secondary-color  // The accent or secondary color
));

// @import "~vue-material/dist/theme/all"; // Apply the theme
@import "~vue-material/dist/components/MdButton/theme"; // Apply the Button theme
@import "~vue-material/dist/components/MdCheckbox/theme"; // Apply the Content theme
@import "~vue-material/dist/components/MdField/theme"; // Apply the Toolbar theme

Maybe I am doing something wrong ?

**Comment by Samuell1** [comment]
@rbayley Because one is components related things and other is only theme related things like colors, backgrounds, border colors etc.

**Comment by askdesigners** [comment]
I don't think this should be closed @Samuell1 . You closed it based on the first comment rather than my initial request...

In order to not break simple things like link styling in my app I had to namespace my entire CSS using sass. Not awesome. 

The framework touts itself as an a la carte component lib but then assumes that you are using it for the entire app in it's sdf of CSS selectors... I don't think that it should touch styles for basic things like links and lists unless it's specifically enabled with a special class on the body or something like that...
