### ISSUE TITLE
vue-material.js?2e0c:13590  Uncaught TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by sergiomonteirodev** [vuematerial/vue-material#1884]
### Steps to reproduce

I created vue app using vue-cli and added vue-material dependency. I created a simple form using vue-material. I got this error from chromiun on firefox and page is blank:

TypeError: Object.values is not a function. (In 'Object.values(MdComponents)', 'Object.values' is undefined)

I tried to add polyfill for Object.values but it does not make any difference.

### Which browser?
chromiun on firefox, vue 2.9.6

### What is expected?
Load my app

### What is actually happening?
I got this error from chromiun on firefox and page is blank

### Reproduction Link
My app run in local server

**Comment by Samuell1** [comment]
Do you using node >7 ?

**Comment by Samuell1** [comment]
I am not sure what can cause this issue. Can you make reproduction of your code? I closing it for now.

**Comment by VdustR** [comment]
try babel-polyfill or other shimming
