### ISSUE TITLE
[md-select] Wrong selected options rendered in dynamic multiple md-select

### ISSUE THREAD

**Issue by Fabroanc** [vuematerial/vue-material#1885]
### Steps to reproduce

- Create a multiple md-select component.
- Bind a list with multiple maps via v-for in the md-option component
- Set the :value to the selected map and the content to the name attribute of the map
- Select multiple options

### Which browser?

Chrome and Firefox

### What is expected?

The selected options should be rendered correctly in the select menu.

### What is actually happening?

Just the first option (in my test case: Fight Club) is shown in the select menu. Even if you select multiple options, only the first option will be inserted. The problem effects just the visualization of the select menu, because the data binding to the selected value works correctly.

### Reproduction Link

https://codesandbox.io/s/1zwr96wl04

(UPDATE: Sorry, for some reason codesandbox toke my old test case. The new one should do it)

**Comment by nkoik** [comment]
Prop | Value
-- | --
value  |  String/ Number/ Boolean

Just put a string in value prop and not the whole object. `:value="m.name"`

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/1458
