### ISSUE TITLE
[MdFIle] Can't close file dialog

### ISSUE THREAD

**Issue by CaiJimmy** [vuematerial/vue-material#1887]
### Steps to reproduce

1. Click a MdFile component
2. You won't be able to close it. The dialog will keep popping out even you choose a file.

### Which browser?

Browser: Chrome 69.0.3497.14 (Official Build) dev (64-bit)
OS: Chrome OS 69.0.3497.14 (Official Build) dev (64-bit) 

I tried on my Windows 10 laptop with latest Chrome Dev, and same thing happened.

![image](https://user-images.githubusercontent.com/5889006/43488417-f77cc442-9519-11e8-8255-b7606a8c6000.png)

### What is expected?

User should be able to close the file dialog without choosing a file. Currently, **there's no way to close** as the file dialog blocks any attempt to close that tab. I achieved it by clicking "x" quickly and press CTRL + W

### What is actually happening?

No idea. I guess the latest Chrome update broke something as this didn't happen before, and I hadn't upgraded any dependencies of my site.

### Reproduction Link

I recorded a video: 
https://drive.google.com/open?id=1cuGqffxTtwiHoORfgbQuXpfHzYDjo-UL

**Comment by CaiJimmy** [comment]
I also tried it on a incognito window, and no difference. So I guess it is not caused by extensions that I have installed.

**Comment by Samuell1** [comment]
Maybe its fixed in dev? https://github.com/vuematerial/vue-material/issues/1677

**Comment by CaiJimmy** [comment]
@Samuell1 

Sorry for late reply.
I guess it's the same issue, so I'll just close this issue for now. 
Thank you :)
