### ISSUE TITLE
md-speed-dial-content is preventing underlaying content from pointer-events

### ISSUE THREAD

**Issue by arnegabriel** [vuematerial/vue-material#1888]
Just wanna mention, that the speed dial content is overlapping underlaying content also if speed-dial not opened.

Trough that the underlaying elements are prevented from getting any pointer-events.

In our project, we solved that by following scss, which I suggest to be added in vuematerial by default

.md-speed-dial-content {
  &.md-active,
  &:hover {

    .md-speed-dial-content {
      pointer-events: auto !important;
      display: inherit;
    }
  }

  .md-speed-dial-content {
    pointer-events: none !important;
    display: none;
  }
}

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/1764
