### ISSUE TITLE
MdCardMediaCover can't display external images because of CORS

### ISSUE THREAD

**Issue by ergofobe** [vuematerial/vue-material#1892]
https://github.com/vuematerial/vue-material/blob/fee150386afe472cb289cb8b18c1af636a6292b5/src/components/MdCard/MdCardMedia/MdCardMediaCover.vue#L47

This line of code is preventing the inclusion of external images as a md-card cover. crossorigin is only needed if CORS is to be enforced. Otherwise it should not be included.

**Comment by scriptcoded** [comment]
Is there any standard solution to this problem? Seems like an odd thing to have in the code...

**Comment by awls99** [comment]
This issue is weird 
sure @Samuell1, we don't get this issue in production, but it means I can't use md-text-scrim or md-solid in development environments because it arbitrarily assigns that option while calculating lightness, it's a very strange thing to do.

**Comment by alexm** [comment]
Unless there is something that I'm doing wrong, I do see this issue in production when using md-text-scrim.
