### ISSUE TITLE
vue-router: exact mode

### ISSUE THREAD

**Issue by rbayley** [vuematerial/vue-material#1896]
Hi,

I am rendering a List: 
```
<md-list>
  <md-list-item v-for="(item, section_key) in this.sections" :key="section_key" @click.native='onClick(section_key, $event)' :to="{ name: locale.id + '-' + section_key  }" :exact="false" :active-class="'md-selected'">
    <span class="md-list-item-text">{{ $t( section_key) }}</span>
  </md-list-item>
</md-list>
```
List is rendered as expected. Issue is with router.

1. Vue-router states  [exact prop](https://router.vuejs.org/api/#exact) default value is **false**. But vue-material makes it true unless specified like I did  :exact="false"
So, we are inverting vue-router natural behaviour. Is my observation correct or am I doing something wrong?

2. After settting the :exact="false" prop I noticed that the item was not highlighted as it should.
I noticed that "router-link-exact-active" and  "router-link-active" class were not added anymore.
The way I found to keep it active is by adding :active-class="'md-selected'" as [vue-router states ](https://router.vuejs.org/api/#exact-active-class)

Again, is this correct ?

**Comment by VdustR** [comment]
Vue Router would be fully supported on next release

https://github.com/vuematerial/vue-material/pull/1651
