### ISSUE TITLE
md-tabs: md-sync-route issue

### ISSUE THREAD

**Issue by rbayley** [vuematerial/vue-material#1897]
Hi,
This is my basic structure
```
<md-app>
  <md-app-toolbar class="md-primary" md-elevation="1">
	<!-- My toolbar content -->
  </md-app-toolbar>
  <md-app-drawer md-permanent="clipped">
	<!-- My drawer content -->
  </md-app-drawer>
  <md-app-content class="data-container">
    <router-view></router-view>
  </md-app-content>
</md-app>
```
Drawer content is specified here  #1896 

content render from router-view is as follows.
```
<md-tabs md-sync-route md-alignment="fixed">
  <md-tab v-for="(tab, key) in this.tabs" :key="key" :id="key"
	:md-label="$t(key)" :to="{ name: key  }">
  </md-tab>
</md-tabs>
<router-view class="content"></router-view>
```
contents are rendered correctly, but the tab is incorrectly highlighted.
I checked the rendered html and classes "router-link-exact-active router-link-active" are correctly set.

Not only I cant get the correct tab to be highlighted but also when I click on any other tab, although the html is set correctly setting classes "router-link-exact-active router-link-active" I have to click two times for the tab to get highlighted.

Hope I made myself clear.
What am I doing wrong ?

Thanks !

Ricardo

**Comment by VdustR** [comment]
Vue Router would be fully supported on next release

https://github.com/vuematerial/vue-material/pull/1651
