### ISSUE TITLE
Getting `TypeError: plugin is undefined` when trying to import VueMaterial

### ISSUE THREAD

**Issue by koehn** [vuematerial/vue-material#1901]
### Steps to reproduce

I can import certain vue-material components (MdCard, MdField, ...) but not others (MdDialog), and not the entire package (VueMaterial). I'm getting a `TypeError: plugin is undefined` when I do something wrong, but I'm not sure what it is I'm messing up.

### Which browser?

FireFox 61/MacOS

### What is expected?

VueMaterial should load

### What is actually happening?

`TypeError: plugin is undefined` on `Vue.use(VueMaterial)` or `Vue.use(MdDialog)`.

### Reproduction Link

Everything in my codebase is tagged [here](https://gitlab.koehn.com/bkoehn/carpool-ui/tree/vue-material-broken).

**Comment by Samuell1** [comment]
Hey, you need to import vue material like this: `import VueMaterial from 'vue-material'`
