### ISSUE TITLE
[MdDatepicker] Bug: Inside of <md-list-item> crashes on Chrome when using "DD-MM-YYYY" as "dateFormat"

### ISSUE THREAD

**Issue by DavidHtx** [vuematerial/vue-material#1907]
### Steps to reproduce

This bug only happens in Chrome, it behaves normally in Firefox:

I have placed the date picker as an element inside of a list, 
I have created a materialLocalConfig file to internationalize the vue-material elements,
and set the Vue.$material.locale to dutch (see sandbox) 
which changes the "dateFormat" from "YYYY-MM-DD" to "DD-MM-YYYY". 
Click on the date picker, select the 1st date of the month.
Chrome freezes.

### Which browser?

Vue 2.5.17, 
Vue-Material 1.0.0-beta-10.2.
Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### What is expected?

Selecting the date shouldn't freeze chrome, instead the datepicker should close normally as experienced in Firefox

### Reproduction Link

https://codesandbox.io/s/rr2688lmjm

**Comment by VdustR** [comment]
duplicated. #1689
