### ISSUE TITLE
[MdDatepicker] Can't disable a datepicker

### ISSUE THREAD

**Issue by matbarker** [vuematerial/vue-material#1916]
### Steps to reproduce

Set the disabled attribute on an md-datepicker component

### Which browser?

Version 68.0.3440.106 (Official Build) (64-bit)

### What is expected?

Clicking on the icon and text region of the datepicker should not open the date selection window

### What is actually happening?

The selection window opens and a new date can be picked

### Reproduction Link

https://codesandbox.io/s/6442j83o5r

**Comment by zapping** [comment]
#1759

**Comment by VdustR** [comment]
@zapping thanks.
