### ISSUE TITLE
[MdTable] `md-select` event would not work before a unselect action (or select all)

### ISSUE THREAD

**Issue by bin16** [vuematerial/vue-material#1921]
### Steps to reproduce

1. Go to https://codesandbox.io/s/qx8kmwok76?module=App.vue
2. Check a checkbox of one row except the on in header
3. `Selected: []` does not change (But the toolbar is well, it says `1 user selected`)
4. Uncheck the checkbox and check it again
5. `Selected: []` works now, with the selected data

ps: select all (check the checkbox in header) is well.

### Which browser?

- Chrome Version 69.0.3497.72 (Official Build) beta (64-bit)
- Firefox 63.0b1 (64 bit)
- Microsoft Edge 44.17751.1.0 / Microsoft EdgeHTML 18.17751 (why edge has two version number?)

All on Windows 10 Pro 17751.1

### What is expected?

fix the bug?

### What is actually happening?

not sure

### Reproduction Link

- https://vuematerial.io/components/table/ the Multiple section
- or https://codesandbox.io/s/qx8kmwok76?module=App.vue

**Comment by Samuell1** [comment]
Do you tried `md-selected-value.sync` prop?

**Comment by readwithyou** [comment]
Hi, 
I meet the same issue. Even with md-selected-value.sync, the issue still exists if I put the table around div/v-if tag, and not loading it first. I have to use div/v-show.  I see this issue somehow fixed in latest code. Is there any release plan?


Thanks

**Comment by VdustR** [comment]
duplicated #1786
