### ISSUE TITLE
[MdDialog] Programatically opening MdDialog - open is not a function

### ISSUE THREAD

**Issue by tomwake** [vuematerial/vue-material#1922]
Whilst reviewing other responses to issues here I've seen a solution for programatically opening dialog components that uses -
```
this.$refs[id][0]
```
When using this with the new beta version I get - this.$refs[id][0].open is not a function.

Has this method changed?

**Comment by Samuell1** [comment]
Yes, its changed now you can just simply pass prop with boolean value.
