### ISSUE TITLE
Imported component not rendering

### ISSUE THREAD

**Issue by dakshshah96** [vuematerial/vue-material#1925]
### Steps to reproduce

I have a main component `DashboardPage.vue`:

```
<template>
	<md-app>
		<nav-toolbar></nav-toolbar>
		<md-app-content>
			<md-card>
				<md-card-content>
					<p>Welcome to the dashboard!</p>
				</md-card-content>
			</md-card>
		</md-app-content>
	</md-app>
</template>

<script>
import NavToolbar from './NavToolbar.vue'

export default {
  name: 'dashboard',
  components: { NavToolbar }
}
</script>
```

The `NavToolbar` doesn't get rendered on the page at all. I have checked that it is imported by doing `console.log(NavToolbar)`.

`NavToolbar.vue` consists of the following:

```
<template>
	<div>
		<md-app-toolbar class="md-dense">
	    	<img class="dashboard-logo" src="../../assets/logo.svg">
	   	</md-app-toolbar>
	</div>
</template>

<script>
export default {
  name: 'NavToolbar'
}
</script>
```

However, the page renders correctly if I embed the content of `NavToolbar` directly on the page:

```
<template>
	<md-app>
		<md-app-toolbar class="md-dense">
      		<img class="dashboard-logo" src="../../assets/logo.svg">
    	</md-app-toolbar>
		<md-app-content>
			<md-card>
				<md-card-content>
					<p>Welcome to the dashboard!</p>
				</md-card-content>
			</md-card>
		</md-app-content>
	</md-app>
</template>

<script>
export default {
  name: 'dashboard'
}
</script>
```

### Which browser?

Vue: v2.5.17
Vue Material: v1.0.0-beta-10.2
OS: macOS Mojave Public Beta 7
Browser: Google Chrome 68.0.3440.106 (Official Build) (64-bit)

### What is expected?

The component should be rendered correctly even on importing them.

### What is actually happening?

The imported component is not rendered at all.

**Comment by dakshshah96** [comment]
cc @VdustR

**Comment by xxRockOnxx** [comment]
I think the `md-app` does not accept any other components other than what is stated in docs.

> The md-app component supports md-app-toolbar, md-app-drawer and md-app-content, which are aliases for md-toolbar, md-drawer and md-content respectively.
