### ISSUE TITLE
Md-Dialog cannot be made un-cancellable

### ISSUE THREAD

**Issue by yaaminu** [vuematerial/vue-material#1931]
In the documentation, it's stated clearly  that setting `md-close-on-esc="false"` or `"md-click-outside-to-close="false"` will prevent the dialog from being cancelled. I've done exactly that but the dialog still closes when I press <kb>ESC</kb> or click outside the dialog. 

I'm using the latest version from [here]( https://unpkg.com/vue-material@beta)` 
I'm testing on firefox 62(64bit) on Ubuntu 18.04.

**Comment by VdustR** [comment]
just pass `boolean` into it: `:md-close-on-esc="false"`, `:md-click-outside-to-close="false"`.

You were passing `string` without `:`.

More information about `v-bind` shorthand: https://vuejs.org/v2/guide/syntax.html#v-bind-Shorthand

**Comment by abhimanusharma** [comment]
@VdustR I am using md-dialog in a reusable component but when I press escape key it show error, 

```
 Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "active"
```

any solution for that?
