### ISSUE TITLE
[MdTable] selected

### ISSUE THREAD

**Issue by ismaeladriano** [vuematerial/vue-material#1933]
Não está funcionando o "md-selected", a primeira vez que é realizada a operação. Na segunda ela funciona perfeitamente. Atualizando o data.
Como exemplo pode ser visto a documentação: https://vuematerial.io/components/table/
- With auto select and alternate headers

**Comment by VdustR** [comment]
I don't understand Portuguese but I guess it's duplicated with #1786

**Comment by ismaeladriano** [comment]
I already made the changes #1786, but is still occurring

**Comment by ismaeladriano** [comment]
The documentation is problematic, as : https://vuematerial.io/components/table/

**Comment by VdustR** [comment]
Try it with `dev` branch. Documentation with fix is not published yet.
