### ISSUE TITLE
Table multi select not executing select function on first click

### ISSUE THREAD

**Issue by fredcarle** [vuematerial/vue-material#1936]
### Steps to reproduce

This is happening even in the docs. Click on a table row with `md-selectable="multiple"`.

### Which browser?

Tested on Chrome only

### What is expected?

I would expect the `@md-selected` fonction to be executed on first click of a row.

### What is actually happening?

The first time you click on a row, the fonction used for `@md-selected` isn't executed. Only on the second click it is actually executed.

### Reproduction Link

https://vuematerial.io/components/table/

**Comment by VdustR** [comment]
duplicated #1786
