### ISSUE TITLE
[MdDatepicker] The v-model is one day back

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#1938]
After selecting a date from the picker, even though the input shows the correct selected value, the v-model gets assigned a date object that is one day back. Probably this could be a time zone issue.

Instead of using the v-model directly, if any dummy date formatting is applied to it and if the formatted value is converted to date object and assigned back to the v-model then the exact selected date value can be had.

https://codesandbox.io/s/o4263xpn5q

**Comment by VdustR** [comment]
That's because of timezone. `Z` stand for `UTC +0:00`.
You can use [`date-fns`*(recommand)*](https://github.com/date-fns/date-fns) or [`moment`](https://github.com/moment/moment/) to format date with your timezone easily.

**Comment by VdustR** [comment]
or you can pass `String` to props `md-model-type` directly with next release(or branch `dev`)
https://github.com/vuematerial/vue-material/blob/8a438aee8eaf8fc566f730818824c697949cac90/docs/app/pages/Components/Datepicker/Datepicker.vue#L72
