### ISSUE TITLE
build size of vendor.js

### ISSUE THREAD

**Issue by Nejik** [vuematerial/vue-material#1944]
### Steps to reproduce

1. create new project with vue cli 3
2. install vue-material
3. build app

Build app with no importing vue-material js - vendor.js size - 113kb. Screenshot 1.
Build app with full vue material import "import VueMaterial from 'vue-material'" - vendor.js size - 393 kb. Screenshot 2.
Build app with one component imported "import {MdCard} from 'vue-material/dist/components';" - vendor.js size - 382 kb. Screenshot 3.

Seems importing single components are broken.

Screenshots:
1. https://clip2net.com/s/3X8IsGz
2. https://clip2net.com/s/3X8Iv0L
3. https://clip2net.com/s/3X8Ixi3

### Which browser?

any

### What is expected?

small  size of chunk.js

### What is actually happening?

big size of chunk.js

### Reproduction Link
-

**Comment by threaz** [comment]
Any update on this issue? Solution proposed in [#1413 (comment)](https://github.com/vuematerial/vue-material/issues/1413#issuecomment-425535449) doesn't solve it either.

**Comment by Samuell1** [comment]
Best will be to separate vendors to separate files to have less all packages in one file.

**Comment by amucunguzi** [comment]
@Samuell1 any solutions to reduce the build size? As @threaz mentioned, the proposed solution in #1413 does not solve the issue (actually seems to make it worse).
