### ISSUE TITLE
Internet Explorer issue with compatibility

### ISSUE THREAD

**Issue by sangemi** [vuematerial/vue-material#1948]
I installed vuematerial/nuxtjs 
bue in nuxtjs github page, I cannot find issues page.

I am using
> md-stepper, md-card, md-tooltip, md-select, md-snackbar
> and vue-smooth-dnd

in my page. It worked well in chrome but in IE,

> **object doesn't support property or method 'values'**

I think this bugs is related with https://github.com/vuematerial/vue-material/issues/165

**Comment by zapping** [comment]
Can you check this #1526

**Comment by Samuell1** [comment]
Duplicate of #1526
