### ISSUE TITLE
Script action to set a theme

### ISSUE THREAD

**Issue by DaniellMesquita** [vuematerial/vue-material#1954]
ZeroNet: http://127.0.0.1:43110/fmwk.bit/
WWW: http://0net.io/fmwk.bit/
>     switch(server_info.user_settings.theme) {
>     case "light":
>         body.innerHTML = '<style>lighttheme</style>' + body.innerHTML
>         break
>     case "dark":
>         body.innerHTML = '<style>darktheme</style>' + body.innerHTML
>         break
>     default:
>         console.log("Theming not supported. Please upgrade your ZeroNet version.")
>     }
> })

Instead of appending HTML style tags, how to set Vue Material light and dark themes?

**Comment by DaniellMesquita** [comment]
@marcosmoura
@coderberry

**Comment by aburai** [comment]
by example
Vue.material.theming.theme = 'default-dark'

look at docs/app/template/MainHeader.vue for theme-selector
and at docs/app/store/actions.js

**Comment by Samuell1** [comment]
Duplicate of #1838
