### ISSUE TITLE
Md-icon doesn't work with src

### ISSUE THREAD

**Issue by fjoalland** [vuematerial/vue-material#1956]
### Steps to reproduce

`            <md-icon class="md-size-2x" md-src="https://betravis.github.io/icon-methods/resources/chrome.svg" />
            <md-icon class="md-size-2x" md-src="../assets/img/logo/chrome.svg" />
            <img src="../assets/img/logo/chrome.svg" />
`
### Which browser?

Tested on Firefox 62 and Chromium 69.
Vue 2.5.17, Vue-material 1.0.0-beta-10.2

### What is actually happening?

This one : `<md-icon class="md-size-2x" md-src="../assets/img/logo/chrome.svg" />` doesn't work. But the two others work.

**Comment by Samuell1** [comment]
You need to use path like you have on website without going backwards in folders.

`<md-icon class="md-size-2x" md-src="/assets/img/logo/chrome.svg" />`
