### ISSUE TITLE
Textarea border incorrect appearance

### ISSUE THREAD

**Issue by gBragamonte** [vuematerial/vue-material#1958]
### Steps to reproduce

Access https://vuematerial.io/components/input
Go to **Errors and Messages**
Click in *Show Errors*

### Which browser?

Firefox Quantum v62.0.3 (64-bit)

### What is expected?

Border around textarea

### What is actually happening?

Border inside textarea

### Reproduction

![screenshot_1](https://user-images.githubusercontent.com/30661999/47447406-c8925e00-d793-11e8-88db-bab231af833c.png)

**PS.:** Also occurred in my application

**Comment by Samuell1** [comment]
This occurs only if you using browser native validation. But we don't support that because it will be broken like you can see. To fix this is best to use `novalidate` attribute on `form` element.
