### ISSUE TITLE
Ripple effect not working for Menu items on Firefox

### ISSUE THREAD

**Issue by Soletiq** [vuematerial/vue-material#1985]
### Steps to reproduce

https://vuematerial.io/components/menu

- Go there (using firefox)
- Look for this section [![Screenshot from Gyazo](https://gyazo.com/d03b86309c0659520aa5e93b67b9b658/raw)](https://gyazo.com/d03b86309c0659520aa5e93b67b9b658)
- Click that button "Bottom End" opening up the list
- Click each menu item in the list. No ripple effect happens on firefox. But it does work on Chrome.

### Which browser?

Firefox

### What is expected?

Ripple effect when clicking menu items.

### What is actually happening?

Nothing

### Reproduction Link

https://vuematerial.io/components/menu

**Comment by Samuell1** [comment]
![2019-01-29_10-35-22](https://user-images.githubusercontent.com/3110002/51898630-9ce5cc00-23b1-11e9-9969-2c47163be57a.gif)

For it works, can you specify what versions you using?
