### ISSUE TITLE
Unexpected button behavior using with electron api.

### ISSUE THREAD

**Issue by MairwunNx** [vuematerial/vue-material#1987]
### Issue Materials

> ![vuematerialbuttonissue](https://user-images.githubusercontent.com/39625750/50694346-b1e96c80-104a-11e9-90f1-89882b49d67c.gif)

### Describe the bug
> - Not correct behavior with material button in electron api.

### Steps to reproduce the behavior
> 1. Create VueJS project.
> 2. Install Electron and vue-material packages.
> 3. Add button to base html markup.
```
        <md-button class="md-primary md-raised">
          <p class="button-open-binary">OPEN SACRED BIN DIRECTORY</p>
        </md-button>
```
> 4. Just do double-click on button and see bug.

### Environment information
> - Vue-Material version [Latest]
> - System version: [Windows 10 x64]
> - Electron Api version: [4.0.0]
> - Chromium version: [69.0.3497.106]
> - Vue version: [3.2.2]

### Additional context
> - With `md-icon-button` not a problem.
> - If ripple disabled with `:md-ripple="false"` - it fix problem.
> - It bug also can be with elements what contains ripple effect.

**Comment by Samuell1** [comment]
Hey, if you remove `p` from button do you get same issue?

**Comment by MairwunNx** [comment]
@Samuell1 Hello! Yes, I still get the same behavior.

![vuematerialbuttonissue2](https://user-images.githubusercontent.com/39625750/50980706-68959300-150a-11e9-982b-2a210341e920.gif)

**Comment by Samuell1** [comment]
@MairwunNx i thinking that can be issue with chrome in electron, because if you test that in normal browser its working fine

**Comment by MairwunNx** [comment]
@Samuell1 However, in the browser there is such a bug. Because I have the opportunity to start a project without an electron.

![image](https://user-images.githubusercontent.com/39625750/50986516-13607e00-1518-11e9-86a0-a4b5eb4a994e.png)

![vuematerialbuttonissue3](https://user-images.githubusercontent.com/39625750/50986526-178c9b80-1518-11e9-82a8-d651fd466ef6.gif)

**Comment by Samuell1** [comment]
@MairwunNx do you getting same issue in our docs?

**Comment by MairwunNx** [comment]
@Samuell1 not, in docs i not get same issue. 😥😥

![vuematerialbuttonissue4](https://user-images.githubusercontent.com/39625750/50990835-342ed080-1524-11e9-84ae-301238275078.gif)

**Comment by Samuell1** [comment]
@MairwunNx can you specify what version do you using?

**Comment by MairwunNx** [comment]
@Samuell1 

> vue-material used version : `vue-material@1.0.0-beta-10.2`
> vue version : `3.2.2`
> electron version : `4.0.0`
> chrome version : `69.0.3497.106`

**Comment by Samuell1** [comment]
@MairwunNx how you have `3.2.2` version of vue? from what i know latest is 2.5.x

**Comment by MairwunNx** [comment]
Sorry, it CLI version, vue version `2.5.21`.

**Comment by Samuell1** [comment]
@MairwunNx did you modifying in your code something with css? If yes check if you dont changing something for button

**Comment by MairwunNx** [comment]
@Samuell1 hi! Absolute not, I just add use vue-material.

**Comment by Samuell1** [comment]
@MairwunNx but using `@beta` you using version 1.0.0-beta-7

**Comment by MairwunNx** [comment]
@Samuell1 lol, maybe it caused button bug? How do good link on style-sheet?

**Comment by Samuell1** [comment]
@MairwunNx just remove that `@beta`

**Comment by MairwunNx** [comment]
Yes!!! It stable work for button and other components what use ripple! Thanks @Samuell1! 😄

###### You can close the issue.
