### ISSUE TITLE
md-speed-dial Is there a way to control click events?

### ISSUE THREAD

**Issue by kimyearho** [vuematerial/vue-material#1989]
Hi
I want to control the click event of md-speed-dial. The manual does not show you how to control click events separately, but let me know if there's a way to open and close it in your script.

**Comment by kimyearho** [comment]
This is fixed with the following code.

```
this.$refs.fab.MdSpeedDial.active = false
```

**Comment by shamoons** [comment]
My `this.$refs` doesn't have a `fab`
