### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined for MdButton with a :to binding

### ISSUE THREAD

**Issue by TomHart** [vuematerial/vue-material#1990]
Button using `:to` throws 'TypeError: Cannot read property 'options' of undefined'

The link

    <md-button :to="{name: 'survey-edit', params: {id: item.id}}" class="md-icon-button md-raised md-primary">
        <md-icon>edit</md-icon>
    </md-button>

The root of the problem is `MdRouterLinkProps.js:5`, `context.$options` doesn't seem to be set.

### Which browser?

Vue version `"vue": "^2.5.21", "vue-material": "^1.0.0-beta-10.2"`. Using Ubuntu 16.04 and Chrome 71.

**Comment by Nolaan** [comment]
@TomHart check out #1998

**Comment by MirzetKameric** [comment]
Even when passing :disabled, this error appears in console
