### ISSUE TITLE
MdAppDrawer, MdAppContent, MdAppToolbar in PascalCase don't display inside MdApp

### ISSUE THREAD

**Issue by hastom** [vuematerial/vue-material#1992]
### Steps to reproduce

Forked vue-material quick start example,
Made simple MdApp with toolbar, content and drawer.
All components written in PascalCase

### Which browser?

vue: latest
vue-material: latest

Browser: Chrome 71

### What is expected?

App with toolbar, drawer and content

### What is actually happening?

Nothing

### Reproduction Link

https://codesandbox.io/s/o7qo94np5y

**Comment by zapping** [comment]
According to Vuejs docs

> In most projects, component names should always be PascalCase in single-file components and string templates - but **kebab-case in DOM templates**.

https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended

**Comment by hastom** [comment]
@zapping problem occurs in single-file component not in DOM template

**Comment by hastom** [comment]
@Samuell1 but according to the docs it's strongly recommended to use Pascal case in single-file components. Certanly i can fix it by renaming, but it should work in both cases

**Comment by Samuell1** [comment]
Yeah, thanks for PR!. I look at your PR later and if everything will be fine i merge it to dev.
