### ISSUE TITLE
Autocomplete blocks text input

### ISSUE THREAD

**Issue by oliver-ni** [vuematerial/vue-material#2010]
### Steps to reproduce

Visit https://vuematerial.io/components/autocomplete
Scroll down, click on a text field.
When the autocomplete dialog pops up, scroll down and you'll see it blocking the text field.

![Autocomplete dialog blocking text field](https://i.imgur.com/8fyVTPs.jpg)

### Which browser?

All browsers, I believe.

### What is expected?

The size and/or position of the box should change. It should get smaller if there's not enough space, or maybe move to the top of the box instead of bottom.

### What is actually happening?

It moves up to block the text field so you can't see what you're typing in it.

### Reproduction Link

https://vuematerial.io/components/autocomplete

**Comment by tomocrafter** [comment]
Just use the dev branch.
(well this bug fixed for using the dev branch. but I still have the problem of empty list bug and doesn't change v-model:value bug.)

**Comment by hugo-feijo** [comment]
Any update on this??
