### ISSUE TITLE
[MdDatePicker] Issue resolved but not updated library

### ISSUE THREAD

**Issue by Samurai016** [vuematerial/vue-material#2011]
I have the same problem of issue #1689.
In the latest version of vue-material the problem was not fixed.

I saw the problem is been fixed in src folder [(these lines are changed)](../blob/dev/src/components/MdDatepicker/MdDatepicker.vue/#L134-L178) but it was not deployed, so if I try to run a snippet using the latest version of vue-material, it doesn't work:

[![Sandbox test](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3l5w0m303)

Could some developer update the library or give me a way to rebuild/update my node module? Thanks.

**Comment by Samuell1** [comment]
Issue is fixed in dev branch.
