### ISSUE TITLE
<md-list-item to="/"> not working <to="/">

### ISSUE THREAD

**Issue by bigidea-kz** [vuematerial/vue-material#2022]
Thank you for your project.
I tried to use <md-list-item then = "/"> but it does not work, it gives an error "Error in render:" TypeError: Cannot read property 'options' of undefined "

my code

<md-list>
  <md-list-item to = "/">
    ......... 
 </ md-list-item>
</ md-list>

**Comment by AlvaroBrasilia** [comment]
Duplicate of #1978
