### ISSUE TITLE
[MdDatepicker] using format 'DD/MM/YYYY' exceeding stack size [re-opened]

### ISSUE THREAD

**Issue by irineos1995** [vuematerial/vue-material#2031]
### Reproduction Link

[https://codesandbox.io/s/6398yyjqn](https://codesandbox.io/s/6398yyjqn)

### Which browser?

- Google Chrome
### What is expected?

- To convert the date to the required format

### What is actually happening?

- Getting stuck in a loop and the whole browser freezes!
#1689 I don't know why this issue has closed while the bug still exists!

**Comment by Samuell1** [comment]
Issue was fixed in dev branch. To use it you need to fork it and rebuild it.
