### ISSUE TITLE
Button styles do not work correctly

### ISSUE THREAD

**Issue by alexReshetnyak** [vuematerial/vue-material#2050]
### Steps to reproduce

Just follow official 'Get Started' instructions

### Which browser?

all

### What is expected?

![Screenshot_1](https://user-images.githubusercontent.com/23313171/55683119-ce948980-5944-11e9-8e2c-019545ef6797.png)

### What is actually happening?

![Screenshot_2](https://user-images.githubusercontent.com/23313171/55683126-de13d280-5944-11e9-9776-9b1663b8e5b7.png)

### Reproduction Link

https://codesandbox.io/s/nn8lqyw0ym

**Comment by lubosmato** [comment]
Try adding `import 'vue-material/dist/theme/default.css'` into your main.js.

**Comment by alexReshetnyak** [comment]
@lubosmato  Thanks for the clue, but seems 'RIPPLE' effect still doesn't work for all buttons, and every time when i tap button it create new span inside <button></button>
![vue-button-dom](https://user-images.githubusercontent.com/23313171/55788581-3d96ed00-5ac1-11e9-9655-c8ee802f8652.png)

**Comment by lubosmato** [comment]
Unfortunately this is a bug. See https://github.com/vuematerial/vue-material/issues/2033

**Comment by nishantprajapti** [comment]
> Unfortunately this is a bug. See #2033

When is this going to work properly ?
