### ISSUE TITLE
Please mark the repo as no longer maintained

### ISSUE THREAD

**Issue by Phosphenius** [vuematerial/vue-material#2051]
As this repo does not seem to be under active development/maintenance any more, please mark it that way so people will no longer create legacy code.

**Comment by Samuell1** [comment]
@marcosmoura ping

**Comment by mxs42** [comment]
I wonder, what are the alternatives? I know about vuetify but for me it looks bloated honestly.

**Comment by rcosta-gcare** [comment]
@mxs42 I have been very impressed with Quasar framework.

**Comment by pscheit** [comment]
I didn't like vuetify, I was rooting for this! Because of the templates from creative-tim.com :/

Quasar - heard only good things but ... it looks... jeiks

**Comment by alexReshetnyak** [comment]
As for me mdbootstrap good enough

**Comment by kadegnon** [comment]
Someone on the Discordd channel proposed [Fomantic-UI](https://github.com/fomantic/Fomantic-UI)

**Comment by ndabAP** [comment]
A better idea would be to add administrators. There are 40 open pull requests with potentially good stuff.

**Comment by coinfork** [comment]
Agreed, we should keep vue-material going!

**Comment by lyziane** [comment]
This repo needs to stay alive.
I like using the form elements in vue-material and mdbootstrap for the rest.

mdbootstrap is good overall (the pro one) as a theme but I don't like how it doesn't use v-models in its form fields components. Also, the select is way better in vue-material.

**Comment by leganz** [comment]
I rly hope this repo will stay alive

**Comment by csteeg** [comment]
could you please add people like @hastom and @diadal as developers to this project? They seem to be actively developing further upon this repo. @hastom and @diadal... would it be an idea to fork away together if this repo is really dead?

**Comment by marcosmoura** [comment]
Hey guys.

It has been a long time since I last commented about Vue Material state. I had busy/crazy months that blocked me from work on any open source project. Since I cannot focus a 100% on open source and I have a daily job, I had prioritize things.

Like @Samuell1 said, the project is not dead. I started to work on it again and it won't take long to release a new version. Along with that I will include more developers to work on the project.

Cheers.

**Comment by hastom** [comment]
I would really like to help with developing, as I am using this lib at my work project. But the thing that really dissaponting me is lack of feedback.
May be the project needs something like a "core team" that can continuously maintain even if some members are too busy, sick, etc. I think that such a decision should be made as quick as possible. 
With all the appretiation to @marcosmoura and @Samuell1

**Comment by Phosphenius** [comment]
I second that. Some reassurance that the project will be maintained in the future would be very welcome. I don't mind by whom, I'd only like to be sure that someone will maintain and take care of it so that I can keep using it in my projects since I very much enjoy doing so. 
@marcosmoura I'd like to suggest that you appoint another maintainer with the right to publish new releases in case you're absent for a longer period of time.

**Comment by marcosmoura** [comment]
@hastom and @Phosphenius You are completely right! I left most of the things in my own hands, and at a difficult time, I couldn't handle them. This is kinda unacceptable and it'll surely change. As I said, it shouldn't take long to include new developers and also make new releases.

Cheers!
