### ISSUE TITLE
Md-menu :md-close-on-click doesn't work

### ISSUE THREAD

**Issue by szymsza** [vuematerial/vue-material#2052]
I use `md-menu` in a project and no matter how hard I try, menu always closes on click on `md-menu-content` children.

### Steps to reproduce

Use `md-menu` with some rich content and set `:md-close-on-click="false"` on `md-menu`

### Which browser?

- Vue: 2.6.5
- Vue Material: 1.0.0-beta-10.2
- Browser: Chrome 70.0.3538.77
- OS: Ubuntu 18.04.2 LTS

### What is expected?

Menu should stay opened even after click on `md-menu-content` children

### What is actually happening?

Menu closes automatically

### Reproduction Link

It can be seen even in documentation - if you uncheck both checkboxes at [https://vuematerial.io/components/menu](https://vuematerial.io/components/menu) (`AutoClose` section), menu still closes on item click.

**Comment by chrisjowen** [comment]
This still doesn't work, and the documentation https://vuematerial.io/components/menu still has issues. Note that it *sometimes* works but often will still close the menu
