### ISSUE TITLE
Cannot disable browser's autocomplete

### ISSUE THREAD

**Issue by gaspo53** [vuematerial/vue-material#2053]
When using autocomplete, if the name of the field matches a previous user's autocompletion saved data, it overlaps the input. Example, using the doc's countries autocomplete:

![image](https://user-images.githubusercontent.com/2250227/56395295-654c2a80-6210-11e9-9fdf-4bd247b46b28.png)

Couldn't find any information in the docs regarding this. If this is not a bug and has a workaround, close it.

Thanks

**Comment by gaspo53** [comment]
Was able to fix it by enclosing all inputs with <form autocomplete="off">.

Thanks

**Comment by igorbuts** [comment]
Not working for me
