### ISSUE TITLE
Card themes don't work

### ISSUE THREAD

**Issue by Strahinja** [vuematerial/vue-material#2055]
### Steps to reproduce

Use the attribute `md-theme="green-card"` along with `class="md-primary"` on a `md-card` to change the card background to green (example).

### Which browser?

Vue latest (2.6.10)
Vue Material latest (1.0.0-beta-10.2)
Opera 58.0.3135.132 on Windows 7 x64
Chrome 73.0.3683.103 on Windows 7 x64

### What is expected?

Card should have a green background.

### What is actually happening?

The card background is left with the default color value, which for the default theme is transparent.

### Reproduction Link
https://codesandbox.io/embed/40xo26vllw (open App.vue)

**Comment by marcosmoura** [comment]
That's not the way that theme works. You should create your theme first and then use the theme in your components. Please follow the guide [here](https://vuematerial.io/themes/concepts) carefully.

Thank you.
