### ISSUE TITLE
Md-select component is not submitting with FormData

### ISSUE THREAD

**Issue by safiullahsarhandi** [vuematerial/vue-material#2058]
### 

Thank you so much for creating such great package but i have an issue with md-select which need to be addressed, i.e. when im going to submit formData as it is not passing name prop.  thats why im unable to submit md-select selected value with formData please fixed this bug.

![Capture](https://user-images.githubusercontent.com/36722999/57073872-ca694b00-6cfb-11e9-931e-45ff061c3d6d.PNG)

![Capture](https://user-images.githubusercontent.com/36722999/57073749-7fe7ce80-6cfb-11e9-962c-66766bdc5f6a.PNG)

**Comment by aburai** [comment]
how do you serialize the form data?

your screenshots shows the name `promocode` but your html says the name is `item`

**Comment by safiullahsarhandi** [comment]
Actually item is md-select and promocode is md-input which i missed to show in html screenshot

**Comment by aburai** [comment]
and how do you serialize the form data or do you use a form element as parent and submit that?

try to create a codepen and we have a look at it
