### ISSUE TITLE
App drawer md-permanent="clipped" treated as md-permanent="full"

### ISSUE THREAD

**Issue by 4140** [vuematerial/vue-material#2070]
In `1.0.0-beta-11` the `md-permanent="clipped"` prop of `app-drawer` seems to have no effect.

Here is the example for `clipped` from docs - https://codesandbox.io/s/w21vv0rkl8?module=App.vue

Here is the very same example with `1.0.0-beta-10.2` - https://codesandbox.io/s/vue-material-clipped-oqvqc

**Comment by Chitzi** [comment]
Same for me, as soon I've made the update of dependencies I've found this problem.

**Comment by vPolyovyj** [comment]
I believe changes in [MdApp.vue](https://github.com/vuematerial/vue-material/blob/v1.0.0-beta-11/src/components/MdApp/MdApp.vue) caused this.

Have a look at changes mage in getDrawers:
1) https://github.com/vuematerial/vue-material/blob/v1.0.0-beta-10.2/src/components/MdApp/MdApp.vue#L76
2) https://github.com/vuematerial/vue-material/blob/v1.0.0-beta-11/src/components/MdApp/MdApp.vue#L84

In 11 child.data.slot == 'md-app-drawer-left' not 'md-app-drawer'
![Знімок екрана 2019-07-09 о 15 00 24](https://user-images.githubusercontent.com/13450012/60886507-d6710c00-a25a-11e9-98be-69779c3c03ef.png)

Hope it helps

**Comment by dragosct10** [comment]
Thanks, @johanfleury! We will close this issue.
