### ISSUE TITLE
Why thead is display none in table?

### ISSUE THREAD

**Issue by frndmr** [vuematerial/vue-material#2072]
Why my table heading is invisible. I searched on the web and i could not find anything.

https://hastebin.com/unulehuvaw.xml

Related part:
![image](https://user-images.githubusercontent.com/48316033/58190568-7b448380-7cc5-11e9-812c-8be62ae44ae2.png)

**Comment by aburai** [comment]
Link to hastebin does not work for me
but your syntax is correct.
Are you sure the `display: none` on thead comes from vue-material?

**Comment by frndmr** [comment]
> Link to hastebin does not work for me
> but your syntax is correct.
> Are you sure the `display: none` on thead comes from vue-material?

I am not using vue material anymore. Thanks.
