### ISSUE TITLE
[mdAutocomplete] Problem in autocomplete color (with array)

### ISSUE THREAD

**Issue by Chitzi** [vuematerial/vue-material#2073]
### Steps to reproduce
Go here https://vuematerial.io/components/autocomplete/
Open console (F12)
Select a color in the Custom Template section
Enjoy the error

### Which browser?
Chrome 74.0.3729.169
Firefox 67.0
Microsoft Edge

### What is expected?
A color to be selected

### What is actually happening?
Nothing and error in console

### Reproduction Link
https://vuematerial.io/components/autocomplete/

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/pull/1338
