### ISSUE TITLE
md-autocomplete BUG

### ISSUE THREAD

**Issue by KonesoN** [vuematerial/vue-material#2160]
the list disappears (does not always appear), all md-autocomplete
https://www.loom.com/share/92bccf0daf0c48cd9fa4837b482add14

URL: https://vuematerial.io/components/autocomplete

Chrome 79.0.3945.88

**Comment by christianopaets** [comment]
Why this is closed? You can easy recreate this issue on this page https://vuematerial.io/components/autocomplete
