### ISSUE TITLE
md-menu appears but closes immediately - 1.0.0-beta-12

### ISSUE THREAD

**Issue by mhio** [vuematerial/vue-material#2207]
### Steps to reproduce
Go to https://vuematerial.io/components/menu/  "AutoClose"
Select `closeOnClick`
Click BOTTOM END

### Which browser?
Chrome, Firefox, Firefox ESR 
vue-material 1.0.0-beta-12

### What is expected?
md-menu opens

What is actually happening?
md-menu appears briefly but immediately closes

Reproduction Link
https://vuematerial.io/components/menu/

**Comment by marqbeniamin** [comment]
done in beta-14 release
