### ISSUE TITLE
1.0.0-beta-13 Introduced bad md-dialog issue

### ISSUE THREAD

**Issue by jbeacham** [vuematerial/vue-material#2218]
The new prerelease (1.0.0-beta-13) introduced a bug for md-dialog. You can actually see it on the official vuematerial website in the dialog component section:

[https://vuematerial.io/components/dialog/](https://vuematerial.io/components/dialog/)

Click on any dialog example there and you will see the dialog appear and then move up and to the left. Tried both Chrome and Safari.

Switching back to 1.0.0-beta-12 solves the issue.

**Comment by JenGL** [comment]
same ase here #2209

**Comment by marqbeniamin** [comment]
done in beta-14 release

**Comment by maximiliannocker** [comment]
Hi,
I have the same problem in beta-15. The dialog appears in the top left corner and not in the center
