### ISSUE TITLE
Add custom cancel label prop for MdDatepickerDialog.vue

### ISSUE THREAD

**Issue by johnkristijan** [vuematerial/vue-material#2252]
Hi,
I am using Vue Material for a project where I need to support several languages.
It would be nice if I could decide the label/text for the _Cancel_ button myself.

Therefore I would like to suggest to add a `customLabel` property for the [MdDatepickerDialog.vue](https://github.com/vuematerial/vue-material/blob/dev/src/components/MdDatepicker/MdDatepickerDialog.vue) component where the default can be 'Cancel', see [@line 82](https://github.com/vuematerial/vue-material/blob/5f7182e49ee4423c3077bbcc4aea9016c8888e84/src/components/MdDatepicker/MdDatepickerDialog.vue#L82).

![image](https://user-images.githubusercontent.com/33238136/89778512-f209ae80-db0d-11ea-9fc3-399979801f36.png)

I am sure this is an easy fix and would help others in the same situation 👍

**Comment by Dan-Correia** [comment]
Hi @johnkristijan,

There's no need to pass it in as a prop on the component, since this is a setting that can be configured as you can see on the documentation [here](https://vuematerial.io/configuration/).

**Comment by johnkristijan** [comment]
Ah, yes, it was fixed in #2278, 2 months ago. Thanks.
