### ISSUE TITLE
[DOCS] Some text remains black in dark mode

### ISSUE THREAD

**Issue by Aveek-Saha** [vuematerial/vue-material#2258]
### Steps to reproduce
Visit the documentation website and change theme to dark or dark green.

### Which browser?
All browsers

### What is expected?
When the theme changes to dark, text should change to a lighter color for legibility.

### What is actually happening?
Some text changes to a lighter color while the rest remains dark, making it illegible against the dark background in dark mode.

### Reproduction Link
https://vuematerial.io/getting-started/

![Screenshot (32)](https://user-images.githubusercontent.com/31800695/90154254-880c3600-dda7-11ea-9d68-00250c255bf2.png)

**Comment by jnt0r** [comment]
I cannot reproduce this. For me, everything is correct in either dark and dark green. Using Firefox 80.0.1

**Comment by Aveek-Saha** [comment]
This seems to have been fixed, as I'm not experiencing this anymore either
