### ISSUE TITLE
MD select wrong value after submitted a form.

### ISSUE THREAD

**Issue by AbingPj** [vuematerial/vue-material#2261]
First of all,. thanks for the great project.

My issue is  this, After submitting a html form the value of md select is wrong,. this is my code:
```
  <md-select v-model="user.state" name="state" id="state" md-dense>
                        <md-option v-for="(item, index) in states"  :key="index"
                               :value="item.id"  >{{item.name}}</md-option>
   </md-select>
```

the value must be the state id but the backend received this:
![image](https://user-images.githubusercontent.com/38340100/90616966-b3c46b80-e240-11ea-8d7a-5eb4f3e26b52.png)
it received state name "District of Columbia",.   instead the id of state.

**Comment by mikimoresi** [comment]
v-binded value should mantain the id, are you able to parse model values with js to generate formdata and then submit this instead of using default html submit?

**Comment by AbingPj** [comment]
> v-binded value should mantain the id, are you able to parse model values with js to generate formdata and then submit this instead of using default html submit?

I`ve updated submission using Js formdata submit.
