### ISSUE TITLE
Make onfocus="blur()"

### ISSUE THREAD

**Issue by varunkumarmedam** [vuematerial/vue-material#2291]
In mobile it becomes clumsy to use. Add `onfocus="blur()"` to input field to disable for raising keyboard

**Comment by maxkopych** [comment]
Any news on this? Specially it's terrible with datepicker

**Comment by varunkumarmedam** [comment]
I solved like this,
`document
      .querySelector(".md-datepicker")
      .querySelector(".md-input")
      .setAttribute("onfocus", "blur()");`

**Comment by maxkopych** [comment]
Thank you I solved it similar way 
`<md-datepicker v-model="date" required :md-disabled-dates="disabledDates" @md-opened="$refs.mkDatePicker.$el.querySelector('input').blur()" ref="mkDatePicker"/>`
