### ISSUE TITLE
Add Datepicker placeholder option

### ISSUE THREAD

**Issue by EmanuelleViana** [vuematerial/vue-material#2303]
Datepicker component misses a placeholder option to be showed on the input

### What is expected?
A  text been showed in the datepicker like common inputs
![image](https://user-images.githubusercontent.com/12875299/107040615-3a90e480-679e-11eb-81f3-73ba7b0a522f.png)

### What is actually happening?
Nothing is showed on the initial datepicker input 
![image](https://user-images.githubusercontent.com/12875299/107040540-1b925280-679e-11eb-96c8-210414551720.png)

**Comment by sanchezpili6** [comment]
Have you tried using label? 
I believe something like this should work for what you want

`<template>
  <div>
    <md-datepicker v-model="selectedDate">
      <label>DD/MM/YYYY</label>
    </md-datepicker>
  </div>
</template>

<script>
  export default {
    name: 'LabeledDatepicker',
    data: () => ({
      selectedDate: null
    })
  }
</script>`

**Comment by sanchezpili6** [comment]
You could try using label.
I believe something like this should work for what you want

```
<template>
  <div>
    <md-datepicker v-model="selectedDate">
      <label>DD/MM/YYYY</label>
    </md-datepicker>
  </div>
</template>

<script>
  export default {
    name: 'LabeledDatepicker',
    data: () => ({
      selectedDate: null
    })
  }
</script>
```
