### ISSUE TITLE
Google translate destroying material-icons <i> tags

### ISSUE THREAD

**Issue by us31t** [vuematerial/vue-material#2322]
Hello I have searched and hope this is no duplicate. 

I have a issue with Chrome, that's why I do not use it, but folks who visit my site won't stop. :smile: :wink: 

When you use Chrome-Tranlate it destroys the material font icons. I have found this issue, which describes it very good. 
https://github.com/google/material-design-lite/issues/1721

I would assume from the other issue, adding the "notranslate" class resolves this issue. This is nuts! 
I think Chromes "feature" sucks... Kill Alphabet or give me shares! :smile: :hatching_chick:

**Comment by huffypiet** [comment]
@albertoaa , typically, <i> tags italicizes content, in a textual case, any text processor would destroy this tag if used for other purpose, safer to use <span> tags for icons in this case. I hope this helps
