### ISSUE TITLE
Can't install into Vue 3.0 project

### ISSUE THREAD

**Issue by juuunior-net** [vuematerial/vue-material#2331]
Created fresh Vue 3.0 project.

Trying to run: **npm install vue-material**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree       
npm ERR! 
npm ERR! While resolving: my-test-vue@0.1.0
npm ERR! Found: vue@3.0.11
npm ERR! node_modules/vue
npm ERR!   vue@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.5.0" from vue-material@1.0.0-beta-15
npm ERR! node_modules/vue-material
npm ERR!   vue-material@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by marqbeniamin** [comment]
Hi @juuunior-net ,
Thank you for using our framework! The project not support vue3 yet. 

If you want to help the project, you can open PR to [vue3 branch](https://github.com/vuematerial/vue-material/tree/dev-vue3)

**Comment by msoutopico** [comment]
Hi there, why is this ticket closed if the issue has not been fixed yet?

**Comment by Nacoma** [comment]
@msoutopico 

They probably should have mentioned that it's a duplicate of https://github.com/vuematerial/vue-material/issues/2277
