### ISSUE TITLE
Missing events on a datepicker input

### ISSUE THREAD

**Issue by larini** [vuematerial/vue-material#2340]
It is not possible to use events in the datepicker input, like @focus or @blur

Example:

`
<md-datepicker v-model="selectedDate" :md-open-on-focus="false" @focus="log('date-birth')" >
    <label>Date birth</label>              
 </md-datepicker>
`

**Comment by sonalikatara** [comment]
try @focusout.native and @focusin.native

Example : 

`
<md-datepicker v-model="selectedDate" :md-open-on-focus="false" @focusin.native="log('date-birth')" > <label>Date birth</label> </md-datepicker>`

**Comment by marqbeniamin** [comment]
@sonalikatara thank you for your help 🔥
