### ISSUE TITLE
Datepicker dialog stays open on loosing focus when Tab keys are used

### ISSUE THREAD

**Issue by sonalikatara** [vuematerial/vue-material#2343]
### Steps to reproduce
Go to this link [https://codesandbox.io/s/vue-material-labeled-example-forked-fl1lq?file=/App.vue](https://codesandbox.io/s/vue-material-labeled-example-forked-fl1lq?file=/App.vue)
 
Use TAB keys to move up and down the page, from one field to other.

### Which browser?
I tried on chrome on windows machine

### What is expected?
The datepicker dialog should close when it looses focus ( when the user moves to the previous or next field on the page using TAB key).

### What is actually happening?

The datepicker dialog stays open on loosing focus most of the time.

No.
### Reproduction Link
[https://codesandbox.io/s/vue-material-labeled-example-forked-fl1lq?file=/App.vue](https://codesandbox.io/s/vue-material-labeled-example-forked-fl1lq?file=/App.vue)

**Comment by marqbeniamin** [comment]
Hi @sonalikatara , thank you for using our framework! 🙏 You can help this repo if you open a PR with your solution 🙏

**Comment by arpansaha13** [comment]
Hi @marqbeniamin, I have made a PR (#2372) to solve this issue. Could you please review it?

**Comment by marqbeniamin** [comment]
Thank you, @arpansaha13 . Your PR is merged into the dev branch.
