### ISSUE TITLE
Request to add a github action

### ISSUE THREAD

**Issue by Jassi10000** [vuematerial/vue-material#2345]
I want to make a feature request to the repo

This is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by marqbeniamin** [comment]
Hi @Jassi10000, thank you for your interest, and sorry for the late response. Do you want to help us to improve this framework?

**Comment by marqbeniamin** [comment]
@Jassi10000 I will close this issue. Please write to me on our discord if you want to help with this framework: https://discord.gg/vuematerial
