### ISSUE TITLE
Remote pagination `md-update` not working

### ISSUE THREAD

**Issue by dland512** [vuematerial/vue-material#2347]
I'm using version `1.0.0-beta-15`.

### Steps to reproduce

I'm attempting to use remote paging on the `<md-table>` control and I can't get it to work. When I run it in my code, everything seems to work except that the `md-update` callback doesn't get called.

Unfortunately, the [example from the website](https://codesandbox.io/s/qvdft?module=App.vue) has some issues. The code uses `this.$http` which isn't defined so I changed it to use `fetch()`. Also the use of `<md-table-toolbar>` appears to make the pager control disappear. I created a [forked version here](https://codesandbox.io/s/vue-material-remote-pagination-forked-hyqjn?file=/App.vue) with those items fixed, but as you can see the paging doesn't work.

From what I can tell it appears that the callback supplied in `md-update` isn't being called when you click on the pager's previous and next buttons.

### Which browser?

```
Google Chrome | 96.0.4664.55 (Official Build) (x86_64)
Revision | 38cededc5d09b785d12203f1d3209aa6eb293e79-refs/branch-heads/4664@{#1090}
OS | macOS Version 11.6 (Build 20G165)
```

### What is expected?

Pager controls should show up and work. Also made the example code needs to be fixed.

### Reproduction Link
https://codesandbox.io/s/vue-material-remote-pagination-forked-hyqjn?file=/App.vue

**Comment by marqbeniamin** [comment]
Hi @dland512, Thank you for using our framework! This bug is solved now in the dev branch. 🙏
