### ISSUE TITLE
Unpublish version 1.0.0

### ISSUE THREAD

**Issue by mistic100** [vuematerial/vue-material#2348]
Please remove version 1.0.0 from NPM. Dependencies checkers like dependabot and snyk consider this version more recent that the last beta (righfully).

If the version cannot be unpublished at least please mark it deprecated  
https://docs.npmjs.com/policies/unpublish#what-to-do-if-your-package-does-not-meet-the-unpublish-criteria

**Comment by marqbeniamin** [comment]
Hi @mistic100, thank you for using our framework! We are working on a 1.0.0 stable version!
