### ISSUE TITLE
Remote pagination not working

### ISSUE THREAD

**Issue by asuarezbravo** [vuematerial/vue-material#2349]
Remote pagination doesn't seem to work. It always displays "Many" pages even though I passed the total number of items as per example. 
https://codesandbox.io/s/vue-material-remote-pagination-forked-hyqjn?file=/App.vue

**Comment by kami4ka** [comment]
Looks like the repository being abandoned

**Comment by marqbeniamin** [comment]
Hi @asuarezbravo, thank you for using our framework. We will come back with a solution. If you fix this, you can create a PR with your solution.

**Comment by huffypiet** [comment]
@marqbeniamin  noticed earlier link submitted was with issues about 'import module', had to change the structure a bit  and  found this to work, https://codesandbox.io/s/vue-material-remote-pagination-forked-olrxeh?file=/src/App.vue. This is currently under review
