### ISSUE TITLE
Font file cannot be downloaded

### ISSUE THREAD

**Issue by Zian502** [vuematerial/vue-material#2356]
### Steps to reproduce

- ![image](https://user-images.githubusercontent.com/26033663/156486529-394eb40f-0b99-4f0d-b8e2-6bf9764ef419.png)

### Which browser?

- chrome

### What is expected?

- Font file can be downloaded 

### What is actually happening?

- 

### Reproduction Link

-

**Comment by huffypiet** [comment]
Might be obscured due to CORS
