### ISSUE TITLE
How does this compare to Vuetify?

### ISSUE THREAD

**Issue by olavfosse** [vuematerial/vue-material#2357]
The first thing a user thinks when seeing this project is "how does it compare to Vuetify". Could you add a section in the README summarizing the differences and describing why one would prefer this package to Vuetify?

**Comment by AdmiralRazorbeard** [comment]
Looks like vue-material is dead and half baked. I've run into so many problems. Still it has been usefull for some time

**Comment by marqbeniamin** [comment]
@olavfosse @AdmiralRazorbeard  @slbayer 
Hi guys, thank you for using our framework. 🔥 We will add a section presenting the differences between all Vue frameworks! 🙏
