### ISSUE TITLE
Error on initial Examples page

### ISSUE THREAD

**Issue by leegee** [vuematerial/vue-material#2365]
From https://www.creative-tim.com/vuematerial/
links to GitHub https://github.com/vuematerial/vue-material
links to a repo, "Examples," with no Issues reporting tab: https://github.com/vuematerial/examples
links to Quick Start:  https://codesandbox.io/s/github/vuematerial/examples/tree/master/examples/quick-start?file=/index.js:0-22

![image](https://user-images.githubusercontent.com/512816/177344130-cb196f39-a945-4f82-9a05-eb2ada569937.png)

**Comment by rodrigoodev** [comment]
+1 

This happened to me too

**Comment by leegee** [comment]
I instantly switched to PrimeVue. It's not great, but the examples worked and allowed us to get the product to the customer in very little time.

**Comment by marqbeniamin** [comment]
Hi @leegee @rodrigoodev ,

Please check these examples, the complex products:
- https://www.creative-tim.com/product/vue-material-dashboard
- https://www.creative-tim.com/product/vue-material-kit
- https://www.creative-tim.com/product/vue-material-dashboard-laravel
- https://www.creative-tim.com/product/vue-argon-dashboard-laravel
