### ISSUE TITLE
Close date picker on blur

### ISSUE THREAD

**Issue by Ragnar-Oock** [vuematerial/vue-material#2371]
### Steps to reproduce

- add a date picker on a page with other focussable elements (inputs, buttons, links...)
- open the date picker
- click on or navigate to another focussable element

### Which browser?
Firefox and Chrome

### What is expected?
When the focus goes on elements outside the date picker it should close.

### What is actually happening?
When the date picker loses focus it stays open and only closes when the focus returns to the input again.

**Comment by marqbeniamin** [comment]
This will be solved with Arpansaha13 PR. I will merge it in the dev branch.
