### ISSUE TITLE
Datepicker issues (no tabindex property, no disabled property, after selecting date and hit tab focus will moved to browser address bar)

### ISSUE THREAD

**Issue by karldemetria** [vuematerial/vue-material#2375]
Need help on datepicker issues

1. tabindex property not working tabindex="-1"
2. disabled property not working disabled="true"
3. after selecting a date in datepicker and press the tab key, the focus will moved to browser address bar not to the next element inputfield. expected result should be, after selecting a date and hit a tab key it should be move to the next element field.

**Comment by marqbeniamin** [comment]
This will be solved with this PR. I will merge it in the dev branch. https://github.com/vuematerial/vue-material/pull/2372
