### ISSUE TITLE
when parent container width change the tab indicator display wrong width.

### ISSUE THREAD

**Issue by despird-zh** [vuematerial/vue-material#258]
original issue : [https://github.com/marcosmoura/vue-material/issues/248](url)

Hi marcosmoura, 

thanks for your update on this issue. today I tried 0.52 and I found another issue.
What happen:
When I embed the tabs into a card widget, the wrong width issue happens again, while if I move tabs out of card I will be ok.
http://codepen.io/despird-zh/pen/ENzXGO (I updated codepen)

![88ec9b17-4ebb-4927-baba-7db9bbc00d0c](https://cloud.githubusercontent.com/assets/9362558/21493708/dc663c70-cc47-11e6-8f61-c4f5f6fa6b0e.png)

**Comment by marcosmoura** [comment]
Sorry about that. The indicator rely on the parent size. I will change to another approach to make it more easy to detect the changes. Thank you

**Comment by despird-zh** [comment]
hi marcosmoura, 
seems this issue still exists. in 0.6.3

**Comment by marcosmoura** [comment]
Yes. I can confirm that. That's really strange. :(

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
