### ISSUE TITLE
Are tabs head swipable?

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#267]
Hi,
 Can you please take a look at this codepen https://codepen.io/zapping/pen/bBPyOz . 

 I tried added the tabs component. But when the no. of tabs increases it does not seem to have a scroll option on desktop browser nor can the tabs be swipped on mobile.

 Have I missed/overlooked something? Can you please clarify on how the tab heads can be navigated in such a case i,e when you have lots of tabs. It will be preferable to have the swipe option.

Thanks and you have a great set of components.

**Comment by marcosmoura** [comment]
This is not possible yet! I will develop this in the next versions.
For now, a possible workaround on mobile devices, is to add a custom css:
``` scss
.md-tabs-navigation {
  overflow: hidden;
}
```

Sorry about that. Thank you.

**Comment by zapping** [comment]
np. Thank you for the work around.

**Comment by igor-ribeiro** [comment]
I got it to work, only problem is the indicator.

**Comment by igor-ribeiro** [comment]
Got it!

![tabs-header-scroll](https://cloud.githubusercontent.com/assets/5148753/22560552/311c721c-e95c-11e6-9a69-610666d3c9fd.gif)

**Comment by zapping** [comment]
Oh, thats nice!! Does it mean that this will be available on the release sooner, thx.

**Comment by marcosmoura** [comment]
@zapping Yep!

**Comment by zapping** [comment]
Hi Marcos,
Can you please take a look at this pen, http://codepen.io/zapping/pen/bBPyOz , and let me know what I missed? The add button on top needs to be clicked twice for the first tab to appear and also the tab needs to be clicked for the content to appear. Same is the case with the delete button too.

Is there a way to customize the tab headers so that a small delete button can be added to each tab header to close it?

When I try to change the Add button to <md-button @click="addTab()">Add</md-button> the method of @click is not being called for some reason.

Thanks.

**Comment by zapping** [comment]
Hi Marcos,
 Please ignore the last one, realized that @click.native="addTab()" is the way to go.

Thanks.

**Comment by zapping** [comment]
Hi Marcos,
 Can you please check the first 2 comments on the post https://github.com/marcosmoura/vue-material/issues/267#issuecomment-280055906

Thanks.

**Comment by igor-ribeiro** [comment]
@zapping I found the problem. https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTabs/mdTabs.vue#L100 Adding/removing keys to an object like that it's not guaranteed the Vue will keep track of changes. I changed to `this.$set()` and `this.$delete` and it worked. @marcosmoura Where do you want me to push the fix?

For now you can hack it adding `ref="tabs"` to `md-tabs` and `this.$nextTick(() => this.$refs.tabs.$forceUpdate());` at the end of `addTab` and `removeTab`.

**Comment by zapping** [comment]
@igor-ribeiro thank you for the work around. On the other query can the tab header be customized so that I can add a close icon to it.

 Also can you let me know how to specify the font colors for the tab headers.

Thanks.

**Comment by igor-ribeiro** [comment]
@zapping For now, I guess neither one is possible.

**Comment by zapping** [comment]
@igor-ribeiro and @marcosmoura np guess will try your work arounds for now and wait for the updates.

It will be good if you can plan something for these customization because it will be helpful for dynamic tabs. Like along with the label in the header it would be nice to add some status indicators like * in case contents of a tab has been modified. If a closed/inactive record has been opened in a then an indicator/label that its read-only. So if its possible to give custom contents for the headers too then it will be cool.

You guys have a wonderful set of components with the materials guidelines. Thank you.

**Comment by marcosmoura** [comment]
@igor-ribeiro Can you create another PR for this issue?

**Comment by zapping** [comment]
Hi @igor-ribeiro / @marcosmoura 
 Can you please take a look at this one http://jsfiddle.net/zapping/d2141cwq/6/
A customization has been done to the tab to include a close icon with the tab header. The issue is the tab content does not seem to get removed when the close icon is clicked on the header. Also when the last tab is closed the tab content still remains even though the header has been removed. The unregisterTab() method is being called on the close icon click.

But when you click on the Delete button on top of the page the header and contents both gets deleted. Do you have any suggestion or is there a fix for it.

Thanks.

**Comment by igor-ribeiro** [comment]
@zapping You are unregistering the tab internally only and not modifying the `lstObj` and that's why the content is still present. You can emit an event when clicking on the button passing the index/id of the tab.

```html
<md-tabs @close="closeTab">
```
```js
closeTab: function (id) {
  this.lstObj = this.lstObj.filter((tab) => tab.id !== id);
}
```

**Comment by zapping** [comment]
@igor-ribeiro Thank you for tips, its worked out!

**Comment by zapping** [comment]
@igor-ribeiro / @marcosmoura  There is one more thing that you might want to look into or let me know if I used and messed a property. The tab has a property 'id' which says it needs to be unique for each tab. If its set like `:id="item.Id"` when creating tab in the template with a unique Id from the users data object then when the html is rendered the divs get the item.Id as in the image below
![tabcontentid](https://cloud.githubusercontent.com/assets/4123026/24452037/0002be2a-149f-11e7-89ed-1d654ace3a0f.PNG)

But when you delete tab(s) from the beginning or randomly from the middle the div ids of the deleted tabs seems to be getting reused or reassigned to the existing tab content div. Thereafter if the deleted objects are dynamically added back to the tab then the divs get duplicate or multiple ids causing issues. This pen https://codepen.io/zapping/pen/bBPyOz has been adjusted to delete tabs from the beginning and add new tabs to the end.

Though this does not happen if you delete tabs from the end and add new tabs to the end. Also this does not happen if the Id property is not used or not set at all when creating the tabs in the then template.

**Comment by igor-ribeiro** [comment]
@zapping That's because you are setting the new id based on the `lstObjt.length`
and delete de second, the new id will be 3 (length + 1), but you already have the id 3, you need to get the last id to set the next.
      
`var ind = this.lstObj[this.lstObj.length - 1].id + 1;`

https://codepen.io/igor-ribeiro/pen/WpaqBY?editors=0010

**Comment by igor-ribeiro** [comment]
@zapping Adding a `:key="obj.id"` solved the issue. https://vuejs.org/v2/guide/list.html#key

https://codepen.io/igor-ribeiro/pen/WpaqBY?editors=1000

**Comment by zapping** [comment]
@igor-ribeiro That solved it. Thank you for the doc link too. It has some suggestions on using the key in terms of performance.

**Comment by nishantbrevitaz** [comment]
> Got it!
> 
> ![tabs-header-scroll](https://cloud.githubusercontent.com/assets/5148753/22560552/311c721c-e95c-11e6-9a69-610666d3c9fd.gif)


@igor-ribeiro  how can i achive the scroll effect in small device urgent for  me ?

**Comment by igor-ribeiro** [comment]
@nishantbrevitaz they did a refactor on the project, I'm not sure this works anymore.

**Comment by sinisarudan** [comment]
Hi, is this still not solved?
Namely, even after adding the prop:
<md-tabs md-swipeable>, md-tabs looks like this.
tabs being cut-out, squeezed and not swipeable.
![image](https://user-images.githubusercontent.com/1769627/126728902-fc0a602a-075b-48d1-881c-7129444d56ed.png)
