### ISSUE TITLE
Swipe on Sidenav

### ISSUE THREAD

**Issue by igor-ribeiro** [vuematerial/vue-material#275]
I got it to work, still need to make it more flexible and think about a solution for multiple sidenavs. But first, do you want it?

![ezgif com-447b40bb5e](https://cloud.githubusercontent.com/assets/5148753/21566198/c3943d36-ce87-11e6-9007-2cd81f620b9e.gif)

**Comment by odranoelBR** [comment]
I will use / like it.

**Comment by marcosmoura** [comment]
Yeah! It will be a very good feature. But, first, are you using a custom library, like Hammer.js? Or you built the feature by hand?

**Comment by igor-ribeiro** [comment]
No library

**Comment by marcosmoura** [comment]
Nice. I would love to see a PR with this improvement.

**Comment by Ealhad** [comment]
So, @igor-ribeiro, still no PR ? I must say I am looking forward to it 🙂

**Comment by igor-ribeiro** [comment]
Sorry, guys. So busy at work. I will send a PR this week!
