### ISSUE TITLE
changeTab removed?

### ISSUE THREAD

**Issue by 0xFireball** [vuematerial/vue-material#283]
According to <https://vuematerial.github.io/#/components/tabs>, the `changeTab` method was removed recently.

Is this intentional or was it a mistake? Could you please consider re-adding the functionality for programmatically changing tabs?

Thanks.

**Comment by marcosmoura** [comment]
You shouldn't use the internal methods, because they can change. What you have to do to change the tabs dynamically is to use the `md-active` in each `md-tab`. This is the best way to change to a specific tab. I will try to create a method like that to the official API.

Thanks!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
