### ISSUE TITLE
md-table selecting the wrong elements

### ISSUE THREAD

**Issue by pablohpsilva** [vuematerial/vue-material#303]
md-table selected objects are wrong.

What I did:
Selected some objects and removed them. On the second selection, it looks like its getting the object n-1 instead of object on the n position.

n being the index of the element on the array.

![screen shot 2017-01-09 at 2 34 37 pm](https://cloud.githubusercontent.com/assets/2090635/21774213/f0006b62-d678-11e6-8a80-72170b4d8cac.png)

**Comment by pablohpsilva** [comment]
The problem could be on this [line](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTable/mdTableRow.vue#L72)

**Comment by marcosmoura** [comment]
I will recreate the pagination component and the logic behind the table selection as well. It's related to #192. Sorry about that.

**Comment by pablohpsilva** [comment]
Wow... That #192 is a nasty bug. That's OK @marcosmoura . I'll try to figure out (and help) some other stuff while you're busy on that LOL.

**Comment by marcosmoura** [comment]
Yep. That's why this needs to be rebuilt. :(

**Comment by kennygoff** [comment]
Hey @marcosmoura is there any update of the new table component? This selection bug in particular is blocking a project of mine. I have a temporary workaround for now by using my own custom table component, but I'd love to get a proper fixed version in 😄 . I can also see if I can write it myself and open a PR if that helps! Thanks!

**Comment by flybayer** [comment]
@marcosmoura I'm also curious on the status of this. Working on a new project that makes heavy use of tables. Looking forward to this!!

**Comment by pablohpsilva** [comment]
Fixing it right now, guys.

**Comment by pablohpsilva** [comment]
Hello everyone! I fixed the issue on PR #783 
Closing this issue now. Move comments to PR #783 page.
