### ISSUE TITLE
unable to control the expand state of the list item

### ISSUE THREAD

**Issue by e-cloud** [vuematerial/vue-material#310]
The current `md-list` composed with `md-list-expand` can display as a collapsable element.
But there is not other way to control the expand state except clicking on it.

Hope to have a way to control the expand state.

- What will it allow you to do that you can't do today?
  control the list expansion when route change
- How will it make current work-arounds straightforward?
  It seems no work-around now

**Comment by marcosmoura** [comment]
I didn't understand that issue. Can you describe it better?

**Comment by e-cloud** [comment]
Description updated.

**Comment by marcosmoura** [comment]
I see. There is a option but it's undocumented. I will add this to the website.

**Comment by chrisnorwood** [comment]
So is there an option to expand the list item programmatically?  I'm trying to figure out how to expand, and select an 'active' list item on route change (similar to the sidebar list the docs website)

**Comment by nicolas-bonnel** [comment]
Hi,

I managed to expand the list as follow :
 * add a `ref` property to your `md-list` element, for instance `<md-list class="md-dense" ref="menu">`
 * expand the item you want by calling `toggleExpandList()`. The item can be accessed in the `$children` property of your list. To expand the first item with my previous example : `this.$refs.menu.$children[0].toggleExpandList()`

Accessing `this.$refs` is common in vue-material example, I don't know if accessing `$children` is not too hacky, perhaps a `children()` method would be nice on md-item component.

**Comment by filipesarturi** [comment]
Waiting for the prop implementation that defines the expansion list state...

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
