### ISSUE TITLE
md-speed-dial improvement

### ISSUE THREAD

**Issue by korylprince** [vuematerial/vue-material#319]
The new speed dial is great!

However it is missing a particular feature.

From the spec:

> The floating action button can fling out related actions upon press. The button should remain on screen after the menu is invoked. Tapping in the same spot should either **activate the most commonly used action** or close the open menu.

Currently you can't have the speed dial to open on click, but have the morphed button become a clickable action, it only works to close the speed dial.

If you're willing, I'd like to add this feature in a new branch.

**Comment by korylprince** [comment]
As far as implementation, I'm thinking to either pass a custom event when a click happens with the speed dial open, or using a prop to pass an event handler. I'm leaning towards the prop method. 

What are your thoughts?

**Comment by marcosmoura** [comment]
Hi @korylprince 

I didn't get it. Have you tried the `@click.native` modifier on the md-fab-trigger?

**Comment by korylprince** [comment]
@marcosmoura So that didn't work (the click handler takes over the md-fab-trigger action), but putting a `@click.native` on the underlying md-icon totally works. Thanks for the clue! I'll post my working implementation for future users:

```
<md-speed-dial md-open="click" md-mode="fling" class="md-fab-bottom-right">
	<md-button class="md-fab" md-fab-trigger>
		<md-icon md-icon-morph @click.native="$router.push({name: 'deviceCreate'})">computer</md-icon>
		<md-icon>add</md-icon>
	</md-button>

	<md-button class="md-fab md-primary md-mini" @click="$router.push({name: 'modelCreate'})">
		<md-icon>grid_on</md-icon>
	</md-button>

	<md-button class="md-fab md-primary md-mini" @click="$router.push({name: 'userCreate'})">
		<md-icon>account_circle</md-icon>
	</md-button>
</md-speed-dial>
```

**Comment by marcosmoura** [comment]
Please note that `md-open="click"` `md-mode="fling"` are the default options, so you can omit them. :)

**Comment by korylprince** [comment]
Fixed! Thanks.

**Comment by korylprince** [comment]
I spoke too soon. This doesn't actually fix the problem.

It appears to possibly be a race condition, or the click event on the icon only works on a very small area.

I'm not sure what exactly is happening, but it very rarely works on the first try. You can click very rapidly and move the mouse over the Fab, and eventually it will do the native click handler, but it is by far a working solution.

Therefore I'll work up a PR for you to check out.
