### ISSUE TITLE
Snackbar disable timeout on hover.

### ISSUE THREAD

**Issue by ozgureffe** [vuematerial/vue-material#321]
Hi Marcos. Thank you so much for your work. Believe me, you are the savior.
I love vue-material and I am very pleased that it is getting better day by day.

I will be very happy if you fix/implement and stop the snackbar counter when hovering.

Thank you so much.

**Comment by marcosmoura** [comment]
That would be a great addition. I will try to prioritize that. Thank you!

**Comment by igor-ribeiro** [comment]
Got this, want a PR?

**Comment by marcosmoura** [comment]
@igor-ribeiro Always, if you can. :)
