### ISSUE TITLE
Selection controls size

### ISSUE THREAD

**Issue by Fogerty** [vuematerial/vue-material#340]
Thank you for doing all of this :)

Will there be a size option for selection controls?
- Radio
- Switch
- Checkbox

**Comment by 0gk** [comment]
- Input

Is it possible to change the vertical size of the <md-input> element?

Great Library, I want to use it. But if I place elements in a column, is too much empty space between them. 
Because of this, the form is less convenient to use, and I can not put all the items in the allotted space.

**Comment by marcosmoura** [comment]
I will create the "dense" variations of some components, including the md-input and md-textarea. This will reduce the space between the rows.
About the radio, checkbox and switches, the specification tells that we should stick with those sizes, so no changes on that. :)

**Comment by 0gk** [comment]
Thank you!
