### ISSUE TITLE
Disabling theme

### ISSUE THREAD

**Issue by allocenx** [vuematerial/vue-material#351]
How can i disable all theming configurations just like in angular material, $mdThemingProvider.disableTheme(), so i can create my own custom themes for components?

**Comment by marcosmoura** [comment]
This is not possible right now. I will try to develop this for the next version.

**Comment by allocenx** [comment]
Thanks, im working on big project, a game web written in vue and i also wanna use material design so i've found yours which i must say really nice job done so far tho there are missing components, if i can help somehow writting missing stuff like disablingTheming can i make a pull request and take in consideration? While i;m developing my web hope you can have a pretty stable version with all material's components.

**Comment by marcosmoura** [comment]
Of course! You can submit any PR. If there is some "design patterns" missing or incompatible, I will do the Code Reviews and you can fix it and then I can merge. :)

**Comment by allocenx** [comment]
Okey, thanks 👍

**Comment by Blizzke** [comment]
+1 For me. I really love everything Vue-Material brings, but it is a pretty big inconvenience that it applies extra styling on the <body> level out of the box that seemingly cannot be disabled. I only need a couple components in an otherwise pretty big layout and it just overrides styling of many of the non-related areas.

**Comment by necevil** [comment]
+1 From me also for the reasons @Blizzke stated above.

**Comment by nikkwong** [comment]
Was this added to 0.7.0?

**Comment by eyalcohen4** [comment]
Hey, there isa status for this issue? maybe roadmap for 1.0?

If not, i'll make a PR

**Comment by zapping** [comment]
#1081

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by LiangNex** [comment]
Boom, is there any update on this issue?
