### ISSUE TITLE
Missing alignment features for md-layout

### ISSUE THREAD

**Issue by razorfever** [vuematerial/vue-material#374]
First: you've got a nice thing going on here, thanks!

However, as an old Angular Material user I'm missing some features from their layout system like being able to assign two values inside a single layout-align attribute like in this interactive demo [here](https://material.angularjs.org/latest/layout/alignment).

It would also be extremely nice to be able to assign those missing 'justify-content' values the same way as in the above demo.

Something like this would be nice: 
`md-align="around center"
=>
justify-content: space-around;
align-items: center;` 
or 
`md-align="between end"
=>
justify-content: space-between;
align-items: flex-end;`

**Comment by marcosmoura** [comment]
I will think about that. Maybe some classes. Thank you.

**Comment by mkurczewski** [comment]
Hi @marcosmoura, maybe [https://github.com/mkurczewski/grider](this) can help you.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
