### ISSUE TITLE
Vue Material crashes in Apple devices.

### ISSUE THREAD

**Issue by ozgureffe** [vuematerial/vue-material#388]
Hi.

After some reported issues, about my vue material powered web site I want to check vue material original site with Apple devices. 

I do not own any apple devices. This screenshots are from [BrowserStack](https://www.browserstack.com) device simulator. 

Browserstack allows only these 3 devices in their free subscription so I made tests -only with them.  Here are the results:

# **iPhone 5 with iOS 6 :**
![image](https://cloud.githubusercontent.com/assets/515248/22237692/1f85cd3e-e216-11e6-9f25-8f180de5c1ab.png)

# **iPad Air with iOS 8.3**
![image](https://cloud.githubusercontent.com/assets/515248/22237564/5efefe78-e215-11e6-9521-3f1d793b80b8.png)

# **Iphone 6S:** 
(Works as expected)
![image](https://cloud.githubusercontent.com/assets/515248/22237770/914aba6a-e216-11e6-955e-19f35eb354d6.png)

Thank you.

**Comment by marcosmoura** [comment]
I will take a look, but I'm not going to add support for older iOS versions (older than 9) for now.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
