### ISSUE TITLE
 [mdRadio] Using md-radio without a v-model

### ISSUE THREAD

**Issue by Shhu** [vuematerial/vue-material#390]
Radio didnt work without a v-model :
[http://codepen.io/anon/pen/xgrmyq](http://codepen.io/anon/pen/xgrmyq)

**Comment by marcosmoura** [comment]
Unfortunately the v-model is mandatory. What do you want to do with a radio without a v-model?

**Comment by Shhu** [comment]
I write an application with Laravel & Vue, i use blade base structure.
The purpose of  #366 #389 #390 is to allow the usage of vue-material in a non-SPA environement

Exemple : 
<form action="..." method="post">
  <md-radio id="my-test1" name="my-test-group1" md-value="1">Yes</md-radio>
  <md-radio id="my-test2" name="my-test-group1" md-value="2">No</md-radio>
</form>

Actually if i want to do that, i have to create a component just for that. It would be great if the composant himself was "html compatible"

**Comment by Shhu** [comment]
I write an application with Laravel & Vue, i use blade base structure.
The purpose of  #366 #389 #390 is to allow the usage of vue-material in a non-SPA environement

Exemple : 
```html
<form action="..." method="post">
  <md-radio id="my-test1" name="my-test-group1" md-value="1">Yes</md-radio>
  <md-radio id="my-test2" name="my-test-group1" md-value="2">No</md-radio>
</form>
```


Actually if i want to do that, i have to create a component just for that. It would be great if the composant himself was "html compatible"

**Comment by korylprince** [comment]
If you are looking for an html/style only version of material components, perhaps you would be better served with something like http://materializecss.com/ or https://getmdl.io/ .

**Comment by Shhu** [comment]
The issue #366 is already fixed for checkbox, i dont see why vue-material shouldnt be improved to support non full vue apps.

Both materializecss and getmdl play poorly with vue. Vue-material is really nice to use and works great out of the box except for those vital basic 3 composants.

**Comment by marcosmoura** [comment]
@Shhu I'm going to change that. For now, you can create an empty v-model variable, just to make it work.

**Comment by Shhu** [comment]
@marcosmoura Thanks ! I have created my own select, radio and checkbox for the moment.

Thanks for your great work.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
