### ISSUE TITLE
[SCSS] md-flex=false has no effect

### ISSUE THREAD

**Issue by emersion** [vuematerial/vue-material#393]
### Steps to reproduce

```html
  <md-layout>
    <md-layout>
      <span>aaa</span>
    </md-layout>
    <md-layout :md-flex="true">
      <span>bbb</span>
    </md-layout>
  </md-layout>
  
  <md-layout>
    <md-layout>
      <span>aaa</span>
    </md-layout>
    <md-layout :md-flex="false">
      <span>bbb</span>
    </md-layout>
  </md-layout>
```

### What is expected?

Setting `md-flex` to `false` should make the layout not to grow to fill all the space.

### What is actually happening?

The layout grows, regardless of the `md-flex` value.

### Reproduction Link

http://codepen.io/anon/pen/ggRENx

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
