### ISSUE TITLE
 [mdDialog] Autofocus field in dialog

### ISSUE THREAD

**Issue by emersion** [vuematerial/vue-material#394]
Currently it's not possible to mark a field as automatically focused in a dialog (and outside, too). Worse, manually giving focus when opening a dialog doesn't work (it seems that the focus is given to the dialog's button when opened).

Adding a way to change this would be great.

**Comment by korylprince** [comment]
Generally you need to set focus using [nextTick](https://vuejs.org/v2/api/#Vue-nextTick).

So you would use something like:

```
this.$nextTick(function() {
    this.$el.focus();
});
```

That may not be exactly right. If you make a codepen reproducing your issue, I can take a look at it.

**Comment by emersion** [comment]
Yeah, that's what I'm doing right now. This issue is about improving vue-material to make it easier.

**Comment by Cadienvan** [comment]
I guess best solution could be adding an option into md-dialog component called "md-target" which could automatically focus defined target on dialog opening..

**Comment by marcosmoura** [comment]
I will add that. It was in my mind, but I didn't implemented yet. Sorry about that.

**Comment by praneetloke** [comment]
The official VueJS guide has an example of how to do this with [custom directives](https://vuejs.org/v2/guide/custom-directive.html). I recommend going with that.

**Comment by Samuell1** [comment]
I using this, input only needs `v-focus`

```
Vue.directive('focus', {
  inserted: (el) => {
    el.focus()
  }
})
```

**Comment by primadi** [comment]
v-focus trick does not work for me.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by jimmywarting** [comment]
Still got an issue with this one...
Problem could have been solved if using native dialog element that have this autofocus behaviour somewhat built in 

I would like to have this same exact behavior: 
https://github.com/GoogleChrome/dialog-polyfill/blob/32434f9699063388d4e9588a80757de4336c5214/dialog-polyfill.js#L235
