### ISSUE TITLE
How to get "currentPage" information of the md-table-pagination?

### ISSUE THREAD

**Issue by alesanfer** [vuematerial/vue-material#397]
Hi guys, ( @pablohpsilva )

How to grab the "currentPage" or "page" information of the md-table-pagination? I searched this on the documentation but not found this info.

i  saw that is emited an event about this in the index.js in the folder mdTable of the component but i dont know how to get this on.

thanks advance

**Comment by jonataswalker** [comment]
If you have this:

```html
<md-table-pagination @pagination="onPagination"></md-table-pagination>
```
Then:
```javascript
    onPagination(evt) {
      console.log(evt.page); // <-- here you are
    }
```

**Comment by alesanfer** [comment]
Hi @jonataswalker ,
This works, I think it would be nice to insert this information into the documentation about these events, they are very usefull.
thanks man

**Comment by pablohpsilva** [comment]
Yeah @jonataswalker . There is no documentation about it [check it out](https://vuematerial.github.io/#/components/table). We have to add it.

**Comment by marcosmoura** [comment]
Oh. That's bad. I have to do it. Sorry about that.

**Comment by pablohpsilva** [comment]
Documentation updated on PR #787
