### ISSUE TITLE
please implement date picker

### ISSUE THREAD

**Issue by mygnu** [vuematerial/vue-material#4]
I've looked at a lot of _vue-material_ they are either old and not compatible with Vue@2 or incomplete and an inconsistent. i like the aim for this package

> Vue Material is lightweight framework built exactly according to the Material Design specs.

I would love to see date and time picker implemented as well

**Comment by marcosmoura** [comment]
Hi Mygnu.

Yeah. This is definitely on my roadmap. I will finish the documentation,
then I will release like as it is and then I will focus on new components.
You can take a look at the projects tab, then you go to New Components and
you'll see all items on my roadmap. It's ordered by the top priority yet
but I'll try as hard as I can to start with those pickers.

Thank you.

**Comment by mygnu** [comment]
hey @marcosmoura can you please prioritize this with the 0.05 release would be nice to have feature with dialogs (this would help me with my app)

**Comment by marcosmoura** [comment]
Well. I don't know yet. To be honest this is not an easy and trivial component. Deal with dates is a difficult job. 
But don't worry. I will develop a time and date pickers. 
Probably this will be developed after release 0.6.0. So I'm sorry for making you to wait a little bit to use those components.

**Comment by mygnu** [comment]
No worries mate, I really appreciate your work. I have been using an abandoned vue1 project that I modified to vue2

**Comment by ragamuffinguil** [comment]
Hi @marcosmoura  same request as above ([please implement time and date selector](https://github.com/marcosmoura/vue-material/issues/4)). thanks in advance. ;)

**Comment by vuchl** [comment]
Maybe you guys can check out this repo in the meantime :https://github.com/bastienGranger/vue-material-datepicker . It needs tweaaking but can be customized to fit into the theme.

**Comment by marcosmoura** [comment]
Sorry about the delay to develop this component, but other things was prioritized.
Already in development!!

**Comment by mygnu** [comment]
All good mate. Great work overall!!!

**Comment by matthiasg** [comment]
You should look at http://element.eleme.io/#/en-US/component/date-picker for reference. Those selectors are pretty top notch. 

An issue with most date and/or datetime selectors is the missing mobile support though. In a mobile scenario I would usually either expect the dialog to be full screen or (one devices with good support) use the built-in methods. Sadly those built-in methods, while looking really good, don't offer features such as select from-to or week etc.

**Comment by marcosmoura** [comment]
The only thing that I'm not planning to develop for the next version is the Date Range. As an preview. right now, the initial layout (might change during the development) is this:

Desktop Screens:
![screen shot 2017-01-12 at 01 27 03](https://cloud.githubusercontent.com/assets/1357885/21875867/4102d286-d866-11e6-9bee-959c7b578bec.png)

Mobile Screens:
![screen shot 2017-01-12 at 01 29 05](https://cloud.githubusercontent.com/assets/1357885/21875912/931cfb78-d866-11e6-9e24-3139f723e8a9.png)

This will be responsive.

**Comment by matthiasg** [comment]
looks great. please make sure that the year is selectable ... otherwise birthdate pickers get really unwieldy :)

the date range picker is definitely advanced and can be overcome with two pickers.

**Comment by matthiasg** [comment]
what about date+time pickers ? any plans ?

**Comment by mehyaa** [comment]
Hi,

This will be great, waiting for it 👍

**Comment by marcosmoura** [comment]
This thread here is only for date picker. I will develop the time picker in another branch and release version.

**Comment by dohomi** [comment]
How @matthiasg mentioned, I'm looking for a datepicker for birthdays too. So it would be great if the year selection would be possible to go back many years without big hassle. Thanks the component looks very nice!

**Comment by marcosmoura** [comment]
@dohomi This will be developed. :)

**Comment by peredulion** [comment]
Hello @marcosmoura i really appreciate your work. You have the best material design vuejs library on the web. Can we know in how much days you will release the next version with date/time picker ?

**Comment by marcosmoura** [comment]
It's planned for 0.8.0. You can check the progress of all versions in the milestones section: https://github.com/marcosmoura/vue-material/milestones

**Comment by leonfather** [comment]
Thank you

**Comment by jonataswalker** [comment]
I think we should go with [Flatpickr](https://github.com/chmln/flatpickr) and there's already a [Vue Component](https://github.com/jrainlau/vue-flatpickr).

**Comment by ricardoduarte** [comment]
Hi @marcosmoura thank you very much for your work.

I really need this component too. Looking forward to next release with md-date-picker.

**Comment by mi1971** [comment]
Can't wait for this... The quality of other Vue datepickers currently available is terrible. Some of them have a material design pop-up, and a Twitter bootstrap style text box. Huh?

**Comment by jonataswalker** [comment]
@marcosmoura Would you like to develop this from scratch or wrap a reliable already-made solution?

I'm quite satisfied with [Flatpickr](https://github.com/chmln/flatpickr) and I could prepare a PR if you agree.

**Comment by mi1971** [comment]
@jonataswalker Flatpickr is nice and small, but are you completely restyling it to make it look like Material Design? From what I can see in the demos, the text box and even the calendar doesn't fit the Material look...or is there some sort of additional theme to make it look like Material Design?

**Comment by marcosmoura** [comment]
It's almost done...

**Comment by jonataswalker** [comment]
There are some themes available @mi1971 but for certain let's wait for @marcosmoura.

**Comment by stefan-hoehn** [comment]
@marcosmoura Is there any place where we can see it and maybe even check it out?
We only started recently with a major project on vue material and I rather would like the "genuine" date picker of the library than anything we add from somewhere else...

**Comment by ghprod** [comment]
need this .. cheers :+1:

**Comment by nathantsoi** [comment]
happy to help finish this if it is on a branch somewhere, @marcosmoura?

**Comment by nathantsoi** [comment]
ping. @marcosmoura

**Comment by vitaly-t** [comment]
> It's almost done...

4 month later - no update.

**Comment by oswaldofreitas** [comment]
it shouldn't be difficult, I did it in one week only here https://vulma.org/#/docs/datepicker.
if you guys want, you can copy code from that ok?

**Comment by mi1971** [comment]
I've changed to vuetify. It has the pickers, and is really nice to use. Development seems to be very active.

**Comment by DavidHavl** [comment]
@mi1971: I am happy for you, but for me that is a no no. I have been working on business critical application and have tried vuetify at first but had to rewrite everything to vue-material as it was not working the way I needed it in many respects. Too much magic that get's in the way.

**Comment by bluekeys** [comment]
@marcosmoura Is this still in the works? Is there a branch we can check out, maybe help a little with? Or do you have a planned release date?

**Comment by Samuell1** [comment]
@bluekeys https://github.com/vuematerial/vue-material/issues/921

**Comment by maac4422** [comment]
Hi,If @marcosmoura permit me I have a temporal solution if you want can go to this repository
https://github.com/maac4422/example-datepicker-vue-material. Hope help someone.

**Comment by sangdth** [comment]
I'm waiting for this 👍

**Comment by marcosmoura** [comment]
Today!

**Comment by vovkats** [comment]
@marcosmoura I don't find options in documentations for config datepicker. I need to change name of some months
