### ISSUE TITLE
 [mdSelect] add min / max to mdSelect on multiple="true"

### ISSUE THREAD

**Issue by dohomi** [vuematerial/vue-material#405]
Please add min / max to `mdSelect` on user Input. Additional option should be disabled if the user tries to add too many values. Thanks!

**Comment by marcosmoura** [comment]
I didn't understand. On mdSelect?

**Comment by dohomi** [comment]
@marcosmoura yes on `mdSelect` for `multiple="true"` select fields and option to select `min` or `max` input values. I'll change the title of this issue again

**Comment by marcosmoura** [comment]
Well. This is not an standard on native <select> tag. Although it seems to be a good thing to have an 'md-max' option to limit the selection. But I'm not going to do a seamless integration with Vuelidate, for now.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
