### ISSUE TITLE
[new] Color Palette Classes In Every Component

### ISSUE THREAD

**Issue by Cadienvan** [vuematerial/vue-material#406]
I'm here to analyze something I think is missing in this library, Color Palette Classes in some components.

In fact, I see components which can be shown by using theme-defined color palette classes (default, primary, accent, warn, dense), but many others can't.

I found it frustrating when I want to show a custom form error (Maybe a span above my form with a detailed explanation of an error). Even with chips, it could be nice to have classes to differenciate how those are shown.

Right now, I solved my text-related issue by applying the following classes:
```
.md-text-primary{
    color: #2196f3;
}

.md-text-accent{
    color: #e91e63;
}

.md-text-warn{
    color: #ff5722;
}

.md-text-warn{
    color: #ff5722;
}

.md-text-warn{
    color: #ff5722;
}

.md-text-warn{
    color: #ff5722;
}
```

I guess they could be useful as a temporary solution, but I think it would be better to have those classes applied to every component.

Thanks,
Michael.

**Comment by marcosmoura** [comment]
Hi @Cadienvan 

I think that not every single component should have different variations of use. The md-chips, with red colors, for accent for example, could make the component a little bit ugly.
Which other components you think that could be improved?

**Comment by Cadienvan** [comment]
HI @marcosmoura 

I think that this framework should be flexible, so I think you shouldn't look at 'ugliness', but functionality.
Even if md-chips with an accent class could look a little bit ugly, it is a functionality that should be spread accross the whole library.

That's only my opinion, of course, but I think that limiting choices isn't a good idea..

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
