### ISSUE TITLE
[SCSS] [core] On iOS / Safari input fields are automatically zoomed upon selection

### ISSUE THREAD

**Issue by BjoernKW** [vuematerial/vue-material#417]
### Steps to reproduce
Tap on an `<md-input>` field in Safari. The field is zoomed automatically moving the rest of the page out of the visible area.

### Which browser?
Vue Material 0.6.3
Vue.js 2.1.10
Safari 10.2.1
iOS 10.2.1

### What is expected?
When using a responsive meta tag such as `<meta name="viewport" content="width=device-width">` the page shouldn't zoom at all.

### What is actually happening?
On iOS / Safari input fields are automatically zoomed upon selection

**Comment by marcosmoura** [comment]
This is a problem with the font size. I will fix that. The workaround, for now, is to set the font-size of all .md-input to 16px.

**Comment by mycarrysun** [comment]
Any progress on this issue? Launching an app on Aug 1 and need a solid fix. By the way Marcos - love your work.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
