### ISSUE TITLE
 [mdIcon] [core] Image cache

### ISSUE THREAD

**Issue by jtouzy** [vuematerial/vue-material#440]
I think an optimization can be made with md-icon with src-based images.
An http request is made each time an image have to be displayed, and browser cache is never used.

I have one case with md-list, each item contains an md-icon with src, and the page is really slow to load because of this :

![capture d ecran 2017-02-04 a 13 38 57](https://cloud.githubusercontent.com/assets/5709133/22618538/53a291ca-eadf-11e6-9d1a-c6ff9b7c9730.png)

Maybe i'm doing something wrong... or specific to svg images?

**Comment by marcosmoura** [comment]
The md-icon does have a cache. But what I think it's happening here is that during the first render, all list-items are evaluated in a batch. So the cache breaks. I will fix this ASAP.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
