### ISSUE TITLE
 [mdDialog] DOMException: Failed to execute 'insertBefore' on 'Node' (md-dialog)

### ISSUE THREAD

**Issue by ghost** [vuematerial/vue-material#446]
I have a simple component like this, which contains  a `md-dialog`:

```
<template>
  <div>
    <!-- any conditional vue-material component -->
    <md-chip v-if="myObj.condition">conditional vue-material component</md-chip>

    <!-- any md-dialog -->
    <md-dialog-alert md-content="Hello World!" ref="dialog"></md-dialog-alert>

    <!-- any vue-material component -->
    <md-chip>another vue-material component</md-chip>

    <!-- any conditional vue-material component -->
    <md-chip v-if="!myObj.condition">conditional vue-material component 2</md-chip>
  </div>
</template>

<script>
export default {
  computed: {
    id() {
      return this.$route.params.id;
    },
    myObj() {
      return this.$store.getters.myObjGetter(this.id);
    },
  },
};
</script>
```

The `myObj` computed property is retrieved from the vuex store. It has a boolean property, named `condition`. If I navigate from a route where `myObj.condition` is `true`, to another, where `myObj.condition` is `false`, I get the following error:

> DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

The error is because of the `md-dialog`. If I remove it or surround it with a `div`, it works fine.

**Comment by marcosmoura** [comment]
I see. I will take a look at this. It seems that the component it's being executed before the v-if evaluation, so I need to postpone the creation of the fake element.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
