### ISSUE TITLE
 [mdList] Multiple expand on demo page does not show all elements

### ISSUE THREAD

**Issue by dohomi** [vuematerial/vue-material#469]
### Steps to reproduce
Open demo page: https://vuematerial.github.io/#/components/list and use the last demo with multiple expand. The outer list content is not scrollable though not all elements of the expanded list are visible to the user
### Which browser?
current Chrome and Mac OSX

### What is expected?
If there are more elements to display need to show some overflow:scroll
<img width="466" alt="screen shot 2017-02-09 at 09 39 34" src="https://cloud.githubusercontent.com/assets/489221/22765512/b325e9a6-eeab-11e6-9927-537a9c63caf0.png">

**Comment by praneetloke** [comment]
Same as #486?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
