### ISSUE TITLE
 [mdRadio] does not support null value for model

### ISSUE THREAD

**Issue by aagahi** [vuematerial/vue-material#475]
Having
```
 <md-radio class="md-primary" name="myname" md-value="false" v-model="v">
...
data: function () {
    return {
      v: null
   }
}
```

Raise
```
[Vue warn]: Error when rendering component <md-radio>:
TypeError: Cannot read property 'toString' of null
```

I guess value is still null and as specified by [the spec](http://www.ecma-international.org/ecma-262/5.1/#sec-11.4.3
), typeof null is 'object'.
so the current code won't work in case of null value
https://github.com/marcosmoura/vue-material/blob/develop/src/components/mdRadio/mdRadio.vue#L34

So maybe the good old test against this.value as is used to be in 0.6.3 was good ;)
https://github.com/marcosmoura/vue-material/blob/v0.6.3/src/components/mdRadio/mdRadio.vue#L34

**Comment by marcosmoura** [comment]
Fair. I will fix it soon.

**Comment by delueg** [comment]
How can i go along with this error for now?

**Comment by Samuell1** [comment]
Its fixed long ago, https://github.com/vuematerial/vue-material/pull/693

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
