### ISSUE TITLE
 [mdInput] Text input doesn't accept spaces when used inside menu

### ISSUE THREAD

**Issue by Struwigcd** [vuematerial/vue-material#478]
### Steps to reproduce
Use the md-input with type="text" inside md-menu's md-menu-content area

Also affects md-input type="password" and md-text-area

Typing spaces get ignored on these fields

### Which browser?
Chrome 56

### Reproduction Link
[codepen](http://codepen.io/struwigcd/pen/PWydOK)

**Comment by marcosmoura** [comment]
Can you create a Codepen with the issue?

**Comment by Struwigcd** [comment]
updated with link

[codepen](http://codepen.io/struwigcd/pen/PWydOK)

**Comment by bertmsk** [comment]
The bug still exists

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
