### ISSUE TITLE
 [mdInput] in a md-list that contains a md-list-expand, can't be focused by mouse

### ISSUE THREAD

**Issue by alberanid** [vuematerial/vue-material#480]
### Steps to reproduce

A md-input inside a list items with an expansion can only be focused using the keyboard; using the mouse, only the accordion is affected.

It may be a corner case that you don't want to support, but I was using it and worked on 0.6.3 :-D

(anyway, thanks for the amazing framework :+1: )

### Which browser?

Vue 2.1.8, Vue Material 0.7.1, Linux, Chromium 55.0 and Firefox 51.

### What is expected?

The click should be passed to the input field.

### What is actually happening?

The accordion is closed/opened but the input field never receive the focus.

### Reproduction Link

https://codepen.io/alberanid/pen/PWyLwr

**Comment by marcosmoura** [comment]
I will take a look at this...

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
