### ISSUE TITLE
The last example in the docs for the List component is missing the code for Multiple Options and Multiple Expand

### ISSUE THREAD

**Issue by praneetloke** [vuematerial/vue-material#486]
### Steps to reproduce
- Go to the [List](https://vuematerial.github.io/#/components/list) component docs page and scroll-down to the last example card.
- Click on the `Code` tab and you will see that the code list is only for the Single Expand. Both Multiple Options and Multiple Expand demo code listings are missing.
### Which browser?
N/A

### What is expected?
The code for [this list](https://github.com/marcosmoura/vue-material/blob/master/docs/src/pages/components/List.vue#L858) and [this list](https://github.com/marcosmoura/vue-material/blob/master/docs/src/pages/components/List.vue#L926) would be shown in the `Code` tab for the examples demonstrated.

### Reproduction Link
https://vuematerial.github.io/#/components/list

EDIT: Updated the steps to reproduce.

**Comment by marcosmoura** [comment]
I will add that ASAP.

**Comment by pablohpsilva** [comment]
I've created a PR for it: #750
I'm closing this issue. Please @praneetloke follow the PR from now on for this issue.
Thank you! :D
