### ISSUE TITLE
 [mdInput] calculated height on start

### ISSUE THREAD

**Issue by delueg** [vuematerial/vue-material#492]
Hello,

when the md-textarea already has a set value from v-modal the height of the textarea will not calculate correctly.

https://jsfiddle.net/rgdoyjcs/

is it possible to trigger the height calculation?

**Comment by marcosmoura** [comment]
It's definitely a bug. I will fix that in the next version.

**Comment by leMaur** [comment]
I got an error about textarea when I minify the code! 
`Uncaught TypeError: Cannot read property 'height' of undefined at HTMLTextAreaElement.s`

My setup is:
- Laravel 5.3 
- elixir 6.0
- elixir-webpack-official 1.0.2
- Vue.js 2.0.1
- VueMaterial 0.7.1

Someone had the same problem?
I'm not sure is VueMaterial md-textarea component instead the autosize plugin.
Any idea?

P.S.
Thank you @marcosmoura for this great project!

**Comment by jdrydn** [comment]
Looking forward to this being fixed 😄  Only (noticeable) bug in my new CMS rebuild is this 🎉

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
