### ISSUE TITLE
 [mdTheme] Access md-theme color

### ISSUE THREAD

**Issue by kpilard** [vuematerial/vue-material#499]
Hello,
is there a way to access the current md-theme color?

Something like `this.$material.currentTheme.primary[500]` or `this.$material.colors.deepOrange[100]`

**Comment by marcosmoura** [comment]
This is not exposed by any Vue Material API. What you can do is to import the src file, that is inside 
`node_modules/vue-material/src/core/components/mdTheme/palette.js`
I will create a way to expose this to the final build.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/themes/configuration
