### ISSUE TITLE
 [mdTable] performance issue on MdTable and md-selection

### ISSUE THREAD

**Issue by dohomi** [vuematerial/vue-material#501]
Hi,
I am using MdTable at the moment and discovered some performance issues on 'MdTable' with `md-selection`

I checked on chrome debugger to search for a peak and found it in following piece of code:
```
 getClickPosition: function(t) {
     if (this.$refs.ripple) {
         var e = this.parentElement.getBoundingClientRect()
         , n = t.pageY
         , i = t.pageX;
         return "touchstart" === t.type && (n = t.changedTouches[0].pageY,
         i = t.changedTouches[0].pageX),
          {
                 top: n - e.top - this.$refs.ripple.offsetHeight / 2 - document.body.scrollTop + "px",
                 left: i - e.left - this.$refs.ripple.offsetWidth / 2 - document.body.scrollLeft + "px"
            }
       }
       return !1
  },
```
On your documentation the page https://vuematerial.github.io/#/components/table seems to be heavy too, the scrolling seems to be a bit un-smooth. 

I'm not sure where the issue belongs, but is it maybe possible that ripple effects are recalculated with `top` `left` positioning rather than `transform`? Just a guess to see where this behaviour is coming from, I found following article which explains about the browser rendering in detail:

https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/

@marcosmoura not sure what is exactly the reason but maybe there is space for improvement on the ripple component?

**Comment by dohomi** [comment]
Here a screenshot of the profiling capture of the https://vuematerial.github.io/#/components/table page. I'm not sure how to investigate further but maybe someone else has an idea?
<img width="455" alt="screen shot 2017-02-14 at 10 44 41" src="https://cloud.githubusercontent.com/assets/489221/22912892/c761bf80-f2a2-11e6-9ef6-6ac218ca8af0.png">

**Comment by dohomi** [comment]
Similar behaviour exist inside of the sidebar while click on expandable list elements. The spike inside of the Chrome profiling is quite high.

**Comment by pablohpsilva** [comment]
I'll look into that ASAP. Thanks @dohomi

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
