### ISSUE TITLE
 [mdTabs] doesnt init first tab when placed in md-dialog

### ISSUE THREAD

**Issue by pluschen** [vuematerial/vue-material#507]
You have to click (the first tab) manually to see first tab content.
Any resize issue?
http://codepen.io/anon/pen/qRggRB

**Comment by marcosmoura** [comment]
Yes. Exactly this! I will fix. Also related to #258

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
