### ISSUE TITLE
 [mdCard] does not recalculate own height in mdDialog

### ISSUE THREAD

**Issue by VicarEscaped** [vuematerial/vue-material#513]
### Steps to reproduce
1. Goto [codepen](http://codepen.io/anon/pen/mRoXRP)
2. Click on *click me*
### Which browser?

Chrome 56.0.2924.87
### What is expected?
`mdCardContent` inside mdCardExpand has no height
### What is actually happening?
`mdCardContent` has height of all children

### Reproduction Link

[Link](http://codepen.io/anon/pen/mRoXRP)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
