### ISSUE TITLE
router-link within md-menu doesn't work

### ISSUE THREAD

**Issue by romangit** [vuematerial/vue-material#520]
Hi!

I need a router-link within md-menu, I try 

```
    <md-menu>
      <md-button md-menu-trigger>Open Menu</md-button>
      <md-menu-content>
        
        <router-link to="/foo" tag="md-menu-item">
          <span>Go to Foo</span>
        </router-link>
        <!-- OR -->
        <md-menu-item>
          <router-link to="/bar">
            <span>Go to Bar</span>
          </router-link>
        </md-menu-item>
        
      </md-menu-content>
    </md-menu>
```
http://codepen.io/anon/pen/dNLNOO

It doesn't work and looks awful, thanks

**Comment by cawa-93** [comment]
See this #470

**Comment by romangit** [comment]
@cawa-93 Even this workaround doesn't work https://github.com/marcosmoura/vue-material/issues/470

**Comment by marcosmoura** [comment]
I will take a look at this issue. It seems that the mdMenuItem is preventing the click.

**Comment by johnwebbcole** [comment]
Any updates on this?  Has someone found a workaround?

**Comment by pablohpsilva** [comment]
Hello everyone.
This issue is the same as #470 (a workaround can be found there too @johnwebbcole ). I'm closing this issue for now and we'll fix it ASAP.

Thank you @johnwebbcole @romangit and @cawa-93 :D
