### ISSUE TITLE
 [mdCard] with mdTabs inside calculate wrong content margin

### ISSUE THREAD

**Issue by VicarEscaped** [vuematerial/vue-material#527]
### Steps to reproduce
1. Open card expand
2. Switch tab
3. Close expand
### What is expected?
Expand area close and display expand trigger
### What is actually happening?

Expand area calculate wrong content margin if tabs content has different content height.
### Reproduction Link

[Link](http://codepen.io/anon/pen/jyorMp)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
