### ISSUE TITLE
 [mdToolbar] in md-table-card ignore md-primary css Class

### ISSUE THREAD

**Issue by cawa-93** [vuematerial/vue-material#528]
### What is actually happening?
`md-toolbar` in `md-table-card` ignore `md-primary` css Class, but colored if using `md-accent`

### What is expected?
It was expected identical behavior when using any CSS class

### Reproduction Link
https://jsfiddle.net/kozack/vtxvLsoj/1/

**Comment by marcosmoura** [comment]
This is intentional. The md-toolbar inside md-table-card should follow the background color regardless its class.

**Comment by cawa-93** [comment]
It would be much better if the toolbar table without class - was the standard design, but vary according to the class themes.

**Comment by marcosmoura** [comment]
Yep. This can be done.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
