### ISSUE TITLE
 [mdMenu] Disabled md-option can be selected 

### ISSUE THREAD

**Issue by cawa-93** [vuematerial/vue-material#529]
### What is expected?
In SELECT are some options with the attribute "disabled." These options change self opacity, but can still be selected and change the view

### What is actually happening?
When you click on an element that has an attribute "disabled" should not happen anything.

### Reproduction Link
https://jsfiddle.net/kozack/y7owLuz1/

**Comment by marcosmoura** [comment]
Wow. This is a bad bug.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
