### ISSUE TITLE
 [mdTheme] Accent always uses A200, cant chage hue

### ISSUE THREAD

**Issue by Skrutten** [vuematerial/vue-material#533]
Hi,

It seems like hue for accent is allways "A200".
Also tried the codepen from the site and I get the same error:
http://codepen.io/vue-material/pen/WGavBE

**Comment by vizo** [comment]
Looks like it's on purpose...  https://github.com/marcosmoura/vue-material/blob/master/src/core/components/mdTheme/index.js#L70

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/themes/configuration
