### ISSUE TITLE
[core] white page on Android browser

### ISSUE THREAD

**Issue by yairpe** [vuematerial/vue-material#537]
Hi, thanks for w great library

The only thing stopping me to use it now is that it shows a blank page on an older Android browser 4.4.2

[https://vuematerial.github.io](url)

Looks like a bug.

Any ideas?

Thanks

**Comment by marcosmoura** [comment]
It wasn't tested on Android 4.x yet. 
For now it only supports Lollipop or greater. I will fix that in the future.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
