### ISSUE TITLE
 [mdInput] Fast typing in input is laggy

### ISSUE THREAD

**Issue by Samuell1** [vuematerial/vue-material#544]
Hey, if i type in input faster its laggy, i check what function doing it and most `validateProp` and `updateFromParent`, How to solve this i need something special on v-models or?

![2017-02-21_14-27-08](https://cloud.githubusercontent.com/assets/3110002/23166722/051facb6-f842-11e6-9bfb-e59ffedcaac7.gif)

**Comment by Samuell1** [comment]
I found some weird things, this lags for inputs its doing select input

**Comment by marcosmoura** [comment]
I will investigate this issue. This is quite strange.

**Comment by Samuell1** [comment]
@marcosmoura i found if many options are rendered for select that starts laggy

**Comment by Samuell1** [comment]
@marcosmoura I created example: http://codepen.io/Samuellsk/pen/ygmQdx, if you have good pc its less laggy but on worse pc is laggy

**Comment by Samuell1** [comment]
@marcosmoura any updates to this? i can't have selects with many inputs inputs :/, its same in chrome and firefox

**Comment by koriroys** [comment]
@marcosmoura I found with some local testing that commenting out
https://github.com/marcosmoura/vue-material/blob/master/src/components/mdInputContainer/common.js#L61-L62
seemed to completely remove the input lag, even if I have 1000 elements in the select dropdown

![events_issue](https://cloud.githubusercontent.com/assets/1118323/23624327/a4a39e24-02a5-11e7-8dcf-afeaaf9f3677.gif)

It seems those events are necessary to let the components work with v-model, but are there some side-effects perhaps?

**Comment by Samuell1** [comment]
@koriroys i think without input emit v-model doesnt work

**Comment by pablohpsilva** [comment]
@Samuell1 is right. Without those events, the v-model is useless

**Comment by Samuell1** [comment]
@marcosmoura @pablohpsilva @koriroys maybe change select to doesnt not use native select and options but use ul, li for rendering list and selected value will be saved to text input

**Comment by pablohpsilva** [comment]
@Samuell1 @koriroys @marcosmoura I think I fixed the issue. Check it out #674
