### ISSUE TITLE
[SCSS] md-flex-small ignored when md-flex-medium is defined

### ISSUE THREAD

**Issue by albanm** [vuematerial/vue-material#546]
Hello,

For example:

    <md-layout md-flex-xsmall="100" md-flex-small="50" md-flex-medium="30"></md-layout>

The xsmall and medium parameters are applied, but not the small one. It is because the class md-flex-small-50 does not take precedence over mx-flex-medium-30. The order of the rules is wrong in vue-material.css.

The weird part is that the order of includes is correct in mdLayout.scss but it is not preserved in the css output ("small" is moved before the other ones). So I guess it might be a bug with node-sass.

**Comment by rockybean** [comment]
+1

**Comment by SyedAman** [comment]
I have a similar issue where in:

```
<md-layout md-flex="10" md-flex-offset-large="10" md-flex-offset-xlarge="10">
```

the `md-flex-offset-large` gets applied to all smaller sizes as well. It doesn't assume 0 for other sizes. There's no way to "disable" the offset for medium sized screen for example.

I tried `md-flex-offset-medium=` `false` and `0` to no avail

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
