### ISSUE TITLE
[mdChips] Add chip on blur

### ISSUE THREAD

**Issue by thoss** [vuematerial/vue-material#550]
Hi,

can you edit the component `md-chips` so when you leave the input field the chip will be automaticaly added (if there is any text) with `@blur` ? 

Many Thanks!

thoss

**Comment by diskman** [comment]
hi @thoss, have you found any workaround for `md-chips` and `@blur`?

**Comment by egortsaryk9** [comment]
+1 It would be very useful improvement

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
