### ISSUE TITLE
 [mdButton] width in table is limited

### ISSUE THREAD

**Issue by superwf** [vuematerial/vue-material#553]
Hi~

when button in table has long string, the string is hidden by the width limit.

src/components/mdTable/mdTable.scss

line 172
$size: 36px;
width: $size;

Is it a bug ?

**Comment by d3radicated** [comment]
I guess it's set to 35px because it's expected that you use icons in the buttons.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
