### ISSUE TITLE
[SCSS] How to use Vue-material just on some element (parent) ?

### ISSUE THREAD

**Issue by l2aelba** [vuematerial/vue-material#556]
Normally **Vue-material** will use/style on **all in** `<body>` right ?

**But** I want to use **Vue-material** just on **some element** like

```html
<body>
   <div id="vue-material-theme">
     <!-- Vue material elements here -->
   </div>
</body>
```

This is possible ?

**Comment by fortael** [comment]
I also don't want to apply theme to the entire site. It makes all links pink and another unnecessary styles in head.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
