### ISSUE TITLE
md-tooltip for md-switch

### ISSUE THREAD

**Issue by d3radicated** [vuematerial/vue-material#558]
Can we use tooltips for `md-switch`?

**Comment by dennyboy** [comment]
I had luck with this via wrapping the switch and tooltip with an inline element

```html
<span>
    <md-switch id="my-switch" name="my-switch">Test</md-switch>
    <md-tooltip>My tooltip text</md-tooltip>
</span>

```

**Comment by pablohpsilva** [comment]
Hello @d3radicated !
You can! All you have to do is wrap those two together in a div or span (like @dennyboy said)
