### ISSUE TITLE
 [mdTheme] Unable to set theme hue

### ISSUE THREAD

**Issue by jkirkby91-2** [vuematerial/vue-material#560]
Your docs to say set a hue according to design material ui palette like so

```
  primary: {
    color: 'indigo',
    hue: 'A200'
  },
```

in my register function i have

```
  app: {
    primary: 'blue',
    background: 'grey',
    hue: 'A300'
  },
```
But it's not working? Am i missing something?

**Comment by cawa-93** [comment]
```
app: {
    primary: {
        color: 'blue',
        hue: 'A300'
    },
    background: 'grey', // default hue - 500
  },
```

**Comment by jkirkby91-2** [comment]
@cawa-93 This structure makes more just leaving this here though as the hue option doesn't take a letter before the value it throws a toString undefined error, the correct syntax should be.

```
Vue.material.registerTheme({
  app: {
    primary: {
      color: 'blue',
      hue: '300'
    },
    background: {
      color: 'grey',
      hue: '300'
    }
  }
})
```

Is there some where I can make a pull request to the docs?

**Comment by wopian** [comment]
300 is an entirely different colour to A300

**Comment by jkirkby91-2** [comment]
regardless it throws a toString undefined error if you use an a in front regardless of what color is set

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

https://vuematerial.io/themes/configuration
