### ISSUE TITLE
 [mdList] Missing list docs

### ISSUE THREAD

**Issue by kevinkleine** [vuematerial/vue-material#564]
Nice work! Keep it up!

In the docs for the list component, at the bottom is a set of three examples called "Control". When switching from 'demo' to 'code', I can only see the code for the second example. It seems the code for the other two is missing.

**Comment by wopian** [comment]
Had that same problem last night when I started work on a project using this. Was pretty annoying as it required trial and error to get the same outcome.

There's a lot of other alternatives of other components that are not shown at all either.

**Comment by Samuell1** [comment]
@kevinkleine if something is missing in code you can simple go in docs folder (https://github.com/marcosmoura/vue-material/tree/master/docs/src/pages) to find it

**Comment by pablohpsilva** [comment]
I had the same issue you had @kevinkleine and I did exactly what @Samuell1 said LOL
We'll fix it ASAP. Thank you!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
