### ISSUE TITLE
 [mdInput] Input Placeholder: Focus vs. Empty

### ISSUE THREAD

**Issue by Quantastical** [vuematerial/vue-material#565]
Currently, when you focus an input field, the placeholder/label text gets tucked above the user input.

I find the animation to be rather annoying tabbing through fields and I like it better when the placeholder text stays inline until some data has been entered.

I was able to solve this with a quick override for my project:

```
/* Don't tuck placeholders until the field has some value */
.md-input-container.md-input-focused:not(.md-has-value) label {
  top: 23px;
  font-size: 16px;
  color: rgba(0,0,0,.54)
}
```

Is this sufficient enough to complete my desired behavior? Or, are there any "@media" nuances that I might not be aware of?

**Comment by jonataswalker** [comment]
Can't confirm this behavior. May you please provide a demo?

**Comment by zapping** [comment]
@Quantastical, if you use a `<Label>` tag then the animation that you mentioned occurs. Just leave out the `<Label>` tag and add your label to the placeholder attribute then it should work the way you prefer.

`  <md-input-container><md-input placeholder="Label in placeholder"></md-input>
  </md-input-container>`

**Comment by pablohpsilva** [comment]
Hello @Quantastical ! :D 
I think that can be an improvement. I tagged this issue and I'll look into it ASAP.
Thank you!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
