### ISSUE TITLE
 [mdTooltip] not work in md-list-item with click event

### ISSUE THREAD

**Issue by cawa-93** [vuematerial/vue-material#567]
### What is expected?
md-tooltip work everywhere

### What is actually happening?
md-tooltip work in md-list-item only if there are not `v-on:click.native`

### Reproduction Link
https://jsfiddle.net/kozack/ga8xyj0x/

**Comment by pablohpsilva** [comment]
Hello @cawa-93 ! How are you?
That's super weird (and a bug) LOL
We'll try to fix it ASAP

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by sumitg-3767** [comment]
This is neither working on vue-material 1.0.0-beta-10.2. Not even @click.native
