### ISSUE TITLE
 [mdRadio][SCSS] and disabled button doesn't respect to dark background

### ISSUE THREAD

**Issue by mingchuno** [vuematerial/vue-material#569]
### Steps to reproduce

1. Using radio button and disable button when setting dark background
2. The radio button and the disabled button just "gone" because they are still dark

http://codepen.io/mingchuno/pen/XMbNjw

### Which browser?

I think all? I have check chrome, firefox and Safrari

### What is expected?

I expect they change to white just like the font?

### What is actually happening?

1. Using radio button and disable button when setting dark background
2. The radio button and the disabled button just "gone" because they are still dark

### Reproduction Link

http://codepen.io/mingchuno/pen/XMbNjw

**Comment by pablohpsilva** [comment]
I think this can be tagged as an improvement, but I'm not really sure if changing the background to specific colors should change elements colors too (like bg-color black setting elements to whitish).
I'll check Material Design guide and I'll come back to this issue ASAP.

Thank you @mingchuno ! :D

**Comment by mix3d** [comment]
Could expanding the theme engine to "dark" and "light" styles be a possible approach, to toggle white-text vs black text? The Material design palette already uses white and dark text depending on the color and hue, but that switch can range anywhere from 200 to 700.

https://material.io/guidelines/style/color.html#color-themes (black theme design at bottom of page)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
