### ISSUE TITLE
[SCSS] [mdCard] md-gutter="40" produces horizontal scroll bar in cards

### ISSUE THREAD

**Issue by shanemgrey** [vuematerial/vue-material#572]
### Steps to reproduce
Create a md-card with a md-layout md-gutter="40" inside of it, and any kind of content inside of that.

### Which browser?
Using latest vue, and vue-material, 
Tested in chrome, firefox, and safari.  Same issue in all.

### What is expected?
There should be no horizontal scroll bar in the card.

### What is actually happening?
A horizontal scroll bar shows up only when md-gutter is set to 40

Seems to happen at any screen size.

### Reproduction Link
http://codepen.io/shanemgrey/pen/qrdLQw

I tried to find any bits of sass or JS that might be causing this, but I couldn't identify where the issue is coming from.

**Comment by Samuell1** [comment]
Its crazy bug, maybe its flexbox bug

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
