### ISSUE TITLE
[md-tabs][md-label] Reactivity issue - value not updated immediately

### ISSUE THREAD

**Issue by fabien-lg** [vuematerial/vue-material#573]
### Steps to reproduce
When using a value as the text of a `md-tab`, the value is not updated immediately, only at the next value update.

### Which browser?
Latest `vue-material`, `vue 2.1.6`

### Reproduction Link
The example below shows that the value is not immediately updated.
I've put an input with a placeholder to show what should happen

http://codepen.io/FabienLG/pen/KWpjRw

**Comment by VicarEscaped** [comment]
Hi, @fabien-lg 
Try this
```js
changeText () {
      this.label = 'LABEL ' + this.val
      let tabData = this.$refs.tab.getTabData()
      tabData.label = 'LABEL ' + this.val
      this.$refs.tabs.updateTab(tabData)
      this.val++
    }
```

**Comment by fabien-lg** [comment]
Thanks @VicarEscaped , it works, but why is this necessary?

**Comment by VicarEscaped** [comment]
First, i think you can simplify code by calling `this.$refs.mytab.updateTabData()`.
This is necessary beacause md-label is not reactive and then it's change it doesn't notify parent to display new label.

**Comment by Morgul** [comment]
The new tracking issue for this is #845.
