### ISSUE TITLE
 [mdTabs] wrong content height on mobile

### ISSUE THREAD

**Issue by fabricecw** [vuematerial/vue-material#574]
Hey @marcosmoura 

Thanks for all your effort on this package!
I noticed that content in mdTabs get cut off in the bottom on iOS 10.

mdTabs.vue Component:
```
       calculateContentHeight() {
        this.$nextTick(() => {
          if (Object.keys(this.tabList).length) {
            let height = this.tabList[this.activeTab].ref.$el.offsetHeight;

            this.contentHeight = height + 'px';
          }
        });
      },
```

So probably a Vue issue on `.ref.$el.offsetHeight;`

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
