### ISSUE TITLE
 [mdRadio] v-model update priority

### ISSUE THREAD

**Issue by bhamon** [vuematerial/vue-material#581]
### Goal
I just want to trigger some async calls when a radio button is checked. I bound the radios to a v-model. The async handler is bound to the same piece of data than the radios.
Unfortunately, when calling the async service from the `@change` handler, the model data is obsolete.

I have other implementation choices that works (like passing the new value to the service method directly).

I just wanted to be sure that this is the expected behaviour.

### Steps to reproduce
Add a `@change` listener to a `md-radio` and output both the provided value and the model value.

### Which browser?
vue@2.2.1
vue-material@0.7.1

### What is expected?
The values should be the same.

### What is actually happening?
The provided value is more up to date than the model one.

### Analysis
I think it comes from the order of the two `$emit` calls here: https://github.com/marcosmoura/vue-material/blob/master/src/components/mdRadio/mdRadio.vue#L42

### Reproduction Link
http://codepen.io/anon/pen/xqZEgP : look at the console output.

**Comment by bolerodan** [comment]
Hmm yeah I see. I'm not sure if this is intended, but you could use a watch on your v-model variable. At that point in time, the value is correct and you could call your service then.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
