### ISSUE TITLE
 [mdList] API for expanding or collapsing all items in a list

### ISSUE THREAD

**Issue by fortil** [vuematerial/vue-material#584]
Hi
 
I have a problem with md-list-expand, i have a code
```
<div class="menu">
      <div class="phone-viewport" v-for="menu in menuItems" :key="menu.id">
        <md-list md-theme="none">
          <md-list-item>
            <h3 class="h3" >{{menu.titulo}}</h3>
            <md-list-expand>
              <md-list>
                <md-list-item class="md-button" v-for="item in menu.items" :key="item.id" @click.native="goTo($event, `/${menu.path}/${item.path}`)">{{item.name}}</md-list-item>
              </md-list>
            </md-list-expand>
          </md-list-item>
        </md-list>
      </div>
    </div>
```
It is part of the code of a menu, then when the app init, the menu is not shown, but when click in menu button the menu is shown. The error is that when you open the menu all md-list-expand are expanded and I need that all md-list-expand be  collapsed.

I wrote a code that worked when you clicked in button menu, but I need that always all md-list-expand be collapsed. So I need your help to solve this problem.

How to collapsed all md-list-expand when close menu?

Code, when you clicked in botton menu
```
let elements = document.querySelectorAll('.md-list-item.md-list-item-expand > button.md-button.md-button-ghost.md-theme-none')
elements.forEach((el) => {
  this.$helpers.eventFire(el, 'click')
})
setTimeout(() => {
   elements.forEach((el) => {
      this.$helpers.eventFire(el, 'click')
   })
}, 50)
```
The function eventFire trigger a event in the element given

**Comment by stramec** [comment]
Hi @fortil - Sorry I am a little unclear what it is you want to happen.

Do you mean you only ever want one menu to expand at a time, so when you click on a menu title, the other menus close?

If so you can achieve this my making each menu a list item. Currently you have it creating a new menu each time, so they act independently of each other.

[http://codepen.io/stramec/pen/bqevEW](url)

Again sorry if I've misunderstood, perhaps you could put up an example or fork the codepen?

**Comment by fortil** [comment]
Hi @stramec I'm sorry for the long time.

I have two question, really.
1-) I need a function that close all menus, because I have a current menu whitout `sidenav` so the menu is not display, then when it is display, all menus (li) are expand.
2-) My custom menu cover all screen like as then I need each menus in horizontal position but I can't get it, so I separate each one but I lose the automatic expandable and collapsible.

**Comment by fortil** [comment]
I try
```
for (let i in this.$refs) {
    this.$refs[i][0].toggleExpandList()
}
```
but not work.

**Comment by fortil** [comment]
Work it!!
```
      for (let i in this.$refs) {
        this.$refs[i][0].$children[0].toggleExpandList()
        this.$refs[i][0].$children[0].toggleExpandList()
      }
```
But, I believe that should it have` .close()` and `.open()`. It is a suggest.
Thanks!!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
