### ISSUE TITLE
 [mdSelect] Having 1000 options will make multi select components slow

### ISSUE THREAD

**Issue by JavaCS3** [vuematerial/vue-material#586]
### Steps to reproduce
select someting

### Which browser?

Chrome

### Reproduction Link

https://jsfiddle.net/javacs3/d3htyscu/7/

**Comment by Samuell1** [comment]
Same issue, not only select its slowly but every input https://github.com/marcosmoura/vue-material/issues/544

**Comment by marcosmoura** [comment]
I will improve this, but indeed, a select with 1000 items will make the page slow. It's not ideal.

**Comment by Samuell1** [comment]
@marcosmoura but not only for 1000 its slow but for few 50 - 200, i have countries select for example and its slow

**Comment by tomeragain** [comment]
Hello same issue, 
i have a table, and user can add rows dynamically,
on every row exists selects and inputs , when reach more than 40 elements,
the navigation through that inputs/selects is slow

**Comment by Samuell1** [comment]
@tomeragain i solved that temporary with simple search :/

**Comment by pablohpsilva** [comment]
We'll fix/optimize this ASAP.
I'm sorry, guys... We've a lot a things to build/fix and we're trying our best.
Thank you for your feedback @tomeragain :)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
