### ISSUE TITLE
 [mdSelect] will trigger set method on computed element during initilization

### ISSUE THREAD

**Issue by liufuyang** [vuematerial/vue-material#590]
Please check this simple code example, where `set` method of a `v-model` bounded on `md-select` is triggered during page initialization, however with standard `select` and `option` tag this won't happen.

http://codepen.io/anon/pen/yMaXeP?editors=1011

### Steps to reproduce
Goto this then see the console output, `set` of `userBirthdayMonth` is triggered when page initializing
http://codepen.io/anon/pen/yMaXeP?editors=1011

### Which browser?

Tried on chrome and firefox, both have this issue
Vue Material 0.71
Vue 2.1.10

### What is expected?
`set` should not trigger during initialization.

(One can try to change the `md-select` and `md-option` tp `select` and `option` this the `set` method won't trigger during initialization)

### Reproduction Link
http://codepen.io/anon/pen/yMaXeP?editors=1011

```
<div id="app">
  <md-layout md-flex-xsmall="100" md-flex-small="33" md-flex-medium="20" md-flex="10" md-flex-offset="1">
      <md-input-container>
        <label for="month">Month</label>
        <md-select name="month" id="month" v-model="userBirthdayMonth" >
          <md-option v-for="month in month_opt" v-bind:value="month">
            {{month}}
          </md-option>
        </md-select>
      </md-input-container>
  </md-layout>
</div>
```

```
Vue.use(VueMaterial)

Vue.material.registerTheme({
  default: {
    primary: {
      color: 'light-green',
      hue: 700
    },
    accent: 'red'
  },
  teal: {
    primary: 'blue',
    accent: 'pink'
  },
  purple: {
    primary: 'purple',
    accent: 'orange'
  }
})

var App = new Vue({
  el: '#app',
  data () {
    return {
      month: 1,
      month_opt: [1, 2, 3, 4]
    }
  },
  computed: {
    userBirthdayMonth: {
      get () {
        console.log('get method run')
        return this.month 
      },
      set (month) {
        // when first loading the page, this method should not run
        // if we replace md-select, md-option to selec and option, then
        // this set method won't trigger during page init
        console.log('set method run - should not run when page load ...')
        this.month = month
      }
    }
  }
})
```

**Comment by 3luyka** [comment]
@change.native?

**Comment by liufuyang** [comment]
@3luyka what do you mean? I don't have `change` called in js code.

**Comment by capttrousers** [comment]
Indeed, I've found this issue as well. 

I have a form with some md-selects, md-inputs, md-checkboxes. They are all using v-model on their computed props, with getters and setters. On page init or component init, the change event is triggered on all md-selects while it is not triggered on any of the other input components. All the input components are wrapped in the md-input-container element as well. 

I am not manually catching the events so I don't have @change to change to @change.native, it seems that on page/component init, the md-select inputs are triggering their change event and setting the current value of the v-model data prop which I think is unexpected behavior compared to the other input elements.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
