### ISSUE TITLE
[mdSelect] error toggle when keyboard navigate 

### ISSUE THREAD

**Issue by zcyzcy88** [vuematerial/vue-material#592]
### Steps to reproduce
https://vuematerial.github.io/#/components/select
use keyboard to navigate and toggle

### Which browser?
all

### What is expected?
Toggle the highlighted item

### What is actually happening?
Toggle the error item, when item below subheader
<img width="202" alt="2017-03-07 20_03_10-components - select - vue material" src="https://cloud.githubusercontent.com/assets/15178410/23655700/1e8ee9fc-0371-11e7-893c-7897d28c9f33.png">

---
May subheader cause the problem

**Comment by marcosmoura** [comment]
Yep. I will fix that!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
