### ISSUE TITLE
[core] Add pkg.module to package.json

### ISSUE THREAD

**Issue by rpjohnst** [vuematerial/vue-material#597]
Bundlers like Rollup and Webpack 2 can look for the `module` key in `package.json` to find an ES6 module to bundle ([more details](https://github.com/rollup/rollup/wiki/pkg.module) on why this is useful). Vue [recently added this](https://github.com/vuejs/vue/commit/1b6a7d4b87ae088d0f1bf0ce28460c5cddaadadd), so it would be nice for vue-material to provide it as well.

**Comment by Morgul** [comment]
@rpjohnst This should be a very simple thing to put into a PR. (Should just be setting `"module": src/index.js`, unless I'm missing something.) Would you be willing to put in a PR?

**Comment by rpjohnst** [comment]
I could, though there's a tradeoff between that and what Vue does, which is to produce a bundle that is an ES module. So it depends on what direction vue-material wants to go, I suppose.

**Comment by marcosmoura** [comment]
@rpjohnst You're right. I need to generate a new module in the dist folder. That's because I use some specific webpack loaders.

**Comment by rpjohnst** [comment]
Why was this closed? It doesn't look like the module key points to an ES module, but rather a UMD.

**Comment by Samuell1** [comment]
Its this possible in new VueMaterial 1.0.0 @marcosmoura ?

**Comment by rpjohnst** [comment]
@Samuell1 That is not pointing to an ES module, and thus will not work correctly.
