### ISSUE TITLE
 [mdSwitch] without v-model

### ISSUE THREAD

**Issue by fergardi** [vuematerial/vue-material#607]
Why the MdSwitch has not the :checked = checked property, as the MdCheckbox has, if they use the same functionality?

https://github.com/marcosmoura/vue-material/blob/36cd794ce92e45d55ca91384b572d80885b30af5/src/components/mdSwitch/mdSwitch.vue#L5

https://github.com/marcosmoura/vue-material/blob/36cd794ce92e45d55ca91384b572d80885b30af5/src/components/mdCheckbox/mdCheckbox.vue#L4

I'm just curious.

**Comment by capttrousers** [comment]
Is this going to apply to checkboxes too? From the Checkbox code linked above it looks like yea

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
