### ISSUE TITLE
 [mdTabs] MdDynamicHeight not working

### ISSUE THREAD

**Issue by fergardi** [vuematerial/vue-material#613]
Hello!

I'm trying to accomplish the following scenario: MdTabs sticked to top in a flex container, and its content scrollable if necessary. Tryied to set height 100% and md-dynamic-height to false, but not working. In the following example, the first tab keeps its height to 0 (autocalculated) until you switch to the next tab and get back, keeping the height of the second one instead of 100%.

http://codepen.io/fergardi/pen/LWebPO

I really need help with that. Thank you guys.

**Comment by rascoop** [comment]
Confirmed! md-tabs-content has a style with height: 0px on initial start of app. Changing to the next tab sets the md-tabs-content style with a height, but this is not set when returning to initial tab. **md-dynamic-height** has no effect.

**Comment by marcosmoura** [comment]
I will recreate the tabs logic to recalculate the size!

**Comment by lexwebb** [comment]
Any update on this? Having a large amount of issues with this myself.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by mdciotti** [comment]
I'm having this same issue on `1.0.0-beta-10.2`. I've gotten around the problem using custom CSS to simply override the dynamic height, but this isn't a universal solution. Perhaps it should be re-opened?

**Comment by Samuell1** [comment]
@mdciotti https://github.com/vuematerial/vue-material/issues/1768

**Comment by hbsoftco** [comment]
I have same issue. O.o
