### ISSUE TITLE
[mdTable] indeterminate checkbox state, darker separator

### ISSUE THREAD

**Issue by zcyzcy88** [vuematerial/vue-material#615]
Now, the top checkbox and separator when partial row select:
<img width="323.5" src="https://cloud.githubusercontent.com/assets/15178410/24107222/20bebd66-0dc5-11e7-9825-c134664818a1.png">

Expect like this:
<img width="262" src="https://cloud.githubusercontent.com/assets/15178410/24107159/0085cf3a-0dc5-11e7-80fc-8eb32fbcffd1.png">
(http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/paper-datatable-card/full-implementation.html)

**Comment by marcosmoura** [comment]
This will be done!

**Comment by ndevadas** [comment]
When I bind length of a data array to md-table-pagination like this v-bind:md-total="+products.length", both previosPage and nextPage buttons get dissabled.

**Comment by pablohpsilva** [comment]
@ndevadas could you please open a separate issue?
That will help us to fix this bug asap.
