### ISSUE TITLE
[mdRipple] Multi Ink Ripples

### ISSUE THREAD

**Issue by zcyzcy88** [vuematerial/vue-material#618]
If active too frequently, the last ripple will suddenly disappear:
![vue](https://cloud.githubusercontent.com/assets/15178410/24150591/1278e238-0e81-11e7-8b65-3c58321ba112.gif)

Should keep animating like [Polymer paper-ripple](https://www.webcomponents.org/element/PolymerElements/paper-ripple):
![poly](https://cloud.githubusercontent.com/assets/15178410/24150563/03df7d86-0e81-11e7-8e66-ce78d140f0ae.gif)

**Comment by Samuell1** [comment]
Added in dev! https://github.com/vuematerial/vue-material/pull/1419
