### ISSUE TITLE
 [mdInputContainer] value field not cleared in dialog

### ISSUE THREAD

**Issue by mmajcenic** [vuematerial/vue-material#619]
Greetings,

I am unsure if this behaviour is due to dialog or not, but the use case where I've noticed the issue is occuring in dialog.

Reproduction link is [here](http://codepen.io/Sarpedion/pen/RpMrZo).

Steps to reproduce:
Open the dialog and change the value of mdInputContainer. Upon closing the dialog, value to which input is bind is cleared. Then reopen the dialog and notice that mdInputContainer is shown like it still has input value:
![image](https://cloud.githubusercontent.com/assets/16826299/24152540/450aa414-0e4c-11e7-80b1-acd80f3f5ad9.png)

Upon inspection in Vue debugger, I've noticed that in this case, value in MdInputContainer and MdInput are not the same.

![image](https://cloud.githubusercontent.com/assets/16826299/24152683/a2f44602-0e4c-11e7-932d-62fae7adc496.png)

![image](https://cloud.githubusercontent.com/assets/16826299/24152720/b5a7fb54-0e4c-11e7-96e9-13a2e4389dfa.png)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
