### ISSUE TITLE
Support for MDI

### ISSUE THREAD

**Issue by Samuell1** [vuematerial/vue-material#626]
Hey, i using default material icons but i find some icons missing like female, male icons. Any possibility to implement this icon set for icon component?

https://materialdesignicons.com/

**Comment by Birssan** [comment]
This project uses the official Material Design Icons by Google => https://material.io/icons/

**Comment by Morgul** [comment]
@Samuell1 This is currently supported. You need to [include the MDI css][mdi], and then you can use the `md-iconset` property of `<md-icon>`:

```html
<md-icon md-iconset="mdi mdi-home mdi-light"></md-icon>
```

(Full docs here: https://vuematerial.github.io/#/components/icon)

[mdi]: https://materialdesignicons.com/getting-started

**Comment by Samuell1** [comment]
@Morgul Oh, I did not notice but thanks!
