### ISSUE TITLE
Unable to set disabled property of md-bottom-bar-item

### ISSUE THREAD

**Issue by diskman** [vuematerial/vue-material#629]
When I try to set disabled property of md-bottom-bar-item I got errors:

1. Trying to pass string true value
```
 <md-bottom-bar  class="fixobaixo md-accent">
    <md-bottom-bar-item :disabled="'true'"  @click.native="next()" md-icon="keyboard_arrow_right">Next</md-bottom-bar-item>
  </md-bottom-bar>
  </div>
```
Invalid prop: type check failed for prop "mdDisabled". Expected Boolean, got String. 
(found in <MdInkRipple>)

2. Trying to pass Boolean value
```
 <md-bottom-bar  class="fixobaixo md-accent">
    <md-bottom-bar-item :disabled="true"  @click.native="next()" md-icon="keyboard_arrow_right">Next</md-bottom-bar-item>
  </md-bottom-bar>
  </div>
```
Invalid prop: type check failed for prop "disabled". Expected String, got Boolean. 
(found in <MdBottomBarItem>)

**Comment by rascoop** [comment]
This is an HTML problem. All properties are converted to string. The way around it is to bind the property to a boolean value in data.

**Comment by Morgul** [comment]
@rascoop That's not quite his problem, as he's using `:disabled="false"` in the second example.

@diskman I've made a codepen demonstrating the disabled property working. Can you modify it to show how it breaks for you?

http://codepen.io/morgul/pen/vxrwKK

**Comment by diskman** [comment]
@Morgul I wasn't able to break your codepen. I use additional packages and now I am not sure is it problem of VueMaterial. Below is short version of component. I use vue-loader + ts-loader to build app. When I set  :disabled="true" then I have:

_Invalid prop: type check failed for prop "disabled". Expected String, got Boolean. 
(found in <MdBottomBarItem>)_

```
<template>
  <div>
    <span class="md-title">Some title</span>
  <md-bottom-bar  class="fixobaixo md-accent">
    <md-bottom-bar-item v-show="stepIndex>1" @click.native="prev()" md-icon="keyboard_arrow_left">Previous</md-bottom-bar-item>
    <md-bottom-bar-item :disabled="true" @click.native="next()" md-icon="keyboard_arrow_right">Next</md-bottom-bar-item>
  </md-bottom-bar>
  </div>
</template>

<script lang="ts">
  import Vue from 'vue'
  import Component from 'vue-class-component'
  import { Watch } from 'vue-property-decorator'
  import { State, Getter, Mutation, Action } from 'vuex-class'

  @Component({
    name: 'search-profile-wizard',
    components: {  } 
  })
  export default class SearchProfileWizard extends Vue {
    @State('done') done
    @State(s=>s.wizardprofile.stepIndex) stepIndex
    @Action('prevStep') prevStep
    @Action('nextStep') nextStep

    prev() {
      this.prevStep()
    }
    next() {
      this.nextStep()
    }
  }
</script>
```

**Comment by Morgul** [comment]
@diskman what happens if you set `:disabled="testVar"` and then make a test variable in the data portion of your component, and set that to true?

Since you're using typescript, I'm worried we might be misdiagnosing where that error is coming from, and it might just be out of date typings for vue-material... or something.

**Comment by Morgul** [comment]
@diskman Never mind! Turns out, you've found a bug:

https://github.com/marcosmoura/vue-material/blob/master/src/components/mdBottomBar/mdBottomBarItem.vue#L32

@marcosmoura The type for the `disabled` prop is wrong, and thinks it should be a string, not a Boolean like the docs say.

**Comment by diskman** [comment]
Thanks @Morgul just to add:

When I use 

`disabled:boolean = true`

to define property on component I have the same error when referencing 
`<md-bottom-bar-item :disabled="disabled" @click.native="next()" md-icon="keyboard_arrow_right">Next</md-bottom-bar-item>`

_[Vue warn]: Invalid prop: type check failed for prop "disabled". Expected String, got Boolean. 
(found in <MdBottomBarItem>)_
