### ISSUE TITLE
 [mdSelect] Uncaught DOMException: Failed to execute 'removeChild' on 'Node' when fast double click outside of a select element.

### ISSUE THREAD

**Issue by tiaod** [vuematerial/vue-material#632]
### Steps to reproduce
When I fast double click outside of a select:
![image](https://cloud.githubusercontent.com/assets/7500825/24242211/12f8f3ca-0ff2-11e7-8838-26154dccf004.png)
It throw out this error:
![image](https://cloud.githubusercontent.com/assets/7500825/24241878/3cffab4c-0ff1-11e7-8c31-70cee98b12ea.png)
### Which browser?
chrome on Windows7 x64

### Reproduction Link
https://vuematerial.github.io/#/components/select

**Comment by d-levin** [comment]
Same issue with https://vuematerial.github.io/#/components/menu

**Comment by pablohpsilva** [comment]
Hello everyone! :D 
That's because mdSelect uses mdMenu internally
Tagging this issue as a bug. Thank you guys for letting us know. :)
We'll fix it ASAP

**Comment by VdustR** [comment]
I think they are fixed in develop branch [here](https://github.com/vuematerial/vue-material/commit/ccbd39ac83f892d7f48e122e47cbc505b3b2d9d6#diff-fb3038b03b917990bd88faca7cbed997R210).

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
