### ISSUE TITLE
How to make a carousel with vue-material?

### ISSUE THREAD

**Issue by fortil** [vuematerial/vue-material#639]
Anybody have some idea?

Thanks!!

**Comment by d3radicated** [comment]
There isn't a carousel component at the moment. You can look forward to it though through here: #549

**Comment by Morgul** [comment]
I'm going to close this. You can track the carousel component in #549, or ask for advice on making your own on our slack channel: 

https://join.slack.com/vuematerial/shared_invite/MTgzMzU2NDQ5ODkwLTE0OTQ4MDI3MDAtNWYyZjhkNzEzMA
