### ISSUE TITLE
Event calendar

### ISSUE THREAD

**Issue by KaRkY** [vuematerial/vue-material#643]
I would like to have a component similar to [FullCalendar](https://fullcalendar.io/) for JQuerry.

**Comment by cawa-93** [comment]
I think that for these purposes it's better to use [vue-fullcalendar](https://github.com/CroudSupport/vue-fullcalendar), or to develop a separate plug-in from the vue-material. In turn, vue-material should remain simple components.

**Comment by capttrousers** [comment]
Or checkout this other vue-fullcalendar implementation that doesn't require jquery [vue-fullcalendar](https://github.com/Wanderxx/vue-fullcalendar)

**Comment by Morgul** [comment]
A date picker is part of the material design [spec](https://material.io/guidelines/components/pickers.html#pickers-date-pickers) and therefore on our roadmap. You can track the progress in #4.

**Comment by capttrousers** [comment]
@Morgul this issue is about a calendar view, not a datepicker input

**Comment by Morgul** [comment]
Ah, I misunderstood. In that case, then yes, that is outside the scope of the project. :smile:
