### ISSUE TITLE
[mdTable] Make md-table-header fixed in a table

### ISSUE THREAD

**Issue by web-surfer** [vuematerial/vue-material#645]
Here is an example table:

http://codepen.io/anon/pen/vxzzxV

Its been modified so that its its table height is set, and overflow is set to auto, so that the table itself gets a scroll bar after X number of rows. The md-toolbar also remains fixed.

But how can I get the **md-table-header** to also be **fixed** (the row that has Username and Tools in it)?

This is also a **feature request**.

**Comment by pablohpsilva** [comment]
I'm personally working on mdTable right now and this was (Yeap, I said was) the first thing I implemented.
Thank you! Soon you'll have it. I guarantee.

**Comment by pablohpsilva** [comment]
I have some work on a branch called table2, but... I'm not confident enough to roll it out yet, OK?
My plan are: Fix as many bugs mdTable I can, then enhance it.
You can check it out here: #787

**Comment by heyitskippy** [comment]
What about fixed header? I don't want to use jQuery for this in my project.

**Comment by pablohpsilva** [comment]
I started it a few weeks ago but I had to take care of bug fixes.
I'll resume my work on that ASAP :)

**Comment by EthraZa** [comment]
Is this happening yet?
I'm trying to do something like [this pen](https://codepen.io/zapping/pen/PKvPrP) but the table is losing the width and I can't find how to fix it.

**Comment by marcosmoura** [comment]
This is already done in the new 1.0 that will come in couple days.

**Comment by EthraZa** [comment]
Oh. Gonna stop wrestling it so. Thx

**Comment by marcosmoura** [comment]
Join our Slack community. I will send you a video demo with this functionality :)

**Comment by EthraZa** [comment]
Dude, I come back in shame. I looked at the manual, I searched at GihHub, I googled it! But can't find how to join a Slack community. The slack site says I need an invitation, what is kind of cumbersome, thinking about and comparing to Gitter. o.O

**Comment by marcosmoura** [comment]
It is in README, but here it is:
https://join.slack.com/t/vuematerial/shared_invite/MTgzMzU2NDQ5ODkwLTE0OTQ4MDI3MDAtNWYyZjhkNzEzMA

**Comment by zapping** [comment]
Is this what you are looking for #1018
