### ISSUE TITLE
Conflict with Leaflet.heat (heatmap don't show up)

### ISSUE THREAD

**Issue by Effects** [vuematerial/vue-material#647]
It resumes to a CSS problem.
If vue-material.css is loaded (regardless of loading order), Leaflet.heat simply won`t show up.
Any ideas?

**Comment by Effects** [comment]
It has something to do with canvas...

font-family:Roboto,Noto Sans,Noto,sans-serif}ul:not(.md-list)>li+li{margin-top:8px}audio,**canvas**,embed,iframe,img,object,svg,video{max-width:100%;

Removing that canvas reference, the error is gone.

**Comment by Samuell1** [comment]
Try override max-width for that element i thinks help, `max-width:none!important`

**Comment by Effects** [comment]
Solved! Thanks :)

**Comment by Morgul** [comment]
I'm going to close this issue. If you feel that there's an actual change that needs to be made to vue material (better css scoping, probably), please open a separate issue.
