### ISSUE TITLE
 [mdTheme] is overriding Leaflet css

### ISSUE THREAD

**Issue by rlightner** [vuematerial/vue-material#652]
The base theme is overriding the base CSS for Leaflet. Is there a way to not have it do this?

![image](https://cloud.githubusercontent.com/assets/354640/24536029/a7f934ae-158c-11e7-8860-ae37bcd11d61.png)

**Comment by Samuell1** [comment]
I think this replaces only colors for <a> tag ?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
