### ISSUE TITLE
[core] Low framerate & high memory usage with hardware acceleration enabled

### ISSUE THREAD

**Issue by sandhose** [vuematerial/vue-material#654]
### Steps to reproduce

Navigate around in [`vue-material`'s documentation](https://vuematerial.github.io/) with a webkit-based browser, and hardware-acceleration enabled.

### Which browser?
Safari 10.0.3 & Chrome 57 on macOS, on an early 2015 Macbook Pro (with an Intel Iris Graphics 6100)

### What is expected?

Consistent framerate across an app (in this case, `vue-material`'s documentation)

### What is actually happening?
As in #29, I'm `vue-material`'s doc on Chrome & Safari on macOS, when hardware acceleration is enabled.

It is because there is a *lot* of compositing layers created by the page. Each `.md-ink-ripple` is creating a layer because of the `will-change` property. Also, opening the Chrome devtool's layer panel makes chrome crash, forcing it to disable hardware acceleration.

Each `.md-tabs-wrapper` is creating a **huge** layer, because of the [`width: 9999em`](https://github.com/marcosmoura/vue-material/blob/master/src/components/mdTabs/mdTabs.scss#L120) property (seriously?), which takes a whole lot of memory, and making repainting really expensive. That's those kind of things that make the framerate drop to ~5fps when switching pages in the documentation.

![image](https://cloud.githubusercontent.com/assets/1549952/24547152/b7226392-160e-11e7-8088-e91961b775d2.png)

For example, the [buttons page](https://vuematerial.github.io/#/components/button) is creating 311 layers on Safari idle, taking 113Mb of GPU memory!

![image](https://cloud.githubusercontent.com/assets/1549952/24548569/1c5f434a-1616-11e7-86eb-ee925f511b8f.png)

In comparaison, `material-ui`'s documentation creates only 2 layers idle, with a couple more when animating, and takes less that 4Mb of memory.

---

**This is I think a really important issue!** I'd be happy to investigate further to fix those issues if you need help. I was about to use `vue-material` for a new project, but can't have those kinds of performance issues in my app, and I don't want to have to monkey-patch `vue-material` in my project to fix those issues.

**Comment by Morgul** [comment]
@sandhose I think you bring up some very valid points. (I've noticed some performance issues, but haven't dug into them yet. As bad as these issues might be, it works well enough for what I've needed to use it for so far.)

My recommendation would be to split up the work as best as you can, and submit some PRs. @marcosmoura  has only just come back from a vacation, so there's a long backlog of work to get through, and this is still a one man project. (There's some community desire to change this, but it hasn't happened yet.)

I am more than willing to volunteer my time to help test these changes (I have a wide variety of devices to test with), and try to get any wrinkles worked out so we can get the fixes in ASAP.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
