### ISSUE TITLE
how to define custom material themes

### ISSUE THREAD

**Issue by sombriks** [vuematerial/vue-material#656]
i'm looking for use the values bellow as a theme:

> 50 : '#f7e0e0',
> 100: '#eab3b3',
> 200: '#dd8080',
> 300: '#cf4d4d',
> 400: '#c42626',
> 500: '#ba0000',
> 600: '#b30000',
> 700: '#ab0000',
> 800: '#a30000',
> 900: '#940000',
> A100: '#ffbfbf',
> A200: '#ff8c8c',
> A400: '#ff5959',
> A700: '#ff4040',

let's call it 'bob'

i want to use the following line on my vue app:

> Vue.material.setCurrentTheme('about')

is there a way to define a theme using such values?

for now i was thinking about an idiom pretty straightforward:

> Vue.material.definetheme("bob",{
>   v50 : '#f7e0e0',
>   v100: '#eab3b3',
>   v200: '#dd8080',
>   v300: '#cf4d4d',
>   v400: '#c42626',
>   v500: '#ba0000',
>   v600: '#b30000',
>   v700: '#ab0000',
>   v800: '#a30000',
>   v900: '#940000',
>   A100: '#ffbfbf',
>   A200: '#ff8c8c',
>   A400: '#ff5959',
>   A700: '#ff4040'
> });

maybe it already exsists and i am simply misinformed.

any guidance is welcome.

**Comment by mix3d** [comment]
This has been added to the develop branch, and will be implemented in the next release :)
