### ISSUE TITLE
How do I pass information while using the confirm dialog?

### ISSUE THREAD

**Issue by jbmyid** [vuematerial/vue-material#658]
How do I pass the info while using the confirm dialog.
eg: I need confirmation to delete the item from list, i need to pass id but not able to get it.

```
<md-dialog-confirm
  :md-title="confirm.title"
  :md-content-html="confirm.contentHtml"
  :md-ok-text="confirm.ok"
  :md-cancel-text="confirm.cancel"
  @open="onOpen"
  @close="onClose"
  ref="dialog5">
</md-dialog-confirm>

<md-button class="md-primary md-raised" @click.native="openDialog('dialog5')">Confirm</md-button>
```

I can achieve that doing work around like caching the id while opening the dialog but dont want to got that path

**Comment by Morgul** [comment]
There's two approaches here. As you mentioned, you can cache the id (this is a very common pattern). However, what I've started doing is splitting lists of items up into single components. Inside that component, you can have a modal that only operates on that one item. It greatly simplifies the code, and removes the need for work arounds like caching the id.

**Comment by jbmyid** [comment]
Yes i did the same but really hate that. May be because I am yet to get familier with Vue and coming from angular.

```
<template>
  <div>
    <div v-on:click="openConfirm('confirmBox')">
      <slot></slot>
    </div>
    <md-dialog-confirm
      :md-title="confirm.title"
      :md-content-html="confirm.contentHtml"
      :md-ok-text="confirm.ok"
      :md-cancel-text="confirm.cancel"
      @close="onConfirm"
      ref="confirmBox">
    </md-dialog-confirm>
  </div>
</template>

<script>
export default {
  name: 'AvmConfirmClick',
  props: ['item'],
  data: function () {
    return {
      confirm: {
        contentHtml: 'Are you sure you want to delete?',
        title: 'Confirm',
        ok: 'Delete',
        cancel: 'Cancel'
      }
    }
  },
  methods: {
    onConfirm: function (type) {
      console.log('type', type)
      if (type === 'ok') {
        this.$emit('onConfirm', this.item)
      }
    },
    openConfirm (ref) {
      console.log('refs', this.$refs)
      if (this.$refs[ref]) {
        this.$refs[ref].open()
      }
    }
  }
}
</script>
```


This is what I have done.

**Comment by d3radicated** [comment]
<template>
        <div class="container">
            <md-dialog-confirm
                :md-title="confirmTitle"
                :md-content-html="confirmContent"
                :md-ok-text="confirmOk"
                :md-cancel-text="confirmCancel"
                @close="onCloseConfirmDialog"
                ref="confirmDialog">
            </md-dialog-confirm>
        </div>
    </template>

    <script>
        export default {
            data() {
                return {
                    confirmTitle: 'Title',
                    confirmContent: 'Content',
                    confirmOk: 'OK',
                    confirmCancel: 'Cancel',
                    confirmOnClose(button) {},
                };
            },
            methods: {
                openConfirmDialog(data) {
                    this.confirmTitle = data.title;
                    this.confirmContent = data.content;
                    this.confirmOk = data.ok;
                    this.confirmCancel = data.cancel;
                    this.confirmOnClose = data.onClose;

                    this.$refs.confirmDialog.open();
                },
            },
        };
    </script>

This is a hackish approach so that you can call only one function to open the dialog.

**Comment by ixcat** [comment]
Ran into this issue as well -

I was using the dialog/delete buttons inside another component which would render a list with 'delete' buttons -

What I did here is rather than using 'md-dialog-confirm', I did a 'raw' md-dialog (like the 'custom' example in the docs) in a v-for loop & bound the 'ref' attribute to the item ID in combination with a single handler function for open/ok/cancel in the main/outer component..

E.g.: template:

> <md-list ...
>   <md-list-item v-for="i in items"
>     <md-dialog ... :ref="'dialog' + i.id"> ...
>     <md-button @click.native="openDialog('dialog' + i.id)">

with the overall/outer component having:

> methods {
>   openDialog(id) { this.$refs[id][0].open() }

etc.

(The array index is necessary since v-bind in a v-for creates an array)
