### ISSUE TITLE
[SCSS] Scope vue-material styles down to a single container

### ISSUE THREAD

**Issue by mbraint** [vuematerial/vue-material#660]
I write a chrome extension. 
And when I include my app to page, apps make affected on page styles.  
I think has two ways to prevent it:

**1. Add scoped attribute like that:**
in root component
`<style src="../../../node_modules/vue-material/dist/vue-material.css" scoped></style>`
**In this case:** all child components don't see styles, because **scoped** attribute  applies only current 
[https://vue-loader.vuejs.org/en/features/scoped-css.html](url)
component. In order to this case vue-loader should be implements recursive applying scoped.

**2. Add more weight for styles like that:** 
`<style lang="sass">
    #app-container
        @import "../vue-material.sass"
</style>`
**In this case** 
- should be sass version of vue-material
- we should to pass in the mdTheme container id, because when we add weight for vue-material.css this weight become more then mdTheme

**I think that second case is best decision, but need some impovement for vue-material:**

1. Add to dist sass version
2. Add to registerTheme new param like container id
3. [https://github.com/marcosmoura/vue-material/issues/556](url)

2, 3 can be combined because, they required pass container id

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by jns1987** [comment]
Has anything been done towards this? I would like to have the styles inside of the components instead of importing a single css file that covers all components.

**Comment by VdustR** [comment]
You could **deep selectors** with scoped CSS.

[vue-loader scoped CSS](https://vue-loader.vuejs.org/en/features/scoped-css.html)
