### ISSUE TITLE
 [mdFile] emitting file name on 'input' event

### ISSUE THREAD

**Issue by DavidHavl** [vuematerial/vue-material#669]
Hello there,
I wanted to ask, is there a reason the md-file component emits filename string on 'input' event when normal (html) file input emits array of file objects?
this.$emit('input', this.filename);

In my case it is not playing well with vee-validator library because it is expecting a array of file objects just like normal input.

Thank you.

**Comment by d3radicated** [comment]
You can listen to the `selected` event as it emits the files.

**Comment by Morgul** [comment]
We should probably change the behavior to be compatible with normal html5 file inputs.

**Comment by pablohpsilva** [comment]
I'm onto it my friends.

**Comment by pablohpsilva** [comment]
Hello everyone.
I'll keep the input event as it is and create a change event, following the [MDN \<input type="file"\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file):
> [...] we add an event listener to the input for when its selected value changes (in this case, when files are selected) [...]
