### ISSUE TITLE
 [mdTooltip] stuck with vue-router on page change

### ISSUE THREAD

**Issue by Linzdigr** [vuematerial/vue-material#673]
I noticed the tooltip was stuck when its state is open and changing the page (the element linked to the tooltip beeing in a router-link).

Is it a known issue?

**Comment by pablohpsilva** [comment]
Hello @Linzdigr ! How are you?

Could you please send us a screen shot or something that could help us see/find the issue?

**Comment by Linzdigr** [comment]
Sure!

Mouse over element triggering the tooltip:
![image](https://cloud.githubusercontent.com/assets/8930392/24859744/3410caa2-1df2-11e7-8bbf-deea5e3910af.png)

This element is actually in a **router-link**. Clicking on it results in the "stucking state" of that tooltip on the next page.
![image](https://cloud.githubusercontent.com/assets/8930392/24859757/48a28ba4-1df2-11e7-9002-d918782b7447.png)

Here is the code used below:
```vue
<router-link :to="{ name: 'foo', params: { id: someId } }">
    <template v-if="isNew()">
        <i class="fa fa-asterisk new">
            <md-tooltip md-direction="bottom">Nouveau</md-tooltip>
        </i>
    </template>
</router-link>
```

**Comment by pablohpsilva** [comment]
Jesus... That's really odd. Have you tried to do something like this:

```html
<router-link :to="{ name: 'foo', params: { id: someId } }">
    <div v-if="isNew()">
        <i class="fa fa-asterisk new"></i>
        <md-tooltip md-direction="bottom">Nouveau</md-tooltip>
    </div>
</router-link>
```

Either way, I'll reproduce the issue here. Thanks for the fast reply @Linzdigr :D

**Comment by Linzdigr** [comment]
You're welcome :)

Yes I already tried to put the md-tooltip outside of the icon (that's why the **template** element is still present in my code). The same problem occurs.

The use of div don't do more :/

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by Linzdigr** [comment]
Is it possible to reopen this issue as it's still present in 1.0.0-beta-10.2?
