### ISSUE TITLE
Are you gonna implement new components like slider (input range), carousel and parallax in the future?

### ISSUE THREAD

**Issue by samuelnovaes** [vuematerial/vue-material#675]

**Comment by zapping** [comment]
Tracked issues on Carousel - #549 and Slider - #115

**Comment by Morgul** [comment]
In short, the answer is "yes".

The long answer is: "Yes. Please make an issue for each component you're interested in, if one does not already exist, and we will discuss timing and implementation."

As @zapping shared, two of the specific components you requested are already being tracked. Feel free to make a separate issue for parallax.

**Comment by tudor33sud** [comment]
are there any plans to include this carousel component on vue 1.0 beta? I'm not able to find any directions.
