### ISSUE TITLE
Pagination issue: Next page is not updated

### ISSUE THREAD

**Issue by wxqee** [vuematerial/vue-material#676]
### Steps to reproduce
0. open http://codepen.io/wxqee/pen/peMOJJ
1. bind `md-total` to `this.total = 0`, and change `this.tatal = 21` by setTimetout 800 seconds.
2. you can see next page is not updated.

### Which browser?
Chrome

### What is expected?
Next page '>' should be updated and be able to click for next page.

### What is actually happening?
Nothing happened to next page button.

### Reproduction Link
http://codepen.io/wxqee/pen/peMOJJ

**Comment by Samuell1** [comment]
Maybe its this? https://github.com/marcosmoura/vue-material/pull/625

**Comment by Morgul** [comment]
@wxqee Was your issue fixed by #625? If not, please reopen this issue.
