### ISSUE TITLE
 [mdRipple] effect doesn't work in buttons inside md-menu

### ISSUE THREAD

**Issue by yazfield** [vuematerial/vue-material#678]
### Steps to reproduce
Put a `md-button` inside `md-menu-content`.
### Which browser?

Vue: 2.1.10
Vue Material: 0.7.1
OS: Fedora 25
Chrome Version: 55.0.2883.87 (64-bit)
PS: No problem in Firefox 50.1.0
### What is expected?
Button should have ripple effect when clicked
### What is actually happening?

No ripple effect
### Reproduction link
[Codepen](http://codepen.io/yazfield/pen/wdwrqz)

**Comment by cawa-93** [comment]
Can you add a reproduce link to jsfiddle or codepen?

**Comment by yazfield** [comment]
@cawa-93 done

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
