### ISSUE TITLE
 [mdMenu] won't highlight with code mdMenuContent.highlightItem(direction) doesn't change highlighted index

### ISSUE THREAD

**Issue by iAlexanderMoon** [vuematerial/vue-material#680]
data.highlighted has a default false and so the logic in highlightItem will never change by issuing up or down via keys.

Suggesting Replace
```
        if (direction === 'up') {
          if (this.highlighted === 1) {
            this.highlighted = this.itemsAmount;
          } else {
            this.highlighted--;
          }
        }

        if (direction === 'down') {
          if (this.highlighted === this.itemsAmount) {
            this.highlighted = 1;
          } else {
            this.highlighted++;
          }
        }
````
With

```
        if (direction === 'up') {
          if (this.highlighted === 1 || this.highlighted === false) {
            this.highlighted = this.itemsAmount;
          } else {
            this.highlighted--;
          }
        }

        if (direction === 'down') {
          if (this.highlighted === this.itemsAmount || this.highlighted === false) {
            this.highlighted = 1;
          } else {
            this.highlighted++;
          }
        }
````

**Comment by iAlexanderMoon** [comment]
Additionally after making this change... I couldn't actually find any styles rules for md-highlighted as set on the item... I added a local style for this so I could see it change.... to be fair I don't really understand the how the themes work... but this may also be a bug.

**Comment by iAlexanderMoon** [comment]
Hmmm... this change doesn't seem necessary when the menu is opened with md-menu-trigger and arrow keys are used to navigate up and down. Calling menu.open() and menuContent.highlightItem('up') or  menuContent.highlightItem('down') directly does seem to require the change. Although I can't put my finger on the difference.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
