### ISSUE TITLE
 [mdInput] The difference of change event between md-input and input element

### ISSUE THREAD

**Issue by idjhuang** [vuematerial/vue-material#683]
The change event is fired for input element when value is changed and focus is lost, and event handler would get the new value of input element.
The change event is fired for md-input element right after value is changed, and event handler would get the original value of md-input element, seems the event is fired before the update of model value.
I suggest that we should make the change event of md-input element follow the same implementation of input element.

**Comment by emalihin** [comment]
I've been figuring out the file upload with md-input type="file" today and I've learned that 'change' events are not generally used with VueJs. More often people tend to use a watcher on the input field to react to the changes in the input data - give it a shot, chances are it will work for you.

**Comment by idjhuang** [comment]
Well, I think VueJs do support the change event. You may check the [jsfiddle](https://jsfiddle.net/idjhuang/8s43nbpa/1/).

**Comment by emalihin** [comment]
It seems like it. I had to use selected event on file input to retrieve the file list, however for simple reaction to the text input value change in your case you should be able to use the watcher:

```
  watch: {
    value: function () {
    	window.alert('New value: ' + this.value)
    }
  }
```

**Comment by emalihin** [comment]
note to self: don't reply before you had coffee. 
You are absolutely right, Vue does of course support change events. The few threads I found advised to use watchers, however none of them were about type="file". It'd be interesting to find out why change event doesn't work with md-input or md-file.

**Comment by Morgul** [comment]
The issues with `md-input type="file"` are being tracked in #669. As for the rest, I definitely support being as close to regular `input` elements as possible

**Comment by rajneesh290** [comment]
use (ngModelChange)="method()"

**Comment by dtruel** [comment]
Agreed.  It makes sense that when the changed function is called, the new value would be available.  When listening for a change, the old value is not very useful.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
