### ISSUE TITLE
<md-snackbar hover on button go to disappearing  and ignore Prop  :md-duration!

### ISSUE THREAD

**Issue by Leadaxe** [vuematerial/vue-material#684]
You can check it in example: 
https://vuematerial.github.io/#/components/snackbar

If you set delay (:md-duration) as 100000 and hover on button (NOT CLICK!) the  snackbar is disappearing instantly

**Comment by zapping** [comment]
The same issue is mentioned/tracked here https://github.com/marcosmoura/vue-material/issues/591?
