### ISSUE TITLE
Layout vertical alignment

### ISSUE THREAD

**Issue by daaru00** [vuematerial/vue-material#685]
[md-align layout property](https://vuematerial.github.io/#/ui-elements/layout) not have a middle, bottom or top alignment. 
How can I center a element  in "center middle" position?
I tried to do something like this
```html
<md-layout class="view" md-align="center" md-column md-gutter>
    <md-layout md-flex="50"></md-layout>
    <md-layout md-align="center" md-row md-gutter>
        <md-spinner md-indeterminate></md-spinner>
    </md-layout>
    <md-layout md-flex="50"></md-layout>
</md-layout>
```
but that's not elegant.

**Comment by d3radicated** [comment]
This feature has already been implemented in the `develop` branch via PR #562.

**Comment by ryanpager** [comment]
@d3radicated Appreciate it -- is there a timeline for getting this into an actual release, or is the best thing to just use develop right now?

**Comment by Samuell1** [comment]
@ryanpager i think yes, but you need to recompile develop

**Comment by ryanpager** [comment]
@Samuell1 Thanks, I just ripped out what I needed and put it into a css attribute system instead -- will hold me over til this gets into a release. Cheers.
