### ISSUE TITLE
 [mdList] List item link - no "rel" attribute

### ISSUE THREAD

**Issue by cjmaxik** [vuematerial/vue-material#690]
List item link has no "rel" attribute. 
`_blank` link w/o proper `rel` attribute can be [dangerous](https://mathiasbynens.github.io/rel-noopener/).

**Comment by Morgul** [comment]
@cjmaxik ah, good catch. Would you be willing to open a PR for this?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
