### ISSUE TITLE
 [mdButton] Focus state indicator on buttons

### ISSUE THREAD

**Issue by lulebe** [vuematerial/vue-material#694]
It seems like vue-material doesn't show any indications for focusing buttons via tabbing through the page for example. [React's material-ui](http://www.material-ui.com/#/components/flat-button) for example shows a little pulsating ink ripple on the focused button.

It would be a helpful feature for people who navigate the page with their keyboard and is especially useful in forms where you tab through the inputs and want to know when you reached the submit button. I think it is important to make material apps accessible, and this seems like an important step to me, that should be rather simple to implement.

I haven't yet gotten familiar with the internal code of vue-material, so I can't yet provide an example implementation or a pull request, but maybe someone else can. If not, I hope to eventually find the time to study the internals and submit the pull request myself.

What are your thoughts on this and can anyone give some hints where I could start my implementation?

**Comment by mycarrysun** [comment]
I would guess you could just activate the md-ink-ripple component on the focus event. I am not familiar with how the ripple works either and seems to not work unless I am on mobile anyways. 

Would be very happy to see if this goes into a PR.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
