### ISSUE TITLE
 [mdSelect] native Change doesn't work with md-select

### ISSUE THREAD

**Issue by Chalfouh** [vuematerial/vue-material#696]
### Steps to reproduce
<md-select id ='country ' name='country' @change.native='edit' >.... 
//apparently  my edit function is totally ignored
edit(event){
console.log('country changed...') // console doesn't log any thing
var id =event.target.id 
}
### Which browser?

chrome
### What is actually happening?

native change doesn't work
### Reproduction Link

http://codepen.io/anon/pen/ZKOWRZ?editors=1111

**Comment by d3radicated** [comment]
`md-select` already has the `change` event, not native though.`<md-select id="country" name="country" @change="edit">`

**Comment by Chalfouh** [comment]
Hi,
Here is my use case, i am trying to achieve a related select functionality and i need to access the
id of the first select item through 'event ,target.id'  in order to fetch appropriate data from the server
unless i am messing something here only the native event can give me access to that "id"
thank you

**Comment by d3radicated** [comment]
Why not set the `value` of `md-option` to the id?

`<md-option v-for="movie in movies" :value="movie.id">{{ movie.name }}</md-option>`

**Comment by Chalfouh** [comment]
because the md-select define a category in itself, let say i am going to fetch some country state list and then i am going to fetch the cities of that state, i need to know exactly what select item was used not only the option id.  and i am using the same function to fetch the data depending on the select id 
if id ==country fetch state
if id== state fetch cities

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by caseyprovost** [comment]
This is kind of against the grain isn't it? When forms are nested we want to do one way data flow instead of v-model's 2way binding. Because the select doesn't have a change callback there is no way to emit an event like `this.$emit('update', { field: field, value: value })`.  This is less than ideal as it writing out "watched" properties to emit the event with some odd data-flow between parent and child.
