### ISSUE TITLE
 [mdTabs] disappear when changing the viewport

### ISSUE THREAD

**Issue by brunocalou** [vuematerial/vue-material#697]
### Steps to reproduce
use keep-alive on the route containing the md-tabs

navigate from the component containing the md-tabs to another component, change the viewport size (resize your browser) and go back

### Which browser?
Tested using the following setup (versions come from the package.json on my project)

* Vue - ^2.2.2
* Vue Router - ^2.2.0
* Vue Material - ^0.7.1
* Browsers: All of them, from desktop to mobile

### What is expected?
To show the tabs as they were before

### What is actually happening?
When the size of the viewport changes and the component is not active, the computed property 'width' on the MdTab component is set to 0px. The keep-alive caches the component, so when it's brought back to the 'width' remains 0px

### Reproduction Link
https://codepen.io/brunocalou/pen/Mmeyzd

**Comment by brunocalou** [comment]
As a quick fix, I added this hook on my component that is using the tabs

`<md-tabs md-fixed ref='tabs'>`
```
activated () {
    this.$refs.tabs.calculateOnResize()
  }
```

The activated hook is called whenever a keep-alive component is activated. So I used it to recalculate the width

see https://vuejs.org/v2/api/#activated

**Comment by Morgul** [comment]
@brunocalou could you put in a pull request for this?

**Comment by brunocalou** [comment]
@Morgul sure #864

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
