### ISSUE TITLE
 [mdButton] keeps hover color on mobile devices

### ISSUE THREAD

**Issue by brunocalou** [vuematerial/vue-material#699]
### Steps to reproduce
Click on a md-button-toggle to make it active, then click it again

### Which browser?

* Chrome 56.0.2924.87
* Android 6.0.1
* Vue Material ^0.7.1
* Vue ^2.2.2

### What is expected?
The color of the md-button-toggle should return to the original color (white)

### What is actually happening?
The md-button-toggle keeps hovered on mobile devices. The :hover selector should be applied just for desktop

### Reproduction Link
https://vuematerial.github.io/#/components/button-toggle

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
