### ISSUE TITLE
This is some problem with Google CDN?

### ISSUE THREAD

**Issue by lovepluskaka** [vuematerial/vue-material#701]
The source of  font can't be loaded which causes the page to load very slowly.

**Comment by lovepluskaka** [comment]
This is the same problem on your website.

**Comment by Samuell1** [comment]
You can use font packages `material-design-icons-iconfont` and `roboto-fontface` instead of google CND

And then simply include in your main js file
```
import 'roboto-fontface/css/roboto/sass/roboto-fontface.scss'
import 'material-design-icons-iconfont/dist/material-design-icons.scss'
```

**Comment by lovepluskaka** [comment]
Thanks ! You solved my problem.
