### ISSUE TITLE
When was the last time version was incremented with new features

### ISSUE THREAD

**Issue by kgrosvenor** [vuematerial/vue-material#705]
I'm seeing a lot of issues raised on this project i was wondering weather it is still being maintained/improved with added components?

**Comment by Samuell1** [comment]
https://github.com/marcosmoura/vue-material/issues/598#issuecomment-294431199

**Comment by Morgul** [comment]
There have been some behind the scenes changes, and more outta moving forward again. :)

**Comment by kgrosvenor** [comment]
I believe this should be community developed and marscomasa should take donations so he can take the project on full time :P, i would happily make a monthly donation if components are set out and released in timely fashions

**Comment by pablohpsilva** [comment]
I agree with @kgrosvenor LOL
Lately @Morgul and I have been added to this project. I believe that soon enough @marcosmoura will open it for more developers.

Rest assured we are working behind the scenes right now but soon we'll bring you a new version with less bugs and awesome-shining-bright-new-features :D
