### ISSUE TITLE
Roboto 700 seems not to be necessary

### ISSUE THREAD

**Issue by Nirazul** [vuematerial/vue-material#710]
### Steps to reproduce
It's suggested that you include Roboto as follows:
`<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">`
However there doesn't seem to be code within the scss files that needs an actual 700 font-weight

### Which browser?
Doesn't apply

### What is expected?
Roboto 700 isn't necessary

### What is actually happening?
Roboto 700 is suggested, was it added for convenience as it's often used? Or for being applied with `<b>` and `<strong>` tags?

### Reproduction Link
Does not apply

**Comment by pablohpsilva** [comment]
Hello @Nirazul! How are you?
As you said, I couldn't find any scss using that weight.
This suggestion is useful if the developer wants to change the weight of a font to be strong.

I'll close this issue for now, OK? But thank you for pointing it out and opening this issue. :D

**Comment by Nirazul** [comment]
Sure, thanks for your reply!

**Comment by pablohpsilva** [comment]
I thank you @Nirazul !
