### ISSUE TITLE
Page background does not change when defining a custom theme color for background

### ISSUE THREAD

**Issue by Nirazul** [vuematerial/vue-material#711]
### Steps to reproduce
Look at the text in the codepen.

### Which browser?
all

### What is expected?
Text to be readable, background to be dark.

### What is actually happening?
When applying a background to the theme, the background color of the body does not change. The text however assumes a light color.

### Reproduction Link
http://codepen.io/Nirazul/pen/EmZVgz

**Comment by zapping** [comment]
This seems to be similar to #355

**Comment by pablohpsilva** [comment]
@Nirazul I'm closing this issue because there's another one opened: #355 
Thank you dude!
