### ISSUE TITLE
modify scss file

### ISSUE THREAD

**Issue by yondaimus** [vuematerial/vue-material#715]
Hi,

I would like to know how modify a scss file like MdSelect.scss and compile to update vue-material.css?

in fact i would change the size of the list generate when you clik on select box.

Thanks

**Comment by iamdevlinph** [comment]
I think it's easier to just override the styles that you want to modify instead of touching the base files.

**Comment by pablohpsilva** [comment]
Hello @yondaimus ! :D 
You can change the CSS/SCSS yourself. All you have to do is change the `md-select` class to change the mdSelect itself. But, be aware: mdSelect is composed, in general, by two main components: `mdSelect` and `mdMenu`. So, before changing the CSS, just take a look into the documentation, OK?

**Comment by yondaimus** [comment]
Thanks all :). But when i change a scss file, this doesn't compile so the changing aren't visible. If i change directly the CSS when i will build the SCSS f i thinks to the CSS file will be erase.

**Comment by pablohpsilva** [comment]
@yondaimus show us which, where and how are you changing SCSS files, if you may.

**Comment by iamdevlinph** [comment]
Don't forget to import your `custom-mdselect.scss` to the `main.scss` by
```css
@import 'path/to/file/scss'; //sometimes no need for .scss extension
```
