### ISSUE TITLE
 [mdTabs] broken when hiding/showing the bar and then resizing window.

### ISSUE THREAD

**Issue by philipfeldmann** [vuematerial/vue-material#719]
### Steps to reproduce
Hide a tab-bar (with v-show or jquery or whichever way you like), then resize the browser window and show it again. The tab-bar will be broken, not displaying any content, also the tab-bar-indicator will be  stretched over the entire width of the tab-bar (rather than only the current button). 

### Which browser?
VueJs 2, Vue Material 0.7.1, Windows, Chrome Version 58.0.3029.81

### What is actually happening?
Once you resize the window again or click on any button of the tab-bar it'll work fine again. v-if also works fine since the component is pushed into the dom again. This is only an issue with hiding/showing.

### Reproduction Link
https://codepen.io/PhilipFeldmann/pen/aWJmxW

**Comment by pablohpsilva** [comment]
That's suuuper weird! LOL...
I attached a gif to help people see what's going on. 
We'll fix it ASAP.
![weirdasfuckresize](https://cloud.githubusercontent.com/assets/2090635/26037883/8f82e4b4-38d3-11e7-9e0f-2336ac5c1c83.gif)

**Comment by stefan-hoehn** [comment]
Could someone please take care of it as it really breaks our application. Or is there anything where we can help out to fix it?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
