### ISSUE TITLE
How to set the md-table-head width??

### ISSUE THREAD

**Issue by skyflysun** [vuematerial/vue-material#720]

**Comment by enesunal** [comment]
Any way to do this?

**Comment by pablohpsilva** [comment]
Hello @skyflysun and @enesunal 
AFAIK the table-head component have CSS rules applied for tables and there's no directive nor anything like that today that could set the width. 

I've not tested it, but I think you could try to fix it using CSS.

I tagged this issue as a question. I'll let @marcosmoura see if this can be an improvement, OK?

Thank you guys :D

**Comment by CatsMiaow** [comment]
https://codepen.io/anon/pen/gRJGew
