### ISSUE TITLE
md-select multiple still selected after reset

### ISSUE THREAD

**Issue by meta0102** [vuematerial/vue-material#721]
https://jsfiddle.net/nh9kxk47/1/

when i reset the v-model on md-select the input text is set to null but the values are still ticked!

thanks

**Comment by Samuell1** [comment]
https://github.com/marcosmoura/vue-material/issues/575

**Comment by meta0102** [comment]
same result https://jsfiddle.net/nh9kxk47/2/

**Comment by pablohpsilva** [comment]
Hello @meta0102 and my firend @Samuell1 !

I fixed this issue on PR #749 
Soon you guys will have this bug killed.

Thanks for opening this issue :D
