### ISSUE TITLE
router-link breaks when tag="md-button"

### ISSUE THREAD

**Issue by a2bsoftware** [vuematerial/vue-material#722]
The router-link element is broken when the tag has md-button, this is with the latest version of Chrome in Windows.

Pretty easy to reproduce with the latest versions of vue.js, router and material.

I have to programmatically use the router push function if I want an md-button to change the view.

Is this a known issue? I couldn't find any other issues reported.

**Comment by d3radicated** [comment]
You can just do the following:

`<md-button @click.native="$router.push({ name: 'ToRoute' })">Go to Route</md-button>`

**Comment by a2bsoftware** [comment]
That is basically what I am doing at the moment as a work around.

The Button component examples on the Vue-Material website has a router-link example and therefore it is expected to work.
[(https://vuematerial.github.io/#/components/button)]

**Comment by pablohpsilva** [comment]
@a2bsoftware we'll fix this bug ASAP. The same issue can be found on #470 so I'm closing this issue and tagging it as a duplicate, OK?

Thank you both @a2bsoftware and @d3radicated
