### ISSUE TITLE
[core] Install via Bower

### ISSUE THREAD

**Issue by FernandoFranco** [vuematerial/vue-material#730]
Is it possible to add settings to use [Bower](https://bower.io/) as a package manager to install it?

**Comment by Morgul** [comment]
I'm not sure there's any settings to add. It looks like the project just needs to be [registered](https://bower.io/docs/creating-packages/#register) with bower, or you have to install with:

```
$ bower install vuematerial/vue-material
```

However, I will point out the notice on bower's site:

> "...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!"

I'm not sure it's sending the right message to officially support bower, especially since the command I gave you should work without any intervention on the vue-material's part.

**Comment by FernandoFranco** [comment]
Yes, but install with [over 100mb](https://github.com/vuematerial/vue-material/issues/734), and not contains bower.json file with main files, etc...
I install current with a bower.json like this:
```json
"dependencies": {
    "vue": "https://github.com/vuejs/vue.git#v2.3.2",
    "vue-material": "https://github.com/vuematerial/vue-material.git#v0.7.1"
  },
  "overrides": {
    "vue": {
      "main": "dist/vue.js"
    },
    "vue-material": {
      "main": ["dist/vue-material.js", "dist/vue-material.css"]
    }
  }
```

And using gulp and wiredep to make automatic inject script in html file.

But all scripts solved by bower.json in vue-material with fix the over 100mb issue

**Comment by Morgul** [comment]
If the 100mb issue were solved, would that resolve this issue? (My suggestion in #734 would work for bower, too.)

**Comment by pablohpsilva** [comment]
I agree with @Morgul .
Do you guys (including @marcosmoura here) think it would be cool to have vue-material on bower too? Personally speaking: I don't mind having it on both npm and bower.

**Comment by Morgul** [comment]
@pablohpsilva I think we should definitely fix the 100mb issue, and registering it on bower takes very little time. (There's not even a publish step, it just pulls from the tags on git.) So, sure, let's register it there.

**Comment by kirbyfan64** [comment]
On update on this?
