### ISSUE TITLE
 [mdTheme] TypeError: Cannot read property 'mdTheme' of undefined

### ISSUE THREAD

**Issue by lmj0011** [vuematerial/vue-material#731]
`"vue-material": "^0.7.1"`

I'm using this lib as a plugin in my VueJS project.

It's being imported into my project like this:

```js
// This code will be injected before initializing the root App
import Vue from 'vue'
import VueMaterial from 'vue-material'

// Activate plugin/component
Vue.use(VueMaterial)

// https://vuematerial.github.io/#/themes/configuration
Vue.material.registerTheme('default', {
  primary: 'white',
  accent: 'brown',
  warn: '',
  background: ''
})
```

whenever I run my app in `production` mode, VueJS throws this error in the console:

![vue-mat](https://cloud.githubusercontent.com/assets/9396189/25779397/60c41ad2-32dc-11e7-887d-c94a442c51e1.png)

**Comment by rumanbsl** [comment]
having the same issue

**Comment by rumanbsl** [comment]
I have found the bug in my use case. Incase you are using baibili to minify bundles, use { simplify: false }

**Comment by lmj0011** [comment]
>Incase you are using baibili to minify bundles, use { simplify: false }

thanks, I will try this.

**Comment by sanpoChew** [comment]
@rumanbsl that fixed it for me, did make my bundle a bit bigger so hopefully it's just a temporary workaround

**Comment by lmj0011** [comment]
@rumanbsl 

>Incase you are using baibili to minify bundles, use { simplify: false }

can comfirm this is a valid workaround

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
