### ISSUE TITLE
Some simple config

### ISSUE THREAD

**Issue by doespresso** [vuematerial/vue-material#732]
Could you provide simple and full webpack config 'for dummies'?
To:
1. Simple import VM (source) into my Vue entry file
2. Have ability to refactor components and SCSS styles, and use some external SCSS
3. Simply build with extract component and base styles

It's great library, but it's real "hardcore" for use if you're not an expert incase to change something.

Thx

**Comment by Morgul** [comment]
I wonder if we should add some [custom templates for vue-cli](https://github.com/vuejs/vue-cli#custom-templates). If we do that, and add some improvements to the documentation, that should ease the learning curve, I think.

**Comment by d3radicated** [comment]
It seems like @marcosmoura just created a [boilerplate for Vue Material](https://github.com/vuematerial/boilerplate).

**Comment by Morgul** [comment]
Oh, nice! That's exactly what I was thinking of.

**Comment by pablohpsilva** [comment]
I'll close this issue for now, since the [boilerplate for Vue Material](https://github.com/vuematerial/boilerplate) is being created.

@doespresso feel free to reopen this issue fi the solution is not good enough. Thank you :D
