### ISSUE TITLE
[core] Download releases is over 100mb

### ISSUE THREAD

**Issue by FernandoFranco** [vuematerial/vue-material#734]
Solution:
Add "dist/docs/releases" in .gitignore

**Comment by Stabzs** [comment]
Seems like this could be a PR...

**Comment by Morgul** [comment]
@FernandoFranco @Stabzs I'm not sure that releases is being included by mistake. It might, instead, be a better solution to add it to a `.npmignore` file. I'd want to check with @marcosmoura what the intention is about storing old releases.

**Comment by Stabzs** [comment]
@Morgul that's a perfectly fair observation, good point.

**Comment by gserrg** [comment]
Docs have recursion copy /dist/docs/releases/v0.7.2/docs/releases/v0.7.1/docs/releases/v0.7.1/docs/releases/v0.7.0
/dist/docs/releases/v0.7.1/docs/releases/v0.7.1/docs/releases/v0.7.1
