### ISSUE TITLE
Very simple template, Vue-material looks like not to be responsive

### ISSUE THREAD

**Issue by fraricce** [vuematerial/vue-material#740]
Hello everyone,
I'm a newcomer, so this issue might be due to  a lack of experience on the library.

Here's the problem: I have a very simple template that looks right on the browser, in full-size screen.  But when I switch to mobile screen (using chrome developer tools) I get a page where controls appear to be smaller...

Any idea? 
Thanks in advance!

Here's the template:

<template>
  <div>
    <md-button class="md-fab md-fab-bottom-right">
      <md-icon>add</md-icon>
    </md-button>
    <md-button>Default</md-button>
  </div>
</template>

Here's the screenshot of chrome in fullscreen

![screen shot 2017-05-10 at 22 47 10](https://cloud.githubusercontent.com/assets/2039075/25920597/ca15cf3c-35d2-11e7-90a1-ca5dd0e2235a.png)

Here the screenshot when I switch to mobile version (see how small are the controls!)

![screen shot 2017-05-10 at 22 47 21](https://cloud.githubusercontent.com/assets/2039075/25920620/d9d9c0fe-35d2-11e7-9c16-6a27f31c9119.png)

**Comment by Samuell1** [comment]
Hey, do you have in head?
```
<meta name=viewport content="width=device-width,initial-scale=1,minimal-ui">
```

**Comment by fraricce** [comment]
Hey Samuel1, that's crazy :) I didn't check such an obvious thing..
thank you very much :)
