### ISSUE TITLE
Swipable toolbar

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#741]
Can the toolbar be made swipable? Like for instance if there are a list of buttons, icons or links added to the toolbar and if the app is browsed on a mobile then there will be space restrictions. In this case it will be good to have a horizontally swipable toolbar.

**Comment by pablohpsilva** [comment]
Hello @zapping ! How are you?
I checked the [Material Design Guidelines](https://material.io/guidelines/components/toolbars.html) and I was unable to see that behavior from the toolbar component.

Perhaps you could aggregate option on a Sidebar or even add a menu to your toolbar. That would be more "Material Design" like.

**Comment by zapping** [comment]
@pablohpsilva going by Material Design Guidelines what you have mentioned is the right way to go, thank you.

**Comment by pablohpsilva** [comment]
I thank you @zapping !
Have a nice one
