### ISSUE TITLE
md-select multiple doesn't select items

### ISSUE THREAD

**Issue by d3radicated** [vuematerial/vue-material#742]
Items in `md-select multiple` component are not checked if they're AJAX loaded (or setTimeout).

[Codepen](http://codepen.io/dEradicated/pen/qRJapb)

**Comment by pablohpsilva** [comment]
Oh lord @d3radicated ... I'm looking into that ASAP
Thank you!

**Comment by pablohpsilva** [comment]
Done @d3radicated !
Fixed on PR #749
