### ISSUE TITLE
Documentation for button on router-link seems out of date

### ISSUE THREAD

**Issue by ddivecs** [vuematerial/vue-material#743]
[This doc page](https://vuematerial.github.io/#/components/button) claims buttons should work as follows when used with router-link

`<router-link tag="md-button" to="/components/button" class="md-raised md-primary">Router Link</router-link>`

this does not work. instead, i followed [the steps in this issue](https://github.com/vuematerial/vue-material/issues/470#issuecomment-279525154) and things worked

**Comment by pablohpsilva** [comment]
Hello @ddivecs this is super odd...
Like @marcosmoura said on #470 this will be delivered soon.

Thank you for opening this issue. It might be useful until this fix is not added to a new version.
