### ISSUE TITLE
Can't select text and e.g. copy to clipboard on disabled md-input

### ISSUE THREAD

**Issue by hlavki** [vuematerial/vue-material#744]
### Steps to reproduce

Try to select text

### What is expected?

Text is selected

**Comment by d3radicated** [comment]
I think you're looking for a `readonly` prop for `md-input`. It's not implemented yet.

**Comment by pablohpsilva** [comment]
Hello @hlavki !
As suggested by @d3radicated , I've just created a PR adding the readonly attribute. I'll close this issue. Follow up via #747 :)
