### ISSUE TITLE
 [mdMenu] Menu backdrop fading via md-active

### ISSUE THREAD

**Issue by Quantastical** [vuematerial/vue-material#745]
The Menu component adds a backdrop behind the active menu.

I wanted to have my backdrop a bit less opaque, so I adjusted the background color from rgba(0,0,0,0.005) to rgba(255,255,255,0.5). It works, but the backdrop flashes from nothing to semi-transparent instead of fading in from nothing to semi-transparent.

There is an `md-active` class applied to the backdrop that adjusts the opacity of the element from 0 to 1 that would work perfectly if done properly.

If the backdrop is added to the DOM without the md-active class and then the md-active class is applied immediately after, it should fade in. The harder part would be to remove the md-active class when the menu is closed, then remove the backdrop DOM element after the transition has completed.

Might be a nice improvement some day. I wasn't able to figure out how to do the "harder part" of my statement above.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
