### ISSUE TITLE
 [mdTabs] as anchors

### ISSUE THREAD

**Issue by doespresso** [vuematerial/vue-material#753]
Please help me modify <md-tabs> to use as static navigation links with <a href="...">, indicator animation, but without any content.

**Comment by pablohpsilva** [comment]
@doespresso the link is broken. Could you fix it so we can help you out?

**Comment by doespresso** [comment]
@pablohpsilva I mean https://vuematerial.github.io/#/components/tabs
not for list content, but for simple link navigation

**Comment by pablohpsilva** [comment]
You can use @click.native on tabs.
```
<md-tabs md-centered>
  <md-tab md-label="Movies" md-icon="ondemand_video" @click.native="functionThatRoutesTheUser">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt dolorum quas amet cum vitae, omnis! Illum quas voluptatem, expedita iste, dicta ipsum ea veniam dolore in, quod saepe reiciendis nihil.</p>
  </md-tab>
</md-tabs>
```

**Comment by doespresso** [comment]
@pablohpsilva native give nothing(

**Comment by pablohpsilva** [comment]
I'll dig it deeper ASAIC

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

New tabs supports router! https://vuematerial.io/components/tabs/home
