### ISSUE TITLE
 [mdTable] Moving a md-table will break its layout on windows

### ISSUE THREAD

**Issue by philipfeldmann** [vuematerial/vue-material#755]
### Steps to reproduce
If you wrap an md-table in a div with a fixxed size (let's say a wrapper with 1200px width) and then move it by adding more content above it, the layout will break. 
![md-table](https://cloud.githubusercontent.com/assets/6271103/26059000/770d308a-3980-11e7-9b05-98a1392f65ca.png)
Tested it on several of my colleague's macs / notebooks (always in chrome) and for some mac users it worked fine while it broke for others and it failed on windows every time. I couldn't find out why exactly it'll work on some machines, since it doesn't seem to be related to the OS.

### Which browser?
VueJs 2, Vue Material 0.7.1, Windows, Chrome Version 58.0.3029.81
Apparantly it seems to work in firefox...

### Reproduction Link
https://codepen.io/PhilipFeldmann/pen/zwaRNN

**Comment by pablohpsilva** [comment]
Thank you @philipfeldmann for opening this issue!
We're having some issues with mdTable and we'll fix it ASAP.

**Comment by vekexasia** [comment]
:+1: i'm experiencing this as well.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
