### ISSUE TITLE
Spinner! Is there any way to add the percentage of progress inside the spinner as it loads??

### ISSUE THREAD

**Issue by M-Hc0d3** [vuematerial/vue-material#756]
This is not for instant loading purposes in my project but rather a component that will progress over the day depending on what the user inputs so displaying the percentage of progress would be best. 

I understand the spinner is an SVG which is why putting anything between the `<md-spinner>` tag wouldn't work. Any other work-arounds?

**Comment by pablohpsilva** [comment]
Hello @M-Hc0d3 How are you? :D  
I was looking into [Material Design Guidelines](https://material.io/guidelines/components/progress-activity.html#) concerning Progress (a.k.a. Spinners) and there's no guideline about having percentage inside spinners. 

The only way to "show" progress is using [Progress bars](https://vuematerial.github.io/#/components/progress). 
Unfortunately, this feature won't be added. 

Thank you so much for using vue-material and opening the issue :)

**Comment by M-Hc0d3** [comment]
@marcosmoura  I'm sure its a feature that can be added then? Vuetify does theirs perfectly but I would not like to have to change libraries for my project for the sake of a spinner, which I'm sure is a feature many in the future will request, no?

**Comment by Samuell1** [comment]
@M-Hc0d3
> Vue Material is lightweight framework built exactly according to the Material Design specs.

**Comment by M-Hc0d3** [comment]
Looks like I'll just have to hack it them kmt
