### ISSUE TITLE
md-table on select select all issues

### ISSUE THREAD

**Issue by dekaulitz** [vuematerial/vue-material#757]
Hai, i found bug on the md-table when the selected all row on header the row will not selected and if your select the row the counting selected is worng countin number. i dont know why, im using like the demo exactly same.
I facing this trouble and didnt know how to solve it maybe anyone facing same problem like me and has solution im very apreciate if you want to share

cheers

**Comment by pablohpsilva** [comment]
Thank you @dekaulitz :D  
We'll fix it ASAP.

**Comment by rogergl** [comment]
Same problem here.

**Comment by pablohpsilva** [comment]
I think I fixed the issue on PR #787
Let's keep our conversation over there, OK?
