### ISSUE TITLE
[SCSS] Momentum scrolling is disabled

### ISSUE THREAD

**Issue by chriscalo** [vuematerial/vue-material#759]
### Steps to reproduce
1. In an iOS browser, visit [vuematerial.github.io](https://vuematerial.github.io/).
2. Try scrolling.
3. Now try scrolling on Github.com in the same browser.

### Which browser?
- Vue Material version: whatever is deployed at vuematerial.github.io
- Browser: Chrome 
- OS: iOS

### What is expected?
Momentum scrolling works

### What is actually happening
Momentum scrolling is turned off for some reason. This is really painful to use on a touch device and requires far more work than necessary to navigate around the web app.

### Reproduction Link
https://vuematerial.github.io/

**Comment by pablohpsilva** [comment]
The idea here is:
```
.module {
  width: 300px;
  height: 200px;

  overflow-y: scroll; /* has to be scroll, not auto */
  -webkit-overflow-scrolling: touch;
}
```
[Source](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/)

**Comment by chriscalo** [comment]
Thanks, @pablohpsilva. It that a proposal for a general fix to the `vue-material` source or something users of `vue-material` should apply to their applications?

**Comment by pablohpsilva** [comment]
I've pasted the CSS above as a reference :D 
We'll implement it soon enough.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
