### ISSUE TITLE
 [mdInput] label animation isn't smooth

### ISSUE THREAD

**Issue by nkovacs** [vuematerial/vue-material#760]
### Steps to reproduce
Click inside an `<md-input>` with a label that will animate from inside the input to above the input.

### Which browser?
- Chrome 58.0.3029.110, Firefox 53.0.2, Ubuntu 16.04
- Chrome 58.0.3029.83, Android 7.0

### What is expected?
A smooth animation. Vuetify's looks decent:
![out-1](https://cloud.githubusercontent.com/assets/2269242/26121977/3d1d1380-3a76-11e7-9a9e-e02d3d32f549.gif)

https://vuetifyjs.com/components/text-fields

### What is actually happening?
The text jumps around (I started with animation speed at 10% to make it easier to see):
![out](https://cloud.githubusercontent.com/assets/2269242/26122069/888916b6-3a76-11e7-8ef6-2e039607e0c8.gif)
![out-2](https://cloud.githubusercontent.com/assets/2269242/26122280/3b25e7f4-3a77-11e7-90e8-e3364392eb6d.gif)

In the second gif you can see it even with normal animation speed, it's especially noticeable when the "Textarea" input loses focus. It jumps around a bit.

### Reproduction Link
https://vuematerial.github.io/#/components/input

**Comment by nkovacs** [comment]
It looks like the font-size doesn't transition smoothly. Both vuetify and [mdc](https://material-components-web.appspot.com/textfield.html) use css transforms instead.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by nkovacs** [comment]
So, are you going to fix it in 1.0.0? The issue is still present in the dev branch.
