### ISSUE TITLE
md-menu without md-menu-trigger

### ISSUE THREAD

**Issue by Bolandish** [vuematerial/vue-material#761]
I would like to make a menu which is only triggered by Javascript and not VueJS component. 
Everytime i try to add md-menu without md-menu-trigger as child, it says
_You must have an element with a md-menu-trigger attribute inside your menu._

Any workaround ?

**Comment by pablohpsilva** [comment]
```
<md-menu>
    <i md-menu-trigger style="display:none;"></i>
</md-menu>
```
