### ISSUE TITLE
md-card - problem with image

### ISSUE THREAD

**Issue by monochromatique** [vuematerial/vue-material#762]
I store all my images in azure blob-container with straight access via http

When I use img-tag - all is ok.

But when I try to use md-card - CORS steps in the game.

Is there a way to use md-card with images, that store on another domain?

**Comment by pablohpsilva** [comment]
Hello @monochromatique 
I'm not sure what's going on with you code, but what you said makes no sense at all to me.
Check [this example](http://codepen.io/pablohpsilva/pen/QvZode) out. 3 different images from 3 different sources (no CORS). 

The issue might be in your app.

**Comment by monochromatique** [comment]
[Check THIS example out](https://codepen.io/anon/pen/ZKPdMP) )))

**Comment by pablohpsilva** [comment]
I still can see all the images, @monochromatique :(

**Comment by monochromatique** [comment]
Are you kidding me?  There is only ine image, others doesn't load.

 <md-card-media-cover md-solid> is the thing. Specifically - **md-solid**

**Comment by d3radicated** [comment]
It's because one of the images linked in the Codepen not in `https`. The image is still not found though when I changed it.

**Comment by lluisandreu** [comment]
This is still an issue, I confirm images does not load when <md-card-media-cover> uses md-solid but they do when I remove it.

**Comment by bahiaxip** [comment]
The same issue, md-solid and md-text-scrim only  allow me get one image from other server

**Comment by koikoishogun** [comment]
> 
> 
> The same issue, md-solid and md-text-scrim only allow me get one image from other server

Experiencing the same  is there a solution yet?

**Comment by bahiaxip** [comment]
One option is to remove the attribute (md-solid) and set one similar background. 
The best solution for me was create one resource from the server (Laravel) with his method file()
(response()->file($path_image)  and works
With Node I think that is response.sendFile(path_image). I hope that this can to help.

**Comment by koikoishogun** [comment]
Thanks went with vanilla css didn't want to touch my backend.
