### ISSUE TITLE
 [mdSelect] component has incomplete keyboard navigation

### ISSUE THREAD

**Issue by thdoan** [vuematerial/vue-material#764]
### Steps to reproduce
1. Go to https://vuematerial.github.io/#/components/select
2. Click "Movie" dropdown
3. Press G repeatedly

### Which browser?
Chrome 58.0.3029.110 (64-bit) on Windows 10 Pro.

### What is expected?
Every time you press G, it is supposed to cycle through items beginning with letter "G".

### What is actually happening?
Nothing happens. The only keyboard navigation supported appears to be Up/Down arrow keys.

**Comment by pablohpsilva** [comment]
Thank you! This looks like an improvement.
Thank you for letting us know @thdoan :D 
You rock.

**Comment by thdoan** [comment]
@pablohpsilva In all fairness, Vuetify also has poor keyboard navigation. The only Material select component that has complete keyboard navigation is Google's own -- just create a form in Google Docs and you'll see the difference :).

**Comment by pablohpsilva** [comment]
I got you @thdoan and I feel your pain (my clients too).
We're structuring some internal things and we'll roll this out ASAP, OK?
Thank you soooo much for helping us. We really appreciate it :D

**Comment by thdoan** [comment]
Awesome, thanks for the quick reply! Can't wait to see what you've got cooked up...

If this is tagged as "improvement", should I close this issue?

**Comment by pablohpsilva** [comment]
Please don't close it. I'll close this issue and all related with select as soon they are fixed/improved.
You're welcome and I'll consider [ARIA attributes](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/) 😉

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
