### ISSUE TITLE
Failed trying to import individual components only

### ISSUE THREAD

**Issue by mubaidr** [vuematerial/vue-material#765]
### Steps to reproduce
Try to register only individual modules from vue-material, like; 
```
import Vue from 'vue'
import VueMaterial from 'vue-material'
Vue.use(VueMaterial.mdCore)
```

### Which browser?
Latest vuejs, Vue-material, Windows 10, Chrome

### What is expected?
Component should be registered with vuejs

### What is actually happening?
```
Uncaught TypeError: Cannot read property 'installed' of undefined
```

**Comment by pablohpsilva** [comment]
That looks suspicious... We'll investigate.
Thank you @mubaidr ! If you have any clues, let us know.

**Comment by mubaidr** [comment]
This code piece looks suspicious to me, can you confirm pls? https://github.com/vuematerial/vue-material/blob/master/src/core/index.js#L10

**Comment by cars10** [comment]
I am having the same issue. Any update on that? I do not want to import everything.

**Comment by mubaidr** [comment]
@cars10 Developer is focusing on major version (i think rewrite).

**Comment by tangdw** [comment]
Vue.use(VueMaterial.MdCore)
Vue.use(VueMaterial.MdSpinner)

uppercasing the first letter

**Comment by cars10** [comment]
Thanks! That works. Maybe consider updating the docs?..
