### ISSUE TITLE
'selection-cirlce' of an icon inside a table cell has offset

### ISSUE THREAD

**Issue by rogergl** [vuematerial/vue-material#766]
Every time an icon is selected a gray circle appears for a short period of time around the icon. This circle has an offset if the icon is inside a table cell.

BTW: and the left top corner of the icon is cropped.

**Comment by pablohpsilva** [comment]
Hello @rogergl ! Could you please provide a gif or, even better, codepen example of the issue you're having?
That will help us out to get down to this issue and both fix it or help you :D

**Comment by rogergl** [comment]
Hi,

it's easy to reproduce. Just click on the pencil icon in the table 'Inline menus, edit icon and alternate headers' showcase.

**Comment by pablohpsilva** [comment]
I believe this issue was fixed on PR #787 :D 
![may-31-2017 12-52-39](https://cloud.githubusercontent.com/assets/2090635/26641174/1e21190a-4600-11e7-8475-1efef5d49370.gif)
