### ISSUE TITLE
 [mdSidenav] backdrop z=index issue when importing individual components

### ISSUE THREAD

**Issue by mubaidr** [vuematerial/vue-material#768]
### Steps to reproduce
-Add Sidenav to Header
-Add some white-frames to the page. 
-Open Sidenav

### Which browser?
Latest vuejs, Vue-material, Windows 10, Chrome

### What is expected?
Sidenav backdrop will be above all other content in the page

### What is actually happening?
Some content inside white-frame is interactive. (Above the backdrop) 

### Screenshot
![capture](https://cloud.githubusercontent.com/assets/2222702/26296072/74727d1a-3ee6-11e7-91a9-049e7cce018f.PNG)

**Comment by pablohpsilva** [comment]
Shit @mubaidr ... That's SUUPER weird!!!
Could you provide a codepen with the code? We're changing internal stuff in this project and a codepen is always welcome to help us out.

Dude, thank you for your help :D

**Comment by xiechao1211** [comment]
"vue": "^2.3.3",
 "vue-material": "^0.7.4",
i find the same question,can not import the individual components.

**Comment by zapping** [comment]
@pablohpsilva, a pen has been added to a similar issue #889

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
