### ISSUE TITLE
[core] In-Compatibility with https://github.com/chrisvfritz/prerender-spa-plugin

### ISSUE THREAD

**Issue by mubaidr** [vuematerial/vue-material#770]
### Steps to reproduce
Add  `prerender-spa-plugin` to webpack build
Build website `npm run build`

### Which browser?
Latest vuejs, Vue-material, Windows 10, Chrome

### What is expected?
Output build website should have theme applied.

### What is actually happening?
Theme for the output files is not enabled. 

### Reproduction Link
This is the source, you can see class name is correct inside the style tag with id `md-theme-default`, but somehow when this loads into browser, theme won't get applied. Somehow, theme names ( all occurrences of `.md-theme-default`) inside style tag are replaced by `.THEME_NAME` on page load in Browser. 

(If i continuously refresh page, i can see theme colors flashing for some moments.)

https://github.com/mubaidr/mubaidr.github.io/blob/master/index.html

**Comment by mubaidr** [comment]
Updated reproduction source link.

**Comment by pablohpsilva** [comment]
Hello @mubaidr ! How are you? :D 
We'll look into that ASAP. Thank you very very much!
Just to clarify some things for me: are you using developer or master's (npm) branch?

**Comment by mubaidr** [comment]
Hi, i am good thanks for the awesome work. I am using stable version. 0.7.1

If possible do let me know how i can help in debugging.

**Comment by mubaidr** [comment]
Seems like web-pack chunk sorting is source of the problem. Will continue investigation and update this.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
