### ISSUE TITLE
 [mdDialog] css outline visible when opened

### ISSUE THREAD

**Issue by badbrainz** [vuematerial/vue-material#771]
### Steps to reproduce
Open an md-dialog and then give it focus.

### Which browser?

Chrome 58.0.3029.96

### What is expected?
No outline when focused:
`.md-dialog-container:focus { outline: none; }`

### What is actually happening?
The shaded backdrop slightly hides it, but in my case I use a dark background with a transparent backdrop which made it more noticeable.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
