### ISSUE TITLE
 [mdSelect] multiple checkboxes appear broken on vue 2.3

### ISSUE THREAD

**Issue by ixcat** [vuematerial/vue-material#777]
Hello - 

Was attempting to use a 'multi select' component the demo docs; did not get the 'checked' detail on the left of the list items (only a box, no checkmark/animation rendered on select, rest of component appears ok). Researching for open issues I stumbled onto  the codepens in:

https://github.com/vuematerial/vue-material/issues/245
http://codepen.io/thoss/pen/BQexmm

https://github.com/vuematerial/vue-material/issues/672
http://codepen.io/jaydubyasee/pen/qrzNNr

and did some experimentation - the issue 245 one was not a multi select,
so I tweaked it to be, and got no checkbox -

cross checking against the issue 672 one which was already a multi, the checkbox worked.

Paring down further to a minimal example, this status stayed the same.

I then checked the 'config' settings for each and noted the working one was pinned to vue 2.1.6, the non-working was pinned to current (currently 2.3.3). Keeping the code the same and modifying the dependencies in each caused the breakage (e.g. vue > 2.2 failed, vue < 2.3 worked.). I did cross check specifically 2.2.6 vs 2.3.0 so it appears some interaction specifically with vue 2.3 causes the issue..

Since the above codepens are fairly minimal and tweakable for testing, didn't create a separate one.. can do if needed. The two together also isolate out static vs dynamic (v-for) list rendering, fwiw.

Obviously this could be a vue regression as well obviously.. 
Further pointers welcome as well.

Thanks in advance & for the library.

**Comment by pablohpsilva** [comment]
Hello @ixcat ! :D 
That's suuuuper weird, but, as you said, this could be a regression or something. I'll tag this issue as a bug and we'll look into it ASAP.

Thank you! :D

**Comment by tsunamilx** [comment]
Up. Having the same issue.

**Comment by jebu75** [comment]
Having same issue issue - thanks!

**Comment by hiporox** [comment]
Same issue here

**Comment by cw4inctec** [comment]
Same issue - any progress on this?

**Comment by bmondolot** [comment]
I had the problem with the 0.7.1 tag, but the 0.7.2 (released yesterday) seems to fix the problem.
