### ISSUE TITLE
Theme Background is too universal

### ISSUE THREAD

**Issue by mix3d** [vuematerial/vue-material#782]
I know that having a carefully crafted set of options is a fine balance, but I am finding the background color to be too strong. For example, it is quite common to have a light-grey background with a white card, but the theme's background setting colors EVERY background, so there's no way to control the contrast.

I know I can manually set the body color, but I have to be specific about overriding the theme's defaults, which signals to me that this approach should be re-thought. 

Thanks!

**Comment by pablohpsilva** [comment]
Hello! We're working on a hole new theme engine for vue-material.
Lighter, faster and easier to use. It won't be release for now, but you can check it's progress by going to [vue-material experiments](https://github.com/vuematerial/vue-material-experiments)
