### ISSUE TITLE
 [mdTabs] tab indicator initial positioning error

### ISSUE THREAD

**Issue by mix3d** [vuematerial/vue-material#784]
### Steps to reproduce
Use tabs that are right-floated

### Which browser?
Chrome, Firefox Safari

### What is expected?

tab indicator initial position matches the tab position

### What is actually happening?
Code appears to assume tabs are left-aligned, and scales the left side of the indicator all the way to the left side of the parent container.

### Reproduction Link
https://codepen.io/mix3d/pen/ybrKep

Happens quickly, but on every page refresh.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
