### ISSUE TITLE
md-tab native click don't work

### ISSUE THREAD

**Issue by doespresso** [vuematerial/vue-material#788]
Please, help me do some action (for example link href redirect for menu - I just visual md-tabs effect, and general link click logic) by md-tab click.
https://codepen.io/anon/pen/PmrNmx?editors=1111
Trying to use @click.native, but nothing happens ((

**Comment by d3radicated** [comment]
You can listen to the `change` event of `md-tabs`.

[Codepen](https://codepen.io/dEradicated/pen/xdvbVe?editors=1111)

**Comment by doespresso** [comment]
@d3radicated big thanx!
Could you hint, how can i catch also some param from md-tab, like an 'href' to make return.redirect to url?
