### ISSUE TITLE
 [mdSnackbar] How to make snackbar stay open

### ISSUE THREAD

**Issue by Andkoo** [vuematerial/vue-material#790]
I wanted to make my snackbar stay open as long as particular property in my data object is set to `true`. Simply setting `:md-duration="0"` for snackbar didn't work. Even if it did, it wouldn't solve my particular problem in which I want to keep my snackbar open as long as some data property value is `true`. I have found a solution for this:

`:class="{ 'md-active': someDataProperty }"`

on snackbar component and

```
mounted () {
  if (this.someDataProperty) {
    this.$nextTick(() => {
      this.$refs.mySnackbar.open()
    })
  }
}
```

in my Vue instance. Could you implement any custom prop on `md-snackbar` like
`stay-open="whileThisIsTrue"` ?

**Comment by pablohpsilva** [comment]
Since the snackbar behavior is
> Upon entrance, snackbars animate upwards from the bottom edge of the screen. When they appear, they do not block input.

This will be an improvement ASAP.

Thank you @Andkoo ! :D

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
