### ISSUE TITLE
 [mdSelect] dropdown position of md-select options

### ISSUE THREAD

**Issue by Mactaivsh** [vuematerial/vue-material#792]
Before, I was using md-select component as a input element. And I noticed that the position of the dropdown menu was always appeared on the top left of the select button. Even though this component actually using the md-menu which has a "md-align-trigger" attribute that allows me to controll the position of menu content. However, the md-select simply can't. I wish this component can add this feature that allows us to make adjustment of the select options position. Thanks!

**Comment by pablohpsilva** [comment]
I believe this can be easily done.
Tagging it right now.

Thank you @Mactaivsh !

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
