### ISSUE TITLE
 [mdMenu] Editable dropdown

### ISSUE THREAD

**Issue by Hidejec** [vuematerial/vue-material#793]
Can you implement an editable md-select. Here are the examples:
 [https://www.zoonman.com/projects/combobox/](https://www.zoonman.com/projects/combobox/)
[https://jsfiddle.net/Ewocker/bnad8os6/5/](https://jsfiddle.net/Ewocker/bnad8os6/5/)

**Comment by pablohpsilva** [comment]
Hello @Hidejec 
vue-material follows the strict rules from material design. If you can find any component on [material design](https://material.io) that supports your request, we'll implement it.

--- 
Couldn't you use an mcAutocomplete for it?

**Comment by Hidejec** [comment]
@pablohpsilva 
Ohhh yes yes I was the autocomplete feature. Thanks!
