### ISSUE TITLE
md-icon + router-link does not stick on the same line

### ISSUE THREAD

**Issue by kaijajan** [vuematerial/vue-material#794]
### Steps to reproduce
          <md-list>
            <md-list-item>
              <md-icon>home</md-icon>
              <router-link to="/" exact>Home</router-link>
            </md-list-item>
          </md-list>
### Which browser?

Vue 2.3.3
Vue Material 0.7.1
macOS
Chrome latest Stable version

### What is expected?
icon and text stick on the same line

### What is actually happening?

md-icon and router-link seperated in two lines

### Reproduction Link

Nope

**Comment by zapping** [comment]
I have tired adding your tags to a pen. Both the icon and text does stick on the same line. Checked on both chrome and firefox.

https://codepen.io/zapping/pen/GmVapv

**Comment by guanzo** [comment]
I'm having the same problem, there's definitely a weird interaction with `router-link` inside `md-list-item`. In your codepen, you neglected to add the vue-router library. 

Here's how it looks with vue-router: https://codepen.io/guanzo/pen/PjWBQX

Vue:
        ```
<md-list-item>
          <md-icon class="md-primary">home</md-icon>
          <router-link to="/" exact>Home</router-link>
        </md-list-item>

```

HTML:

`<li class="md-list-item">
   <i aria-hidden="true" class="md-icon md-primary md-theme-default material-icons">home</i> <a href="#/" class="md-list-item-container md-button router-link-exact-active router-link-active">Home</a> 
   <div class="md-ink-ripple">
      <div class="md-ripple" style="width: 1512px; height: 1512px;"></div>
   </div>
</li>`
Please reopen this issue.

**Comment by zapping** [comment]
@guanzo Can you try including your `<router-link>` in a `<span> or <div>` that should work. Like this

```
<md-list-item>
          <md-icon class="md-primary">home</md-icon>
          <div><router-link to="/" exact>Home</router-link></div>
</md-list-item>

```
or 

```
<md-list-item>
          <md-icon class="md-primary">home</md-icon>
          <span><router-link to="/" exact>Home</router-link></span>
</md-list-item>
```

or add this to your css
```
.md-list-item {
    display: flex;
    align-items: center;
}
```
