### ISSUE TITLE
 [mdTheme] Processing themes during runtime?

### ISSUE THREAD

**Issue by petr001** [vuematerial/vue-material#796]
Hi,
I've looked into the source code and saw, that all theme code is parsed in JS.

This is quite expensive operation (~130ms on my i7 processor), because of all those regex replacing and manually adding styles via JS.

Isn't better approach to setup themes during webpack compile time?

**Comment by pablohpsilva** [comment]
Hello @petr001 ! :D 
Dude, you're right. Theming is the first issue @marcosmoura is working right now. Soon the new code will be available and perfomance issues will be solved :D 
Thank you!

**Comment by petr001** [comment]
Any idea how long will it take?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
