### ISSUE TITLE
 [mdCard] Always apply md-text-scrim on card cover?

### ISSUE THREAD

**Issue by truongio** [vuematerial/vue-material#800]
Is it possible to always add the gradient effect? I've noticed the calculation doesn't seem to apply sometimes even though it's the same image. Maybe it could be because of rendering order or something but refreshing or scrolling sometimes automatically applies the gradient and sometimes it doesn't.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
