### ISSUE TITLE
 [mdSnackbar] can't close

### ISSUE THREAD

**Issue by chengzhixuan** [vuematerial/vue-material#801]
dbclick md-snackbar ,chrome throw warning "Unable to preventDefault inside passive event listener due to target being treated as passive" and md-snackbar can't close

**Comment by chengzhixuan** [comment]
dbclick md-snackbar ,chrome throw warning "Unable to preventDefault inside passive event listener due to target being treated as passive" and md-snackbar can't close

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
