### ISSUE TITLE
[SCSS] all li been overwriten

### ISSUE THREAD

**Issue by erw13n** [vuematerial/vue-material#802]
`ul:not(.md-list)>li+li { margin-top:8px }`

Those stylesheet is overwrite all li element.

**Comment by pablohpsilva** [comment]
Could you please provide what issue are you having with this css class?
Tell us what are you trying to do, so we can help you.

**Comment by pablohpsilva** [comment]
Could you please provide what issue are you having with this css class?
Tell us what are you trying to do, so we can help you.

**Comment by erw13n** [comment]
I my case, Vue-material CSS is load after Bootstrap, its been overwrite all li element, and give a margin gap on navigation menu after the first li element.

![image](https://user-images.githubusercontent.com/792847/27014742-fa08a7f4-4f28-11e7-976e-9d0516a65f0a.png)

**Comment by pablohpsilva** [comment]
Hello again! :D
You're using two UI frameworks on the same project? Wow... That's bold!

OK, I believe I can try to fix it :D

**Comment by bogish** [comment]
Not only about <li>, also ` img { max-width: 100% }` as example

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
