### ISSUE TITLE
 [mdInput] types allow v-model or v-bind:value w/ change event methods

### ISSUE THREAD

**Issue by capttrousers** [vuematerial/vue-material#805]
It'd be nice if the vue material input components like input/select/checkbox etc could support both the v-model or the v-bind / custom event method styles of data binding. 

Right now they're all requiring v-model objects either in computed props or the data object, but allowing one or the other data binding pattern could allow more complex data mappings. 

I think I've seen that this is on the road map for switches and checkboxes at least, see #607 .

For example you could have an array of values to map to a sequence of select menus, or an array of booleans to map to a sequence of checkboxes, or even map an object with all of its keys to a sequence of checkboxes like so:

```
md-layout(v-for="day in daysOfWeek")
    md-checkbox(:value="daysOfWeekList[day]", @change="toggleDay(day)) {{ day }}
```
where the toggleDay method is defined like so:
```
toggleDay(day) {
    this.daysOfWeekList[day] = ! this.daysOfWeekList[day];
}
```
and where the daysOfWeekList is defined like so:

```
daysOfWeekList : {
      'S'  : false,
      'M'  : false,
      'T'  : false,
      'W'  : false,
      'Th' : false,
      'F'  : false,
      'St' : false
    }
```

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
