### ISSUE TITLE
 [mdTabs] reactivity issue with vuex

### ISSUE THREAD

**Issue by mjmaenpaa** [vuematerial/vue-material#806]
### Steps to reproduce

- Create tabs with md-tabs
- Use Vuex store to manage state
- Access state with computed properties and Vuex getters
- Determine md-tab md-disabled state based on Vuex state
  - For example: `<md-tab :md-disabled="disabledStatus"></md-tab>`

### Which browser?

Vue: 2.3.3, Vuex: 2.3.1, Vue-Material: 0.7.1

### What is expected?

- When Vuex store changes, tab changes its disabled state to reflect what is in Vuex store.

### What is actually happening?

- When Vuex store changes, tab changes disabled state, but it is actually previous state and not current one.

### Reproduction Link

Small example with two components, vuex store and label printing value of the variable. Pressing button in second component should change disabled status of md-button and second md-tab in first component. Md-button changes disabled state correctly but md-tab does not.

https://codepen.io/anon/pen/LLEWRr?editors=1111

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by vaggelis2018** [comment]
@Samuell1 same here with toolbars. It is a big issue if u need to split code to smaller components
