### ISSUE TITLE
Documentation for mdFile component

### ISSUE THREAD

**Issue by DeanSh0w** [vuematerial/vue-material#807]
In docs for file component on https://vuematerial.github.io/#/components/file I couldn't find any events, that emits this component to handle file. There is no description for 'selected' and 'input' events (on file select), that I found in source code

**Comment by mycarrysun** [comment]
I was having trouble with this component the other day...tried to manually grab the emitted value from select (which is a File object) but couldn't get it to send to the server correctly. Has anyone had success with this?

**Comment by Samuell1** [comment]
Example with `axios`:

```
<md-file name="file" ref="file" v-model="filesInput" @selected="updateFiles($event)" accept="*"></md-file>
```

Methods: 

Dont forget to add axios: `import { put } from 'axios'`

```
  data () {
    return {
      filesInput: null,
      file: null,
      progress: 0
    }
  }
  methods: {
    updateFiles (event) {
      this.file = event[0]
    },
    async sendFile (file, request, progress) {
      const options = {
        headers: {
          'Content-Type': file.type
        },
        onUploadProgress (progressEvent) {
          progress(Math.round((progressEvent.loaded * 100) / progressEvent.total))
        }
      }
      return await put(request, file, options)
    },
    async uploadFiles () {
      const uploadFile = await this.sendFile(this.file, 'http://url.to.put.com/upload', (progress) => { this.progress = progress })
      console.log(uploadFile)
    }
  }
```

**Comment by pablohpsilva** [comment]
Enhanced documentation on develop. Thank you!
