### ISSUE TITLE
 [SCSS] CSS classes are not cascading properly for grid/flex

### ISSUE THREAD

**Issue by mix3d** [vuematerial/vue-material#808]
### Steps to reproduce
using the following template snippet:
```vue
<md-layout md-gutter>
  <md-layout md-flex-xsmall="100" 
                      md-flex-offset-xsmall="0" 
                      md-flex-small="80" 
                      md-flex-offset-small="10"  
                      md-flex-large="60" 
                      md-flex-offset-large="20">
   ... content ...
  </md-layout>
</md-layout>
```
On the xsmall size it still has an offset, because css classes .md-flex-offset-large-20 has a higher priority than .md-flex-offset-small-10, and md-flex-xsmall-0 doesn’t exist, I can’t reset the offset on smaller sizes.
[Example of the css cascade issue on Chrome](https://files.gitter.im/vuematerial/Lobby/gzjU/image.png)
### Which browser?
all

### What is expected?
What I’m _trying_ to do is make a card of a % based centered design, with 100% width on xsmall, 80% width on small, 60% on medium and up.

### What is actually happening?
There is no offset="0" style, meaning if `md-flex-offset-large` is specified, for example, you CANNOT reset back to default for smaller styles. Furthermore, the -large and -medium css specifications are lower in the CSS declaration than -small, so they will automatically overwrite the styles intended to take precedence at the -small screen size.

Because of the choice to make the flow classes desktop-oriented, (using `max-width` instead of `min-width`), this becomes a hard usecase to solve for. You have to use the largest-first approach, which is opposite of most UI frameworks, which are "mobile-first", with the default being 100% widths, and any screen-width size specification is applied to that break _and up_, whereas material-vue is _up-to-that-point_. 

I recognize to change this approach would break backwards compatibility, but aligning with other well-known ui breakpoint implementations makes sense.

### Reproduction Link
https://codepen.io/mix3d/pen/awzVBd

**Comment by nicoschmitt** [comment]
Same issue here.

**Comment by SyedAman** [comment]
+1

**Comment by Frizz925** [comment]
Any update on this?

**Comment by mix3d** [comment]
I doubt it. Most effort seems to be in the from-scratch overhaul.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
