### ISSUE TITLE
md-file does not trigger change on manual clear

### ISSUE THREAD

**Issue by ThomasRalee** [vuematerial/vue-material#809]
Hi,

There seems to be a bug with md-file, if i manually set the binding element to null. When i select the same file, the selected event will not fire. 

I am using this with cropperjs, so on the crop UI, theres a cancel event that will reset the input. But if i upload the same file again, the selected event will not fire.

Is there another way to flush the file selection on md-file? Other then: 
````
this.single = null
````

Great Framework by the way, love it.

**Comment by pablohpsilva** [comment]
I'll look into it ASAP. Thank you!! :D

**Comment by pablohpsilva** [comment]
Hello! I looked into it. Since you're using another library and it seems to be reseting the input, the truth is it is not. Internally the component still have the file data. That's why when you select the same file, it won't trigger the selected event.

What you could do to fix it: 
```html
<md-file ref="mdfile"... />
...
<script>
  // ...
  methods: {
    resetFile(ref) {
      this.$refs[ref].parentContainer.value = '';
      this.$refs[ref].textInput.value = '';
    }
  }
</script>

```
