### ISSUE TITLE
Issue with Vue 2.3.x and md-table md-selection

### ISSUE THREAD

**Issue by vin-e** [vuematerial/vue-material#810]
This issue was identified by @Mihail04 on the gitter channel. His codepen sample is listed below. To solve the issue you can lower the vue version <= 2.2.6.

### Steps to reproduce
To reproduce make your vue framework version any version >= 2.3.0

### Which browser?
Vue 2.3.x, vue-material 0.7.1, and only tested chrome on windows.

### What is expected?
When md-selection is used the check boxes are expected to update when clicking the check all and/or checking multiple check boxes. 

### What is actually happening?
If you check all then it doesn't show that the check boxes on the rows are selected. If you check multiple rows it will not check all but it will update the value correctly.

### Reproduction Link
[CodePen](https://codepen.io/Mihail_04/pen/OgPjPG)

Thanks.

**Comment by Samuell1** [comment]
https://github.com/vuematerial/vue-material/issues/795

**Comment by vin-e** [comment]
Sorry didn't see that ticket
