### ISSUE TITLE
md-dialog not workin properly

### ISSUE THREAD

**Issue by Rajashanmugam** [vuematerial/vue-material#811]
Hi,

it seems `this.$ref[ref].open()` not working when used with route containing params used inside created lifecycle hook.

`    created(){
          api.getRequest(userDetailUrl).then((detail) => {
            this.userDetails = detail.data;
            const p = {
              isLoggedIn: !!localStorage.getItem('email'),
              email: localStorage.getItem('email'),
              name: detail.data.name,
              createddt: detail.data.createddt
            };
            this.$store.commit('updateUserInfo', p);
            this.user = detail.data;
          }, (err) => {
            if (err.status === 0) {
              this.alert.title = 'Oops..,';
              this.alert.content = 'It seems server lost the connection';
              this.alert.ok = 'reload';this.alert.success = false;this.$refs['alertUser'].open();
            }
            console.log(err);
          });
    }` this code just works fine.
when comes to this 
`created(){
      let p = this.$route.params.token;
      let date = p.split('_')[0];
      console.log(Math.floor((Date.now() - new Date(parseInt(date))) / 60000));
      if (Math.floor((Date.now() - new Date(parseInt(date))) / 60000) > 30) {
        this.disabled = true;this.msg = 'Oops.., Link expired';
      }
    }` not working as expected providing err // open() not defined

**Comment by guanzo** [comment]
It's because the component isn't rendered yet. Try moving your code to `mounted`.
