### ISSUE TITLE
 [mdRadio] not responsive with long texts

### ISSUE THREAD

**Issue by truongio** [vuematerial/vue-material#813]
### Steps to reproduce

1. Create two radio buttons with long texts
2. Resize browser window to 400px wide

### Which browser?
Chrome

### What is expected?
Text shouldn't overlap and just move the radio button under further down

### What is actually happening?
Text overlap and radio button not circular

### Reproduction Link
https://codepen.io/anon/pen/ZyQemQ

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
