### ISSUE TITLE
can md-radio work with md-input-container/md-error?

### ISSUE THREAD

**Issue by leo108** [vuematerial/vue-material#814]
My code is:

```
<md-input-container :class="{'md-input-invalid': form.errors.has('transfer_type')}">
    <md-radio v-model="form.transfer_type" name="transfer_type" md-value="electronic">Electronic</md-radio>
    <md-radio v-model="form.transfer_type" name="transfer_type" md-value="mail_in">Mail In</md-radio>
    <span v-if="form.errors.has('transfer_type')" class="md-error">{{ form.errors.get('transfer_type') }}</span>
</md-input-container>
```

and it shows

![image](https://user-images.githubusercontent.com/1551716/26984769-4491e144-4d73-11e7-9bf1-7e8c46105976.png)

and

![image](https://user-images.githubusercontent.com/1551716/26984778-4fd72492-4d73-11e7-8486-03e040b9bf36.png)

**Comment by pablohpsilva** [comment]
```
```

**Comment by pablohpsilva** [comment]
That's because you can't use md-input-container containing a md-radio. Please, check the [documentation](http://localhost:8080/#/components/radio).

**Comment by leo108** [comment]
@pablohpsilva How can md-radio work with md-error?

**Comment by garymcm** [comment]
Looks like you are using VeeValidate, too. It seems the element must have both .md-error and .md-input-container invalid to work, or .md-error must be a child of a .md-input-container ([CSS](https://github.com/vuematerial/vue-material/blob/master/dist/vue-material.css#L1475)). 

I created my own radio group inline style and copied the relevant CSS to make it work.
