### ISSUE TITLE
slow, doesn't feel nice

### ISSUE THREAD

**Issue by elbarto132** [vuematerial/vue-material#815]
When i'm browsing the Demo https://vuematerial.github.io everything feels slow and sluggish, the animations look like they have just a few fps. Same in all browsers (Chrome, Firefox, Safari) on a Macbook Pro.
Don't know if this is a bug or this framework is always like this.

**Comment by pablohpsilva** [comment]
Could you provide more details? I'm not having the same experience you're having. Check it out:


![notslow](https://user-images.githubusercontent.com/2090635/27010747-3387d150-4e82-11e7-9644-1d3d5308fa92.gif)

**Comment by elbarto132** [comment]
Of course you can't see what i mean on a gif which has even been speeded up ;)
I made a Video: https://youtu.be/KvD7HQALOhA
After every click you can see that it takes some time until the content is shown, and the fade in transition looks like it's rendered with 10fps, same with the menu transition and the ripple effects.
This here for example runs totally smooth: https://vuetifyjs.com/vuetify/quick-start

**Comment by Klainer** [comment]
+1

**Comment by Soletiq** [comment]
+1
