### ISSUE TITLE
[core] in cellphone is very slow

### ISSUE THREAD

**Issue by c941010623** [vuematerial/vue-material#817]
apple iphone 7 => ios 10 and safri and chrome
when layout have scroll
all ui and scroll move so slow.....

**Comment by pablohpsilva** [comment]
Could you please provide any sort of way of testing it? 
Your issue is super wide and is hard for us to track down the issue

**Comment by Hidejec** [comment]
add `-webkit-overflow-scrolling: touch;` on the element with scroll. Do NOTE that it doesn't work if you put it in your CSS file. You need to use Inline Style for this.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
