### ISSUE TITLE
 [mdRipple] doesn't reappear after being un-disabled

### ISSUE THREAD

**Issue by MichaelFedora** [vuematerial/vue-material#818]
### Steps to reproduce

Create a button, start off enabled, disable it, and then re-enable it (all via the `:disabled` prop); there is no more "ripple" effect.

### Which browser?

Win10 x64, Chrome x64, Vue 2.3.3, Vue-Material 0.7.1

### What is expected?

That the ripple element would re-appear after being enabled.

### What is actually happening?

The ripple element doesn't re-appear after being enabled.

### Reproduction Link

https://codepen.io/anon/pen/QgNOvg

Top row of buttons are showing the bug in action, the bottom bar is normal.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
