### ISSUE TITLE
Icon buttons in table cells not aligned correctly

### ISSUE THREAD

**Issue by philBrown** [vuematerial/vue-material#821]
### Steps to reproduce

Create a table containing an icon button, eg

    <md-table>
      <md-table-body>
        <md-table-row>
          <md-table-cell>
            <md-button class="md-icon-button md-raised">
              <md-icon>star</md-icon>
            </md-button>
          </md-table-cell>
        </md-table-row>
      </md-table-body>
    </md-table>

### Which browser?

Only tried in Chrome so far (59.0.3071.86).
Vue 2.3.4, Vue Material 0.7.1

### What is expected?

Icons are aligned vertically and horizontally centred within the button boundary.

### What is actually happening?

Icons are aligned top-left.

### Reproduction Link

https://codepen.io/anon/pen/vZKgZq

**Comment by inful** [comment]
Confirmed in safari 10.1 (via codepen)

**Comment by zapping** [comment]
`.md-button.md-fab .md-icon, .md-button.md-icon-button .md-icon {position:relative}` adding this to css will align the icon.

**Comment by pablohpsilva** [comment]
I fix it on develop branch =]
Soon this fix will be available
