### ISSUE TITLE
Build Master -> No name attribute on inputs

### ISSUE THREAD

**Issue by Bolandish** [vuematerial/vue-material#822]
When i build the Master-branch its not adding the name-attribute to the input. 

Html:
![image](https://user-images.githubusercontent.com/7235443/27121496-ebd1367c-50e7-11e7-8f1a-34b529692ae1.png)

From element-inspector
![image](https://user-images.githubusercontent.com/7235443/27122323-9e319a08-50ea-11e7-88e1-5e7eddd81fb8.png)

**Comment by Samuell1** [comment]
In Vue on inputs doesnt exists `name` only `v-model`

**Comment by pablohpsilva** [comment]
This was fixed on develop branch. It is not yet on masters :)
