### ISSUE TITLE
 [mdTable] select is broken if rows were updated

### ISSUE THREAD

**Issue by yurykabanov** [vuematerial/vue-material#823]
### Steps to reproduce
1. Click `click me` button (loads new data)
2. Try to select all/some element

### Which browser?

Vue 2.3.x (latest)
Vue Material 0.7.1 (also I've forked repo and built fresh version to fix #795, bug still present there)

### What is expected?
New elements will present is the selected list, old elements will not.

### What is actually happening?

Selected elements are mixed with old ones.
1. In dist version selected elements will have ids: 1, 11, 12, 13, 15 instead of 11, 12, 13, 14, 15
2. In fresh versions selected elements will have ids: 13, 2, 3, 14, 15 instead of 11, 12, 13, 14, 15

Moreover it is possible to have more elements than there're in the list in newest version (e.g. after updating I can have list of 5 elements and have 7 elements selected)

### Reproduction Link

https://codepen.io/anon/pen/VWKQwP (for dist version)

**Comment by heyitskippy** [comment]
same here
can't properly add or remove row from the table

**Comment by Ken-Yang** [comment]
@yurykabanov , I have the same issue too.
The workaround is to downgrade your Vue version to 2.2.6, or build this repo from dev branch by yourself.

**Comment by iyedg** [comment]
Downgrading to Vue 2.2.6 worked for me too

**Comment by Ken-Yang** [comment]
@iyedg this issue has been merged to master now. you can upgrade your Vue version to the latest one and install vue-material 0.7.4.
