### ISSUE TITLE
[SOLVED] Tabs: Vue material Md Tabs on change & click event  + Eventbus

### ISSUE THREAD

**Issue by martinandersen3d** [vuematerial/vue-material#824]
After lot of headache, finally got most part to work, here is a solution for all the Tabs problems:

All works, but "event.target" gives varied results, see the console log. Else from that the getActiveTab and setActiveTab:0  works perfect, since they are not effected.

Enjoy ;-)
```
<!-- 

https://github.com/vuematerial/vue-material/issues/788
https://codepen.io/dEradicated/pen/xdvbVe?editors=1111

 -->

<script>
export default {
data(){
    return{
    getActiveTab:1,
    setActiveTab:0  // Sets which tab is the active one from start | integer based
    
    };
},

    methods: {
        onChange(tabIndex) {
        switch (tabIndex) {
            case 0:
                this.activeTab=0;
                console.log('0')
            break;
            case 1:
                this.activeTab=1;
                console.log('1')
            break;
        }
        },
        onTabClick(event){
            alert('hit')
            console.warn(event.target)
        }
    }//methods  
}//export
</script>

<template>
<div>

<md-tabs @change="onChange"  @click.native="onTabClick"  >
  <md-tab   :md-active="setActiveTab ==0">
    This is tab 1
  </md-tab>
  <md-tab   :md-active="setActiveTab ==1">
    This is tab 2
  </md-tab>
  <md-tab   :md-active="setActiveTab ==2">
    This is tab 3
  </md-tab>

</md-tabs>

  </div>
</template>
```

**Comment by martinandersen3d** [comment]
But how on earth do i get the emitted event from  the event bus?  This doesnt work:
`
mounted() { // Recieve
            eventBus.$on('change', (data) => {
                console.log(data)
                }
            );
}//mounted

`

**Comment by Kustopher** [comment]
Hi, I'm struggling with the md tabs as well. Thanks for the code! The switching between tabs works fine, but it's not working on page load. No matter if I load /page1 or /page2 or /page3 it's always loading /page1. This is because the change event is called on page load, and beeing the tabIndex=0 at this moment, it's loading /page1. Any idea how to prevent the change event to be fired on page load? Or any other solution? Would be great:)

**Comment by martinandersen3d** [comment]
Vie router Google it

**Comment by martinandersen3d** [comment]
Vue

**Comment by Kustopher** [comment]
I do use vue router, otherwise not even the switching from tab to tab would work.... The problem is the change event of md-tabs beeing triggered on page load although apparently no change happend at all.

**Comment by Kustopher** [comment]
Hi, I found a workaround by creating a variable on the `mounted` instance:

[https://codepen.io/kustopher/pen/dVmOgP](https://codepen.io/kustopher/pen/dVmOgP)
(check the console, here you can see what I mean by the change event beeing triggered on page load)

**Comment by pkimtani** [comment]
I know the it is already answered but there's a straight forward solution to this which I found today. May be it will help someone else.

`md-sync-route` property can be used with `<md-tabs>` tag and this shall keep the current active tab in sync with the route.

Ref [Here]


  [Here]: https://vuematerial.io/components/tabs
