### ISSUE TITLE
md-radio: How to repeat md-value?

### ISSUE THREAD

**Issue by CatsMiaow** [vuematerial/vue-material#827]
```vue
<div v-for="item in server.list">
    <md-radio name="selected" v-model="selected" :value="item.value">{{item.name}}</md-radio>
</div>
```
Error: Missing required prop: "mdValue"
<br/>

```vue
<md-radio name="selected" v-model="selected" md-value="item.value">{{item.name}}</md-radio>
```
md-value is "item.value" string
<br/>

Is there a way?

**Comment by Samuell1** [comment]
You need to bind it if you want to use it
`<md-radio name="selected" v-model="selected" :md-value="item.value">{{item.name}}</md-radio>`

**Comment by CatsMiaow** [comment]
@Samuell1 Thank you. object not allowed, but resolved.

https://codepen.io/anon/pen/BZQeZY
> Invalid prop: type check failed for prop "mdValue". Expected String, Boolean, Number, got Object.
