### ISSUE TITLE
Maxlength doesn't work with input type number

### ISSUE THREAD

**Issue by vitorcominato** [vuematerial/vue-material#828]
I'm with some trouble setting maxlength to a input type number.
The maxlength appear, but it doesn't limit when i type in the input field, as you can see below

"vue": "^2.2.6",
"vue-material": "^0.7.1",

![printissue](https://user-images.githubusercontent.com/1869108/27282825-152554f2-54c8-11e7-81f1-af035823b855.png)

``` html
<md-input-container>
    <label>CEP</label>
    <md-input type="number" maxlength="8"></md-input>
</md-input-container>

**Comment by d3radicated** [comment]
Since `md-input` is just a wrapped `input` element, the `maxlength` property is ignored on inputs with number type by design. More info [here](https://stackoverflow.com/a/18510925).

**Comment by vitorcominato** [comment]
Thanks!
