### ISSUE TITLE
 [mdSidenav] Bug in sidenav docs

### ISSUE THREAD

**Issue by digitalhydra** [vuematerial/vue-material#829]
Hey guys I think there is a issue in the docs, the sidenav won't close and the options are not clickable.
that happen upon loading, it was working 2 days ago, so maybe a new update get the bug.
https://vuematerial.github.io/#/

**Comment by Toomean** [comment]
https://github.com/vuematerial/vue-material/blob/1e0178ceb3e06fb75f306e99ce7fb0cbc958737c/src/components/mdSidenav/mdSidenav.scss#L18

This line breaks sidenavs

**Comment by cilqnd** [comment]
Switching the version in the header from 0.6.3 to version 0.7.1 will allow you to click sidenavs.

**Comment by digitalhydra** [comment]
I did, but in most components redirect back to the bugged version, the bug it's  not critical mainly it's just annoying.

**Comment by cilqnd** [comment]
@digitalhydra 
https://vuematerial.github.io/releases/v0.7.1/#/

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
