### ISSUE TITLE
mdTablePagination mounted() warning

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#830]
Vue development mode warning:

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "mdPageOptions"

found in

---> MdTablePagination

`this.mdPageOptions = this.mdPageOptions || [10, 25, 50, 100]`

**Comment by Fleeck** [comment]
Same issue here.
