### ISSUE TITLE
Website using development mode

### ISSUE THREAD

**Issue by ishitatsuyuki** [vuematerial/vue-material#833]
The current version of the docs site is using the development mode. This degrades performance.

**Comment by pablohpsilva** [comment]
Thank you for opening this issue @ishitatsuyuki ! 
We left it in development mode so users could use tools like [vue devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) to see events, and how data was being manipulated. It's a plus considering the documentation :D
