### ISSUE TITLE
 [mdIcon] v-html in md-icon

### ISSUE THREAD

**Issue by capttrousers** [vuematerial/vue-material#834]
https://github.com/vuematerial/vue-material/blob/b992c27a3b6407ae2fc836345dc91bcd32c1f379/src/components/mdIcon/mdIcon.vue#L2

Would it be more prudent to use the {{ }} mustache notation to interpolate the string value of the icon rather than v-html? 

I was just reading [this article on XSS](https://blog.sqreen.io/xss-in-vue-js/?utm_campaign=Revue%20newsletter&utm_medium=Newsletter&utm_source=revue) and I'm not too familiar with this attack vector but the only component that uses v-html in a way that the user isn't specifically asking for raw html interpolation is the icon component.

**Comment by pablohpsilva** [comment]
Thank you! Will fix it ASAP

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
