### ISSUE TITLE
Components - Onboarding not working.

### ISSUE THREAD

**Issue by webpackages** [vuematerial/vue-material#836]
`<md-boards :md-auto="true" :md-infinite="true" :md-duration="5000" :md-swipeable="true">
              <md-board id="slide1">
                <p>Text one.</p>
              </md-board>
              <md-board id="slide2">
                <p>Text two.</p>
              </md-board>
              <md-board id="slide3">
                <p>Text three.</p>
              </md-board>
            </md-boards>`

Error console
```
app.js:510 [Vue warn]: Unknown custom element: <md-boards> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
(found in <Root>)
```

**Comment by pablohpsilva** [comment]
Hello @webpackages !
I'm not 100% sure what's up with that but I'll take a look into it ASAP. Thanks for opening this issue! :D 

As a quick fix, I believe you could import the mdBoards straight from vue-material source on your node_modules and use it :)

**Comment by pablohpsilva** [comment]
Fixed

**Comment by CrixuAMG** [comment]
Possible related issue, I'm getting the same error with `<md-toolbar>`
