### ISSUE TITLE
Codepen Examples

### ISSUE THREAD

**Issue by marcosmoura** [vuematerial/vue-material#84]

**Comment by craigvantonder** [comment]
Do you just need codepen links to component examples as with the docs or what do you need help with exactly and how might we go about it?

**Comment by marcosmoura** [comment]
@craigvantonder I need every single example inside Codepen. A playable example of the same example in the Documentation. This shouldn't be created by hand, you know? Should be implemented using the Codepen API for better support.

Thanks for the interest in contribute with this project! :D
