### ISSUE TITLE
[core] Unable to load Vue Component to a vue-webpack2 project

### ISSUE THREAD

**Issue by bannewng** [vuematerial/vue-material#840]
Hi,

I am trying to include vue-material in a vue & webpack2 project.

main.js
```main.js 
import Vue from 'vue'
import App from './app'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'

Vue.use(VueMaterial)

/* eslint-disable no-new */
new Vue({
  // to define element
  el: 'body',
  components: { App }
})
```

Also included in index.html
```html
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
<link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
```

While I was trying to display on App.vue..

```vue

  <md-toolbar>
    <md-button class="md-icon-button">
      <md-icon>menu</md-icon>
    </md-button>

    <h2 class="md-title" style="flex: 1">Default</h2>

    <md-button class="md-icon-button">
      <md-icon>favorite</md-icon>
    </md-button>
  </md-toolbar>
```

I got the following warning
![warning from console](https://user-images.githubusercontent.com/14172209/27374012-e2980774-569c-11e7-9ba2-540d40f3a9a6.png)

![Able to load CSS](https://user-images.githubusercontent.com/14172209/27374011-e2979154-569c-11e7-9b09-06d29ae19380.png)

The CSS could be load & it's okay.
While the component, e.g. md-button or md-toolbar couldnot be load. 

I am new to vue, and thank you so much for you guys help :(~

**Comment by pablohpsilva** [comment]
Hello!! :D 
Could you please show us your App.vue?

**Comment by vannesachan** [comment]
Got similar issue.
When I include the vue component/element. i.e. 
`<md-button> button </md-button>`
it couldn't be displayed, nothing change. But when I try to do it as 
`<div class="md-button"> button </div> `
it could be display properly.
Yet, not all element can be displayed properly when use it as class, e.g. toolbar.

I suspect that i couldn't load the javascript component.

my main.js is like this
`import Vue from 'vue'
import App from './App'
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'

Vue.use(VueMaterial)
Vue.use(VueMaterial.MdButton)

/* eslint-disable no-new */
new Vue({
  // to define element
  el: 'body',
  components: { App }
})
`

**Comment by zapping** [comment]
@vannesachan you don't need the Vue.use(VueMaterial.MdButton) statement since the entire VueMaterial plugin in included in the previous statement. If you intend to include individual components then do check these issues which has the details #11 and #899. 

You might want to try changing the case in the use() statement. As mentioned in the latest issue #899

**Comment by vannesachan** [comment]
@zapping  Hi, I also tired using Vue.use(VueMaterial) only. got the same issue

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
