### ISSUE TITLE
Pagination not work in 7.0.2

### ISSUE THREAD

**Issue by husseinjahan** [vuematerial/vue-material#841]
### Steps to reproduce
browse to
https://vuematerial.github.io/#/components/table

### Which browser?
all browsers

### What is expected?
next page button must be active

### What is actually happening?
nextpage is inactive

**Comment by pablohpsilva** [comment]
I'll look into it ASAP. Thank you @husseinjahan :D

**Comment by daviddelucca** [comment]
@pablohpsilva  I have the same problem. The last version that pagination is working is on 0.7.1 - version 0.7.3 is broken too.

**Comment by shvelo** [comment]
The row count selector doesn't work too.

**Comment by pablohpsilva** [comment]
I believe @d3radicated fixed it on v0.7.4 guys. Could you please have a try and feed me back ?

**Comment by d3radicated** [comment]
The issue I fixed is for the `md-table` selection. I'll try to look into this. :D

**Comment by daviddelucca** [comment]
@pablohpsilva
Still not working on 0.7.4.

**Comment by hypercub3d** [comment]
Version 0.7.4.
The paginator seems to have an issue when the component is loaded from cache.

So let's say I have a table component loaded on route A. If I load the page on route A, then navigate to route B, and then back to route A, the paginator's forward and backward buttons are disabled.

It shows the correct number of items, and the correct row count, but I'm unable to navigate to a different page.

If I reload the page, the component works again, until I navigate away and back.

**Comment by Samuell1** [comment]
@hypercub3d same issue i have too

**Comment by bendo01** [comment]
vue-material: 0.7.4
vue: 2.3.4

i think i found the bug
on https://github.com/vuematerial/vue-material/blob/master/src/components/mdTable/mdTablePagination.vue

on data
```
data() {
        return {
            totalItems: 0,
            currentPage: 1,
            currentSize: parseInt(this.mdSize, 10)
        };
 },
```
it suppose 
```
data() {
        return {
            totalItems: this.mdTotal,
            currentPage: 1,
            currentSize: parseInt(this.mdSize, 10)
        };
    },
```

**Comment by hypercub3d** [comment]
@bendo01 I tried this change, and it does not seem to fix the problem for me.

**Comment by dixonwille** [comment]
@bendo01 you were close. But `this.mdTotal` can be string. I just added a line in `$nextTick` that will update `totalItems` appropriately on component load.

**Comment by CrustyJew** [comment]
@dixonwille if I'm not mistaken, that still has an issue if you are dynamically loading data. The total size used for the pagination disabling buttons is only calculated once when the component is mounted, but the property can change afterwards.

**Comment by levthedev** [comment]
Just chiming in here to say that I love vue-material but I can't use it until pagination works for me. 

Currently, copying and pasting in the pagination example from the docs produces a table that shows all of the items at once and won't let me change the number of rows per page or click to the next or previous page.

**Comment by Samuell1** [comment]
@levthedev for me works fine, do you define all options for pagination?

**Comment by levthedev** [comment]
@Samuell1  All options are defined, yeah. I've gotten it to mostly work now, with the only remaining issue being that the next page button is disabled except right after a full page refresh. So for example, if I navigate to another router view and then click back to my component with pagination, the next button is disabled until I do a page refresh.

**Comment by pablohpsilva** [comment]
The issue was fixed on #914 according to @dixonwille and @Samuell1 :D 
Thank you everyone! :D

**Comment by Samuell1** [comment]
@levthedev you need recompile after PR

**Comment by MRxiongyu** [comment]
I use the version 0.7.4, or encounter this problem

**Comment by dixonwille** [comment]
@MRxiongyu I encountered it in 0.7.4. It is on the develop branch now if you build it from there. Will have to wait for another release otherwise.
