### ISSUE TITLE
Vee-validate confirmed validation doesn't work in 0.7.2

### ISSUE THREAD

**Issue by hlavki** [vuematerial/vue-material#842]
### Steps to reproduce

Click on working example and try to edit email box. Then edit confirm email. When confirm email is same as original email, there is no error. When you try this in non working example (same code, only upgrade from 0.7.1 to 0.7.2), error is still there.

#### Working example:
https://jsfiddle.net/hlavki/xexpq0g7/

#### Non working example:
https://jsfiddle.net/hlavki/k1wg2j2f/

 

### Which browser?

All browsers

**Comment by pablohpsilva** [comment]
I'll look into it ASAP

**Comment by tidus30691nexus5** [comment]
0.7.2 not render name attribute  of element so can't work with vee valid but 0.7.1 it render.
please check and fix it.
![error](https://user-images.githubusercontent.com/28834552/27415815-7239860a-5733-11e7-9459-3f800393bd1a.png)

**Comment by pablohpsilva** [comment]
New release was lunched today with these changes :)
