### ISSUE TITLE
Docs and demo site is broken

### ISSUE THREAD

**Issue by assolsmile** [vuematerial/vue-material#848]
The documentation isn't usable, versions can't be changed. Please check the https://vuematerial.github.io.

**Comment by liuxue0905** [comment]
Change the size of browser, or visit the demo site by mobile phone. The Layout function do not work.

**Comment by superbogy** [comment]
same to me

**Comment by heyitskippy** [comment]
same

**Comment by pablohpsilva** [comment]
New release was lunched today with these changes :)

**Comment by JobJob** [comment]
Demo site seems down, it redirects to `http://vuematerial.io/` whose DNS address can't be found.
