### ISSUE TITLE
Defining and setting a custom theme is not working

### ISSUE THREAD

**Issue by petarpanicVIU** [vuematerial/vue-material#849]
### Steps to reproduce
Define a custom theme and set it afterwards globally with Vue.material.setCurrentTheme;

### Which browser?

Vue Material 0.7.2, Vue 2.3.4, every browser.

### What is expected?
The body element should have the theme set as a class.

### What is actually happening?
The body element is either empty or set to default theme

The last version that worked perfectly fine was 0.7.0.

**Comment by pablohpsilva** [comment]
We'll look into it ASAP. Thank you @petarpanicVIU :D
