### ISSUE TITLE
Tag 0.7.3 breaks simple md-select

### ISSUE THREAD

**Issue by bmondolot** [vuematerial/vue-material#851]
### Steps to reproduce
Go to the demo site : https://vuematerial.github.io/#/components/select
Click on one of the select element (the simple one, not the multiple selection ones)
Click on one of the value in the dropdown list

### Which browser?

At least Firefox and Chrome

### What is expected?
The value is changed on click

### What is actually happening?
Nothing happens (nor the drop down list closes nor the value is changed)

### Reproduction Link

https://vuematerial.github.io/#/components/select
(it's also true for the version select in the header toolbar)

**Comment by daviddelucca** [comment]
Or you could try select another version on header - switch version 0.7.3 to another one...it's not working :(

**Comment by filipesarturi** [comment]
Same here :/

**Comment by de5peratelighter** [comment]
Last working version of basic md-select is within 0.6.3 release.
https://vuematerial.github.io/releases/v0.6.3/#/components/select

b8f1f2e doesn't seem to resolve the issue for 0.7.3 version if applied manually, but I might be missing something;(

**Comment by pablohpsilva** [comment]
Fixed on develop and #853

**Comment by bmondolot** [comment]
The problem is indeed fixed in 0.7.4

Thanks !
