### ISSUE TITLE
md-autcomplete not working using list

### ISSUE THREAD

**Issue by devistar** [vuematerial/vue-material#859]
When I type a string, it returns a blank block. There are no results. when there should be. I also lose the focus of the field.

```html
<md-input-container>
       <label>Country</label>
       <md-autocomplete v-model="country" :list="countries"></md-autocomplete>
</md-input-container>
```

```javascript
...
data: {               
    country: '',
    countries: [
           'Belgium',
           'Luxembourg',
           'France',
    ]
 }
```

**Comment by pablohpsilva** [comment]
Try this:
```html
<md-autocomplete v-model="country" :list="countries" printAttribute="name"/>
```

```javascript
 countries: [
  { name: 'Belgium' },
  { name: 'Luxembourg' },
  { name: 'France' },
]
```

**Comment by devistar** [comment]
The results are displayed however there is no filtering, nor navigation with the arrows, nor possible selection. Is this normal? Should this be managed by the developer ?

**Comment by Samuell1** [comment]
@devistar filtering and other things for data you need to manage yourself

**Comment by pablohpsilva** [comment]
@devistar the filtering should be done by the developer because there's no guarantee way of telling how autocomplete should filter your data.

I'll check the issue with the menu
