### ISSUE TITLE
default md-input debouncing rate may be too long

### ISSUE THREAD

**Issue by jbonachera** [vuematerial/vue-material#861]
Hello !

I'm using an md-input in a login form, and when a user submit the form (using the keyboard), the model used in md-input often appears to be empty.

I searched around a bit, and it appears that the debouncing done in md-inputs since https://github.com/vuematerial/vue-material/pull/674 is causing this: if the user waits a bit before submiting the form, all is good.

I did not expect an input field from a UI framework to do debouncing (at least not so aggressively!), so a high default value induce a behaviour that is quite confusing to debug (i'm quoting myself: "but, why did it sent an empty password ?!").

I did not found a previous discussion / issue on this topic, so here is my question: isn't 300 ms too long for debouncing an input? There is often (in my opinion) less than 300 ms between the last keyboard input, and the submit input if the user is submitting a form with en Enter key.

I known debouncing rate could be lowered with a prop, but I think a lower default value could lead to a better user experience.
What do you think ?

### Steps to reproduce

Use an md-input in a form
Fill the md-input, then quickly submit the form

### Which browser?

Vue-Material 0.7.3 / Chromium 59 / Linux

### What is expected?

The entered value should be in the md-input model when submiting the form

### What is actually happening?

The entered value is truncated or empty

**Comment by Samuell1** [comment]
Debounce is only temporary to fix this issue: https://github.com/vuematerial/vue-material/issues/544

**Comment by Morgul** [comment]
300ms is probably too long, you're right. I feel like we should probably drop it to the minimum possible value that doesn't have the lag issue.

Additionally, we might want to ping the vuejs guys on the forum, to see if they have suggestions. Also, it may be that we need to have it fire on the leading and trailing edge, with a maximum time value. So, there's a lot of knobs we can turn here to improve the user experience.

**Comment by pablohpsilva** [comment]
Hello! On v0.7.4 I dropped it to 100ms minimum. If debouncing is troubling you, you could set it to 0 :D 

Like @Samuell1 said, soon this will be removed.
