### ISSUE TITLE
 [mdRatingBar] component missing in npm

### ISSUE THREAD

**Issue by thomasbrunier** [vuematerial/vue-material#862]
Hi there,
I installed vue-material with npm, but I can't find any mdRatingBar component inside the node_modules folder.

when I call `<md-rating-bar v-model="ratingValue" disabled></md-rating-bar>`, I got the following error :
`[Vue warn]: Unknown custom element: <md-rating-bar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Working with *vue-material@0.7.4*

Anything I'm missing on my side ?

Thanks for the awesome work.

**Comment by pablohpsilva** [comment]
I'll check it out ASAP. Thank you for opening this issue :)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
