### ISSUE TITLE
md-back-continue property on stepper md-step not working in 0.7.0

### ISSUE THREAD

**Issue by dedayoa** [vuematerial/vue-material#863]
### Which browser?
Vue 2.3.3, Vue Material 0.7.0, Chrome 58.0

### What is expected?
By setting md-back-continue on the last md-step, it should modify the "FINISH" to the string I assigned to md-back-continue

### What is actually happening?
"FINISH" is not modified. the property does not seem to have any effect.

**Comment by lfpoelman** [comment]
How did you resolve this issue? I'm currently having the same issue.

**Comment by dedayoa** [comment]
I didn't. I decided against using the component.
