### ISSUE TITLE
 [mdSelect] not displaying selected value if the selected value is stored as an integer in the model

### ISSUE THREAD

**Issue by durino13** [vuematerial/vue-material#865]
My md-select button is not displaying correctly the selected option, if the value in the model is stored as integer, but it works OK, if the value is stored as a string.

### Which browser?
Chrome Version 55.0.2883.87 (64-bit)

### What is expected?
The select box will display the correct selected value, when a form is displayed, not a placeholder text ..

### What is actually happening?
Instead of the selected value, the placeholder value is displayed. When I open the select box, I see that the correct option is selected though.

### Reproduction Link
https://codepen.io/anon/pen/GEMvdQ

Is this a bug? I want to store the ID values in the VUE model as integers, not as strings ..

**Comment by Samuell1** [comment]
I think its because `.toString()` https://github.com/vuematerial/vue-material/blob/master/src/components/mdSelect/mdOption.vue#L41

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
