### ISSUE TITLE
Docs website throws DNS error (vuematerial.io)

### ISSUE THREAD

**Issue by didimitrie** [vuematerial/vue-material#867]
Trying to access the docs on http://vuematerial.io/, getting a DNS error. Hope all is well! PS: sorry if wrong spot to report this.

**Comment by Samuell1** [comment]
Quote from Vuematerial slack:

> marcosmoura
> [6:33 AM] 
> @here The website is down for a maintenance! Basically we’re moving from vuematerial.github.io to our own domain vuematerial.io! \o/

**Comment by jan1993** [comment]
When is the site expected to be back?

**Comment by didimitrie** [comment]
hopefully as long as it takes for them dns record changes to propagate.

**Comment by oschettler** [comment]
Hopefully the DNS update goes through quickly. For me it helped to temporarily add the line
````
151.101.12.133  vuematerial.io
````
... to my /etc/hosts. The IP address is the one of _vuematerial.github.io_

**Comment by marcosmoura** [comment]
I switched back. Still available at vuematerial.github.io

**Comment by AgustinVargas11** [comment]
Still not available.

**Comment by djayd** [comment]
Yeah. Not available for us either. Is it possible to fork this and run the docs locally?

**Comment by AgustinVargas11** [comment]
@djayd yes

**Comment by Samuell1** [comment]
@AgustinVargas11 @djayd https://vuematerial.github.io is working for me, try flush dns in cmd `ipconfig /flushdns`

**Comment by emalihin** [comment]
actually the web server returns 301

< HTTP/1.1 301 Moved Permanently
< Server: GitHub.com
< Content-Type: text/html
< Location: http://vuematerial.io/

**Comment by Samuell1** [comment]
@emalihin use https://vuematerial.github.io/
