### ISSUE TITLE
Row deletion does not update md-table data / computed properties

### ISSUE THREAD

**Issue by iyedg** [vuematerial/vue-material#869]
When deleting an element form an array linked to md-table, the selectedRows data field and the numberOfSelected computed property do not update accordingly.

[Codepen reporoduction](https://codepen.io/iyedg/pen/WOodro)

**Screenshot from my actual project**
![bug](https://user-images.githubusercontent.com/2780980/27555725-b4f9c2b4-5aaa-11e7-8777-657e184903d9.gif)

Currently on **Vue 2.3.4** and **Vue-Material 0.7.4**
Tested on *Chrome Version 59.0.3071.109 (Official Build) (64-bit)* and Firefox *54.0 (64-bit)*

**Comment by pablohpsilva** [comment]
Fixed on PR #871
