### ISSUE TITLE
 [mdSteepDial] click issue when not expanded

### ISSUE THREAD

**Issue by capttrousers** [vuematerial/vue-material#870]
https://codepen.io/anon/pen/qjVdxp

Scroll down to the bottom to find the speed-dial.

What should happen:
- Clicking any of the buttons that fall underneath the expanded speed dial should be allowed if the speed dial is not expanded.

What happens:
- The buttons that are directly under the speed-dial are not clickable as the container div is as big as the button list will be when expanded and block any click events on the elements beneath.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
