### ISSUE TITLE
 [mdCheckbox] indeterminate

### ISSUE THREAD

**Issue by Hidejec** [vuematerial/vue-material#874]
### Steps to reproduce
1. Create an md-checkbox component with an id.
2. Using javascript, get the element by id. 
3. Set the indeterminate to true.
4. `var checkbox = document.getElementById('test-checkbox');`
    ` checkbox.indeterminate = true;`
5. Nothing happens.

### What is expected?
I'm expecting to see the checkbox on its indeterminate state.

**Comment by pablohpsilva** [comment]
Yeap! That's awesome.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
