### ISSUE TITLE
 [mdOnBoarding] within dialog has no content

### ISSUE THREAD

**Issue by Fleeck** [vuematerial/vue-material#875]
### Steps to reproduce
1. Use onboarding within dialog and open it.
2. You have to click or resize on order to see content

### Versions
Vue 2.3.3, VueMaterial 0.7.4, Chrome 59

### What is expected?
Content seen initially

### What is actually happening?
Content is not seen until user either clicks on directions or resizes window 

### Reproduction Link
Reproduced here: https://codepen.io/artur_js/pen/WOXppJ

P. S. Temporary fix - force programmatical click on the first item in the onboarding, like so :
`document.getElementsByClassName('md-board-header md-active')[0].click()`

**Comment by zapping** [comment]
A similar fix might help #697 ?

**Comment by fergardi** [comment]
Fixed using the @open event on the mdDialog calling this function:

`fix () {
      setTimeout(() => {
        document.querySelector('#slide1').style.width = '1px' // anything above 0px
      }, 0)
    }`

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
