### ISSUE TITLE
router-link on md-button not work

### ISSUE THREAD

**Issue by husseinjahan** [vuematerial/vue-material#876]
### Steps to reproduce
I've changed to PROP of router-link in button doc page but nothing happens, but when i changed the a href tag it works. 
In general router-link when tag is a custom component link md-button or md-option doesn't work. UI is OK but routing does not happen.

### Which browser?
I checked all browsers and i use Vue 2.

### What is expected?
We expect  when we use this code, it render a md-button that when we click on it route to /components/button1.

`<router-link tag="md-button" to="/components/button1" class="md-raised md-primary">Router Link</router-link>`

### What is actually happening?
It renders button but when we click on it, nothing happen.
I checked this with md-option tag to.

**Comment by martinandersen3d** [comment]
`  <md-button class="md-icon-button iconStyle"   @click.native='setRoute("projects")'>
    <md-icon >ondemand_video</md-icon>
    <md-tooltip md-direction="right">My Projects</md-tooltip>
  </md-button>



    methods: {
        setRoute(id){
            this.$router.push(id)
        },//setRoute
`

OR....

<router-link to="/components/button1" >
<md-button>
Router Link
</md-button>
</router-link>

**Comment by husseinjahan** [comment]
Thank you @martinandersen3d , I've did the same thing you suggested first.
but it's not solution, it's a trick, what if we use md-card, md-option and other components?

**Comment by martinandersen3d** [comment]
look in some of the threads in here, i remember one that looks something like <md-something @click=" {  router.push("/myurl")} ">  please write here when you find it

**Comment by martinandersen3d** [comment]
<md-button @click.native="$router.push({ name: 'project'})">Project</md-button>

https://github.com/vuematerial/vue-material/issues/785

**Comment by martinandersen3d** [comment]
you are probably going to use this sooner or later:

<md-button id="somename" @click.native="myMethod">Project</md-button>


    methods: {
        myMethod(event){
                alert(event.target.id) //will output "somename"
        }
    },//methods  


above is ES6 syntax

**Comment by pablohpsilva** [comment]
Thank you @martinandersen3d :D
