### ISSUE TITLE
How to change state of checkbox dynamically?

### ISSUE THREAD

**Issue by Hidejec** [vuematerial/vue-material#878]
I want to check the checkbox programatically.

**Comment by d3radicated** [comment]
Just change the value of the `v-model`.

**Comment by Hidejec** [comment]
It's not working

**Comment by Hidejec** [comment]
It's not working if I put it inside a function.

**Comment by d3radicated** [comment]
You mean a method function? It's working fine.

[Codepen](https://codepen.io/anon/pen/yXpQQX?editors=1010)

**Comment by Hidejec** [comment]
Ooops sorry, I found the problem why it was not working. It turns out that my code just have some logical issues. BTW Thanks for helping, it made me sure that this is indeed working.
