### ISSUE TITLE
 [mdToolbar] Text inside ".md-title" classed elements wraps inside "md-toolbar" when the content is too long

### ISSUE THREAD

**Issue by patoezequiel** [vuematerial/vue-material#880]
### Steps to reproduce
1. Put an element, let's say a `h1` header, with the `md-title` class inside a `md-toolbar` element.
2. Set the `flex` CSS property of the `h1` element with the value `1` (this prevents the `h1` element from wrapping and breaking the toolbar's layout).
3. Write a long title inside the `h1` tags.
4. The text inside the `h1` header now wraps and goes multiline when the width of the viewport is lower than its own.

#### Example

```
<md-toolbar>
    <h1 class="md-title" style="flex: 1">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis venenatis nisl, eu malesuada mauris. Praesent at mi sit amet justo pharetra volutpat sed non.
    </h1>
</md-toolbar>
```

### Which browser?
Vue 2.1.6
Vue Material 0.7.4
Chrome 59.0.3071.115
Windows 10 Pro v1703

### What is expected?
I expected the text inside the `md-title` classed element to hide the overflowing text and add an ellipsis to signal the overflow.

### What is actually happening?
The text inside the `md-title` classed element goes multiline when the viewport's not wide enough to show it in a single line.

### How did I mitigate the issue?
I applied the following CSS rules to the `md-title` classed element, to force it to a single line, clipping the overflow and showing an ellipsis at the end.

```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

### Reproduction Link
You can check this codepen for a comparison between the current behavior and the expected:

[https://codepen.io/PatoEzequiel/pen/EXodON](https://codepen.io/PatoEzequiel/pen/EXodON)

#### Pictures of the codepen

_The current behavior_
![image](https://user-images.githubusercontent.com/5291103/27673617-fa914dc8-5c77-11e7-95ef-27a55c913850.png)

_and the expected behavior_
![image](https://user-images.githubusercontent.com/5291103/27673641-1376d178-5c78-11e7-95d1-7410b9525378.png)

**Comment by pablohpsilva** [comment]
Very good enhancement. We'll make it happen. Thank you!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
