### ISSUE TITLE
How do I change background color for Snackbar?

### ISSUE THREAD

**Issue by Muyv** [vuematerial/vue-material#882]
### Steps to reproduce
Snackbar's background color is always in black,  there's no any effect when I change default theme or use scoped theme.

### Which browser?
Latest chrome.

### What is expected?
Change the background color according to scoped theme or provide a attribute to do this.

**Comment by Samuell1** [comment]
Snackbar doesnt have other color then black in material specs https://material.io/guidelines/components/snackbars-toasts.html#

**Comment by Muyv** [comment]
@Samuell1 Ok, I'm gonna find other way

**Comment by Samuell1** [comment]
@Muyv you can overwrite css i think, but accent, primary, warning snackbar will be cool
