### ISSUE TITLE
 [mdMenu] bug! 

### ISSUE THREAD

**Issue by c941010623** [vuematerial/vue-material#884]
i use 0.7.4 and 0.7.3 and 0.7.2 all have this bug
you can try it
http://vuematerial.io/releases/v0.7.2/#/components/menu
and click any one menu then
press TAB then press ENTER
then
press ESC ESC ESC (faster) and the error will show

docs.320e0ba5.js:3 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.t (http://vuematerial.io/releases/v0.7.2/docs.320e0ba5.js:3:13495)

how can  fix it ??

**Comment by pablohpsilva** [comment]
The issue here is the menu is not removing the events the right way. 
We'll fix it ASAP. Thank you :)

**Comment by VdustR** [comment]
Same issue: #632

**Comment by VdustR** [comment]
I think they are fixed in develop branch [here](https://github.com/vuematerial/vue-material/commit/ccbd39ac83f892d7f48e122e47cbc505b3b2d9d6#diff-fb3038b03b917990bd88faca7cbed997R210).

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
