### ISSUE TITLE
 [mdCheckbox] error styling

### ISSUE THREAD

**Issue by dionysiosarvanitis** [vuematerial/vue-material#886]
Is there any way to append validation error to checkbox similarly to text input? Any plan to support it?

**Comment by pablohpsilva** [comment]
Not yet, my friend... But we're working on it. Thank you!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.

**Comment by snarcraft** [comment]
Any update on this issue?
