### ISSUE TITLE
Maxlength not enforced on md-dialogue-prompt

### ISSUE THREAD

**Issue by gabrielbonner** [vuematerial/vue-material#887]
I'm expecting to see a character limit enforced for prompts, like in the fourth example here -http://vuematerial.io/#/components/dialog

However in my codepen (with the exact same code from above) you'll notice that there is no character limit - https://codepen.io/anon/pen/dReRwd

Even if I add `:maxlength="prompt.maxlength"` to the element, still nothing.

Thoughts?  :)

**Comment by zapping** [comment]
The property is `:md-input-maxlength` can you try with this one and check.

```
<md-dialog-prompt
    :md-title="prompt.title"
    :md-ok-text="prompt.ok"
    :md-cancel-text="prompt.cancel"
    :md-input-maxlength="prompt.maxlength"
    @open="onOpen"
    @close="onClose"
    v-model="prompt.value"
    ref="dialog5">
  </md-dialog-prompt>
```

**Comment by gabrielbonner** [comment]
@zapping Thanks, I'll try it on Wednesday, we have a holiday tomorrow in the US.

**Comment by gabrielbonner** [comment]
@zapping Yay, that worked, thanks.  Maybe updating the docs on the fourth example [here](http://vuematerial.io/#/components/dialog) would be in order so that other people don't have the same issue?

Thanks for your help.  👍
