### ISSUE TITLE
 [mdSidenav] issues

### ISSUE THREAD

**Issue by ordazgustavo** [vuematerial/vue-material#889]
Hi, Im experiencing some issues with the sidenav:
1. When I use `router-link` and try to bind a click event to the `md-list-item` that event does not work nor creating a method.
```
<md-sidenav class="md-left" ref="leftSidenav">
...
  <md-list>
    <md-list-item @click="$refs.leftSidenav.close()">
      <router-link v-bind:to="'/'"><md-icon>dashboard</md-icon> <span>Inicio</span></router-link>
    </md-list-item>
  </md-list>
</md-sidenav>

```
2. Also, I tried to use a fixed sidenav (`md-fixed`) but for some reason anything inside the sidenav can be clicked.

**Comment by zapping** [comment]
Seems like an issue https://codepen.io/zapping/pen/GmVapv . I tried adding a sidenav to the Setting and Backup menu. But for me the sidenav contents as such do not display.

**Comment by zapping** [comment]
The issue with Sidenav not showing up was due to horizontal scrollbar. Also the md-list-item has a z-index set to 2 but the sidenav and sidenav-backdrop has z-index 100 and 99. Hence the md-list-item was hidden behind the sidenav-backdrop. Adding the following css fixed it.

```
#app{
  overflow-x: hidden;
}
.sideNavListItem{
  z-index:101;
}
```

**Comment by zapping** [comment]
@ordazgustavo Please check the pen https://codepen.io/zapping/pen/GmVapv . The Settings and Backup menu option has the sidenav set. The click event works for the `md-list-item` both within and outside the sidenav.

**Comment by ordazgustavo** [comment]
Thank you @zapping, I'll try that. Yesterday I read that in orden to bind click events to nested components was using `@click.native` as you did

**Comment by pablohpsilva** [comment]
Can
