### ISSUE TITLE
 [mdTable] does not respond properly when binding data changes

### ISSUE THREAD

**Issue by sunziping2016** [vuematerial/vue-material#894]
I'm using vue-material^0.7.4.

It seems someone has forgotten to update the data filed `index` in `mdTableRow.vue`, which causes the `mdItem` watcher at line 57 actually messes up the data field `data` in `mdTable.vue`.

**Comment by sunziping2016** [comment]
Add this line just before Line 119 in `src/components/mdTable/mdTableRow.vue` may fix this bug.

    this.index = this.parentTable.data.length;

But it relies that the `key` of `mdTableRow` are set to the row index.

**Comment by hoopyfrood** [comment]
+1

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
