### ISSUE TITLE
header-item slot for mdTabs is not in latest release (0.7.4)

### ISSUE THREAD

**Issue by Nirazul** [vuematerial/vue-material#896]
### Steps to reproduce
The header-item slot for mdTabs is not in the latest release of `vue-material@0.7.4` as stated in the documentation.
According to this [PR](https://github.com/vuematerial/vue-material/pull/596) I thought that it would be in the next release. However, it's not...

### Which browser?
All browsers

### What is expected?
Ability to populate a slot for a custom mdTabs header.

### What is actually happening?
It's not included in the latest release, although the PR was already merged into develop.

**Comment by argarak** [comment]
I took a look at the history of src/components/mdTabs/mdTabs.vue (in the `develop` branch) and it appears that commit https://github.com/vuematerial/vue-material/commit/500e5b5beac99421b2440b976918a30b404b424f has removed the header-item functionality. I'll submit a PR to put it back shortly.
