### ISSUE TITLE
If manuel adding the value its not editable (md-input)

### ISSUE THREAD

**Issue by Bolandish** [vuematerial/vue-material#897]
When i manually adding the value-attribute on md-input its not possible to edit the value.
Check my video : https://www.dropbox.com/s/49d6gp6hyb2kzxr/can%27t%20delete.mov?dl=0

**Comment by zapping** [comment]
If you can give the code or a pen it will be great. Unfortunately by seeing the video its tough to guess your code. But I tried adding an md-input with the following to a pen

```
<md-input-container>
    <Label>Label in tag</Label>
    <md-input value='set using value'></md-input>
</md-input-container>
```
It seems to be working well. The code is in this pen https://codepen.io/zapping/pen/bBPyOz. Try manually changing the value of 'Label in tag' md-input component.

**Comment by pablohpsilva** [comment]
Hello guys! @Bolandish could you please check @zapping codepen?
I'm closing this issue for now. Feel free to reopen it
