### ISSUE TITLE
Vue-material 0.7.4 md-input-container input font-size set to 1px and label does not move above input box.

### ISSUE THREAD

**Issue by jdjd1118** [vuematerial/vue-material#898]
### Steps to replicate
Set up md-input-container

### Which browser?
Tested in Chrome 59.0.3071.115 and Firefox 54.0

### What is actually happening?
Label does not move and text is set at 1px in CSS.

### Reproduction Link
https://jsfiddle.net/e0zr5gp7/5/

**Comment by zapping** [comment]
You have used the default html `<input type="text">` please replace it with Vue-Material input component  `<md-input type="text">` and try.

**Comment by jdjd1118** [comment]
Wow I feel stupid :)  Thanks a lot.
