### ISSUE TITLE
 [mdButton]  fix documentation

### ISSUE THREAD

**Issue by j4k0bk** [vuematerial/vue-material#901]
Button Toggle - no documentation on how to apply it to a model. Please describe this, as the documentation on Button Toggles is very vague.

**Comment by d3radicated** [comment]
You can't bind `v-model` to `md-button-toggle` nor the `md-button`'s inside it.

**Comment by pablohpsilva** [comment]
We'll look into it ASAP. Thank you!! :D

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
