### ISSUE TITLE
Documentation mistake！

### ISSUE THREAD

**Issue by Mini256** [vuematerial/vue-material#902]
Hello, Sir : I think you make some mistakes in the documentation,

First of all,Please turn to [the page of stepper](http://vuematerial.io/#/components/stepper)  ,the PROPERTIES 'md-back-continue' should be corrected to ‘md-button-continue’.

And why did you not write down "import 'vue-material/dist/vue-material.css'" or "require('vue-material/dist/vue-material.css')" in the  ''[Getting Started](http://vuematerial.io/#/getting-started)" page.

**Comment by pablohpsilva** [comment]
Hello @Mini256 . Wow! Thank you ! 
Part of the issue I believe it was fixed by @githrdw. I'll double check and fix the `import .css`.
Once again, thank you! :D
