### ISSUE TITLE
 [mdSelect] do not display image

### ISSUE THREAD

**Issue by vietlong90** [vuematerial/vue-material#909]
Hi,
I'm using md-select to display option with image and text. But when I select an item, It's only show the text, the image is hidden. How can I show the image and text together?
Thanks

`<md-select v-model="lang">`
`        <md-option value="eng">`
`          <span><img src="../../static/flags/4x3/gb.svg" style="width: 20px;" /> English</span>`
`        </md-option>`
`        <md-option value="jp">`
`          <span><img src="../../static/flags/4x3/jp.svg" style="width: 20px;" /> Japanese</span>`
`        </md-option>`
`</md-select>`

**Comment by pablohpsilva** [comment]
Hello @vietlong90 :D 
Dude, I'll check it out ASAP. I'll check the material.io guideline to see if it's OK.

Thank you!

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
