### ISSUE TITLE
Md-select multiple reset

### ISSUE THREAD

**Issue by bmondolot** [vuematerial/vue-material#910]
Md-select with the multiple properties keeps track internally of the previous selected values even when the v-model is reset/changed outside of the md-select

### Steps to reproduce
Click on a md-select with the multiple attribute and select some items
Reset the v-model of the select with an empty array
Click on the md-select to show the list of items

### Which browser?
All browsers

### What is expected?
No values are shown as selected

### What is actually happening?
The previous selected values (before the reset) are still seen as selected.

### Reproduction Link
https://codepen.io/anon/pen/OgdgKV

**Comment by tsunamilx** [comment]
Same issue here, my workaround is to use "v-if" to destroy-then-recreate it, something like:
```vue
<template>
  <md-select multiple v-if="! resetting"></md-select>
</template>

<script>
export default {
  data() {
    return {
      resetting: false
    }
  },

  methods: {
    reset() {
      this.resetting = true
      setTimeout(() => {this.resetting = false}, 100)
    }
  }
}
</script>
```

**Comment by pablohpsilva** [comment]
This seems a very quick fix. I'll look into it ASAP.
Thank you! :D

**Comment by pablohpsilva** [comment]
Hello! The `v-model` only gets the selected value from the `md-option` component.
It really doesn't do much. What I can do is clean `md-select` internal state when a `md-option` is destroyed.
