### ISSUE TITLE
 [mdTheme] Issue with setting background color in default theme

### ISSUE THREAD

**Issue by MysticSheik** [vuematerial/vue-material#912]
Hi, I'm trying to set the background to a dark color to create a dark theme but it doesn't seem to work. No matter what I set the background to, it still gives me a Grey A100 background with black text it seems like. So it seems like the theme

Browser is latest version of Chrome using latest version of Vue Material.

[Codepen](https://codepen.io/anon/pen/pwYRPv)

**Comment by zapping** [comment]
You can track the issue in tickets #355 and #782

**Comment by c941010623** [comment]
body{
  background: black;
}

**Comment by MysticSheik** [comment]
@c941010623 That only changes the background. The text still defaults to black instead of white, and manually overriding every single element to change the text color to white is a huuuuge pain :/

@zapping Thanks c:

**Comment by pablohpsilva** [comment]
Theming issues: #912 #782 and #355
We'll look into it ASAP. Thank you!! :D

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
