### ISSUE TITLE
md-layout not bind to event

### ISSUE THREAD

**Issue by Thaina** [vuematerial/vue-material#913]
### Steps to reproduce
Making `md-layout` with `v-on:click` event or `v-on:drop` event

### Which browser?
Chrome 59

### What is expected?
`md-layout` converted to `div` so it should react to event like div

### What is actually happening?
`md-layout` does not react to those vue event. change that element to normal div make it work

**Comment by d3radicated** [comment]
Use `@click.native` instead.

**Comment by Thaina** [comment]
@d3radicated What about `ondrop` `onpaste` and so on? Is it would work too?

**Comment by d3radicated** [comment]
Just add the `.native` modifier for any event on `md-layout`. I think it should work.

**Comment by Thaina** [comment]
@d3radicated Thank you very much
