### ISSUE TITLE
 [mdAutocomplete] Problem with IME in autocomplete in Chrome

### ISSUE THREAD

**Issue by dennishu001** [vuematerial/vue-material#916]
Open the input component demo page in Chrome. Try to use an IME such as Windows Chinese input editor in autocomplete input, it will just take each character and will not compose. 

The IME works fine in normal text input field.  Any suggestion?

**Comment by pablohpsilva** [comment]
Well look into it ASAP. Thank you!! :D 
Could you please provide a codepen or something to express the bug? That would make much easier get help from others developers.

**Comment by dennishu001** [comment]
Thanks for looking into the issue.  Just let you know, it seems to work fine in Firefox.

To duplicate the issue, you will need to have an IME installed. In  Windows 7, you can download google pinyin from here: http://tools.google.com/pinyin/ It'll probably be in Chinese. Just click the big blue button on the top right it'll start downloading.  After installing, you can activate it by clicking the keyboard option on your windows status bar. 

To see the problem, open http://vuematerial.io/releases/v0.7.3/#/components/input in Chrome. Try to enter some thing in any normal input field with the IME enabled, you will see some Chinese characters popping up. However, when you try to do the same  in the one labeled  "Autocomplete (with fetch)", you should not see the Chinese characters but your original keyboard entries.

**Comment by c941010623** [comment]
i also have some problem +1
i use chinese

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
