### ISSUE TITLE
 [mdTheme] Change list item non-title text

### ISSUE THREAD

**Issue by matthew-carroll** [vuematerial/vue-material#918]
I've altered the default theme to have a dark background and white text.  The first line of my md-list-items is white, however, line 2 and line 3 of my md-list-items remain dark so that they can't be seen on the dark background.

How should one go about making the non-title text of list items light instead of dark?

**Comment by pablohpsilva** [comment]
Well look into it ASAP. Thank you!! :D

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
