### ISSUE TITLE
 [mdSelect] with custom mdOption layout - wrong displayed text

### ISSUE THREAD

**Issue by lucasfernog** [vuematerial/vue-material#919]
### Steps to reproduce
Create a mdSelect with extra inner text on mdOption.

### Which browser?
Chrome 59.0.3071.115
Vue ^2.3.4
VueMaterial ^0.7.4
Windows 10

### What is expected?
The text displayed on mdSelect input is only my mdOption primary content (e.g. "Option Text" [codepen example])

### What is actually happening?
`this.$refs.item.textContent` at `setParentOption()` from mdOption causes the display text to be every inner text from DOM elements.

### Reproduction Link
https://codepen.io/lucasfernog/pen/qXWYrZ

"add" or "edit" shouldn't be part of the text displayed of the selected option. An extra named slot after `<span ref="item"` (mdOption) should solve the issue.

**Comment by pablohpsilva** [comment]
Well look into it ASAP. Thank you!! :D

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
