### ISSUE TITLE
Start to worry about this repo

### ISSUE THREAD

**Issue by tsunamilx** [vuematerial/vue-material#920]
From the date of last commit of this repo, it was a month ago, and I hardly see any response from the maintainers among the hundreds of issues in the month.

It doesn't feel right especially when the repo is such popular..

So I wonder what's the status of this repo?

**Comment by d3radicated** [comment]
@pablohpsilva, the current maintainer of this repo, has been sick recently and can't tend to the issues and PRs at the moment. @marcosmoura, the creator of Vue Material, is rewriting it from scratch. You can see his progress [here](https://github.com/vuematerial/vue-material-experiments).

**Comment by marcosmoura** [comment]
I'm going to give the currenty status really soon!

**Comment by tsunamilx** [comment]
OK thanks for the update.

**Comment by marcosmoura** [comment]
#921 See here a HUGE text explaining everything!
