### ISSUE TITLE
 [mdFile] Issue w/ Image Uploading

### ISSUE THREAD

**Issue by MysticSheik** [vuematerial/vue-material#923]
### Steps to reproduce
```html
<md-input-container>
    <label for="thumbnail">Thumbnail</label>
    <md-file name="thumbnail" v-model="file.name" @selected="onFileUpload($event)" accept="image/*"></md-file>
</md-input-container>

<md-button class="md-raised md-accent" type="submit" @click.native="submit()">Create</md-button>
```

```javascript
data() {
        return {
            file: {
                name: ''
            }
        };
    },
    methods: {
        onFileUpload (evt) {
            this.file = evt[0]
        },
        submit() {
            functionSend({thumbnail: this.file})
        }
}
```

### Which browser?
Latest version of Chrome

### What is expected?
When submitting the form, the thumbnail field should containt a file and not be null. 

### What is actually happening?
The <input> field rendered by Vue when using MdFile has a type of text instead of file which may have something to do with the problem, but I'm not sure.

**Comment by pablohpsilva** [comment]
Hello @MysticSheik ! Thank you for opening this issue :D
I'll look into it ASAP.

**Comment by dedayoa** [comment]
Well, I'm currently using md-file to upload images ok. When it comes to file upload, you have to pay attention to the following
1. set your content-type to multipart/form-data
2. Make sure you are posting (or puting) a form, using FormData()
3. On the server side, make sure you can actually handle file uploads.

I use...
```
function getFormData(object) {
    let formData = new FormData();
    Object.keys(object).forEach(key => formData.append(key, object[key]));
    
    return formData;
}
```

**Comment by pablohpsilva** [comment]
Hello everyone.
I pretty much did what @dedayoa said and it worked for me just fine. Could you please double check it @MysticSheik ?
I'm closing this issue for now, but fell free to reopen it.
