### ISSUE TITLE
When opening a snackbar while it's already open, the snackbar doesn't close and then open

### ISSUE THREAD

**Issue by petarpanicVIU** [vuematerial/vue-material#926]
### Steps to reproduce
Try to click the open the snackbar button in the docs or just try opening the snackbar multiple times in the code.

### Which browser?

Every browser, every OS, every vue, the latest vue-material which is 0.7.4 at this point.

### What is expected?
Close the old snackbar and show the new one as that is the 'Material' way.

### What is actually happening?

The snackbar either stays open and just the message changes or it disappears and sometimes doesn't appear again.

**Comment by pablohpsilva** [comment]
Thank you for registering this issue and fixing it on PR #928 LOL
You rock dude! :D
