### ISSUE TITLE
Using md-autocomplete logs lots of warnings about "Avoid using non-primitive value as key, use string/number value instead"

### ISSUE THREAD

**Issue by calebsander** [vuematerial/vue-material#930]
### Steps to reproduce
Just use an md-autocomplete element and give it some data to search through. In development mode, at least, Vue will look repeated warnings saying, "Avoid using non-primitive value as key, use string/number value instead".

### Which browser?

Using Chrome 59, Vue 2.4.1, and Vue Material 0.7.4

### What is expected?
No warnings logged

### What is actually happening?
I think this is because [the option object is used as the key](https://github.com/vuematerial/vue-material/blob/7daa66daa7b7cf0e117814f9f2f9f79f2c66c2c9/src/components/mdInputContainer/mdAutocomplete.vue#L26). This could be fixed either by using `item[printAttribute]` as the key (it seems reasonable to assume that there wouldn't be multiple items with the same display value), by providing a `keyAttribute` prop, or by using the index of the iteration as the index.

**Comment by pablohpsilva** [comment]
Hello! Thank you for opening this issue.
Since the new Vue version I'll update vue-material vue package and fix small issues like these.
