### ISSUE TITLE
How to clear the input when to click the "close" button in a prompt dialog?

### ISSUE THREAD

**Issue by ety001** [vuematerial/vue-material#932]
Is there a grace way to clear the input when to click the "close" or "done" button in a prompt dialog?

**Comment by calebsander** [comment]
If you attach the input to your model by adding `v-model='inputField'` (or any other field name), you can just do `this.inputField = ''` and it will clear the input.

**Comment by ety001** [comment]
@calebsander , thank you for your reply, I have tried this way, Buy it seems to no effect.
The code is here. [https://jsfiddle.net/3wf443Lw/](https://jsfiddle.net/3wf443Lw/)

**Comment by calebsander** [comment]
Hmm, I have never worked with `md-dialog-prompt` before, so I'm not sure why that doesn't work. I got it working by calling `this.prompt.value = ''` before opening the dialog rather than after closing it. See this fiddle: https://jsfiddle.net/wuybmmho/.

**Comment by ety001** [comment]
Maybe this is the most grace way to clear input value for now.

**Comment by zapping** [comment]
@ety001, Actually the value does get cleared when you give `this.prompt.value=''` in the `onClose()` function. You can test it with the following code 
```
    onClose(type) {
      this.prompt.value = '';
      console.log('Closed', type, this.prompt.value);
    }
```
 The console does show an empty string. If you comment out `this.prompt.value()=''` statement then the console will show the actual value entered. But when the prompt is opened again the input does show the previous value. If you do not want it then you can try out what @calebsander suggested to include this.prompt.value='' in the onOpen() function.

```
    onOpen() {
      this.prompt.value = '';
      console.log('Opened');
    },
```

Maybe @pablohpsilva can help you out like if its actually the way it should work.

**Comment by mattisback** [comment]
I'm still getting this issue (with beta 8).

I've noticed that if I set this.prompt.value in the chrome console, nothing happens but if I set it twice, and to two different values then it works (eg. value = '1', then value = '').
Unfortunately this simple code does not work:
```js
onClose () {
  this.prompt.value = '1'
  this.prompt.value = ''
}
```
However if you use `$nextTick`, it does work.
```js
onClose () {
  this.prompt.value = '1'
  this.$nextTick(() => {
    this.prompt.value = ''
  })
}
```

This however seems very hacky.  I think there is a problem with the md-dialog-prompt component that's causing the data to flow through to the input field in two steps rather than in one.

**Comment by VdustR** [comment]
@mattisback That's because of vue.js lifecycle.

**Comment by mattisback** [comment]
@VdustR so how can I get around needing to call `$nextTick`?  Surely this isn't the intended way to use the prompt dialog.  And surely clearing the text on open/close is a fairly common use case..

**Comment by VdustR** [comment]
Would you provide your code in Codepen?
