### ISSUE TITLE
 [mdTable] mdTablePagination.vue: Computed property subTotal is written

### ISSUE THREAD

**Issue by markus-s24** [vuematerial/vue-material#943]
Warning 'Computed property "subTotal" was assigned to but it has no setter.' results from readonly computed property "subTotal" being written in watch method "mdTotal(val)":

this.subTotal = sub > val ? val : sub;

**Comment by Ashirogi-Muto** [comment]
Did anyone find the solution for this?

**Comment by superbogy** [comment]
so many bug i want to give up

**Comment by pablohpsilva** [comment]
Hello everyone! I think it was fixed on @d3radicated PR #961
