### ISSUE TITLE
 [mdTable] md-size doesn't set by default

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#944]
### md-size not setting value by default 

Hello, first at all , thank you for the md-pagination :+1:  ! 
Then i think it have a bug with md-pagination 

i write this below :
`<md-table-pagination
        md-size="5"
        :md-total="agencies.length"
        md-page="1"
        md-label="Lignes par page"
        md-separator="sur"
        :md-page-options="[5, 10, 25, 50]"
        @pagination="paginate"></md-table-pagination>
`
So i set the amount of rows displayed with md-size but my generated select has no option selected corresponding to the value 5 , this is the right way to do it ? 

i've try ` md-size="5" `and `: md-size="size" `and passing size into data but it's doesn't work

Thank you for your help !

Alex

**Comment by alexMugen** [comment]
I found something else : 
When i set my md-total dynamically  like `:md-total="agencies.length"`, the arrows for changing pages are disabled and when i set in static like `md-total="30"` it's work

**Comment by zapping** [comment]
Is this similar to #482

**Comment by MRxiongyu** [comment]
I also encountered this problem, when I update md-total, the browser will be error, `Computed property "subTotal" was assigned to but it has no setter.`

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
