### ISSUE TITLE
 [mdInput] labels for md-input overflow when the text is too long FIX INCLUDED

### ISSUE THREAD

**Issue by rodrigoAbril** [vuematerial/vue-material#945]
### Steps to reproduce
add lots of text to a label

### Which browser?

all

### What is expected?
for height consistency, it should hide the rest and show the text with ellipsis

### What is actually happening?

just overflows horribly 

### Reproduction Link

you can see the [issue and simple fix here](https://codepen.io/anon/pen/MveYNo)

(edit) Would love to do it all with flex-box but it would mean rewriting all the current label/input css...

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
