### ISSUE TITLE
md-stepper:  Is there a way to change the steps with JS?

### ISSUE THREAD

**Issue by vitorcominato** [vuematerial/vue-material#946]
How can i change a step on my methods?
Is there a way of doing that?

**Comment by rodrigoAbril** [comment]
Hi @vitorcominato 
You can try asking in the slack channel i think it will be faster than the issues section
https://join.slack.com/vuematerial/shared_invite/MTgzMzU2NDQ5ODkwLTE0OTQ4MDI3MDAtNWYyZjhkNzEzMA

**Comment by zapping** [comment]
@vitorcominato Please check this issue #931
