### ISSUE TITLE
 [mdTheme] Body has incorrect class when using custom theme

### ISSUE THREAD

**Issue by jakubbilko** [vuematerial/vue-material#947]
### Steps to reproduce
Register a new theme and set it as the current one.

```
Vue.material.registerTheme('myTheme', theme)
Vue.material.setCurrentTheme('myTheme')
```

### Which browser?
Tested on Chrome 59.0.3071.115

### What is expected?
`body` should have an `md-theme-myTheme` class.

### What is actually happening?
`body` has the `md-theme-default` class, furthermore there are two theme `style` elements injected into the `head`: `md-theme-myTheme` and `md-theme-default` causing the latter to override the styles of the newly created theme.

### Reproduction Link
https://codepen.io/vue-material/pen/WGavBE

**Comment by Hjort-e** [comment]
Having the same issue on Vue 2.4.2 with vue-material 0.7.4.
Funnily it applies the theme class to the dialog element but nothing else

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
