### ISSUE TITLE
 [mdSelect] `change` event was triggered if md-select's default value is not null

### ISSUE THREAD

**Issue by leo108** [vuematerial/vue-material#952]
### Steps to reproduce

Relate a `md-select` component with a data by `v-model`, if the data is not `null`, it will trigger a `change` event after mounted.

But if click a `md-option` with `null` value, it will trigger a warning

> [Vue warn]: Invalid prop: type check failed for prop "value". Expected String, Number, Array, got Boolean.

### Which browser?
vue 2.3.3, vue-material 0.7.4

### What is expected?

`change` event should not be triggered after mounted.

### What is actually happening?

The `md-select` triggers a `change` event after mounted.

### Reproduction Link

Check the console to see the difference.

https://codepen.io/anon/pen/jLVggj?editors=1111

https://codepen.io/anon/pen/yogByy?editors=1111

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
