### ISSUE TITLE
`change` event triggers twice when clicking on a md-radio's label

### ISSUE THREAD

**Issue by decksterr** [vuematerial/vue-material#953]
### Steps to reproduce  
Click on a label from the ```md-radio``` component

### Which browser?
Google Chrome 59.0 and Firefox 47.0 with vue 2.3.3, vue-material 0.7.4

### What is expected?
Change event should trigger once

### What is actually happening?
Change event triggers twice when clicking on label (but not when clicking directly on radio container)

### Reproduction Link
https://codepen.io/decksterr/pen/mMROyL  
Check the console for logs

**Note:** change event also triggers even if value of the related ```v-model``` didn´t actually change, although i am not sure if that is indeed desired behaviour

**Comment by zapping** [comment]
Just noticed something else too. If you use @change.native instead of @change only the change event for the label triggers but not the change event for the radio.

**Comment by decksterr** [comment]
That seems to be because the native input is disabled intentionally by design and serves only as storage for the selected value. The label being natively tied to the input however isn't disabled and therefore triggers the native @change event when in fact it really shouldn't, cause of the issue actually.

I do believe this will be fixed with #954
