### ISSUE TITLE
 [mdInput] Size of input textarea

### ISSUE THREAD

**Issue by zapping** [vuematerial/vue-material#958]
### Steps to reproduce
Is there a way to show the multiline contents of a textarea in full. If the textarea has multiline content then only the first line is displayed initially. When the content in the textarea is edited manually then it shows the contents in full.

### Which browser?
In all browsers, latest version of Vue and Vue-Material

### What is expected?
When the page loads initially the multiline contents of the textarea needs to be displayed in full instead of just the first line.

### Reproduction Link
In this pen, https://codepen.io/zapping/pen/bBPyOz , if you click the 'Open Dialog' button then a dialog appears with the textarea Friends. Initially only the first line of friends are displayed. But if the textarea is edited manually then all the names of friends or the multiline contents are displayed.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
