### ISSUE TITLE
 [mdTable] mdTablePagination : Computed property "subTotal" was assigned to but it has no setter.

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#959]
Hello, 

Since i update vue material (^0.7.1 ), i have an error in my console : 
```
Computed property "subTotal" was assigned to but it has no setter.

found in

---> <MdTablePagination>
       <MdCard>
         <MdTableCard>
```

I don't understand because i didn't use subTotal property in my code

Thank you for your help 
Alex

**Comment by wandroll** [comment]
Probably a duplicate of #943 . There is this PR #915  that should resolve your bug.

**Comment by alexMugen** [comment]
ok thank you @wandroll
