### ISSUE TITLE
[core] Can we hide log :  [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#960]
Hello,

Since i update vue-material i have log violation : 

>  [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

can we hide this log  ? Why do we have this log now  ?

thank you for your help 
Alex

**Comment by pablohpsilva** [comment]
We'll look into it ASAP. Thank you @alexMugen

**Comment by marcosmoura** [comment]
This is due to a event on mdInkRipple component. This will be fixed soon.

**Comment by Flugund** [comment]
What is the current status for this issue?

**Comment by lucasm-iRonin** [comment]
@pablohpsilva @marcosmoura what is the status of this ticket? Which versions are affected?

Thanks in advance!

**Comment by p0rsche** [comment]
+1 What is the status of this? I'm on 0.8.1 and the message still exists.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
