### ISSUE TITLE
obligation of md-input hidden type wrapping 

### ISSUE THREAD

**Issue by GergelyLakatos** [vuematerial/vue-material#963]
### Steps to reproduce
Just check the console.

### Which browser?
All browsers.

### What is expected?
There should not be Vue warn if I do not wrap the hidden `md-input` element.

### What is actually happening?
In the console there is a vue warn that every `md-input` should be in `md-input-container`, but if I take it in a input container the output will be ugly (the vue generate an empty line for that). 

### Reproduction Link
https://codepen.io/anon/pen/oewrbw

**Comment by marcosmoura** [comment]
This is not a bug. You should always wrap the md-input in a container. This is because all styles are controlled by the parent itself. 
In the case of a input hidden, just use the regular <input> tag.

**Comment by GergelyLakatos** [comment]
All right. Thanks for the answer!
