### ISSUE TITLE
[mdTable] Single selection without checkboxes

### ISSUE THREAD

**Issue by HerrLoesch** [vuematerial/vue-material#965]
I guess the current solution for selection in mdTable is quite handy if you must select multiple elements. But if you just want the user to select only single elements, it seems a bit weird to have a check box at the beginning of each row.

In my case I want to show additional information for each selected row. Thus, the user selects a row and the details are updated based on this selection. It looks strange and is hard to handle if the user can select multiple rows.

Just to be sure: I don’t want to show details within the table. I just would like to use selection with single rows and without (visible) checkboxes. 

This if-statement is what it breaks for me currently because I want to use "AutoSelect" but without "hasSelection". 

`        if (this.mdAutoSelect && this.hasSelection) {
          this.checkbox = !this.checkbox;
          this.handleSingleSelection(this.checkbox);
          this.parentTable.emitSelection();
        }`

Maybe you could introduce another property "singleSelection" in addition to "hasSelection" that hides the checkboxes.

**Comment by HerrLoesch** [comment]
"you could introduce" does not mean, that you have to do it. I would take a try to do it if I would know if this change is appreciated.

**Comment by aplandev** [comment]
here is my workaround:
button at the last cell.

<md-table v-once>
.......
<md-table-cell>
  <md-button @click="openDialog(item, 'dialog')" class="md-icon-button">
    <md-icon>edit</md-icon>
  </md-button>
</md-table-cell>
....
<md-table>

**Comment by adefelicibus** [comment]
@HerrLoesch I'm trying to do something similar to you. Have you done something new to face it? Thank you.

**Comment by deivan** [comment]
@HerrLoesch i join to your opinion, a possibility for selection only one item is very important..
Now, i hide first cell with selector via CSS:
`td.md-table-cell.md-table-selection.md-has-action {
    display: none;
}`

**Comment by adefelicibus** [comment]
@marcosmoura Any ideas about it?

**Comment by marcosmoura** [comment]
Let's discuss this a little bit. With the new 1.0.0 beta around the corner, we will have a new md-table component. This will introduce a new API, way easier to implement. At least I think it will be easier. For this particular feature, I was thing in something like this:
For multiple selections with checkboxes and a select action inside the entire row:
``` vue
<md-table-row md-selectable="multiple" md-autoselect>...</md-table-row>
```
Or
``` vue
<md-table-row md-selectable md-autoselect>...</md-table-row>
```
-----

For single selection, without checkboxes
``` vue
<md-table-row md-selectable="single" @md-selected="onSelected">...</md-table-row>
```
In this case, when a user click inside a table row, it will highlight and work as a radio, emitting an event with the selected value.

What do you guys think?

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
