### ISSUE TITLE
[mdRatio] doesn't work on md-card-media

### ISSUE THREAD

**Issue by reo4** [vuematerial/vue-material#966]
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

**Comment by pablohpsilva** [comment]
Hello @reo4 
Could you provide a codepen with it? What did you do to get that error?

**Comment by reo4** [comment]
> <md-card md-with-hover v-for="team in teams">
> 				<md-card-media-cover  md-text-scrim>
> 					<md-card-media md-ratio="16:9">
> 						<img src="images/card-sky.jpg" alt="Skyscraper">
> 					</md-card-media>
> 					<md-card-area>
> 						<md-card-header>
> 							<span class="md-title" v-if="teams.length">{{team.title}}</span>
> 						</md-card-header>
> 						<md-card-content>
> 							<md-speed-dial md-open="hover" class="md-fab-bottom-right">
> 								<md-button class="md-icon-button md-raised" md-fab-trigger>
> 									<md-icon md-icon-morph>close</md-icon>
> 									<md-icon>reorder</md-icon>
> 								</md-button>
> 								<md-button @click.prevent="$refs.dialog2.open(); openedDialogID = team._id" class="md-fab md-mini md-clean">
> 									<md-icon>delete</md-icon>
> 								</md-button>
> 
> 								<md-button class="md-fab md-mini md-clean">
> 									<md-icon>content_copy</md-icon>
> 								</md-button>
> 							</md-speed-dial>
> 						</md-card-content>
> 					</md-card-area>
> 				</md-card-media-cover>
> 			</md-card>

**Comment by reo4** [comment]
<md-card md-with-hover v-for="team in teams">
				<md-card-media-cover  md-text-scrim>
					<md-card-media md-ratio="4:3">
						<img src="images/card-sky.jpg" alt="Skyscraper">
					</md-card-media>
					<md-card-area>
						<md-card-header>
							<span class="md-title" v-if="teams.length">{{team.title}}</span>
						</md-card-header>
						<md-card-content>
							<md-speed-dial md-open="hover" class="md-fab-bottom-right">
								<md-button class="md-icon-button md-raised" md-fab-trigger>
									<md-icon md-icon-morph>close</md-icon>
									<md-icon>reorder</md-icon>
								</md-button>
								<md-button @click.prevent="$refs.dialog2.open(); openedDialogID = team._id" class="md-fab md-mini md-clean">
									<md-icon>delete</md-icon>
								</md-button>

								<md-button class="md-fab md-mini md-clean">
									<md-icon>content_copy</md-icon>
								</md-button>
							</md-speed-dial>
						</md-card-content>
					</md-card-area>
				</md-card-media-cover>
			</md-card>

**Comment by reo4** [comment]
![image](https://user-images.githubusercontent.com/20121364/29250535-363d6c4a-8044-11e7-83da-8eb769d3e00c.png)

**Comment by reo4** [comment]
![image](https://user-images.githubusercontent.com/20121364/29250552-7531efa2-8044-11e7-8a86-e820633cfcbb.png)

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
