### ISSUE TITLE
How to handle click event on a card's cover image ? 

### ISSUE THREAD

**Issue by reo4** [vuematerial/vue-material#967]

**Comment by pablohpsilva** [comment]
Hello @reo4 
Do you want to handle a click event on a card's cover image? You really meant clicking on the image and getting an click event back or you're talking about the component below?

![screen shot 2017-08-13 at 12 08 58 am](https://user-images.githubusercontent.com/2090635/29245798-a2934d62-7fbb-11e7-9db8-21242b521218.png)

Clicking on the image: no go. It has no click event to catch;
Clicking on a button over the card's cover image: grab the click event from the button.
