### ISSUE TITLE
Build the library when installing this package from git.

### ISSUE THREAD

**Issue by titouancreach** [vuematerial/vue-material#976]
Feature requested:

Build the library when installing this package from git.
Bugs are often solved on the branch `develop`. This is why I often use the git repo instead of the release in my `package.json`.
```
  "vue-material": "vuematerial/vue-material.git#develop",  
```
The problem is that the `dist` folder is outdated on the develop branch. 
It would be useful to run the `build` script when installing. For now, I have to do `cd node_modules/vue-material && yarn && yarn run build` (or npm equivalent).

What will it allow you to do that you can't do today?
--------
Directly add the develop branch as a dependency and have the bug fixed and experimental features.

How will it make current work-arounds straightforward?
--------
We won't need to build package manually.

What potential bugs and edge cases does it help to avoid?
--------
Running with outdated version of `vue-material`.

I think a `prepublish` script and a `.npmignore` would solve this.

I can make a PR if this you are interested in.

(This issue is not directly related with git install, but in the master branch, `dist` folder is update)
 
Regards

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
