### ISSUE TITLE
Master merge  ?

### ISSUE THREAD

**Issue by alexMugen** [vuematerial/vue-material#978]
Hello,

Just quick question , when  _**master**_ will be merged with _**develop**_ ? 
I ask this because some bugs are fixed now on develop branch , i use :

> "vue-material": "^0.7.1",

I know i can specify develop version but i just want to know  if the merge will comes soon :)

**Comment by pablohpsilva** [comment]
Don't worry my friend, we're preparing to release it soon. :D

**Comment by alexMugen** [comment]
@pablohpsilva  thank you a lot and great Job all :1st_place_medal:

**Comment by alexMugen** [comment]
Hello, 
any idea for the date of the new Master branch  ?

**Comment by alexMugen** [comment]
i don't know if its ok if i use  develop branch of vue material in my package.json ? 
if it's ok , can you tell me the syntax of it please ?

i have this code 
`"dependencies": {
    "axios": "^0.16.2",
    "vue": "^2.3.3",
    "vue-material": "^0.7.1",
    "vue-router": "^2.3.1"
  },`

Thanks a lot
