### ISSUE TITLE
[mdButton] <router-link> raises error when used with tag="md-button" inside <md-tabs>

### ISSUE THREAD

**Issue by cesarzagonel** [vuematerial/vue-material#979]
### Steps to reproduce
Pen: click on "go to bar"

### Which browser?

vue: 2.1.6
vue-material: 0.7.4
vue-router: 2.7.0
os: macOS
browser: chrome 60.0.3112.90 (Official Build) (64-bit)

### What is expected?
Any error raised.

### What is actually happening?
error raised: Uncaught TypeError: Cannot read property 'scrollWidth' of undefined

### Reproduction Link

https://codepen.io/cesarzagonel/pen/QMaWVV?editors=1010

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
