### ISSUE TITLE
[mdAutocomplete] In mobile browsers, when typing, the keyboard disappears

### ISSUE THREAD

**Issue by vrnehot** [vuematerial/vue-material#982]
### Steps to reproduce
Start typing in the mobile browser, when the selection opens, the keyboard closes

### Which browser?
Android
Moblie browsers
Vue 2.4.2
vue-material 0.7.4

**Comment by argarak** [comment]
This is because there was a bug with `md-autocomplete` losing focus when the menu appeared, we are aware of this and it should be fixed in the next release (you can also build the source from the `develop` branch). [Here](https://github.com/vuematerial/vue-material/pull/969) is the PR.
