### ISSUE TITLE
[mdTabs] Feature: `active` event from tab components?

### ISSUE THREAD

**Issue by VdustR** [vuematerial/vue-material#986]
Please check [this CodePen reproduction](https://codepen.io/VdustR/pen/LjQbYe) first.

1. click E via the tab
2. click A via the button

![peek 2017-08-18 17-49](https://user-images.githubusercontent.com/29639463/29453875-c6286d58-843d-11e7-845d-54dd07381218.gif)

If the tabs what to be changed via another component events, it needed to handle the `tabs change` event to change the `mdActive` value first.

![peek 2017-08-18 17-57](https://user-images.githubusercontent.com/29639463/29454154-b6ec63a2-843e-11e7-9467-e8ab979b1db1.gif)

As [this CodePen reproduction](https://codepen.io/VdustR/pen/dzdXEM), I use `tabs.tabList[tabs.activeTab].ref` to find which tab is active instead of using the index because sometimes the number of the tabs is dynamic so I think it might not convenient because the index of the tab would be dynamic in this case too.

It would be great to emit an `active` event from the `tab` component:

```pug
md-tab(v-if="aIsOn" md-label="A" :md-active="isAActive" @active="activeA")
```
```javascript
methods: {
  activeA: () => store.commit('goToA')
}
```

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
