### ISSUE TITLE
Backcolor doesn't change

### ISSUE THREAD

**Issue by wbbenatti** [vuematerial/vue-material#989]
I'm trying to use Vue-Material for the first time and when I tried to change the background color on the default theme, it simply does not change the color and the background color always turns white. I'm doing the following:

```
Vue.material.registerTheme('default', {
    primary: 'orange',
    accent: 'red',
    warn: 'red',
    background: {
        color: 'blue-grey',
        hue: 800
    }
})
```

What is wrong?

**Comment by wbbenatti** [comment]
I've seen these issues before, but I still have not been able to solve the problem.
I'm just creating a new Vue-Material project without changing anything except the Theme as it's in the Vue-material documentation.  I did what is shown in the documentation and also what follows below but It doesn't work:

```
import Vue from 'vue'

import VueMaterial from 'vue-material'

import App from './App'

Vue.use(VueMaterial)

Vue.material.registerTheme({
  default: {
    primary: 'red',
    accent: 'red',
    background: {
      color: 'blue-grey',
      hue: 800
    }
  },
  green: {
    primary: 'green',
    accent: 'pink'
  },
  orange: {
    primary: 'orange',
    accent: 'green'
  }
})

new Vue({
  el: '#app',
  render: h => h(App)
})
```

**Comment by zapping** [comment]
As per this #912 its a known issue and its being looked into.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
