### ISSUE TITLE
Page jumps when opening Sidenav component in Chrome

### ISSUE THREAD

**Issue by raahede** [vuematerial/vue-material#991]
### Steps to reproduce
Add Sidenav component to a page that's longer than the viewport. Open sidenav component.

### Which browser?
Chrome Version 60.0.3112.90 

Probably relates to 
https://bugs.chromium.org/p/chromium/issues/detail?id=423155

---

I'm using the sidenav in context of a regular website, and appending it to the DOM dynamically (i.e. the bottom of the DOM). When the code focuses on the sidenav (this line https://github.com/vuematerial/vue-material/blob/master/src/components/mdSidenav/mdSidenav.vue#L46) the browser scrolls to the bottom.

### What is expected?
The sidenav opens, and the page stays at the current scroll offset.

### What is actually happening?
The page jumps to the bottom in the background.

### Reproduction Link
https://codepen.io/anon/pen/jLzpYw

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
