### ISSUE TITLE
Property or method "checkbox" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by iamdubx** [vuematerial/vue-material#995]
When using with Nuxt I got this error, even if I use SSR false and mounted hook:

```
[Vue warn]: Property or method "checkbox" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
```

**Comment by chiuchihyung** [comment]
i have meet the same issue , too

**Comment by iamdubx** [comment]
@chiuchihyung I hope this will be fixed with coming release, we should wait a little bit.

**Comment by Samuell1** [comment]
Older version (0.8.x) doesn't have support for SSR. Try new version
