### ISSUE TITLE
[core] body class has md-theme-xxxx

### ISSUE THREAD

**Issue by titouancreach** [vuematerial/vue-material#996]
In the file: https://github.com/vuematerial/vue-material/blob/develop/src/core/components/mdTheme/dom.js

Vue material add the class md-theme-xxx to the body class. In some case, we want to use vue-material in a section of the page. I think we should let the user put this class where he wants to. This issue only appears in the develop branch.

**Comment by zapping** [comment]
You can use this and remove it from the body tag.
```
<script type="text/javascript">
        $(document).ready(function () {
            $("body").removeClass("md-theme-xxxx");
        });
</script>
```

**Comment by marcosmoura** [comment]
Vue Material need that class to theme the body tag, following the guidelines. Maybe a option to disable the body theming will be better for this use case. We will think about a way to change that.

**Comment by titouancreach** [comment]
@zapping I know this is possible to remove this class. But the issue was more: Does vue-material should theme the body?
