### ISSUE TITLE
Change v-model on multiselect won`t deselect selected options

### ISSUE THREAD

**Issue by gabemule** [vuematerial/vue-material#997]
### Steps to reproduce
When you clear the multiselect v-model, the selected options won`t deselect as expected.
The placeholder will change it`s value, but opening the menu will show the previous selected items.

### Which browser?
Chrome

### What is expected?
When clearing the v-model is expected that both placeholders and previously selected options are cleared.

### What is actually happening?
The placeholder will clear, but the previously selected options will still show as selected.

### Reproduction Link
https://codepen.io/anon/pen/brKxya
Wait for the alert, and open the multiselect menu to check the selected options.

**Comment by Samuell1** [comment]
Closing this issue as our focus is on the new 1.0.0 version.
